### ISSUE TITLE
how can i use shipyard in my docker swarm cluster?

### ISSUE THREAD

**Issue by xiaoea** [shipyard/shipyard#1003]
I hava three physical machine with some properties as follows.
   no       Ip                                role in docker swarm 
   1:        192.168.1.10                  master      
   2:       192.168.1.11                   worker
   3:       192.168.1.12                   worker

I create a  docker swarm cluster with overlay network ,all  my cluster applications can  using "docker  stack deploy *** "  command  to quickly start up and  work very fine  . but  you know , docker officials  didn't  provide any interfaces for docker swarm cluster,  so  I want to create my cluster using  "docker swarm  + shipyard ".   and  I have a question  about that  if shipyard have  functions that all the docker containers on the diffrent docker machine can access each other normally?
 How can I do it  if  I use " docker swarm + shipyard" mode ? please help me . thank you very much。

**Comment by ehazlett** [comment]
See #1001.  Shipyard doesn't yet support swarm mode.
