### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#1004]
I'm looking for some new maintainers.  I don't have the time nor energy to keep up with the project.  Any interest?

**Comment by shipbuildersjamuscore** [comment]
Hi jamuscoreshipbuilders

Pleaseet me know when we can meet

Jamuscoreshipbuilders@gmail.com

**Comment by opsforge** [comment]
@ehazlett better late than never - i would like to keep the project alive (if not under active development) as I found portainer and rancher lacking compared to this (still). I've forked the project to https://github.com/opsforgeio/shipyard and started transitioning your test suite to CircleCI. I did some involuntary upgrades too as some components were behaving incorrectly (like rethink and older version of Go). I'd like to ask for your help in figuring out the build pipeline so I can automate the image builds myself to DockerHub using Circle. If possible I would also want to transition the drone test suite to Circle too, to keep everything in one location.

Can you let me know if you have some time to discuss this?

**Comment by ehazlett** [comment]
@opsforge np.  everything build related is in the Makefile (`make build`, `make image`, `make test`).  i'm not super familiar with circle so i'm not sure how much help i'll be there.
