### ISSUE TITLE
Help with "shipyard/docker-proxy"

### ISSUE THREAD

**Issue by systemroot** [shipyard/shipyard#1005]
hello,

is here any way to make shipyard work without exposing port `2375` of my server for public?

i think there's a security leak. someone somehow is abusing with my dedicated servers in all 3 ded which i have someone starts a mining program with them
```bash
root@node1:~# ps aux | grep htt
root     13337  499  0.0 694880 14452 ?        SLl  06:50 1794:38 ./httpsd -a cryptonight -o 178.32.145.31:8005 -u 49xRakEeqGnTobg9zsVQQffcSK1TqWLfEbMDoGQWKbtKCJLgHgetkDjYuLJgqCvzkRimujgMvvgNp63sEdgSshsw2MHMki9.160915018 -p x -k
```
and i think he's doing this from swarm api.. 
because there's no other way how to.. 
22 days uptime no mining program just nothing then i install docker+shipyard i get up from sleep next day, and just i see a mining program running on my servers. and i'm the onlyone who have access on them and i can login only with ssh keys... 

also is a python script or idk what it does which eat 15GB of server ram..
![image](https://user-images.githubusercontent.com/19308979/29749502-165411c0-8b1d-11e7-9f35-953be7cb65fe.png)

Someone can help about this?

**Comment by ehazlett** [comment]
Yes, secure it with TLS.  There are instructions https://shipyard-project.com/docs/deploy/automated/ on how to do it as well as the official Docker docs [here](https://docs.docker.com/engine/security/https/)
