### ISSUE TITLE
How to run shipyard code

### ISSUE THREAD

**Issue by DragonSuper** [shipyard/shipyard#1007]
Hi，everyone。
I want to run this project。But I do not know how to select ide.
This project is go or js  project?
I want to modify go code and to check result，how to do it?
I try use intellij idea and golang plugin to run this project , but it have some errors!

**Comment by ehazlett** [comment]
Hi.  The backend is written in Go and the UI is written in HTML/JS/CSS.  See https://github.com/shipyard/shipyard#contributing for a quick start on contributing.  You can also use Docker Compose with the included docker-compose.yml to get a local environment up and running.
