### ISSUE TITLE
About the swarm-mode branch

### ISSUE THREAD

**Issue by apple9915** [shipyard/shipyard#1009]
Hello
I build the swarm-mode branch :
```
git clone git clone https://github.com/shipyard/shipyard.git
cd shipyard
git checkout swarm-mode
make image
```
And then I got an image, I run a container by using the image and visit localhost:8080, I got a ui like the picture :
![image](https://user-images.githubusercontent.com/18019929/30358107-113a540a-9875-11e7-8232-1b709306f4cc.png)

Is there something wrong with my step?
Thanks!

**Comment by systemroot** [comment]
i just did a fresh install because i was thinking i'm out of date but nah :sob:
