### ISSUE TITLE
how do i make it see the existing local docker containers?

### ISSUE THREAD

**Issue by mailinglists35** [shipyard/shipyard#1011]
I have installed docker 17.03 on oracle linux 7 via oracle official repo

next i have manually did all the steps from here https://shipyard-project.com/docs/deploy/manual/

now how do i make it see existing containers that i already see with 'docker ps' on host? it sees no node nothing, just the web interface which the docs do not even mention the default user and password, had to google it.

thanks

**Comment by mailinglists35** [comment]
output from installing and docker logs


http://sprunge.us/OEQE

**Comment by mailinglists35** [comment]
> ehazlett closed this 2 days ago

@ehazlett mind a few kind words of why has this been silently closed?
thank you

**Comment by ehazlett** [comment]
Please see the [Readme](https://github.com/shipyard/shipyard/blob/master/README.md).  Thanks and sorry.
