### ISSUE TITLE
oops，shipyard Gateway Timeout","status":504

### ISSUE THREAD

**Issue by neosun100** [shipyard/shipyard#1015]
```zsh
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$gyMtIKFUzKq2zcHsOiUPUuwyYNWJkyq3C/bta2GkPshYju4mzWU0."}},"statusText":"Gateway Timeout"}
```
MY sys is ubuntu 17.04

![tim 20171202002825](https://user-images.githubusercontent.com/13846998/33492476-1d19462a-d6f8-11e7-82c0-5029ec14ee40.png)

**Comment by neosun100** [comment]
other buttons is ok
![1](https://user-images.githubusercontent.com/13846998/33492569-5d66114a-d6f8-11e7-86b9-b09daf26cf21.png)
![2](https://user-images.githubusercontent.com/13846998/33492570-5d9de89a-d6f8-11e7-9007-ea87cb193585.png)
![3](https://user-images.githubusercontent.com/13846998/33492571-5dd41eb0-d6f8-11e7-9448-f1cfa7898237.png)

**Comment by ehazlett** [comment]
sorry this project is not longer maintained.  see https://github.com/shipyard/shipyard/blob/master/README.md
