### ISSUE TITLE
add node failed

### ISSUE THREAD

**Issue by longye321** [shipyard/shipyard#1016]
添加Node不成功，但节点没什么问题。如果执行curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://192.168.0.150:4001 bash -s 
ERR:
Adding Node
 -> Starting Cert Volume
 -> Starting Proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint shipyard-proxy (647b9144811902a10ea4c1d775dc98e8ceb984b25ec036370acbaff6d4a6674d):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 2375 -j DNAT --to-destination 172.17.0.3:2375 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
我用的OS是centos 7.4 friewall防火墙已经关闭

**Comment by ehazlett** [comment]
sorry this project is not longer being supported (see https://github.com/shipyard/shipyard/blob/master/README.md)
