### ISSUE TITLE
CoreOS Support

### ISSUE THREAD

**Issue by rolikeusch** [shipyard/shipyard#134]
Any plans to add CoreOS http://coreos.com Support? Now when i start the Agent on CoreOS i get the following Error:
```./shipyard-agent: error while loading shared libraries: libdevmapper.so.1.02.1: cannot open shared object file: No such file or directory```

It looks like there are some missing dependencies.

**Comment by cdancy** [comment]
Coreos user here. Had the same issue and just mounted libdevmapper in as noted in the below article and it worked as expected.

https://groups.google.com/forum/#!topic/coreos-user/4nyJh8lYaiA

**Comment by ehazlett** [comment]
Shipyard runs completely in containers.  This should be supported out of the box.  If not, please open a new issue.  Thanks!
