### ISSUE TITLE
Import of fig configuration as application

### ISSUE THREAD

**Issue by legoheld** [shipyard/shipyard#172]
I'm watching different projects all around docker, IMHO next shipyard [fig]([https://orchardup.com/blog/fig) is an interesting one. Especially the automatic linkage between containers is handy. And its very close to the "application" feature in shipyard.
So just as an idea, would it be possible to read in a fig configuration to generate the application setting with the required containers?

That would allow an easy way of application deployment.

But as I said thats just an idea and I very new to docker. So I cant't estimate if its doable and how much work it would be. So take it as an input ;)

By the way there is a python project [figcloud](https://pypi.python.org/pypi/ficloud) that allows deployment though git.

**Comment by ehazlett** [comment]
We will track this in #591. Thanks!
