### ISSUE TITLE
Read only user for gui

### ISSUE THREAD

**Issue by kassanmoor** [shipyard/shipyard#259]
I guess that could be a good enhancement add a new rol for with read only privileges, then you can share how is your docker/shipyard infrastructure without compromise any container

**Comment by wmariuss** [comment]
+1

**Comment by ndcampbell** [comment]
+1

This would be very useful. So users can monitoring running containers, and view logs, but not destroy or stop them.

**Comment by ehazlett** [comment]
This is coming in v3.

**Comment by ehazlett** [comment]
This is fixed in v3.  Thanks!
