### ISSUE TITLE
Using --privileged in the API

### ISSUE THREAD

**Issue by Pwu** [shipyard/shipyard#309]
Hello, 

It seems that the option is not **--privileged** implemented in the **API**. 
Does someone can help me?

Regards,

*PS: I found that, but it can't save me: https://github.com/shipyard/shipyard/issues/35*

**Comment by Stono** [comment]
Hi @ehazlett  any news on this one?
Super important for me to run a privileged container

**Comment by paweloczadly** [comment]
I would also need this functionality, since using `--privileged` in *Arguments* during container deployment, doesn't work...

**Comment by tombee** [comment]
+1

**Comment by eoghanino** [comment]
+1

**Comment by robtec** [comment]
+1

**Comment by tombee** [comment]
Have implemented this in PR #401, but it depends upon https://github.com/citadel/citadel/pull/91 first.

**Comment by ehazlett** [comment]
This is now fixed in v3.  For updated API docs see https://shipyard-project.com/docs/api.  Thanks!
