### ISSUE TITLE
Docker exec bash feature

### ISSUE THREAD

**Issue by alexproca** [shipyard/shipyard#318]
Since docker 1.3 we have exec command which can attach a new process to a running container. It would be great if the feature ilustrated in [this video (container attaching over websockets)](https://www.youtube.com/watch?v=aLlp-kemx_s) would use the exec command in order to attach a process with a shell (example bash) to selected container through websockets.

**Comment by ehazlett** [comment]
This is now implemented in v3.  Thanks!
