### ISSUE TITLE
extension: LDAP authentication

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#324]
For our use case, we're going to require LDAP authentication.

**Comment by Telmo** [comment]
+1

**Comment by eoghanino** [comment]
+1

**Comment by robtec** [comment]
+1

**Comment by egorpe** [comment]
+100

**Comment by ehazlett** [comment]
v3 now has LDAP authentication.

**Comment by shairozan** [comment]
Is there any information on configuring the LDAP / AD integration? Been having trouble finding anything besides the fact it can do it.
