### ISSUE TITLE
Issue with formatting of add-engine events in formatEngine angularjs filter

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#343]
![screen shot 2014-11-19 at 13 44 59](https://cloud.githubusercontent.com/assets/60068/5106649/57891fa8-6ff2-11e4-89a2-3a4f4a1f1da3.png)

A newly added engine just shows up as "undefined" and an error is displayed in the console.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
