### ISSUE TITLE
Adding user role to account

### ISSUE THREAD

**Issue by hanxiang9** [shipyard/shipyard#357]
![ss](https://cloud.githubusercontent.com/assets/8997741/5258055/81547886-7a20-11e4-8adf-c674f883cf33.png)

When I add user role to create an account, I got this error. I'm able to create account with admin role though. Anybody know what's the problem?

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
