### ISSUE TITLE
Quickstart needs to walk through adding engine

### ISSUE THREAD

**Issue by airtonix** [shipyard/shipyard#369]
Maybe it's something that's incredibly obvious to other people, but the quickstart doesn't actually get us to a useful point.

Without an engine, you can't do anything useful.

I've tried adding `http://127.0.0.1:2375` as an engine, but all I get is 

```
Error
Get http://127.0.0.1:2375/_ping: dial tcp 127.0.0.1:2375: connection refused
```

**Comment by kadishmal** [comment]
Having problem adding a host engine on CentOS. Quickstart is still missing the quickstart.

**Comment by ryanbaldwin** [comment]
I'm also receiving the same as @kadishmal. I'm stuck. I'm running shipyard inside an OS X boot2docker. No clue what to do.

**Comment by ehazlett** [comment]
@ryanbaldwin @kadishmal @gnoymmij @atonit @airtonix 

Added b2d instructions in the quickstart: http://shipyard-project.com/docs/quickstart/#toc_4

**Comment by ryanbaldwin** [comment]
Incredible. You just made my day. Thanks dude!

- ryan.

**Comment by ehazlett** [comment]
ha awesome. thanks!

**Comment by ryanbaldwin** [comment]
Just finally got a chance to try your example. the -v flag is causing an Incorrect Usage error. I’m using shipyard-cli:latest. 




Suggestions?


- ryan.

**Comment by ryanbaldwin** [comment]
(btw - UI instructions worked perfectly… Just the cli was giving problems due to -v)


- ryan.

**Comment by ehazlett** [comment]
It's working for me -- what version of Docker and how are you running it?

**Comment by ryanbaldwin** [comment]
boot2docker 1.4.1. 




https://github.com/boot2docker/osx-installer/releases/tag/v1.4.1



- ryan.

**Comment by ryanbaldwin** [comment]
was running it exactly as described in your example. 




ryanbaldwin$ docker run -it —rm shipyard/shipyard-cli

shipyard cli> shipyard add-engine —id b2d —add https://…. (etc.) 




If I include the -v argument all hell breaks loose.





shipyard cli> shipyard add-engine --id b2d --addr https://192.168.59.103:2376 --label local -v /Users/ryanbaldwin/.boot2docker:/b2d --ssl-cert /b2d/certs/boot2docker-vm/cert.pem --ssl-key /b2d/certs/boot2docker-vm/key.pem --ca-cert /b2d/certs/boot2docker-vm/ca.pem 

Incorrect Usage.




NAME:

   add-engine - add shipyard engine




USAGE:

   command add-engine [command options] [arguments...]




OPTIONS:

   --id 					engine id

   --addr 'http://127.0.0.1:2375'		engine address

   --cpus '1.0'					engine cpus

   --memory '1024'				engine memory

   --label '--label option --label option'	engine labels

   --ssl-cert 					path to ssl certificate

   --ssl-key 					path to ssl key

   --ca-cert 					path to ca certificate




Unless, of course, I have screen face right now and can’t see what i’m doing wrong (certainly wouldn’t be the first time)




- ryan.

**Comment by ehazlett** [comment]
Yes that was a typo.  Fixed and pushed to the quickstart.

**Comment by andrewcstewart** [comment]
I'm also getting the connection refused error, though I'm using the actual IP of the docker host.  Centos 6.5, maybe that's one of the offending OS's w.r.t TCP?

**Comment by ehazlett** [comment]
Check your firewall rules.

**Comment by Huntter** [comment]
@andrewcstewart I got the same situation, cannot add-engine by shipyard cli. I created another issue https://github.com/shipyard/shipyard/issues/437

**Comment by nlhkh** [comment]
I cannot add the engine even in UI. I did as the instruction and all I got was this error message `Get http://192.168.59.103:2376/_ping: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

**Comment by ehazlett** [comment]
It looks like you are trying to connect to a TLS instance?  Have you looked
at http://shipyard-project.com/docs/quickstart/#toc_4 ?

**Comment by nlhkh** [comment]
It was my fault. I used `https` and it works now. Thanks!

**Comment by ehazlett** [comment]
You're welcome!

**Comment by wildone** [comment]
404 on http://shipyard-project.com/docs/quickstart/#toc_4 

dang

**Comment by ehazlett** [comment]
The docs have been restructured.  This is no longer valid.

**Comment by jdkealy** [comment]
how does it work now ?
