### ISSUE TITLE
Allow editing of engines

### ISSUE THREAD

**Issue by grimmy** [shipyard/shipyard#371]
It would be awesome if I could edit an engine to add additional labels, change dedicated cpu/memory, and so on.

**Comment by Stono** [comment]
+1 for this

**Comment by binarycrafts** [comment]
+1. Makes sense on OpenStack where you scale things as needed.

**Comment by diamantn** [comment]
+1

**Comment by onbjerg** [comment]
Any updates on this?

**Comment by ehazlett** [comment]
With v3 we are moving to Swarm so the engines will be whatever nodes are a
part of the Swarm.

**Comment by jvanz** [comment]
+1

**Comment by ehazlett** [comment]
This is no longer valid as we use Swarm nodes.  Closing.  Thanks for reporting!
