### ISSUE TITLE
Allow copying of containers

### ISSUE THREAD

**Issue by grimmy** [shipyard/shipyard#372]
Editing of containers would be cool, but I understand why it's frowned upon.  As such I suggest the ability to copy a container by hitting a button that'll drop you into the edit view for a new container will all of the settings of the copied container.  This way, when I typo an environment variable or forget a port, I don't have to manually enter everything again.  I realize this is kind of possible with the api, but it would be nice to have it in the ui as well.

**Comment by larrymyers** [comment]
+1 Being able to copy a container config would make it easy to start a new container with the same configuration, just using a newer version of the docker image.

**Comment by derFunk** [comment]
+1 on that.

**Comment by ehazlett** [comment]
I recommend use docker compose for updating configs and re-deploying.  We are also planning compose integration as well.  Thanks!
