### ISSUE TITLE
Automatic get CPU and memory info of the engine

### ISSUE THREAD

**Issue by hangyan** [shipyard/shipyard#387]
![image](https://cloud.githubusercontent.com/assets/3939015/5522005/667a768a-89ea-11e4-95af-6dc7a47a7c7c.png)
Since docker 1.4.1(may be earlier) has provide the cpu number and total momery,seems we can add an option to atomatic get it.

In add-engine command,after set the dockerclient,I think we can use the client to obtain the infomation and update it in the rethinkdb

**Comment by tombee** [comment]
@ehazlett 
What needs to change for this?  Do we still prompt the user for the CPU/Memory for the engine?

**Comment by ehazlett** [comment]
I'm not sure this is valid anymore with Swarm.  In Swarm we aren't guaranteed to be able to connect to the node and get this info.  Perhaps we can open a PR against Swarm that would add this to the `info` endpoint?

**Comment by ehazlett** [comment]
This is handled via swarm and is in v3.  We can now see the node info.  closing.
