### ISSUE TITLE
Random CPU spikes

### ISSUE THREAD

**Issue by Stono** [shipyard/shipyard#392]
Hi, 
I'd say every 3-4 seconds controller uses ~35-40% cpu for a few seconds, and then drops off:
8309 root      20   0  400412  17784   5176 S  __35.2__  0.3  12:02.22 controller

I've only got three containers in shipyard atm, i'm wondering what this cpu usage could be as it feels like unnecessary load on the server?

Thanks

**Comment by ehazlett** [comment]
hmm what are the versions (shipyard, docker, OS)?  there is a health check
that runs for the hosts but i think that is configured for 10 seconds and
it just does a GET so it shouldn't eat that much.

**Comment by Stono** [comment]
Shipyard Latest (pulled this morning to validate your https fix)
Docker: 1.4.1 build 55bc2ff8 (latest)
OS: Centos7 minimal on kernel 3.10.0-123.13.2

I suppose it could be the additional overhead of the SSL negotiation? 
If I "time docker ps", which is also using TLS, it takes ~/ 260ms

**Comment by ehazlett** [comment]
Hmm perhaps but I wouldn't think it would be that much.  Could you profile
a few runs of "docker ps" to see if the CPU load matches?

**Comment by Stono** [comment]
Just done it, docker uses around 1% - so it's not that.
Perhaps something to do with how shipyard is invoking/validating TLS?  Not sure without profiling shipyard components!

**Comment by Stono** [comment]
Hi @ehazlett, a little more investigation.  I've lowered the certificates from 4096 to 2048 and now the cpu spikes are 10-12%, so i'm definitely feeling that it's SSL overhead

**Comment by Stono** [comment]
Also the response time, as reported by the web ui has dropped from 1400ish to 200-300

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
