### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by hbokh** [shipyard/shipyard#393]
Happy new year!
When deploying a container from both the webUI and / or CLI I get JSON input error(s) like this:

`FATA[0000] error running container: unexpected end of JSON input`

First with my own settings, but later on even when using this specific example from the docs:
```
shipyard cli> shipyard run --name ehazlett/go-demo \
    --cpus 0.1 \
    --memory 32 \
    --type service \
    --hostname demo-test \
    --domain local \
    --link redis:db \
    --port tcp/10.1.2.3:80:8080 \
    --port tcp/::8000 \
    --restart "on-failure:5" \
    --env FOO=bar \
    --label dev \
    --pull
```

Engine has been setup on CoreOS 550.0.0 like this:
```
shipyard cli> shipyard inspect-engine e08564b8-d604-48e8-8a37-ae6aadff05d9ae6aadff05d9
{
    "id": "e08564b8-d604-48e8-8a37-ae6aadff05d9",
    "engine": {
        "id": "coreos01.internal",
        "addr": "http://coreos01.internal:2375/",
        "cpus": 2,
        "memory": 4096,
        "labels": [
            "CoreOS",
            "dev",
            "local"
        ]
    },
    "health": {
        "status": "up",
        "response_time": 14727148
    },
    "docker_version": "1.4.1"
}
```

Any hints?

**Comment by hbokh** [comment]
Found the cause:
`"addr": "http://coreos01.internal:2375/",`
Had to remove the trailing slash after port-number to make it look like this:
`"addr": "http://coreos01.internal:2375",`
Will close the issue.

**Comment by ehazlett** [comment]
thanks!
