### ISSUE TITLE
allow unsecured private registry

### ISSUE THREAD

**Issue by cristifalcas** [shipyard/shipyard#395]
When using a private registry we add this for the image:
registry.hostname:5000/base

This is throwing the following error:

500 Internal Server Error: Invalid registry endpoint https://registry.hostname:5000/v1/: Get https://registry.hostname:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.hostname:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.hostname:5000/ca.crt

**Comment by ehazlett** [comment]
I believe you need to add that in the docker daemon config.  Shipyard does
not do anything for ssl as far as registries nor does it manage the actual
daemon options.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
