### ISSUE TITLE
Can't add Engine via docker.sock

### ISSUE THREAD

**Issue by mauimauer** [shipyard/shipyard#396]
FATA[0000] error adding engine: Get unix:///docker.sock/_ping: unsupported protocol scheme "unix"

**Comment by EmileVauge** [comment]
Same for me :)

**Comment by benhosmer** [comment]
@mauimauer Would you mind sharing how you accomplished this with socat?

**Comment by ehazlett** [comment]
You can see an example here https://github.com/ehazlett/dockerfiles/tree/master/docker-proxy
