### ISSUE TITLE
Web hooks are not working

### ISSUE THREAD

**Issue by EmileVauge** [shipyard/shipyard#397]
I cannot get this feature working. DockerHub gets an error calling my url and when I test it locally, I get a 404 error.

**Comment by EmileVauge** [comment]
OK, I found the problem. Sorry for the inconvenience. Do you know if it's possible to force the name of the container created after a web hook call?

**Comment by ehazlett** [comment]
Right now you can't. However it probably wouldn't be hard to add.

**Comment by EmileVauge** [comment]
That  would be a nice feature :) If you want to run a container with env variables or every other non default parameter, you can't do that in Shipyard with web hooks.

**Comment by ehazlett** [comment]
By default, it will use the entire container config.  It just creates a new
container name because I didn't want to destroy the container before
launching -- however I have to do that anyway if you specify dedicated
ports.

**Comment by Stono** [comment]
What was the problem?  I get 404s too...
http://127.0.0.1:8000/hub/webhook/ded2e55ee2311a50

**Comment by ehazlett** [comment]
If you are running shipyard in a container, you will almost never use
127.0.0.1 as that is the local IP of the container not the host.  Change it
to use whatever the IP is of the actual Docker host (10.1.2.3, etc).

**Comment by AnalogJ** [comment]
It seems like this still isnt working. Could it have something to do with the fact that we arn't doing a validation call to `callback_url` which is in the json payload? Though honestly that shouldnt matter, it seems like its only really used for webhook chaining... I just have no idea why shipyard is ignoring the webhook payload.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
