### ISSUE TITLE
allow specification of "name" in api container deploy

### ISSUE THREAD

**Issue by thecb4** [shipyard/shipyard#398]
When specifying creation of a container in the API POST, the name of the container is automatically set.  

Should probably have "image" as an option and "name" as an option.

Where
{
  image:ehazlett/elasticsearch
  name:es
...
}

**Comment by seedsofcode** [comment]
close this...
kept digging and found "container_name" to pass to the POST request

**Comment by ehazlett** [comment]
Yeah "container_name" is what you want.  I noticed it was missing from the
API docs -- I'll get that added.  Thanks!

**Comment by seedsofcode** [comment]
Thanks!!

**Comment by ehazlett** [comment]
This is fixed in v3.  Thanks!  For updated api docs, see https://shipyard-project.com/docs/api
