### ISSUE TITLE
api mount volume from host

### ISSUE THREAD

**Issue by thecb4** [shipyard/shipyard#399]
trying to mount volume from host in container post api call.  Not sure what I may be doing incorrectly?

"volumes": [
		  "/xxx/yy:/elk"
	  ]

The container recognizes and mounts /elk, but does not bind it to the host /xxx/yy

Using 2.0.4 so I can have unix socket capability (not working in latest release).

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!  For updated api docs see https://shipyard-project.com/docs/api
