### ISSUE TITLE
Allow running shipyard-cli non-interactively

### ISSUE THREAD

**Issue by brmakana** [shipyard/shipyard#407]
Hello,

I would love to use Shipyard as part of my build process, but I need the ability to script the shipyard-cli. I've tried without luck to do this - here's an example:

```bash
$docker run -a stdin -t shipyard/shipyard-cli shipyard login <<EOF
> http://test:8080
> admin
> shipyard
> EOF
FATA[0000] cannot enable tty mode on non tty input    
```

Is there a way to do this?

**Comment by ehazlett** [comment]
I haven't tried this but what happens if you add the "-i" flag to docker to
allocate the tty?

**Comment by brmakana** [comment]
It will still fail - I tried all different permutations of the command. I'll paste each result for completeness: 
```
$docker run -a stdin -it shipyard/shipyard-cli shipyard login <<EOF
> http://test:8080
> a
> b
> EOF
FATA[0000] cannot enable tty mode on non tty input 
```

```
$docker run -it shipyard/shipyard-cli shipyard login <<EOF
> http://test:8080
> a
> b
> EOF
FATA[0000] cannot enable tty mode on non tty input      
```

```
$docker run -i shipyard/shipyard-cli shipyard login <<EOF
> a
> b
> c
> EOF
URL: Username: Password: panic: inappropriate ioctl for device
```

**Comment by dayer4b** [comment]
I think I have this working.  First, I ran the shipyard/shipyard-cli image and logged into it:

```bash
$ sudo docker run -it shipyard/shipyard-cli /bin/bash
shipyard cli> shipyard login
...
shipyard cli> exit
```

After exiting, that container stops, but its state is saved.  Run `docker ps -a` to find it, then commit it to a new image.  In this example, the random name of that container was `trusting_torvalds`:

```bash
$ sudo docker commit trusting_torvalds local/shipyard-cli
```

Now you have a saved local Docker image that is "pre-authenticated."  If you want to script some Shipyard CLI stuff, you can just use that image like so:

```bash
$ sudo docker run -it --rm local/shipyard-cli shipyard info
Controller Version: 2.0.8
Cpus: 4.00
Memory: 8096.00 MB
Containers: 3
Images: 29
Engines: 1
Reserved Cpus: 6.00% (0.24)
Reserved Memory: 9.49% (768.00 MB)
$
```

You could go even further and wrap that Docker command into a shell script that accepts input and pipes input right into the command:

```bash
#!/bin/bash

# use the local/shipyard-cli image (customized with pre-authentication)
sudo docker run --rm local/shipyard-cli "$@"
```

**Comment by brmakana** [comment]
Nice, that works great. Thanks for the solution!
