### ISSUE TITLE
unable to scale container

### ISSUE THREAD

**Issue by mbonski** [shipyard/shipyard#409]
Hi I have some containers running java Spring boot applications and when I want to scale the container I'm getting:

     "error scaling container: no scheduler for type"

Did anyone had this issue and know how to get round it?

**Comment by ehazlett** [comment]
How did you deploy them?  What type did you use?

**Comment by mbonski** [comment]
I see now. The host is no set I've used docker run command to start the container. Does this mean that scaling will not work with containers started directly using docker run command?

**Comment by ehazlett** [comment]
Unfortunately no. Shipyard can only scale containers it knows what the
resource limits and type of scheduling they run under.

In the near future this will be possible as we are moving the backend to
Swarm.  Shipyard will then use Swarm for all scheduling.

**Comment by isymbo** [comment]
what's the relationship of CitadelToolkit and Swarm then? Is only scheduling part replaced by Swarm?

**Comment by ehazlett** [comment]
Yes the scheduling system of Shipyard has been replaced with Swarm.
