### ISSUE TITLE
shipyard-cli events would exit with error

### ISSUE THREAD

**Issue by isymbo** [shipyard/shipyard#412]
shipyard-cli events would exit with error, hit in v2.0.8

<pre>
shipyard cli> shipyard events
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x713aa0, 0x91ec6f)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.eventsAction(0xc208042210)
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/events.go:40 +0x953
github.com/codegangsta/cli.Command.Run(0x75b510, 0x6, 0x0, 0x0, 0x7913b0, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/home/dev/dev/gocode/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0xc2080540c0, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
	/home/dev/dev/gocode/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/cli.go:65 +0x4f9

goroutine 19 [finalizer wait]:
runtime.park(0x4244c0, 0x922cb8, 0x920f09)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x922cb8, 0x920f09)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
</pre>

**Comment by isymbo** [comment]
With below code changes, the error would go away.

<pre>
symbo@FunU:~/gitlist/afanti$ git diff cli/events.go
diff --git a/cli/events.go b/cli/events.go
index f5cd0a2..936abdb 100644
--- a/cli/events.go
+++ b/cli/events.go
@@ -36,11 +36,11 @@ func eventsAction(c *cli.Context) {
                tags := strings.Join(e.Tags, ",")
                message := e.Message
                engine := ""
-               if e.Container != nil {
+               if e.Container.ID != "" {
                        cntId := e.Container.ID[:12]
                        message = fmt.Sprintf("container:%s %s", cntId, e.Messag
                }
-               if e.Engine != nil {
+               if e.Engine.ID != "" {
                        engine = e.Engine.ID
                }
                fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", e.Time.Format(time.RubyDa
</pre>

**Comment by isymbo** [comment]
This is due to e.Container is not a null pointer, it's empty value, but not nil.

Similar error happens to the GUI, changes below would make js error go away

<pre>
symbo@FunU:~/gitlist/afanti$ git diff controller/static/app/filters.js
diff --git a/controller/static/app/filters.js b/controller/static/app/filters.js
index 613ae1a..aa75221 100644
--- a/controller/static/app/filters.js
+++ b/controller/static/app/filters.js
@@ -54,9 +54,9 @@ angular.module('shipyard.filters', [])
         return function (e) {
             var evt = "";
             evt += e.type + " ";
-            if (e.container !== undefined) {
+            if (e.container.id !== undefined) {
                 evt += truncate(e.container.id) + " " + e.container.image.name 
-            } else if (e.engine !== undefined) {
+            } else if (e.engine.id !== undefined) {
                 evt += e.engine.id + " (" + e.engine.addr + ") ";
             } else {
                 if (e.message !== undefined) {
</pre>

**Comment by ehazlett** [comment]
@isymbo thx for reporting!

**Comment by ehazlett** [comment]
This should be fixed in master.  Thanks!
