### ISSUE TITLE
Why shipyard can't start 

### ISSUE THREAD

**Issue by hanxy** [shipyard/shipyard#416]
I execute command "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start", but shipyard/shipyard can't started! the detail is follow:

	root@docker01:/home/docker/hanxy/scripts# docker ps
	CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS               NAMES
	0471f9a76fd6        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    22 minutes ago      Up 22 minutes                           shipyard-rethinkdb        
	e141e540245f        shipyard/rethinkdb:latest   "/bin/bash -l"         22 minutes ago      Up 22 minutes                           shipyard-rethinkdb-data   
	
	
	root@docker01:/home/docker/hanxy/scripts# docker run -it -p 8080:8080 -d --name shipyard --link shipyard-rethinkdb:rethinkdb shipyard/shipyard
	16ea16c2ac7eaa721b119fe6f1565fb3144ab2b95d09a2a4f769ef89ca33b85d
	2015/02/04 17:20:50 Error response from daemon: Cannot start container 16ea16c2ac7eaa721b119fe6f1565fb3144ab2b95d09a2a4f769ef89ca33b85d: link: command not found

**Comment by ehazlett** [comment]
This is working with the deploy image.  What version of Docker are you on?

**Comment by Telmo** [comment]
I am running into a similar situation since updated docker to `1.4.1`

The logs show:
```
time="2015-01-18T04:27:34Z" level="warning" msg="unable to detect docker version: Not found"
```
over and over 

My docker info is:

```
[root@shipyard-wc-1p ~]# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by ehazlett** [comment]
I have just confirmed this is working with Docker 1.4.1.  Can you tell me more about your setup?

**Comment by ehazlett** [comment]
```
ehazlett ~> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start
Pulling image: shipyard/rethinkdb
Starting Rethinkdb Data
Starting Rethinkdb
Starting Shipyard
Pulling image: shipyard/shipyard:latest
Shipyard Stack started successfully
 Username: admin Password: shipyard
ehazlett ~> docker ps
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                                                                         NAMES
0bffe8de517b        shipyard/shipyard:2.0.8     "/app/controller"      29 seconds ago      Up 29 seconds       0.0.0.0:8080->8080/tcp                                                        shipyard                  
c95ea6eea7be        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    31 seconds ago      Up 30 seconds       0.0.0.0:49153->28015/tcp, 0.0.0.0:49154->29015/tcp, 0.0.0.0:49155->8080/tcp   shipyard-rethinkdb        
3b86a6b730c1        shipyard/rethinkdb:latest   "/bin/bash -l"         31 seconds ago      Up 31 seconds       8080/tcp, 28015/tcp, 29015/tcp                                                shipyard-rethinkdb-data   
```

**Comment by ehazlett** [comment]
Try doing a `docker pull shipyard/deploy` to make sure you have the latest version.

**Comment by ehazlett** [comment]
Can you report the version of `shipyard/deploy` you have?

**Comment by hanxy** [comment]
@ehazlett  I use the docker1.3.0 and docker1.3.1 version

**Comment by hanxy** [comment]
@ehazlett  docker1.3.0 and docker1.3.1 version not support?

**Comment by Telmo** [comment]
I am not using `shipyard/deploy` but both images individually linked in docker. This is my fig file:

```
shipyard:
  image: shipyard/shipyard:2.0.8
  ports:
    - "8080:8080"
  links:
    - rethinkdb:rethinkdb

rethinkdb:
  image: shipyard/rethinkdb:latest
  expose:
    - "8080"
    - "28015"
    - "29015"
````

**Comment by ehazlett** [comment]
Shipyard tracks the latest stable of docker. I've been thinking of
releasing "api compatible" tags where a certain version would be tagged
against a certain docker version but the maintenance burden worries me.

**Comment by ehazlett** [comment]
@Telmo Can you try the shipyard/shipyard:test image and see if it does the same?

**Comment by Telmo** [comment]
@ehazlett I destroyed the running containers and used the shipyard/shipyard:test image and everything works fine now. However I have to re-add all my engines now. Could you guys by any chance document how to backup the data from the rethinkdb container? or whats the mount point within the rethink DB container that we could mount?

**Comment by ehazlett** [comment]
Good!  Simply don't kill the rethinkdb containers.  That's why we use the
data container and links.  The deploy image can manage this for you too --
it has an "upgrade" command.

**Comment by hanxy** [comment]
@ehazlett I know your means，currently i can't use shipyard on docker1.3.2 and only used by docker1.4.1?

**Comment by ehazlett** [comment]
Yes currently Shipyard tracks the latest Docker stable.  You could try an older version.  Perhaps we could put the Docker API version that it works with when we release.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
