### ISSUE TITLE
unable to create engine with SSL endpoint via API 

### ISSUE THREAD

**Issue by jaychris** [shipyard/shipyard#417]
I've tried several variations of this:

newEngine.json:
```
{
  "id": "",
  "ssl_cert": "-----BEGIN CERTIFICATE----- <lots of cert stuff here>-----END CERTIFICATE-----",
  "ssl_key": "-----BEGIN RSA PRIVATE KEY-----<lots of key stuff here>-----END RSA PRIVATE KEY-----",
  "ca_cert": "<ditto the above>",
  "engine": {
    "id": "myHost",
    "addr": "https://myHost:2376",
    "cpus": 32,
    "memory": 128000,
    "labels": [
      "128GB"
    ]
  }
}
```

This is the command I'm using to POST to the api:
```
curl -i -X POST -s -H 'X-Service-Key: <service_key_redacted>' -H "Content-Type: application/json" \
--data-binary "@newEngine.json" shipyard:8080/api/engines
```

and this is the response I get:

```
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Date: Thu, 05 Feb 2015 23:05:52 GMT
Content-Length: 49

crypto/tls: failed to parse certificate PEM data
```

Not sure what I am missing here, I've tried different variations.  I can add engines with the UI (cutting/pasting certificate info) with no issue and I can add via the API, as long as I don't try to add a ssl-endpoint engine.  From what I see here (https://golang.org/src/crypto/tls/tls.go) it seems to think that the certificate length is 0.

**Comment by jaychris** [comment]
It looks like the issue is that the certificate needs to be output into one line with "\n" at the join of each line.  So, just a bit of formatting to do when parsing a cert for inclusion into the JSON.

**Comment by ehazlett** [comment]
you beat me to it ;)  thanks for posting back the fix!
