### ISSUE TITLE
Shipyard API error

### ISSUE THREAD

**Issue by devopsrhce** [shipyard/shipyard#423]
Hi,

I’m trying to create a new container using API. I created a service-key following this link http://shipyard-project.com/docs/servicekeys/

I get the JSON error:

root@shipyard-node1:~# curl -H "Content-Type: application/json" -H 'X-Service-Key: k4o7OdcS/wjk3SZpqwuYMFvOWr3J4ewg39Li' -X 'POST' -d '{"name":"redis:latest","container_name":"redis:latest","cpus":2,"memory":2048,"type":"service","hostname":"","domain":"","labels":"","type":"service","restart_policy":{"name":"always" }}' http://192.168.1.1:8080/api/containers
json: cannot unmarshal string into Go value of type []string

**Comment by ehazlett** [comment]
The second `"type"` shouldn't be there and `"labels"` should be an array (list) - `"labels": ["local", "dev"]` etc.

**Comment by devopsrhce** [comment]
Thank you for quick response.

While I do a POST of this string  {"name": "redis:latest","container_name": "redis:latest","cpus": 2,"memory": 2048,"type": "service","domain": "","hostname": "","labels": ["local"],"restart_policy": {"name": "always"}} 

I get the following error:
Status
500 Internal Server Error 
no eligible engines to run image


However I have two engines with available resources for my requested container.
http://192.168.1.1:8080/api/engines
[{"id":"26a180fd-0e1d-4f7e-93c5-bb578680d37b","engine":{"id":"snode2", "addr":"http://192.168.1.10:2375","cpus":4,"memory":8192,"labels":["node2"]},"health":{"status":"up","response_time":1388873},"docker_version":"1.4.1"},{"id":"1b399620-a936-4e0e-a317-3f7e78373604","engine":{"id":"snode1", "addr":"http:// 192.168.1.11:2375","cpus":4,"memory":8192,"labels":["node1"]},"health":{"status":"up","response_time":1568273},"docker_version":"1.4.1"}]

**Comment by ehazlett** [comment]
Do you already have containers running that would be using some of the resources?

**Comment by devopsrhce** [comment]
No, these nodes haven’t any containers or images.  

My plan is to run a containers on “some” node that has the most available resource. In case the requested image is not exist in the node it should download from public or private hub registry.

**Comment by linecheng** [comment]
fllowing the guid  http://shipyard-project.com/docs/api/#post-containers
 I got a same error like that 

```
no eligible engines to run image
```


this is my script
```
curl -H "X-Service-Key:cKYTOIVUrTUIgWUao6kpoAxuWJYUmiS9i7wu" \
-H "Content-Type:Application/json" \
-X POST \
--data \
'{ 
  "name": "shawn/nginx",
  "container_name": "demonginx",
  "cpus": 0.1,
  "memory": 32,
  "type": "service",
  "hostname": "",
  "domain": "",
  "labels": ["local"]
}' \
http://192.168.5.152:8080/api/containers

```

I solved this problem by modifing  `labels` to `lables`  .....

this is scripts 

```
curl -H "X-Service-Key:cKYTOIVUrTUIgWUao6kpoAxuWJYUmiS9i7wu" \
-H "Content-Type:Application/json" \
-X POST \
--data \
'{ 
  "name": "shawn/nginx",
  "container_name": "demonginx",
  "cpus": 0.1,
  "memory": 32,
  "type": "service",
  "hostname": "",
  "domain": "",
  "lables": ["local"]
}' \
http://192.168.5.152:8080/api/containers

```

It is Ok Now.

**Comment by ehazlett** [comment]
That will simply omit the labels and choose a random node.  Are you sure
you are specifying a label that is on one of the engines?

**Comment by linecheng** [comment]
I am so sorry for that , I have maked an error on `labels`.
At first ,I don't understand the purpose of  `labels`.

Thank you for your reminding, I change labels of  my engine  to `local` , and it works very well.

Thanks again.
