### ISSUE TITLE
Setting up docker images true the webinterface, documentations to learn this?

### ISSUE THREAD

**Issue by rubytastic** [shipyard/shipyard#424]
I found setting up an docker container  true the interface not easy.
Most of the terms listed there I don't know.

Are there some recommended documentations for the container page in shipyard or some examples with configured docker containers to learn how to proceed in this?

I find it all very confusing and the provided documentation on shipyard does not address the provided input fields with some clarification. 

Thank you!

**Comment by ehazlett** [comment]
Check the docs provided here http://shipyard-project.com/docs/containers/.
