### ISSUE TITLE
Multiple Engines of the same docker daemon can be added

### ISSUE THREAD

**Issue by cdancy** [shipyard/shipyard#425]
Can seemingly add an infinite number of the same docker daemon/engine over and over again.

**Comment by vbichov** [comment]
I'm seeing the same issue.

**Comment by cdancy** [comment]
@vbichov this should be a non-starter with shipyard v3 as it will use docker-swarm to manage docker nodes/daemons.

**Comment by ehazlett** [comment]
@cdancy this is fixed in v3.  you actually can only specify a single swarm master which then uses its nodes.  thanks for the report!
