### ISSUE TITLE
deploy doesn't work

### ISSUE THREAD

**Issue by DarkPark** [shipyard/shipyard#429]
```
$ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start

Unable to find image 'shipyard/deploy' locally
Pulling repository shipyard/deploy
ec8a310a5557: Download complete 
511136ea3c5a: Download complete 
19e1e1d132d3: Download complete 
e153b2ff5a59: Download complete 
Pulling image: shipyard/rethinkdb
error pulling shipyard image: Not found
```

**Comment by ehazlett** [comment]
This is working fine for me.  Where are you pulling from (can you do a lookup of the registry endpoint you are hitting)?

**Comment by DarkPark** [comment]
just a regular https://registry.hub.docker.com/
no custom configuring or tuning
stock docker from ubuntu 14.10

**Comment by ehazlett** [comment]
Are you behind any proxies or firewalls that could be interfering?

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
