### ISSUE TITLE
QuickStart: Why publish all RethinkDB ports?

### ISSUE THREAD

**Issue by Romke-vd-Meulen** [shipyard/shipyard#431]
It's nice that http://shipyard-project.com/docs/quickstart/ warns me that following the guide leaves all my rethinkDB ports publicly accessible. But why does the quickstart or Shipyard Deploy leave these ports publicly accessible at all? Wouldn't it be much safer to run e.g.:

```
docker run -it -d --name shipyard-rethinkdb --volumes-from shipyard-rethinkdb-data -p 127.0.0.1:49153:8080 -p 127.0.0.1:49154:28015 -p 127.0.0.1:29015:29015 shipyard/rethinkdb
```

so that Shipyard can locally access RethinkDB, but public access is restricted?

**Comment by ehazlett** [comment]
This only works if shipyard and rethinkdb are colocated.  This breaks if
you want to add a node to the cluster or another shipyard instance for HA.

**Comment by Romke-vd-Meulen** [comment]
True. I wonder though if deploying Shipyard on a cluster is a typical use-case, especially for somebody reading the quickstart. Wouldn't it make more sense to explain the simple, secure setup in the quickstart, and describe how to deploy a secure, distributed Shipyard network elsewhere?

I'm simply worried that even with this warning attached, a lot of people are going to leave unsecured, open access to their RethinkDB instance running on production servers. And if the DB data leaks, anybody can read your entire Docker setup. That would be a huge security risk, wouldn't it?

**Comment by ehazlett** [comment]
That is a valid point.  I think setting this to localhost by default would be good.  Since we use the data volume you could always start a new RethinkDB instance with the ports exposed to grow.  I will do some testing to make sure it doesn't break anything.  Thanks for the feedback!

**Comment by Romke-vd-Meulen** [comment]
No problem!

**Comment by ehazlett** [comment]
I'm going to re-open so I can remember to update this :)  Thanks!

**Comment by jankeromnes** [comment]
Yes please! :+1:

**Comment by jankeromnes** [comment]
Actually, since the containers are linked, what is the point of exposing the RethinkDB ports at all? Maybe the Quickstart should just contain:

    docker run -it -d --name shipyard-rethinkdb --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb

And add a note like "If you want to expose the RethinkDB ports locally, you can expose them by adding the `-p [...]` parameters".

**Comment by ehazlett** [comment]
Yeah that's probably a good idea.  Since we use the data volume, I don't
think there is any reason to expose it.  Thanks!

**Comment by tombee** [comment]
@ehazlett I've updated shipyard/shipyard, shipyard/shipyard-project.com and shipyard/shipyard-deploy

**Comment by ehazlett** [comment]
There is a new deployment method (https://shipyard-project.com/docs/deploy) that no longer exposes rethinkdb.  Thanks!
