### ISSUE TITLE
QuickStart: correction on data volume container command

### ISSUE THREAD

**Issue by Romke-vd-Meulen** [shipyard/shipyard#432]
The QuickStart uses this command to set up a data volume container:

```
docker run -it -d --name shipyard-rethinkdb-data \
    --entrypoint /bin/bash shipyard/rethinkdb -l
```

This actually runs the data volume container persistently by launching bash. That's not necessary: data volume containers don't need to run at all. Following [Docker's documentation](https://docs.docker.com/userguide/dockervolumes/) a better way would be:

```
docker create --name shipyard-rethinkdb-data shipyard/rethinkdb
```

which creates the volume container but doesn't run it.

**Comment by ehazlett** [comment]
Yes you are correct, however, I like to show that a container is actually
doing something and serving a purpose.  It allocates little resources and
also prevents you from removing a container by filtering for stopped
containers.

**Comment by Romke-vd-Meulen** [comment]
Ah, I see. Fair enough.
