### ISSUE TITLE
Web UI always tries to pull latest image

### ISSUE THREAD

**Issue by apognu** [shipyard/shipyard#434]
Hi,

According to what I'm seeing, the Web UI always tries to pull the latest image when deploying a container. The CLI offers an option --pull that will enable this behavior.

As far as I know, there is no way from the Web UI, to prevent that. It can be quite useful when testing locally on unpublished images.

Cheers.

**Comment by ehazlett** [comment]
Yes unfortunately this was needed for the UX in the web ui.  Once we migrate to Swarm, we will use the default behavior of Swarm (which will only pull the first time).

Thanks for the feedback!
