### ISSUE TITLE
Run the Web UI over HTTPS?

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#435]
Hello! The [quickstart docs](http://shipyard-project.com/docs/quickstart/) explain how to start `rethinkdb` (with [3 ports exposed publicly](https://github.com/shipyard/shipyard/issues/431)) and `shipyard`.

Is there a way to start `shipyard` so that it listens to port 8080 but uses a local `.key` file to serve HTTPS? You could then access it at `https://<your-host-ip>:8080`.

I don't like my login transactions to happen over HTTP and I have an SSL certificate.

**Comment by ehazlett** [comment]
Thanks for the feedback.  We recommend to put Shipyard behind a load balancer or reverse proxy (such as nginx/haproxy) and terminate SSL there.  There are no current plans to add TLS to Shipyard itself (we already support TLS to the engines).

**Comment by jankeromnes** [comment]
Makes sense, thanks for the quick reply! I'll use [scoutcamp](https://github.com/espadrine/sc) then.
