### ISSUE TITLE
Extend the Web UI?

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#436]
Is it possible to extend the Web UI without forking the project?

And run some pages on different ports (e.g. a front page on port 443)? I'd like to add several custom pages, a front page, and reuse Shipyard's login system to have users sign in and be allowed to use certain pages.

**Comment by ehazlett** [comment]
If you just want to add certain pages over SSL, I would recommend using a load balancing service (nginx/haproxy) and terminate SSL there.  This is a common pattern.

If you want to customize specific page content you will need to fork or open a PR.

Thanks!
