### ISSUE TITLE
Cannot add engine by shipyard cli

### ISSUE THREAD

**Issue by Huntter** [shipyard/shipyard#437]
When I try to add an engine by shipyard cli, it is cannot added, I tried the following ways, one is via `http` and another one is via `https`.

```shell
shipyard cli> shipyard add-engine --id local --addr http://192.168.240.78:2375 --cpus 4.0 --memory 4096 --label local --label dev
FATA[0000] error adding engine: Get http://192.168.240.78:2375/_ping: dial tcp 192.168.240.78:2375: connection refused
 
shipyard cli> shipyard add-engine --id local --addr https://192.168.240.78:2376 --cpus 4.0 --memory 4096 --label local --label dev
FATA[0000] error adding engine: Post http://192.168.240.78:8080/api/engines: EOF
```

**Comment by Huntter** [comment]
```
curl http://192.168.240.98:2375/_ping
curl: (7) Failed to connect to 192.168.240.98 port 2375: Timed out
```

**Comment by Huntter** [comment]
![image](https://cloud.githubusercontent.com/assets/4601460/6700985/358598c0-cd51-11e4-9043-937223a5a7a2.png)

**Comment by ehazlett** [comment]
A timeout is usually a firewall issue or that the Docker engine is not
listening on tcp.  Could you check those?

**Comment by Huntter** [comment]
@ehazlett Thanks. I start the shipyard by the option 1 from the shipyard homepage, and I disabled the selinux and iptables (centos).
And I'm not sure is the docker engine listening on tcp, below is the containers info:
![image](https://cloud.githubusercontent.com/assets/4601460/6703806/93b47eaa-cd7b-11e4-99a8-558b6a2e64b9.png)


![image](https://cloud.githubusercontent.com/assets/4601460/6703784/4eb1504e-cd7b-11e4-8a7c-feb80a7ab142.png)

**Comment by Huntter** [comment]
Yep, the problem is the docker bind to the default port 4243, so when create the shipyard engine, should using the *4243* port, I'm confused by the web "Address" field.

**Comment by dokier** [comment]
Hi, I just installed shipyard and I don't see the Engine Tab in the GUI, and when I try from CLI I get 
FATA[0000] error adding engine: 404 page not found 

Why would that be? I see online there used to be an ENGINE Tab.

**Comment by ehazlett** [comment]
we use swarm for the clustering. To add a node you can use the deploy
script. see the docs for details. shipyard-project.com

**Comment by dokier** [comment]
I went with the default automated installation but I don't see any containers or images. Shouldn't at least see the ones shipyard is using? I also have a mysql container running. All this is on the same host.

![shipyard](https://cloud.githubusercontent.com/assets/15022774/10353748/19ea1910-6d1f-11e5-965e-aeda95bdcdc2.png)
