### ISSUE TITLE
json: cannot unmarshal string into Go value of type float64

### ISSUE THREAD

**Issue by radhub** [shipyard/shipyard#440]
Hi,

When I ran a  container provisioning against shipyard, I got the error
json: cannot unmarshal string into Go value of type float64

Command I ran to provision
 curl -s -X POST -H "Content-Type: application/json" -H "X-Service-Key: <key>" http://10.10.0.10:8080/api/containers -d '{"environment":{"FOO":"bar"},"restart_policy":{"name":"none"},"type":"service","container_name":"Test","args":[],"bind_ports":[],"labels":["local"],"name":"ubuntu:sshd", "memory":32,"cpus":"0.1","domain":"","hostname":"Test"}'

Shipyard version that I am running
docker images | grep shipyard
shipyard/deploy         latest              ba94b7a205d6        11 days ago         6.514 MB
shipyard/shipyard       2.0.10              f1be70df06c1        2 weeks ago         36.26 MB
shipyard/shipyard       latest              f1be70df06c1        2 weeks ago         36.26 MB
shipyard/shipyard-cli   latest              b73f9452c2ff        10 weeks ago        146.3 MB
shipyard/shipyard-cli   2.0.8               b73f9452c2ff        10 weeks ago        146.3 MB
shipyard/rethinkdb      latest              3321c25168cd        5 months ago        291 MB

Docker container version that I am running
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1

Thanks and Regards,

~ Vijay

**Comment by radhub** [comment]
Additional information - 
When I look at the logs of the shipyard container i.e. docker logs -f 18e92795fa9e, I get the below error
time="2015-03-20T11:19:28Z" level="warning" msg="error decoding image: json: cannot unmarshal string into Go value of type float64"
time="2015-03-20T11:25:26Z" level="warning" msg="error decoding image: json: cannot unmarshal string into Go value of type float64"

PFB details of my running containers
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                                                                         NAMES
18e92795fa9e        shipyard/shipyard:2.0.10    "/controller"          20 seconds ago      Up 1 seconds        0.0.0.0:8080->8080/tcp                                                        shipyard
755b69bb5f84        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    About an hour ago   Up 5 seconds        0.0.0.0:49156->28015/tcp, 0.0.0.0:49157->29015/tcp, 0.0.0.0:49158->8080/tcp   shipyard-rethinkdb
51a87cc2d43d        shipyard/rethinkdb:latest   "/bin/bash -l"         About an hour ago   Up 6 seconds        29015/tcp, 8080/tcp, 28015/tcp                                                shipyard-rethinkdb-data

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
