### ISSUE TITLE
catn't run deploy image

### ISSUE THREAD

**Issue by alanRiveros** [shipyard/shipyard#441]
hi, when i run 
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start
docker send me the next msg

Pulling image: shipyard/rethinkdb
error pulling shipyard image: invalid character 'c' looking for beginning of value

**Comment by mbentley** [comment]
Sounds like you're running an old version of docker; probably from the docker-io package available from your distro.  Upgrading to the latest official docker version (1.5.0) should solve it.

**Comment by alanRiveros** [comment]
great it works thanky ou so much
