### ISSUE TITLE
shipyard server cannot identify the containers which were renamed by  `docker rename` command

### ISSUE THREAD

**Issue by LeonSin** [shipyard/shipyard#443]
At the beginning, I boot up a container named pentaho-parallel on a host. Then renamed it using command [`rename`](https://docs.docker.com/reference/commandline/cli/#rename)
```bash
docker rename pentaho-parallel pentaho-1
```
Next , I registered this host on shipyard server.But it still displayed the old name, pentaho-parallel. Furthemore, when hit the `restart` button of this container, it failed and display the following error info,
```
error restarting container: 500 Internal Server Error: Cannot restart container 3e513194763e012c1ae86664958902886e2bc1527b129e7a0bec26ac6e85f7ad: Cannot find child for /pentaho-parallel
```
![container-restart-error](https://cloud.githubusercontent.com/assets/3809597/6798650/4d596c3a-d24a-11e4-8052-371ba5df1d13.png)

**Comment by ehazlett** [comment]
Hmm so this looks like an issue with the links/names. Can you try the same
restart command on the host with docker and see if you have the same issue?

**Comment by LeonSin** [comment]
@ ehazlett
Thanks.That's the issue of [`docker rename`](https://github.com/docker/docker/issues/3036), not shipyard.
Better to delete the container next time. :)

**Comment by ehazlett** [comment]
@LeonSin thanks for confirming!
