### ISSUE TITLE
Can shipyard pull images from a private repository? 

### ISSUE THREAD

**Issue by ashish235** [shipyard/shipyard#448]
I 've a local repository running and have my docker is also running with --insecure-registry

docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d --insecure-registry 0.0.0.0:5000 &

An image is pushed into the local repository. 

docker push   localhost:5000/ole_app_patched  localhost:5000

[root@server1 ~]# curl -X GET http://172.16.201.41:5000/v1/search?q=
{"num_results": 1, "query": "", "results": [{"description": "", "name": "library/ole_app_patched"}]}

Now from the shipyard if I try pulling the image I get the below error.

Error: image library/ole_app_patched not found 

Even if I add the IP like 172.16.201.41:5000/ole_app_patched, I get the below error. 

invalid character 'I' looking for beginning of value 

How am I supposed to tag the repository name in the shipyard? 

Kindly help.

**Comment by ashish235** [comment]
Will this solve my problem? 
https://github.com/shipyard/docker-private-registry


Also will this work with self signed certificates?

**Comment by ehazlett** [comment]
You cannot use "localhost" as the shipyard container will use itself.  You need to use either the non-local IP or a DNS name for the registry.
