### ISSUE TITLE
Can't connect docker daemon running shipyard as engine

### ISSUE THREAD

**Issue by lucaro** [shipyard/shipyard#449]
I have multiple server running docker 1.5.0 on Ubuntu Server 14.04.02. One of them is running shipyard and I want to manage all of them via shipyard including the one it's running on. But whenever I try to add the engine I get the following error message:

Error

Get http://:*server_ip*:4243/_ping: dial tcp *server_ip*:4243: i/o timeout

Docker is configures identically on all servers and it worked fine for all the other ones. How can I get around this?

**Comment by ashish235** [comment]
Check your firewall if the port 4243 is allowed on the docker host machine. 

Also check if 4243 is listening all on that port.

**Comment by lucaro** [comment]
It was actually a firewall issue. Interestingly, I had to open the port for all interfaces to make it work...
