### ISSUE TITLE
Cannot connect to local Docker engine using SSL

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#452]
Hello! I'm trying to add my local Docker engine to Shipyard using SSL (filtered on localhost), on Ubuntu 14.04:

I generated SSL credentials for Docker and Shipyard, and a CA (files  `ca.crt`, `ca.key`, `shipyard.crt`, `shipyard.key`, `docker.crt` and `docker.key`).

I moved `docker.crt` and `docker.key` to `/var/run/`, and copied `ca.crt` there as well (renaming it `docker.ca`).

I made the Docker daemon use these, by appending the following line to `/var/default/docker`:

    DOCKER_OPTS="--tlsverify --tlscacert=/var/run/docker.ca --tlscert=/var/run/docker.crt --tlskey=/var/run/docker.key -H tcp://127.0.0.1:2376 -H unix:///var/run/docker.sock"

Trying the Docker client with Shipyard's certificates works:

    $ docker --tlsverify --tlscacert=ca.crt --tlscert=shipyard.crt --tlskey=shipyard.key -H 127.0.0.1:2376 ps
    CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                            NAMES
    c8690cbbef06        shipyard/shipyard:latest    "/controller"          14 minutes ago      Up 13 minutes       127.0.0.1:8080->8080/tcp         shipyard                                
    210d7995a469        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    14 minutes ago      Up 13 minutes       28015/tcp, 29015/tcp, 8080/tcp   shipyard/rethinkdb,shipyard-rethinkdb   
    6f92f9176335        shipyard/rethinkdb:latest   "/bin/bash -l"         14 minutes ago      Up 13 minutes       29015/tcp, 8080/tcp, 28015/tcp   shipyard-rethinkdb-data

However, when I try to add that engine in the Shipyard web interface:

    Name: docker-host
    Labels: local
    CPUs: 8
    Memory: 4096
    Address: https://127.0.0.1:2376
    SSL Certificate: [content of shipyard.crt]
    SSL Key: [content of shipyard.key]
    CA Certificate: [content of ca.key]

I get the following error:

    Error
    Get https://127.0.0.1:2376/_ping: dial tcp 127.0.0.1:2376: connection refused

What am I doing wrong? I bet this has something to do with `127.0.0.1` being the localhost of the `shipyard` container and not my host, but I don't know how to fix that.

Please help.

**Comment by jankeromnes** [comment]
P.S. I can provide bash scripts to help reproduce this issue.

**Comment by ehazlett** [comment]
You cannot use `127.0.0.1` as it refers to the shipyard container and not the host.  You will need to use a routable IP -- i.e. 192.168.x.x.

**Comment by jankeromnes** [comment]
Thanks!
