### ISSUE TITLE
Can the Shipyard CLI be used in batch mode?

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#453]
Hello,

I'm writing scripts to automatically setup Shipyard on Ubuntu/Debian. I'm at the point where Shipyard installs, but I'd like to use the API/CLI to login, change the admin password, and add the local Docker engine.

I managed to get an `auth_token` using the following command:

    curl -H "content-Type: application/json" -X POST -d '{"username":"admin","password":"shipyard"}' http://127.0.0.1:8080/auth/login | sed 's/.*"auth_token":"\([^"]\+\)".*/\1/' > auth_token

But apparently, this can't be used with the API...

Can the CLI be used in non-interactive batch mode? I'd like to call `shipyard change-password` and `shipyard add-engine` in my installation script, or maybe just `shipyard add-service-key` and do the rest with `curl` commands.

Please help.

**Comment by tombee** [comment]
Thanks for this, +1

**Comment by ehazlett** [comment]
You can just use `curl` with the auth token.  Instead of using the `X-Service-Key` header you will need to use `X-Access-Token: username:token` format.

**Comment by jankeromnes** [comment]
@ehazlett Thanks! However, using the `X-Access-Token` header doesn't seem to be enough because I always receive "unauthorized". Should other headers be used as well, e.g. a cookie?

**Comment by ehazlett** [comment]
This should work -- I use this:

curl -s -H 'X-Access-Token:
admin:$2a$10$7bGkeGydeL0fc0D4RnVeo.ElpShBzhp4Eodap/2123456790'
http://localhost:8080/api/containers

Make sure you include the username before the token

**Comment by ehazlett** [comment]
@jankeromnes were you able to use curl like above?

**Comment by jrwthll** [comment]
Hi, 

I'm also working on a shell script that should change the admin password after Shipyard has been deployed. 
I'm following the official documentation here: http://shipyard-project.com/docs/api/#auth-login

When I type 
curl -H "content-Type: application/json" -X POST http://localhost:8080/auth/login '{"username": "admin", "password": "shipyard",}'
I get the following response

EOF

[1/3]: "username": "admin" --> <stdout>
--_curl_--"username": "admin"
curl: (6) Could not resolve host: "username"

[2/3]:  "password": "shipyard" --> <stdout>
--_curl_-- "password": "shipyard"
curl: (6) Could not resolve host:  "password"

[3/3]:  --> <stdout>
--_curl_--
curl: (3) <url> malformed

Any ideas?

**Comment by ehazlett** [comment]
don't put a trailing slash after the password on the first curl.

**Comment by ehazlett** [comment]
sorry -- i meant trailing comma after `'shipyard'` in the curl.

**Comment by jrwthll** [comment]
I removed the comma, which now returns

EOF

[1/2]: "username": "admin" --> <stdout>
--_curl_--"username": "admin"
curl: (6) Could not resolve host: "username"

[2/2]:  "password": "shipyard" --> <stdout>
--_curl_-- "password": "shipyard"
curl: (6) Could not resolve host:  "password"

**Comment by ehazlett** [comment]
It shoudl be this:

```
curl -H "content-Type: application/json" -X POST http://localhost:8080/auth/login '{"username": "admin", "password": "shipyard"}'
```

**Comment by jrwthll** [comment]
I hope this output helps:

curl -v -H "content-Type: application/json" -X POST http://localhost:8080/auth/login '{"username": "admin", "password": "shipyard"}'
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> POST /auth/login HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> content-Type: application/json
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 09 Apr 2015 13:55:55 GMT
< Content-Length: 4
< 
EOF
* Connection #0 to host localhost left intact

[1/2]: "username": "admin" --> <stdout>
--_curl_--"username": "admin"
* Rebuilt URL to: "username": "admin"/
* Hostname was NOT found in DNS cache
* Could not resolve host: "username"
* Closing connection 1
curl: (6) Could not resolve host: "username"

[2/2]:  "password": "shipyard" --> <stdout>
--_curl_-- "password": "shipyard"
* Rebuilt URL to:  "password": "shipyard"/
* Hostname was NOT found in DNS cache
* Could not resolve host:  "password"
* Closing connection 2
curl: (6) Could not resolve host:  "password"

**Comment by ehazlett** [comment]
ah sorry -- you are posting the content.  it should be:

```
curl -H "content-Type: application/json" -X POST -d '{"username": "admin", "password": "shipyard"}' http://localhost:8080/auth/login
```

**Comment by jrwthll** [comment]
Thanks, this worked. Now I received my auth_token

**Comment by ehazlett** [comment]
yw!

**Comment by jrwthll** [comment]
One last question, with regard to adding engines. Which part of the following command is wrong:
request:
curl -H 'X-Access-Token: admin:$2a$10$nj7nkeftEO89xIRnaYK7jOqLDotFAVEO.CHvldSW09J4qyPCAk87i' -H 'Content-Type application/json' -X POST -d '{"id":"local", "ssl_cert": "", "ssl_key": "", "ca_cert": "", "engine": {"id": "local", "addr": "http://172.17.42.1:7890", "cpus": 3.0, "memory": 4096, "labels":["local"]}' http://localhost:8080/api/engines

reply:
unexpected EOF

**Comment by jankeromnes** [comment]
Sorry for the lag, yes I was able to use the curl. Thanks again!

**Comment by ehazlett** [comment]
yw!
