### ISSUE TITLE
Scale to a different engine

### ISSUE THREAD

**Issue by xuxogarcia** [shipyard/shipyard#465]
Hi,
I have a 3-node CoreOS with shipyard. Everything works fine and all 'engines' are displayed properly and running. 

While studying the API and the UI I couldn't find a way to deploy and/or scale to another engine in the cluster. Am I missing something? It seems to scale on the same engine always.

**Comment by clearraining** [comment]
It will always launch on the first available host that has capacity,ehazlett said.

<https://github.com/shipyard/shipyard/issues/460>

**Comment by ehazlett** [comment]
Correct.  In the current state it will only launch on the first available node.  However, we are moving to Swarm (within the next couple of weeks) and this will add all of the options that Swarm supports (random, binpacking, targeting, etc).
