### ISSUE TITLE
Make better use of space on the container inspect page

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#479]
The red area I've highlighted below, looks a little... empty :smile:.  I think we could re-arrange some of the segments to make better use of the space.

![screen shot 2015-04-12 at 01 14 34](https://cloud.githubusercontent.com/assets/60068/7103820/8333ac06-e0b1-11e4-909f-adf87d392ef8.png)

**Comment by ehazlett** [comment]
+1
