### ISSUE TITLE
slice bounds out of range?

### ISSUE THREAD

**Issue by clearraining** [shipyard/shipyard#483]
```
shipyard cli> shipyard events
panic: runtime error: slice bounds out of range
```

the problem is mean what ?   but the web UI  could browse the events.

**Comment by arnoleo** [comment]
I got the same panic, maybe the following logs lines be useful to you : 

`shipyard cli> shipyard events
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x713aa0, 0x91ec6f)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.eventsAction(0xc208040210)
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/events.go:40 +0x953
github.com/codegangsta/cli.Command.Run(0x75b510, 0x6, 0x0, 0x0, 0x7913b0, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/home/dev/dev/gocode/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0xc2080540c0, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
	/home/dev/dev/gocode/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/cli.go:65 +0x4f9

goroutine 19 [finalizer wait]:
runtime.park(0x4244c0, 0x922cb8, 0x920f09)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x922cb8, 0x920f09)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 23 [runnable]:
net/http.(*persistConn).readLoop(0xc2080402c0)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc2080402c0)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957`

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
