### ISSUE TITLE
Connect to Engines on Amazon EC2

### ISSUE THREAD

**Issue by lawansubba** [shipyard/shipyard#485]
Following the tutorials on the website. I have been able to install Shipyard locally and administer a local docker Engine.

Next I would like to also add several docker engines which are not local but are running on amazon EC2 instances.

When i try to do that i get an error 

Get http://54.**.**.**:4243/_ping: dial tcp 54.**.***.***:4243: i/o timeout

**Comment by ehazlett** [comment]
You need to make sure the security groups allow access.  Also I recommend
using TLS if you are accessing the engines over the Internet.

**Comment by lawansubba** [comment]
thanks for the reply Evan. I can already  connect to the instances via terminal so i don't think the problem is related to the security groups. 
Also without TLS, can i not add the remote engine?

**Comment by ehazlett** [comment]
You can. If you can use the cli you should be fine. Can you give the logs
of when you try to add ?  docker logs shipyard

**Comment by lawansubba** [comment]
I tried to add the engine again and i can see the most recent entry in the logs as

time="2015-04-14T00:29:26Z" level="warning" msg="error sending usage info: Post http://tracker.shipyard-project.com/update: dial tcp: i/o timeout"

**Comment by ehazlett** [comment]
Yeah that should be fine. Try adding --disable-usage-info to shipyard and
add again

**Comment by lawansubba** [comment]
Sorry i cannot follow the last request. Am i supposed to start the CLI with a flag like 
sudo docker run --disable-usage-info -it  shipyard/shipyard-cli

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
