### ISSUE TITLE
Shipyard container sometimes fails to start

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#495]
It looks like there is a race condition if you quickly install the shipyard containers in sequence:

    sudo docker run -it -d --name shipyard-rethinkdb-data --entrypoint /bin/bash shipyard/rethinkdb -l
    sudo docker run -it -d --name shipyard-rethinkdb --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb
    sudo docker run -it -d --name shipyard -p 127.0.0.1:8080:8080 --link shipyard-rethinkdb:rethinkdb shipyard/shipyard

Right after this, `sudo docker ps` gives:

    CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                            NAMES
    18f83687c035        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    24 minutes ago      Up 7 seconds        29015/tcp, 8080/tcp, 28015/tcp   shipyard-rethinkdb        
    ce62b27d6ed6        shipyard/rethinkdb:latest   "/bin/bash -l"         24 minutes ago      Up 7 seconds        28015/tcp, 29015/tcp, 8080/tcp   shipyard-rethinkdb-data

With `sudo docker ps -a`, you can see that the shipyard stopped almost instantly:

    84c083587d3c        shipyard/shipyard:2.0.10    "/controller"          28 minutes ago      Exited (1) 3 minutes ago                                    shipyard

Doing `sudo docker logs shipyard` gives:

    INFO[0000] shipyard version 2.0.10                      
    INFO[0000] checking database                            
    FATA[0000] error creating table: gorethink: Table `shipyard.config` already exists. in: 
    r.Db("shipyard").TableCreate("config")

It is possible to restart the Shipyard container with `sudo docker start shipyard`, but this problem is annoying when trying to automate a Shipyard installation.

**Comment by ehazlett** [comment]
This is the reason to use `shipyard/deploy`.  This isn't a Shipyard thing per se -- the service needs to exist before connecting -- similar to something like nginx and a git clone for an app -- the app would need to existing before nginx can serve it.

I think using `shipyard/deploy` is the safest (it also give you upgrade capabilities and removal).  However, a reconnect option would be nice in the gorethink driver -- that should solve the issue.

**Comment by ehazlett** [comment]
Also, just FYI, this delay will increase as the rethinkdb storage grows -- it loads on startup.

**Comment by ehazlett** [comment]
Actually after thinking about it, perhaps we could add a retry.

**Comment by jankeromnes** [comment]
Yes, I think adding a retry is a good idea.

Also, I don't use `shipyard/deploy` because I'm afraid it will expose Shipyard and RethinkDB publicly (as in the Quickstart docs). My server is public-facing, so I expose only Shipyard and only allow connections from `127.0.0.1`.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!

**Comment by SerialVelocity** [comment]
@ehazlett Just so you know, this still happens on version 3.0.2

**Comment by u-foka** [comment]
I can confirm that it is still an issue. And more generally, the issue is not with shipyard, but, somehow docker-compose should have some constraint to check if the service within a linked container (and not the container itself) already up & running before starting a dependant container.
