### ISSUE TITLE
Error: Image not found

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#500]
On my host server, I built an image like so:

    sudo docker build -t me/myimage - < my.dockerfile

When it was successfully built and tagged, I try to deploy containers from Shipyard:

- Image: me/myimage
- Ports: 2x TCP
- Type: Service

When I click on "deploy", I get the following error message:

    Error: image me/myimage: not found

Does Shipyard only work with remote images downloaded from DockerHub?

**Comment by jankeromnes** [comment]
However, when from the host I run:

    sudo docker run -d -p 22 -p 8088 me/myimage

I can see it in Shipyard's container list.

**Comment by tombee** [comment]
Hi @jankeromnes! 

If you want to use a private registry, you'll need to tag it with the registry hostname and then push it
```
docker tag me/myimage registry.example.org:5000/me/myimage
docker push registry.example.org:5000/me/myimage
```

Then in the deploy view, you'll need to specify `registry.example.org:5000/me/myimage` as the image name.

**Comment by jankeromnes** [comment]
Thanks @tombee!

I don't use a private registry, do I have to? I was hoping to just build & tag images locally on the server, and start containers from them.

I suppose that won't work if my Shipyard instance tries to deploy to remote hosts that don't have the local images, but I don't see why local deploy should fail when the image is readily available.

**Comment by abhishekbsharma** [comment]
@ehazlett @tombee @jankeromnes 
I have the same issue. I don't understand why local deploy should fail. 
Note: This was working earlier. I have this issue lately from the last 2-3 days. Shipyard doesn't seem to recognize the fact that I have the image locally.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
