### ISSUE TITLE
When was a container created?

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#501]
I'd like to use the Shipyard API to know when a container was created.

When I do `docker ps`, I can see a `CREATED` field with something like `About an hour ago`, `4 weeks ago`, etc.

The Shipyard API docs for `/api/containers` say that there is a `state` field with something like:

    "state": {
      "started_at": "2014-09-12T00:48:23.824260519Z",
      "pid": 5845,
      "running": true
    }

Maybe `state` could also include a `"created_at"` field?

Note: When I use the API myself, `state` containers even less information: `"state": "running"`

**Comment by tombee** [comment]
Container creation time is displayed in V3!  Beta coming up soon..

**Comment by jankeromnes** [comment]
So many cool things coming in V3! Where can I get the beta when it's out?

**Comment by tombee** [comment]
There'll be an image available to the public on Docker hub, it'll probably be released under a 'v3-beta' tag initially.

**Comment by jankeromnes** [comment]
Thanks! I'll be sure to try it out. I may even start buidling my own nightly versions at some point, because there are some feature I'd like to contribute.

**Comment by tombee** [comment]
@jankeromnes Awesome man, we'd love to have your help!  Be sure to hop onto irc.freenode.net #shipyard and say hi :smile:, we can help out with grabbing the latest code and development environment setup!

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
