### ISSUE TITLE
Why is there no way to list images?

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#502]
When you manage a build server that creates Docker images, it would be nice to list and inspect these images in Shipyard, e.g. to see when they were created.

I currently use a workaround: Creating a reference container every time an image build is complete.

**Comment by tombee** [comment]
Private registry management is implemented in V3! :smile: We hope to have a beta version released very soon.

**Comment by jankeromnes** [comment]
Ah, thanks for the info! I suppose I'll use that instead of `docker images`. I just hope that I won't have to push all my heavy images to a single server with private registry.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
