### ISSUE TITLE
Verify / Improve: Quickstart

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#507]
Review and improve (if needed) the quick start docs (http://shipyard-project.com/docs/quickstart/)

**Comment by airtonix** [comment]
Following these new and improved docs with the `shipyard/deploy` image got me up and running with minimal effort.

I did this on my home server (`ubuntu 12.04.5` with `linux 3.13.0-49-generic` )which at the time of writing has the latest version of docker (`Docker version 1.6.0, build 4749651`) However the docs talk about certificates from a boot2docker vm.

I assume that I can generate my own set of ssl files (`ca`, `private`, `public`) and supply those ?

**Comment by ehazlett** [comment]
Yes you can supply your own certs. The b2d info is just an example.
