### ISSUE TITLE
Running shipyard/deploy fails with permissions issue

### ISSUE THREAD

**Issue by Ramblurr** [shipyard/shipyard#514]
On Fedora 21 I'm following the quickstart, and I get:

```
$ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start
Pulling image: shipyard/rethinkdb
error pulling shipyard image: Post http://unix.sock/v1.15/images/create?fromImage=shipyard%2Frethinkdb: dial unix /var/run/docker.sock: permission denied
```

Nothing funky is up with the perms on /var/run/docker.sock so I'm not sure what the issue is.

**Comment by kernelmode** [comment]
+1, getting this on CentOS

**Comment by sstarcher** [comment]
What's the permission of /var/run/docker.sock
What version of docker are you running?

This would also be an issue with docker and not shipyard itself, but I can see if I can point you in the right direction.

**Comment by kernelmode** [comment]
Thanks, I have already resolved this issue by disabling socket activation. http://bsaunder.github.io/2014/12/21/running-docker-without-sudo/

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!

**Comment by IceFrozen** [comment]
issue is still exist!!!!
[root@localhost run]# docker --version
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

the logs in shipyard-proxy show that:
2016-05-05 16:02:45: 2016/05/05 08:02:45 socat[44] E connect(5, AF=1 "/var/run/docker.sock", 22): Permission denied
2016-05-05 16:02:55: 2016/05/05 08:02:55 socat[45] E connect(5, AF=1 "/var/run/docker.sock", 22): Permission denied

and the node in UI is 
(unknown) !

**Comment by Tochirou** [comment]
@IceFrozen This is SELinux or some other access control denying socat to connect to the docker socket.
Check its logs.
Its not a problem with shipyard itself.
