### ISSUE TITLE
Update cli/utils.go to allow environment variables with an '=' sign in them

### ISSUE THREAD

**Issue by amarneris** [shipyard/shipyard#518]
Hello!

We're trying to use shipyard CLI to start a couple of containers that use environment variables that contain an equal sign.
For example: JENKINS_OPTS="\$JENKINS_OPTS --prefix=/jenkins"

Based on this code here ( shipyard/cli/utils.go Line: 16):

func parseEnvironmentVariables(pairs []string) map[string]string {
	env := make(map[string]string)
	for _, p := range pairs {
		parts := strings.Split(p, "=")
		if len(parts) != 2 {
			logger.Error("environment variables must be in key=value pairs")
			return nil
....

Shipyard CLI will attempt to split on EVERY '=' sign but ideally it would only split on the first '=' occurence and ignore the rest to allow environment variables to contain as many equal signs as they need.

I think the answer can be as simple as using 'splitN' rather than 'split' and allowing a max of two substrings (https://golang.org/src/strings/strings.go?s=6725:6767#L298)

parts := strings.SplitN(p, "=", 2)

Regards,
Andreas

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
