### ISSUE TITLE
manager/manager.go:74: unknown gorethink.ConnectOpts field 'IdleTimeout' in struct literal

### ISSUE THREAD

**Issue by Silence2012** [shipyard/shipyard#519]
It happened when go build under the controller directory .
go version
go version go1.3.3 linux/amd64
shipyard commit
 b5a14e1f56dd6e614e41336c3024ddb132c86a4a

**Comment by tombee** [comment]
Hi @Silence2012, do you have godeps installed?  If so, try using 'make' in the controller directory.

**Comment by Silence2012** [comment]
I have godeps installed  but when  'make' in the controller directory the error happened like this "godep: Get https://code.google.com/p/go/source/checkout?repo=crypto: dial tcp 173.194.72.100:443: connection timed out", I am in beijing and is there any other way to solve this problem , thanks

**Comment by Silence2012** [comment]
If I comment this line ,"go build" will be ok . Is it ok ?

**Comment by ehazlett** [comment]
You should now be able to use `make TAG=test image`.  I'm updating the contributing guide soon.
