### ISSUE TITLE
Private Dockerhub Container

### ISSUE THREAD

**Issue by jacinto123** [shipyard/shipyard#526]
I am trying to pull a new container but I keep getting Error: image not found. I followed the comment here: https://github.com/shipyard/shipyard/issues/345#issuecomment-63684665 and docker login on my docker host as root and on my docker host I can pull the image but when i try and use the GUI I keep getting the image not found error.

**Comment by pkaeding** [comment]
I am seeing this as well. Even if I pull the image first (outside of shipyard, on the docker host) I get this failure.

**Comment by ehazlett** [comment]
This should be fixed in v3.
