### ISSUE TITLE
v3: multi-select and action boxes in the UI?

### ISSUE THREAD

**Issue by mbentley** [shipyard/shipyard#533]
I am not sure if this was a design decision or not but I found myself wishing that I could select multiple containers and performing tasks on multiple containers instead of having to destroy them one at a time.  The same was true when viewing images on the nodes.  It would be great to be able to clean up my hosts through a single action after selecting multiple items.

**Comment by tombee** [comment]
Totally agree on this one @mbentley.  I'll get this done as soon as I can.  

Appreciate the feedback!

**Comment by tombee** [comment]
@mbentley @ehazlett 
Hey guys, I've playing around with the UX around multi-select operations, would love to get your feedback on what I've done so far:

https://youtu.be/RiidZb1faqs

**Comment by MarkHerhold** [comment]
:+1: Looks amazing!

**Comment by tombee** [comment]
@MarkHerhold Thanks man!! :laughing:

**Comment by eoghanino** [comment]
@tombee looks great!

**Comment by leonidp** [comment]
Looks great!!! Waiting for the new release

**Comment by mbentley** [comment]
That's awesome!  I'm a fan :+1:

**Comment by tombee** [comment]
Latest update: https://youtu.be/A2VJFg-gt8g

Think we're almost ready to go with this feature now!

**Comment by ehazlett** [comment]
:+1: :+1:
