### ISSUE TITLE
cant't enter tab "dashboard" and "containers" on web ui page!!

### ISSUE THREAD

**Issue by Linux-Dream** [shipyard/shipyard#538]
i use this command "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start" to deploy shipyard on ubuntu14.04 in virtualbox,then i can open page ,visit "engines" and "events", but can't visit "dashboard" and "containers", what's the reason of this?

**Comment by mbentley** [comment]
Did you add any engines yet?  If not, that would be why.

**Comment by Linux-Dream** [comment]
i have add one, my add method is:
1 run docker use this command:   sudo /usr/bin/docker -H my_ip:8888 -d &
2 add engine with address http://my_ip:8888
and add successful!

one strange thing is: my docker damon machine print a lot of messages in console like this:
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on tcp (172.27.1.163:8888)
INFO[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\
INFO[0000] -job init_networkdriver() = OK (0)
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] docker daemon: 1.5.0-dev fc0329b/1.5.0; execdriver: native-0.2; graphdriver: devicemapper
INFO[0000] +job acceptconnections()
INFO[0000] -job acceptconnections() = OK (0)
INFO[0002] GET /_ping
INFO[0002] GET /v1.15/version
INFO[0002] +job version()
INFO[0002] -job version() = OK (0)

what's could be the problem?

**Comment by mbentley** [comment]
It is just printing the output since it was started from the command line instead of an init script.  The daemon output looks normal so thst isn't a concern.  Do you get any messages or errors when you try to visit the other pages?  I'd have to try to reproduce to troubleshoot much further. Is there anything useful in the docker logs of the shipyard container?

**Comment by Linux-Dream** [comment]
no error found in "docker logs shipyard" output..
so, i am confused!

**Comment by MarkHerhold** [comment]
I encountered this issue today with a fresh install (docker shipyard quickstart) with both 1 and 2 engines added.

The angular app seems to be redirecting me back to the engines screen. To add containers, I manually entered `http://127.0.0.1:8080/#/containers/deploy`

The issue disappears if you have one or more containers added.

**Comment by MarkHerhold** [comment]
I managed to track down the issue. When the containers query comes back, there is a check for `data.length === 0` which redirects to `/engines`. However looking at the source on master, it looks like @tombee fixed this back on commit fd4ba0265 by removing the offending code at [line 19](https://github.com/shipyard/shipyard/commit/fd4ba0265bdce5f34d69e7a7b06aac6428e028a7?diff=unified#diff-2c4480e3fcf52d2fae6da76b5baf0c58L19).

Maybe a new docker container update is needed? I am not familiar with the release cycle.

**Comment by Linux-Dream** [comment]
thanks, it's worked.
actually it's should not to redirects to /engines when container number is 0, beacuse the now docker server without container is common.

**Comment by ehazlett** [comment]
Hmm ok I will push a new image. We are hard at work on v3 if anyone is
interested in testing. It is quite different though. For example it needs
swarm. Just a thought.

Thanks for the feedback!

**Comment by MarkHerhold** [comment]
I am interested in testing! I take it the new stuff is on the [swarm-v3 branch](https://github.com/shipyard/shipyard/tree/swarm-v3)? The machine branch is 300 odd commits ahead of master as well though.

**Comment by ehazlett** [comment]
Yes the machine branch was based off of v3.  It was just an experiment. All
new dev is on the swarm-v3 branch. It is still in dev (finishing up some
features and testing) but you can test if you want. The new WIP docs site
is http://v3-docs.shipyard-project.com/. The QuickStart has instructions on
getting started.

Thanks!

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
