### ISSUE TITLE
Fields do not reset when upon failed deploy

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#539]
When deploying using Swarm constraints, if you use an invalid constraint and the deploy fails, you cannot update the constraint field. It uses the old value.

Here is a screenshot where I entered an invalid constraint, then tried a value one.  It throws an error using the old constraint.

![2015-05-14-121524_1301x552_scrot](https://cloud.githubusercontent.com/assets/260642/7636117/0052ecd4-fa33-11e4-83ec-3e2a26b965ef.png)

**Comment by robtec** [comment]
@ehazlett thanks for the info, will get on it over the weekend :+1:
