### ISSUE TITLE
v3: improve container inspect page design

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#542]
Hey guys,

I think we can do a better job of the container inspect page design, since we have quite a sparsely populated page and we're not making effective use of the real estate on the page that we have.

Would like to get some ideas on how we might improve the page.

![screen shot 2015-05-14 at 22 07 15](https://cloud.githubusercontent.com/assets/60068/7642037/bae80cb2-fa85-11e4-9842-61295ee4896e.png)

![screen shot 2015-05-14 at 22 07 06](https://cloud.githubusercontent.com/assets/60068/7642038/bae84f56-fa85-11e4-9a17-cf65b66bda88.png)

**Comment by ehazlett** [comment]
Is this still the case with v3?
