### ISSUE TITLE
v3: allow user to specify filtering rules for containers view

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#543]
When Shipyard V3 calls the `/containers/json` api at the moment, we pass a param to show all containers (i.e. swarm agent/master containers).  Might be better for the UX to hide these by default and supply an option to view them if the user wants to.

**Comment by ehazlett** [comment]
Perhaps we should change to only show running containers by default, add a
filter drop down and show the swarm containers in the "all" view. Basically
what the docker cli does. Thoughts?

**Comment by tombee** [comment]
I think it might be handy by default to show all containers, except the swarm ones.  This is the default behaviour of swarm anyway:

> GET "/containers/json" : Containers started from the swarm official image are hidden by default, use all=1 to display them.

It's probably not very useful in general to see these `swarm` containers running, they tend to clutter the view in the environment that we have running.

**Comment by ehazlett** [comment]
Exactly. The default for swarm shows only running containers without the
swarm ones. That's what I was saying. Then perhaps a dropdown or something
to show all containers which would show the swarm ones. Just like the swarm
API.

**Comment by tombee** [comment]
Cool -- I think it'd still be useful for ops/support people to see stopped/failed containers by default.
What do you think?  We'd probably just have to provide the `all=1` param, but then provide our own filter to switch on/off visibility of the `swarm` containers.

**Comment by ehazlett** [comment]
I don't know. It definitely clutters the view for sure seeing all. I don't
like the idea of hiding the swarm containers and not being able to see
them.  As an ops person I wouldn't like that. I also think it would be
counterintuitive to show all containers and then a "all" view that just
shows the swarm ones.

Perhaps an alternative would be to show the swarm container info in a
node detail view?  Then we could filter the swarm containers and leave the
container view of all as is.

Thoughts?

**Comment by tombee** [comment]
Ah, oops!  I'm not saying we hide them completely, initially we could supply a simple button/menu to toggle visibility of the swarm containers.

Though now you mention displaying the info on the nodes view, that's interesting.. any thoughts on how that might look?

**Comment by MarkHerhold** [comment]
I like the idea of designating specific containers as swarm containers. I personally wouldn't hide the containers, but rather peg them to the bottom of the list (group) and shade them all gray.

**Comment by vbichov** [comment]
It seems odd to make an exception for **specific** containers. 
Moreover, there may very well be other containers that clutter your view.
Swarm relies on automatic registration and pulls hosts from something like the Consul - that also have agents running on every machine.

I would propose simply allowing the user to filter on the containers' view.
The user will choose which containers to view or not.

**Comment by tombee** [comment]
Good point @vbichov, thanks for your input.

So I think we should be looking at a better UX for filtering what containers should and should not be displayed based upon rules provided by the user.

In other words, an example use case might be that, as a user I would like to exclude containers running a particular image (or images) from the containers view.

We do have the search box for filtering, but in some cases it is not flexible enough for users that are trying to use the container view as a dashboard of particular containers that they are interested in.

**Comment by sstarcher** [comment]
+1 for generic filtering.
In my case we run a significant amount of infrastructure containers that would be nice to be able to filter out by default.
Things like consul, swarm, logspout

**Comment by llitfkitfk** [comment]
👍

**Comment by lihaixin2** [comment]
how to change the "/containers/json?all=1" to "/containers/json",so the shipyard-* containers can hide in the web UI
