### ISSUE TITLE
Add status field to a container that is encountering issues

### ISSUE THREAD

**Issue by damienjoyce** [shipyard/shipyard#545]
Hi Guys, 
on the shipyard container ui, 
would it be possible to add something like "Requires Action" status to a container that is encountering issues, for example if it has restarted multiple times in a short time frame?
and/or change the icon from grey to red to indicate an issue ?

Thanks
Damien

**Comment by tombee** [comment]
:+1:

**Comment by eoghanino** [comment]
+1

**Comment by ehazlett** [comment]
+1
