### ISSUE TITLE
v3: log streaming

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#549]
Instead of having to refresh to update the logs, it'd be cool if we could follow/tail the logs.

**Comment by ehazlett** [comment]
+1

**Comment by guanxudong** [comment]
shipyard logs API seems can not add **tail** param to tail last rows of logs

**Comment by ehazlett** [comment]
Can you give an example of the request you are sending?

**Comment by guanxudong** [comment]
Hi @ehazlett ,
``` 
docker run -d <image> sh -c "while true;do date;sleep 3;done"
```
I used python requests libary ,
```
import requests
res = requests.get('http://<ip>:<port>/api/containers/<container_id>/logs?tail=1', headers={'X-Service-Key': 'xxxxx'}
print res.text
```
it will flood me all logs...did I do it wrong way?

**Comment by ehazlett** [comment]
In v2 we wrapped the requests in our own API and didn't implement
streaming.  In v3, we proxy directly to Swarm therefore streaming should
just work (although it would be a different endpoint).  Would you want to
try that?

**Comment by guanxudong** [comment]
@ehazlett 
Thanks for you kindly reply.
My docker servers are not deployed with Swarm, only shipyard.
But it's not a big problem, I will workaround this.：）
