### ISSUE TITLE
Error invalid character 'v' looking for beginning of value

### ISSUE THREAD

**Issue by woshihaoren** [shipyard/shipyard#552]
Web cli deploy new contain has problem
When i fill form, click deploy button,then top space display

Error
invalid character 'v' looking for beginning of value

but cli was ok,
shipyard cli> shipyard run --name 10.255.33.19:5000/ubuntu_sshd:14.04 --cpus 0.1 --memory 256 --type service 
started 1af7a0ed2c4a on 10.255.33.18

**Comment by woshihaoren** [comment]
restart physic host can fix

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
