### ISSUE TITLE
should not connect http://fonts.googleapis.com 

### ISSUE THREAD

**Issue by apachemycat** [shipyard/shipyard#556]
when run it in a data center ,the web is very slowly

**Comment by tombee** [comment]
@apachemycat 
Thanks for this -- I can have a look at fixing this in V3.

**Comment by marsmensch** [comment]
+1 for the removal OR integration of google fonts.

fonts.googleapis.com does not work, is slow and adds a phone-home component to a self-hosted application that many people simply do not want.

I invested a couple of minutes to research the used fonts and their individual licenses:

> Font name: Droid Sans Mono
> License:   Apache License, version 2.0, https://www.apache.org/licenses/LICENSE-2.0.html
> Google Font Link: https://www.google.com/fonts/specimen/Droid+Sans+Mono
> 
> Font name: Poiret One
> License:   SIL Open Font License (OFL), http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL
> Google Font Link: https://www.google.com/fonts/specimen/Poiret+One
> 
> Font name: Roboto
> License:   Apache License, version 2.0, https://www.apache.org/licenses/LICENSE-2.0.html
> Google Font Link: https://www.google.com/fonts/specimen/Roboto

Google Fonts Github project:
https://github.com/google/fonts/

/cc @ehazlett @tombee
