### ISSUE TITLE
how to add  cAdvisor plugin

### ISSUE THREAD

**Issue by apachemycat** [shipyard/shipyard#557]
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest

there is no document about shipard's plugin detail ,so I can't write a conf file to integrate cAdvisor
can any guys help ?

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. We have temporarily disabled the extension feature as we are re-designing it to be better.  Thanks!
