### ISSUE TITLE
Help indicate a node activity for maintenance 

### ISSUE THREAD

**Issue by damienjoyce** [shipyard/shipyard#558]
Would it be possible to help indicate that a node was stopped by an operator for maintenance for example? This would help when multiple users are using shipyard and prevent a node being restarted accidentally, maybe this could be indicated by a different colour or a text field or a "maintenance" status option ?

Thanks,
Damien

**Comment by ehazlett** [comment]
We use Swarm nodes and there is currently no way to bring down a node.  Perhaps we could use an agent for this type of functionality?  I'm closing this one specifically but if you would like something else please feel free to open a new issue.  Thanks!
