### ISSUE TITLE
Ressource management at runtime 

### ISSUE THREAD

**Issue by mboussaa** [shipyard/shipyard#559]
Hi all,
Is there any attempt to manage containers configuration at runtime?
I have to change ressources limitation at runtime.
it would be great to manage all containers settings at runtime like memory or CPU customization 

Thanks in advance.

**Comment by ehazlett** [comment]
Are you looking for something like this? https://github.com/shipyard/shipyard/issues/335

**Comment by mboussaa** [comment]
I mean changing the amount of memory and cpu limitation of running containers at runtime. Is it possible?

**Comment by ehazlett** [comment]
No that is currently not possible in the docker daemon.

**Comment by mboussaa** [comment]
Is there a way to do that?thank you

**Comment by ehazlett** [comment]
No it's not supported in the docker engine.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor. Could you please check to see if this is still an issue? If so, please re-open. Thanks!
