### ISSUE TITLE
How can I get Certificates ?

### ISSUE THREAD

**Issue by mboussaa** [shipyard/shipyard#560]
I can't understand where can I get the “SSL Certificate", “SSL Key” and “CA Certificate”.
I am not using b2d. I am using ubuntu

**Comment by ehazlett** [comment]
Are you using TLS?

**Comment by mboussaa** [comment]
I have no idea about what is TLS. Sorry I am beginner

**Comment by ehazlett** [comment]
Then you probably aren't using it :)  If you aren't using TLS you can just
leave the fields blank or leave off the parameters in the CLI.

**Comment by mboussaa** [comment]
I tried like that but the ADD button didn't work

**Comment by russmack** [comment]
I can't tell you where the certificates are, because I'm using boot2docker, but I can corroborate that the web controller add button doesn't respond when http is used.  Tried last night.

**Comment by mboussaa** [comment]
I finally followed another tutorial and it worked. I suggest to enhance the given tutorial in Shipyard website using this link https://www.digitalocean.com/community/tutorials/how-to-deploy-wordpress-with-shipyard-on-ubuntu-14-04

**Comment by ehazlett** [comment]
There is also http://shipyard-project.com/docs/quickstart/#toc_6 -- please
let us know how we can improve the docs for this?  In v3 we use Docker
Machine for creation of the engine so we know where the certs are.

**Comment by russmack** [comment]
Is v2 development finished now?

**Comment by ehazlett** [comment]
You mean v3?  We are getting very close -- fixing a few bugs and docs.

**Comment by russmack** [comment]
No, I mean the current version - are you done with it and focusing only on v3 now? (Looking forward to v3).

**Comment by mboussaa** [comment]
and how can I upgrade from v2 to v3

**Comment by mboussaa** [comment]
@ehazlett : you should add this to the tuto
The Droplet that we've just deployed Shipyard on is also a Docker host, so we'll be able to manage it with Shipyard. Before we can do that; however, we'll need to add the server to Shipyard as an engine.

By default, Docker is configured to listen on Unix socket /var/run/docker.sock, but that socket can't be accessed from our Shipyard instance. We'll need to configure Docker to also listen to requests on a port. To do this, edit the Docker configuration file using your favorite text editor. (Here, we use nano.)

nano /etc/default/docker
At the end, add this line:

DOCKER_OPTS="-H tcp://your_server_ip:4243 -H unix:///var/run/docker.sock"
This will ensure that Docker accepts connections on port 4243, but only from your server itself. Now restart Docker to load the new configuration:

service docker restart
This will also restart your Shipyard containers. Since we ran the containers with --restart=always they should come back up automatically. You can verify this by running:

docker ps
If for some reason the Shipyard containers didn't restart, you can restart them manually by running docker start shipyard-rethinkdb shipyard.

Now that your Docker host is properly configured, we can add it to Shipyard as an engine. Access your Shipyard GUI and go to the Engines tab. Click on the + Add button.

**Comment by ebuildy** [comment]
Ya! 

I believe every one will try this "localy", so the Docker engine where shipyard is running should be added by default.

I have some trouble to add my host (an Amazon docker-machine):

    /usr/bin/docker -d --tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem

I copy the content of these .pem files but always get "connection refused". Any idea? thanks

**Comment by ehazlett** [comment]
Are you specifying the right port and "https" in the URL?

**Comment by ebuildy** [comment]
Yep I think:

![]
(http://b3.ms/RNgqnVpZ9Bwz)

**Comment by ehazlett** [comment]
You can check the new deploy guide for v3 -- it gives an example on using TLS with Shipyard.  http://shipyard-project.com/docs/deploy/
