### ISSUE TITLE
Build container from image on docker host?

### ISSUE THREAD

**Issue by shairozan** [shipyard/shipyard#561]
Hey, 

I just deployed to a container on my docker host, and want to deploy from an image that resides on that host (not a private registry or public). Whenever I try to specify the image name, it just returns that libary/X not found. 

Is there a way to work with local images? I also don't have any menu items for images.

**Comment by ehazlett** [comment]
This is fixed in v3.  If you would like to try it out, I recommend
http://v3-docs.shipyard-project.com/docs/quickstart/ -- Note this is
pre-release and subject to change :)

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor.  Could you please check to see if this is still an issue?  If so, please re-open.  Thanks!
