### ISSUE TITLE
v3: select all checkbox when filtering selects non-visible containers

### ISSUE THREAD

**Issue by tombee** [shipyard/shipyard#562]
When you type something into the filter box on the containers view, and then click the "select all" checkbox, intuitively only the visible containers should be selected.  At the moment all of the containers are selected -- even non-visible ones.

**Comment by mbentley** [comment]
Yikes!  Good catch!

**Comment by ehazlett** [comment]
Ouch -- any fix?

**Comment by tombee** [comment]
I'll get on a fix for this ASAP.

**Comment by ehazlett** [comment]
Cool thx!
