### ISSUE TITLE
Docker sucks - sometimes

### ISSUE THREAD

**Issue by mrlove** [shipyard/shipyard#563]
I cannot run "docker run -it --name -P --link rethinkdb:rethinkdb shipyard/shipyard"
because it fails and says 

FATA[0000] Error response from daemon: Invalid container name (-P), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

what I am doing wrong? Its from the readme file...

**Comment by ehazlett** [comment]
You have to give it a name for --name -- you aren't specifying anything and
blank is not allowed.

**Comment by ehazlett** [comment]
Closing as this is a usage error.  Just friendly feedback, descriptive issue titles are better than offensive ones. :).
