### ISSUE TITLE
v3: no logs for some containers.

### ISSUE THREAD

**Issue by chromerobv** [shipyard/shipyard#567]
so first off since i couldn't get v3 to work via docker-machine on my current setup.
existing swarm with 2 nodes running on steel, i grabbed the ehazlett/shipyard:v3. which looked to be fairly recent and v3. it installs fine and works. i can see all my containers and everything, but for some reason on some of the containers i can not see the logs. the only thing that i see is that the ones that aren't showing for the most part are ones with large logs. i can see the logs fine via docker swarm host, just not in shipyard.

**Comment by ehazlett** [comment]
Using Machine should work with existing systems with the Generic driver but
that would require manual setup.

There is probably a timeout waiting for the large logs.  We should look
into truncating and tailing or perhaps streaming to the client.

**Comment by chromerobv** [comment]
you wouldn't be able to help me out with the generic way of doing it would you?
at least something to get me started. i have tried in the past with the generic driver but could never get it working.

**Comment by chromerobv** [comment]
as for the main problem im not sure how you are pulling the logs, im guessing api.
but on the cli you can limit what you pull like so
docker logs -f --since=$(date +%s) <container>
maybe there is a way to do the same with how you are pulling it, maybe just pull the last hour or so?


**The --since option shows only the container logs generated after a given date. You can specify the date as an RFC 3339 date, a UNIX timestamp, or a Go duration string (e.g. 1m30s, 3h). Docker computes the date relative to the client machine’s time. You can combine the --since option with either or both of the --follow or --tail options.

**Comment by chromerobv** [comment]
fyi. just realized the --since option is new to 1.7.
but you can use the --tail option and maybe only --tail=100 or something reasonable?

**Comment by ehazlett** [comment]
ya we will probably do something like that.  we've wanted a tail option for
awhile.
