### ISSUE TITLE
Docker compose integration

### ISSUE THREAD

**Issue by mboussaa** [shipyard/shipyard#570]
Hi all,

Is it possible/any attempt to deploy shipyard using docker-compose.yml?

Thanks in advance.

**Comment by ehazlett** [comment]
Yes, it should run.

**Comment by mboussaa** [comment]
Cool. I Will try to do it and give you feedback :-)

**Comment by tuxknight** [comment]
I wrote a docker-compose.yml 
```
rethinkdb:
  image: shipyard/rethinkdb
  volumes:
    - ./rethinkdb-data:/data
  expose:
    - 29015
    - 28015
    - 8080

shipyard:
  image: shipyard/shipyard
  ports:
    - 8080:8080 
  links:
    - rethinkdb:rethink
  command: -rethinkdb-addr="rethink:28015"
```

But it won't work and gave an error message below
```
Creating shipyard_rethinkdb_1...
Creating shipyard_shipyard_1...
Attaching to shipyard_rethinkdb_1, shipyard_shipyard_1
shipyard_1  | time="2015-07-16T02:19:13Z" level="info" msg="shipyard version 2.0.10" 
shipyard_1  | time="2015-07-16T02:19:13Z" level="fatal" msg="factory is not able to fill the pool: gorethink: dial tcp 172.17.0.101:28015: connection refused" 
shipyard_shipyard_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping shipyard_rethinkdb_1...
```
And then, everything stopped.

Here are logs in rethinkdb
```
[elc@atsg153 shipyard]$ docker-compose logs rethinkdb
Attaching to shipyard_rethinkdb_1
rethinkdb_1 | Running rethinkdb 2.0.3~0trusty (GCC 4.8.2)...
rethinkdb_1 | Running on Linux 3.10.0-123.20.1.el7.x86_64 x86_64
rethinkdb_1 | Loading data from directory /data/rethinkdb_data
rethinkdb_1 | Listening for intracluster connections on port 29015
rethinkdb_1 | Listening for client driver connections on port 28015
rethinkdb_1 | Listening for administrative HTTP connections on port 8080
rethinkdb_1 | Listening on addresses: 127.0.0.1, 172.17.0.101, ::1, fe80::42:acff:fe11:65%746
rethinkdb_1 | Server ready, "bf6c142c0dcd_sd2" f01a84a7-11d1-4432-9b46-185dcc7a5704
rethinkdb_1 | A newer version of the RethinkDB server is available: 2.0.4. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.

^C
Aborting.
```

Maybe the problem was that rethinkDB wasn't ready while shipyard trying to connect to it ?
It seems docker-compose couldn't set wait time between services.

PS:

```
[elc@localhost shipyard]$ docker-compose  -v
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

```

```
shipyard cli> shipyard --version
shipyard version 2.0.8
```

```
[elc@atsg153 shipyard]$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by mboussaa** [comment]
Add at the end of /etc/default/docker the following command to configure Docker to listen to requests port (4243 for example).

DOCKER_OPTS="-H tcp://10.0.2.15:4243 -H unix:///var/run/docker.sock"
and restart docker:

sudo service docker restart

**Comment by tuxknight** [comment]
Thanks @mboussaa 
But docker daemon already listens to a tcp port
``
/usr/bin/docker -d -H 0.0.0.0:2375 -H unix:///var/run/docker.sock --insecure-registry   xxxxxxxxx:5000 
```

**Comment by mboussaa** [comment]
try to put your host ip instead

**Comment by tuxknight** [comment]
@mboussaa  The problem is that shipyard couldn't connect to rethinkdb.
My docker daemonn works fine.

**Comment by mboussaa** [comment]
So, I don't know how to help you. 
Good luck.
you may ask @ehazlett ...

**Comment by ehazlett** [comment]
I think this is due to rethink not being ready. I thought there was s fix
where it would attempt a reconnect. I will check.

**Comment by mboussaa** [comment]
Ok here my solution:
<pre><code>
in terminal :
docker create 
--name shipyard-rethinkdb-data 
shipyard/rethinkdb

in docker-compose.yml:
#Shipyard: Graphical dokcer manager
shipyardrethinkdb:
  image: "shipyard/rethinkdb"
  volumes_from:
    - "shipyardrethinkdbdata"
  ports:
    - "127.0.0.1:49153:8080"
    - "127.0.0.1:49154:28015"
    - "127.0.0.1:29015:29015"
#     - "8080"
#     - "28015"
#     - "29015"

shipyard:
  image: "shipyard/shipyard"
  ports:
    - "8085:8080"
  links:
    - "shipyardrethinkdb:rethinkdb"
</code></pre>

This works fine.
If I create shipyard-rethinkdb-data  container within YAML file it won't work. Any idea to how integrate all this stuff on the YAML file? Compose does not support "create" feature...

**Comment by ehazlett** [comment]
You shouldn't need to hard code ports.  If you link them they should be
able to talk to each other.  What version of Engine / Compose are you using?

**Comment by mboussaa** [comment]
docker-compose version: 1.3.1

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor.  Could you please check to see if this is still an issue?  If so, please re-open.  Thanks!

**Comment by tuxknight** [comment]
Thanks @ehazlett 
Shipyard V3 is really awesome!
