### ISSUE TITLE
is this project solid enough to manage your private registry?

### ISSUE THREAD

**Issue by rubytastic** [shipyard/shipyard#575]
Are you guys using this in production and is it solid enough for basic tasks of managing some docker containers or would it be advisable to use another frontend to mange private repositories. Have this installed on my production server but regarding the issue list im not sure. Kind regards and thanks for all the hard works that went into making this.

**Comment by ehazlett** [comment]
In v3 (just released) there is a way to manage private registries.  Right now this is limited to the Docker open source v1 registry until the v2 gets delete capabilities, etc.  I would love feedback around the usage and we plan to expand the functionality around registry management.
