### ISSUE TITLE
V3 bad gateway

### ISSUE THREAD

**Issue by rlanore** [shipyard/shipyard#576]
hi,

i'm unable to understand how to debug my shipyard install.

In container page after login i see:

Error...
{"data":"Bad Gateway","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Bad Gateway"}

what i do

1- install docker on 2 debian jessie ( node : 10.1.20.76/16,  manager: 10.1.254.55/16 )
2- install and configure swarm ( 1 node docker swarm management and other docker is swarm node )
  to check swarm install i'm doing 

```
docker -H tcp://10.1.254.55:1024 info
Containers: 3
Images: 30
Storage Driver: 
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 1
 node.troy.kvm: 10.1.20.76:2375
  └ ... ...
GNU/Linux 8 (jessie), storagedriver=aufs
Execution Driver: 
Kernel Version: 
Operating System: 
CPUs: 4
Total Memory: 16.49 GiB
Name: 
ID: 
Http Proxy: 
Https Proxy: 
No Proxy: 
```

3 - Get un deploy shipyard has quick start guide V3

Start db container
```
docker run -d --restart=always --name shipyard-rethinkdb shipyard/rethinkdb
```

Start Gui

```
docker run --rm -ti -p 8080:8080 --link shipyard-rethinkdb:rethinkdb -v /var/lib/boot2docker:/etc/docker:ro --name shipyard ehazlett/shipyard:v3 -D server --rethinkdb-addr=rethinkdb:28015 -d tcp://10.1.254.55:3376 --auth-whitelist-cidr 10.1.0.0/16
```

"-D" flag aren't usefull

```
INFO[0000] shipyard version 3.0.0                       
INFO[0000] whitelisting the following subnets: [10.1.0.0/16] 
INFO[0000] checking database                            
DEBU[0000] connected to docker: url=tcp://10.1.254.55:3376 
DEBU[0000] configured docker proxy target: http://10.1.254.55:3376 
INFO[0000] controller listening on :8080
```

**Comment by ehazlett** [comment]
That error usually means that the controller can't reach the swarm agent.  Make sure the swarm agent isn't blocked by any firewall and is listening on TCP.

**Comment by rlanore** [comment]
To test it i'm doing this

On host where shipyard controller running
```
docker -H tcp://10.1.20.76:2375 info    // It's work
```

Inside same docker that shipyard controller

```
curl -X GET "http://10.1.20.76:2375/info"  // It's work
```

**Comment by rlanore** [comment]
perhaps is into the V3 docs you specify an 

```
-d tcp://$(docker-machine ip shipyard-swarm-master):3376
```

do you mean 

```
-d tcp://$(docker-machine ip shipyard-swarm-master):2376
```

**Comment by ehazlett** [comment]
The port `3376` in the docs are for the automated setup using the script (which configures them that way).  You will need to adjust for any custom ports if you don't use the setup since the controller doesn't have access to that information.
