### ISSUE TITLE
Goroutines are called again and again when add or remove engines

### ISSUE THREAD

**Issue by Dumbear** [shipyard/shipyard#578]
In file `controller/manager/manager.go`, the function `init` calls three go routines `go m.extensionHealthCheck()`, `go m.engineCheck()` and `go m.usageReport()`.

It's OK, but when the function `AddEngine`, `RemoveEngine` or even `SaveServiceKey` was called, the `init` got called again. This leads to the three forever-running go routines being launched again and again.

I suggest move the three go routines into the constructor `NewManager`, the go routines will be guaranteed to be called only once.

**Comment by ehazlett** [comment]
Shipyard v3 has been released and is a major refactor.  Could you please check to see if this is still an issue?  If so, please re-open.  Thanks!
