### ISSUE TITLE
v3: Shipyard doesn't start properly

### ISSUE THREAD

**Issue by dpravn** [shipyard/shipyard#582]
Hi,

I am trying to run v3 version of software behind proxy. The commands executed on server are as follows

docker run -d -e http_proxy=http://xyz:80 -e https_proxy=http://xyz:80 --restart=always --name shipyard-rethinkdb shipyard/rethinkdb

docker run -i -t -p 8080:8080 -d -e http_proxy=http://xyz:80 -e https_proxy=http://xyz:80 --name shipyard --link shipyard-rethinkdb:rethinkdb ehazlett/shipyard:v3 server.

I get the following error when I login to shipyard

Webpage

Error...

{"data":"Bad Gateway","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$vi.pHJpaFh/kUYS9q0hbNetHWgprY2EIF9rS2AInQ5ZdRHkk17xqC"}},"statusText":"Bad Gateway"}

Server logs

INFO[0000] shipyard version 3.0.0
INFO[0001] checking database
INFO[0006] created admin user: username: admin password: shipyard
INFO[0006] controller listening on :8080
WARN[0038] unauthorized request for /containers/json from xyz:53859

Docker version

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

Please let me know if I am doing anything wrong

Regards
Praveen

**Comment by ehazlett** [comment]
I don't see where you are pointing it to Swarm.  This should help:
http://v3-docs.shipyard-project.com/docs/quickstart/#toc_1

**Comment by lubia** [comment]
I have the same problem, because shipyard-swarm not work.
when i `docker logs shipyard-swarm`
```
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0015] Registered Engine development-001 at proxy:2375
2015/09/29 08:43:22 http: panic serving 192.168.42.234:58291: runtime error: index out of range
goroutine 32 [running]:
net/http.func·011()
	/usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/docker/swarm/api.getContainersJSON(0xc208034700, 0x7f65c2d374a0, 0xc208102aa0, 0xc20824b110)
	/go/src/github.com/docker/swarm/api/handlers.go:197 +0x1815
github.com/docker/swarm/api.func·007(0x7f65c2d374a0, 0xc208102aa0, 0xc20824b110)

```
anyone know how to solve it?

**Comment by ehazlett** [comment]
What version of docker are you using?

**Comment by lubia** [comment]
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by ehazlett** [comment]
You need at least Docker 1.7. We are adding in version checks to error upon
install.

**Comment by khushil** [comment]
I have the same thing with latest docker:

```
INFO[0000] shipyard version 3.0.4
INFO[0000] checking database
INFO[0002] created admin user: username: admin password: shipyard
INFO[0002] controller listening on :8080
WARN[0030] unauthorized request for /containers/json from 10.17.8.250:60511
root@ip-10-10-18-204:~# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
root@ip-10-10-18-204:~# docker -H 10.10.18.204:4000 info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: swarm/1.2.2
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 ip-10-10-12-251: 10.10.12.251:2375
  └ ID: YZ55:V273:O5MO:HWWF:7XR3:SEKU:ZMSL:MCXG:ICVD:EL3K:U73O:JRKU
  └ Status: Pending
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 31.46 GiB
  └ Labels: com.tescloud.environment=development, com.tescloud.nodetype=swarm-host, com.tescloud.recourse=first, executiondriver=, kernelversion=3.19.0-59-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: ID duplicated. YZ55:V273:O5MO:HWWF:7XR3:SEKU:ZMSL:MCXG:ICVD:EL3K:U73O:JRKU shared by this node 10.10.12.251:2375 and another node 10.10.13.55:2375
  └ UpdatedAt: 2016-05-13T06:50:30Z
  └ ServerVersion: 1.11.1
 ip-10-10-13-55: 10.10.13.55:2375
  └ ID: YZ55:V273:O5MO:HWWF:7XR3:SEKU:ZMSL:MCXG:ICVD:EL3K:U73O:JRKU
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 31.46 GiB
  └ Labels: com.tescloud.environment=development, com.tescloud.nodetype=swarm-host, com.tescloud.recourse=first, executiondriver=, kernelversion=3.19.0-59-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-13T06:50:24Z
  └ ServerVersion: 1.11.1
 ip-10-10-14-159: 10.10.14.159:2375
  └ ID: YZ55:V273:O5MO:HWWF:7XR3:SEKU:ZMSL:MCXG:ICVD:EL3K:U73O:JRKU
  └ Status: Pending
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 31.46 GiB
  └ Labels: com.tescloud.environment=development, com.tescloud.nodetype=swarm-host, com.tescloud.recourse=first, executiondriver=, kernelversion=3.19.0-59-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: ID duplicated. YZ55:V273:O5MO:HWWF:7XR3:SEKU:ZMSL:MCXG:ICVD:EL3K:U73O:JRKU shared by this node 10.10.14.159:2375 and another node 10.10.13.55:2375
  └ UpdatedAt: 2016-05-13T06:50:30Z
  └ ServerVersion: 1.11.1
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-59-generic
Operating System: linux
Architecture: amd64
CPUs: 4
Total Memory: 31.46 GiB
Name: 009902cb3434
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

unclear how to fix this...

**Comment by ehazlett** [comment]
I just tested this with Docker 1.11.1, Swarm 1.2.2 and Shipyard 3.0.4 and
everything works.  Can you give more info in how you deployed?
