### ISSUE TITLE
There is possible to skip login?

### ISSUE THREAD

**Issue by marcosps** [shipyard/shipyard#584]
Just a question, skip login, or maybe do an autologin?

Thanks!

**Comment by ehazlett** [comment]
Currently there are no plans to bypass login.  It is part of the access control system.  Although I wouldn't be necessarily against a pull request ;)

**Comment by jvanz** [comment]
Nice, we need this features and I volunteer myself to make this change and send a pull request. =]
I believe the best place to do this change is in the shipyard v3.

Do you have some code pointers? Which do you think is the best approach, do some kind of auto login where the authenticated user is always the default user or allow Shipyard to run without authenticate user? I think the second option is the better...

**Comment by marcosps** [comment]
:+1:
