### ISSUE TITLE
docker swarm-v3 compilation problem

### ISSUE THREAD

**Issue by marcosps** [shipyard/shipyard#585]
So, when trying to compile branch swarm-v3 it get this problem:

| error: object directory /opt/sources/git2/github.com.shipyard.shipyard.git/objects does not exist; check .git/objects/info/alternates.
| main.go:7:2: cannot find package "github.com/codegangsta/cli" in any of:
|       /usr/src/go/src/pkg/github.com/codegangsta/cli (from $GOROOT)
|       /go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/cli (from $GOPATH)
|       /go/src/github.com/codegangsta/cli
| api/api.go:21:2: cannot find package "github.com/mailgun/oxy/forward" in any of:
|       /usr/src/go/src/pkg/github.com/mailgun/oxy/forward (from $GOROOT)
|       /go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/mailgun/oxy/forward (from $GOPATH)
|       /go/src/github.com/mailgun/oxy/forward
| Godeps/_workspace/src/github.com/dancannon/gorethink/connection.go:13:2: cannot find package "gopkg.in/fatih/pool.v2" in any of:
|       /usr/src/go/src/pkg/gopkg.in/fatih/pool.v2 (from $GOROOT)
|       /go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/gopkg.in/fatih/pool.v2 (from $GOPATH)
|       /go/src/gopkg.in/fatih/pool.v2
| godep: go exit status 1
| Makefile:16: recipe for target 'build' failed
| make: *** [build] Error 1
| WARNING: exit code 2 from a shell command.

Godep seems to not find these libraries. I'm missing something here?

**Comment by ehazlett** [comment]
This has been simplified.  I will update the contributing section soon.  You can now just checkout and run `make TAG=test image'.  That will build everything and will give you a resulting image of `shipyard/shipyard:test`.  You can then deploy the local image with the deploy script: `curl -sSL https://shipyard-project.com/deploy | IMAGE=shipyard/shipyard:test bash -s`
