### ISSUE TITLE
webui not deploy containers

### ISSUE THREAD

**Issue by gregorianzhang** [shipyard/shipyard#586]
roy@ubuntu:~$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu                  latest              91e54dfb1179        12 days ago         188.4 MB
base_t3                 latest              f70ff9052b7e        4 weeks ago         577.5 MB
shipyard/rethinkdb      latest              01d0c7f830ab        11 weeks ago        296.2 MB
shipyard/deploy         latest              ba94b7a205d6        5 months ago        6.514 MB
shipyard/shipyard       latest              f1be70df06c1        6 months ago        36.26 MB
shipyard/shipyard-cli   latest              b73f9452c2ff        8 months ago        146.4 MB

roy@ubuntu:~$ sudo docker run shipyard/shipyard
time="2015-09-02T10:08:18Z" level="info" msg="shipyard version 2.0.10" 
time="2015-09-02T10:08:18Z" level="fatal" msg="factory is not able to fill the pool: gorethink: dial tcp 127.0.0.1:28015: connection refused" 
roy@ubuntu:~$ sudo docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

I use webui deploy containers the post url is 
http://172.18.102.13:8080/api/containers?count=1&pull=true
always error 
get the message
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/base_t3/images. You may want to check your internet connection or if you are behind a proxy.

I manual post the url http://172.18.102.13:8080/api/containers is OK ,not args  

maybe something is wrong。

apologize for my english  poor

**Comment by ehazlett** [comment]
First, it doesn't look like rethinkdb is running.  You will want to check
that container as Shipyard needs it.  Second, it looks like you are having
network issues as there is a timeout connecting to a remote host.

**Comment by gregorianzhang** [comment]
roy@ubuntu:/$ sudo docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                                         NAMES
08cf9df82b9d        shipyard/shipyard:latest   "/controller"            4 days ago          Up 50 minutes       0.0.0.0:8080->8080/tcp                                                        shipyard
b88ccec09a88        shipyard/rethinkdb         "/usr/bin/rethinkdb -"   4 days ago          Up 51 minutes       0.0.0.0:32770->8080/tcp, 0.0.0.0:32769->28015/tcp, 0.0.0.0:32768->29015/tcp   shipyard-rethinkdb
7860d5613b40        shipyard/rethinkdb         "/bin/bash -l"           4 days ago          Up 51 minutes       8080/tcp, 28015/tcp, 29015/tcp                                                shipyard-rethinkdb-data
rethinkdb is running.

images name is base_t3 is local images.

I use firefox open url http://172.18.102.13:8080/#/containers/deploy
Shift + Ctrl + I to developer tools .
deploy new container get 500 error 
the post url is http://172.18.102.13:8080/api/containers?count=1&pull=true
I click the 500 POST and click headers ,check edit the resend 
change the url is http://172.18.102.13:8080/api/containers
and click send ,response 200 and create new container.

network is Local Network 
roy@ubuntu:/$ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr da:ef:bd:0a:1d:1d  
inet addr:172.18.102.13  Bcast:172.18.103.255  Mask:255.255.254.0

**Comment by ehazlett** [comment]
What is the output of `docker logs shipyard`

**Comment by gregorianzhang** [comment]
Sorry. I forget error message and I success deply containers message.

time="2015-09-07T02:39:47Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:39:49Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:39:57Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:39:59Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:03Z" level="warning" msg="error running container: Error: image library/base_t3: not found" 
time="2015-09-07T02:40:07Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:09Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:17Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:19Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:27Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:29Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:37Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:39Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:47Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:49Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:57Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:40:59Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:41:02Z" level="info" msg="event: date=Mon Sep 07 02:41:02 +0000 2015 type=create image=base_t3 container=43a719f411db" 
time="2015-09-07T02:41:02Z" level="info" msg="event: date=Mon Sep 07 02:41:02 +0000 2015 type=create image=base_t3 container=43a719f411db" 
time="2015-09-07T02:41:02Z" level="info" msg="event: date=Mon Sep 07 02:41:02 +0000 2015 type=start image=base_t3 container=43a719f411db" 
time="2015-09-07T02:41:02Z" level="info" msg="event: date=Mon Sep 07 02:41:02 +0000 2015 type=start image=base_t3 container=43a719f411db" 
time="2015-09-07T02:41:07Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:41:09Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:41:17Z" level="warning" msg="unable to detect docker version: Not found" 
time="2015-09-07T02:41:19Z" level="warning" msg="unable to detect docker version: Not found"

**Comment by ehazlett** [comment]
what version of docker are you using?
