### ISSUE TITLE
Question about linking controllers

### ISSUE THREAD

**Issue by Lovecannon** [shipyard/shipyard#588]
Well Im a devops guy that's setting up a cloud network for a web dev/hosting company I work for. Im looking to simplify our deployment and server management system and Ive been playing around with Shipyard and so far it seems perfect for us.

Right now, Im only setting shipyard to manage our development and staging server but in about 4 months Im planning on using it to manage our production environment. I used Shipyard Deploy to setup the dev server with the controller/api/engine servers. Whenever I add the production system is there any way to link two API/controller servers with all of their nodes so that they can work as one system? Im also using Interlock to do all the routing. If I have to I can keep them as separate clusters but it would nice to manage them through one Shipyard interface. 

On a side note we run a lot of stateful (Wordpress/Drupal) sites and Im thinking about using a distributed filesystem (XtreemFS/Gluster) to share the data files for the databases but run the application instances through Shipyard so that they are available to all of the engines. Does anyone have any experience with that?

**Comment by ehazlett** [comment]
Thanks!  There has been a discussion about a way to browse multiple controllers in the UI.  We haven't done anything yet, but ideas, suggestions, etc would be great if that's desired.

As a heads up, Shipyard v3 is very, very close.  I would recommend checking that out for the production move.  You can get early info here: http://v3-docs.shipyard-project.com/
