### ISSUE TITLE
Docker Compose Integration

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#591]
It would be nice to see Compose applications and services in Shipyard.

**Comment by Lovecannon** [comment]
Apparently it's going to be included as part of v3, which is due to be released soon.

**Comment by tombee** [comment]
+1

**Comment by DarkReZuS** [comment]
+1

**Comment by williamjie** [comment]
+1

**Comment by sebglon** [comment]
+1

**Comment by foliea** [comment]
I just wrote an issue for the docker client that could be related to docker-compose about a common way to add headers for any docker client when communicating with the docker api.

This would be compatible with the way a user can access the remote api of its swarm cluster through shipyard api:

https://github.com/docker/docker/issues/16388

**Comment by kenni-shin** [comment]
Yep it would be nice to add template and edit feature

**Comment by wildsurfer** [comment]
+1

**Comment by Smile42RU** [comment]
What is need implement for this integration?

**Comment by ehazlett** [comment]
A high level design first.  We have discussed a rough idea but would love
to hear what users would like to see.  Does anyone have any ideas?

Here is what we are thinking:

- section to show the containers grouped by a compose project
- the ability to run docker-compose against a shipyard endpoint (that
proxies to swarm)

Thoughts?

**Comment by SmallwoodDR82** [comment]
+1 to #589 

I'd love to be able to edit container configurations after deployment.  Adding a mount or changing port would be much quicker.

**Comment by mahnunchik** [comment]
+1

**Comment by jonaskello** [comment]
+1

**Comment by Aphex2k** [comment]
+1

**Comment by pavankumarkatakam** [comment]
It would be awesome.

**Comment by mavencode01** [comment]
+1

**Comment by dupperinc** [comment]
+1

**Comment by dupperinc** [comment]
any tentative timelines for this feature?

**Comment by AduchiMergen** [comment]
+1

**Comment by taiidani** [comment]
+1

**Comment by yoyostile** [comment]
+1

**Comment by edasque** [comment]
+1

**Comment by shairozan** [comment]
+1

**Comment by bitsofinfo** [comment]
+1

**Comment by afallison** [comment]
+1

**Comment by KonstantinKuklin** [comment]
+1

**Comment by elboletaire** [comment]
:+1:

**Comment by OmgImAlexis** [comment]
Are there any updates on this? Having to destroy and recreate a container just to change a setting is really annoying.

**Comment by tombee** [comment]
I don't think anyone is working on this yet.  If anyone is interested in contributing this feature, I believe Evan had already asked for a proposal/high level design on how this would work.

**Comment by OmgImAlexis** [comment]
@tombee that's for the reply. Is there a chance https://github.com/shipyard/shipyard/issues/589 would be reopened? I understand it was closed in favour of this issue but I see them as two separate issues.

This one is about adding support for Docker Compose where as https://github.com/shipyard/shipyard/issues/589 is just wanting the ability to edit a config of a container and then have it redeployed. The main reason I personally want the second one is if I have to change ENV vars then I should be able to just edit the container, change what I need and then have it redeploy over the top of the old container.

**Comment by tombee** [comment]
That's probably one for @ehazlett to answer.

Personally, I don't really like the idea of adding an 'edit container' option.  I don't feel that it fits with Docker nomenclature.  We don't really want to give new users the idea that they should be 'editing' containers :smile: 

The declarative approach of having an application and/or container definition in compose, and then allowing compose to manage whether a container is re-created  seems like it would be a little more robust.

**Comment by OmgImAlexis** [comment]
Good point, I can understand that it's just annoying to have to destroy and create a new container even if I miss something as simple as a single ENV var.

Even just being able to "suspend" a container and create a new one from the old config would be better than it is right now. Currently I'm still testing out Shipyard but from what I can gather you need to create a new container and guess which settings you had before as it's not laid out on the status page in the same format as the creation page.

If it comes down to it even a "create container from currently running container" button would help so that the current settings would be copied over to the creation dialog. For people just starting out with Shipyard/Docker this would help tremendously.

**Comment by fedya** [comment]
+1

**Comment by RVN-BR** [comment]
+1

In terms of how this is implemented I'm definitely not sure of the "best" way, but I think the rancher folks do a pretty good job with their concept of Applications/Stacks...  Each compose file is an application or stack (dont know why but they use the term interchangably it seems)  Each stack is comprised of one or more containers with respective links (as a normal docker-compose file defines)...  Additional information is currently stored in an external file (container initial scale, etc), but I understand it will all be migrated to the docker-compose file at some point...  I think it would make sense to have something similar...  They support some neat features such as "cross-stack" networking, etc (so you can have a DB stack and a Web stack for example)... not sure how much is based on their "proprietary" development, and how much is just based on docker networking, etc...  They also include their own flavor of loadbalancer which is useful when "upgrading" an application, or set of containers.  You can duplicate an application, test it, and then just change the load balancer mapping in their UI or API to the new one... (I have no idea if the loadbalancer thing is beyond the scope of shipyard, but I think its a nice touch which makes the entire rancher system quite a bit more "polished")...

**Comment by Burstaholic** [comment]
:+1: @RVN-BR - I think Tutum is a great model for this. My group of techie friends is actually kind of up against a wall, as we've been using Tutum to control Dockers on our servers. With Tutum being deprecated in favor of Docker Cloud, which costs money if you want to manage multiple nodes (servers/hosts), Shipyard is the only real free alternative.

The ability to handle Docker-Compose stacks is the single killer feature we would need for Shipyard to be a viable replacement.

**Comment by shairozan** [comment]
You know you can use docker-compose with shipyard, just not from the UI. If you modify the deploy script to expose the Swarm Master you can connect to it via client. [Here](http://darrellbreeden.kinja.com/building-docker-the-scale-of-enterprise-1751723343) is a link to the build instructions if you're interested.

**Comment by ffrouin** [comment]
Thanks for last post, I integrated it with another bash script in order to allow "simple" deployment and management with or without TLS. You can find this tool [here](https://github.com/ffrouin/docker/tree/master/shipyard)

**Comment by stroem** [comment]
+1

**Comment by RVN-BR** [comment]
Tutum is cool, apart from the fact it apparently (from my understanding) uses its own "blueprints" which I dont like as much as docker-compose...

And then thee is the fact that its proprietary and costs money... We are really looking away from lockins at this point... the ecossystem is just too volatile for a true commitment imo...

Good to know shipyard can support docker-compose to deploy, but we still dont have any way of looking/managing these "app groups" (composer definitions) as an object... its a list of containers... (I guess one could work with labels, but it would be just a sore workaround)...

**Comment by robsweet** [comment]
@OmgImAlexis Maybe some kind of 'Deploy Clone Of' functionality would serve your purpose and also satisfy the concerns that @tombee had?

**Comment by OmgImAlexis** [comment]
@robsweet that sounds okay since that'd help people needing to deploy multiple similar containers as well where you have a single master container and then a bunch of similar but slightly different ones like if you're running clusters of the same container but need a different env var in each of the or something. That'd also help if you needed to edit a var you just clone, edit and deploy if it's correct then keep the new one and delete the old one.

**Comment by robsweet** [comment]
@OmgImAlexis Sounds like you should write up a feature request.  It might be something quick for somebody to pick up and bang out.

**Comment by santiagopoli** [comment]
+1 

It would be awesome use docker compose in shipyard since is the only one thing I think Tutum is better for, and I prefer Shipyard for everything else.

**Comment by imkebe** [comment]
+1

**Comment by opthomas-prime** [comment]
+1

**Comment by Dids** [comment]
I'd love to migrate to self-hosted Shipyard from Docker Cloud, but having the ability to write up "stacks" like this would make me instantly switch.

**Comment by CybotTM** [comment]
+1

- defining a storage with project/compose files (git, filesystem, db, ...)
- section to show all projects/compose files
- being able to start/stop/rm/restart projects

- section showing all running and not running services of a project/compose
- being able to start/stop/rm/restart single services

- being able to edit or create new projects/compose (with or without templates) should be a later step

**Comment by YamiOdymel** [comment]
+1

**Comment by alirezaDavid** [comment]
+1

**Comment by tbjers** [comment]
+1

**Comment by Smile42RU** [comment]
One year for complete this issue >_<

**Comment by edasque** [comment]
With all due respect, @smile42RU, you aren't paying a dime for this. I am sure @shipyard knows about this request. In the mean time feel free to submit a pull request like you can for any open source project. Or fork it and fix it in your fork.

**Comment by AndrewAlexMac** [comment]
+1

**Comment by harrybvp** [comment]
+1

**Comment by yeruisen** [comment]
+2

**Comment by Aadachi** [comment]
+1

**Comment by 4383** [comment]
+1

**Comment by allamand** [comment]
Hi all, compose-ui provide very interesting way to integrate compose https://github.com/francescou/docker-compose-ui, It would be very nive to have such a feature integrate within shipyard with authent features and all value added by shipyard.  what do you think ?

**Comment by lukasz-pyrzyk** [comment]
+1

**Comment by Braintelligence** [comment]
+1

**Comment by luchiniatwork** [comment]
+1

**Comment by benwinding** [comment]
Does writing **+1** accomplish anything? 
(was that too obnoxinous?)

**Comment by zhengfc** [comment]
I think this function is like ```rancher``` stack. Hope will coming

**Comment by alekseysemenov** [comment]
+1

**Comment by Samurais** [comment]
+1
