### ISSUE TITLE
shipyard cannot add local docker engine

### ISSUE THREAD

**Issue by marcosps** [shipyard/shipyard#595]
While testing shipyardv2, we tried to add the local docker engine, but some errors happen.

When trying to use 127.0.0.1:2375 (docker http port) shipyard shows "i/o timeout". When using an ip 192.168.x.x, shipyard shows "connection refused". Looking at docker logs, shipyard request does not reach shipyard.

This can be something related to iptables, since docker uses it a lot? Or is this a bug fixed in v3?

Thanks!

**Comment by marcosps** [comment]
I found the option "allow-insecure" in main.go. I'll take a look if this solves my problem.

**Comment by ehazlett** [comment]
Thanks for the feedback.  We have updated the docs as well.  See the preliminary docs here: http://test.shipyard-project.com/docs/deploy/.
