### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by huangminlong** [shipyard/shipyard#596]
Sorry to bring this similar issue if it is annoying, I'm using shipyard v2.0 

something i have done : 
1.go get github.com/tools/godep
 2.npm install -g bower

but i failed when i  make build in my dictoory which i git clone  the shipyard.

my go version is:
 go version go1.4.2 linux/amd64
godep version is:
godep v6 (linux/amd64/go1.4.2)

[long@localhost shipyard]$ make build
# _/home/long/ua_long/git_source/shipyard/controller
usage: 6l [options] main.6
  -1	use alternate profiling code
  -8	assume 64-bit addresses
  -B info
    	define ELF NT_GNU_BUILD_ID note
  -C	check Go calls to C code
  -D addr
    	data address
  -E sym
    	entry symbol
  -I interp
    	set ELF interp
  -L dir
    	add dir to library path
  -H head
    	header type
  -K	add stack underflow checks
  -O	print pc-line tables
  -Q	debug byte-register code gen
  -R rnd
    	address rounding
  -S	check type signatures
  -T addr
    	text address
  -V	print version and exit
  -W	disassemble input
  -X name value
    	define string data
  -Z	clear stack frame on entry
  -a	disassemble output
  -c	dump call graph
  -d	disable dynamic executable
  -extld ld
    	linker to run in external mode
  -extldflags ldflags
    	flags for external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -installsuffix suffix
    	pkg directory suffix
  -k sym
    	set field tracking symbol
  -linkmode mode
    	set link mode (internal, external, auto)
  -n	dump symbol table
  -o outfile
    	set output file
  -r dir1:dir2:...
    	set ELF dynamic linker search path
  -race
    	enable race detector
  -s	disable symbol table
  -shared
    	generate shared object (implies -linkmode external)
  -tmpdir dir
    	leave temporary files in this directory
  -u	reject unsafe packages
  -v	print link trace
  -w	disable DWARF generation
godep: go exit status 2
make: *** [build] Error 1

**Comment by beyondblog** [comment]
cd controller

**Comment by beyondblog** [comment]
```
➜  shipyard git:(master) ✗ pwd
/Users/xxxxxxxxxx/gopath/src/github.com/shipyard/shipyard
➜  shipyard git:(master) ✗ ls
Dockerfile.build   Makefile           controller         event.go           readme.md          roadmap.md         usage.go
Godeps             auth               docker-compose.yml info.go            registry           test.sh            utils
LICENSE            consolesession.go  dockerhub          node.go            registry.go        tlsutils           version
➜  shipyard git:(master) ✗ cd controller 
➜  controller git:(master) ✗ go build ./
➜  controller git:(master) ✗ ls
Dockerfile api        commands   controller main.go    manager    middleware mock_test  readme.md  static
➜  controller git:(master) ✗ ./controller -v
shipyard version 3.0.0 (HEAD)
```

**Comment by ehazlett** [comment]
Yes, please try the Makefile included or go build.

**Comment by asdfsx** [comment]
I got the same problem, so what should I do, if I want to use Makefile???
