### ISSUE TITLE
Where is the container APIs ?

### ISSUE THREAD

**Issue by John-Lin** [shipyard/shipyard#597]
Hi, 
I am using `shipyard v2.0.8` on my project.

Recently, I found the [docs website](http://shipyard-project.com/docs/api/) has been upgraded for v3.0.0 documentation but I need the v2.0.8 docs... 
where can I get them?

I am considering move my project to `shipyard v3.0.0` but it seems there is no container APIs for deploy/destroy/list containers?

**Comment by ehazlett** [comment]
We support the entire Docker Remote API (
http://shipyard-project.com/docs/api/#docker) so anything relating to
containers, images, etc can be sent as a request expected by the Docker
Remote API (i.e. create, start, stop, pull, etc).  I will add a link to
call that out more.

**Comment by John-Lin** [comment]
Thank you! 
So the v3.0.0 documents are all compatible with Docker Remote API docs!

I found that the v3 deploy will fail with permissions issue, and I am trying to [Create a Docker group](http://docs.docker.com/installation/ubuntulinux/#create-a-docker-group) fixed the issue.

the permissions issue is like:
```
linton@linton-ubuntu:~$ curl -sSL https://shipyard-project.com/deploy | bash -s
Deploying Shipyard
 -> Starting Database
Post http:///var/run/docker.sock/v1.20/containers/create?name=shipyard-rethinkdb: dial unix /var/run/docker.sock: permission denied.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

**Comment by ehazlett** [comment]
Try using sudo. curl -sSL https://shipyard-project.com/deploy | sudo bash -s
