### ISSUE TITLE
No docker engine version check in deploy script

### ISSUE THREAD

**Issue by guedressel** [shipyard/shipyard#598]
I just stumbled when I tried to run shipyard the first time:
My machine was not up to date with the lates docker engine version (was running on 1.7.1).
While running the deploy script from https://shipyard-project.com/deploy it failed.
Looked like this:

```
me@host:~$ curl -sSL https://shipyard-project.com/deploy | TLS_CERT_PATH=./certs bash -s
Deploying Shipyard
 -> Starting Database
 -> Starting Cert Volume
Error: Path not specified
```

After some reading in the script an manual tests I discovered, that my installed docker version did not support the "docker cp [host path] [container]:[container path]" command.
It was added in docker v1.8!

Would have saved me some time if the deploy script would have done some environmental checks before deploying containers and leaving me with a broken setup...

**Comment by ehazlett** [comment]
Great feedback!  I will get some checks added.
