### ISSUE TITLE
Documentation for adding new nodes.

### ISSUE THREAD

**Issue by augieschwer** [shipyard/shipyard#599]
Is there some documentation on how to add docker swarm nodes to shipyard?

**Comment by John-Lin** [comment]
+1 There seems no UI for adding a new `Node` (Engine)

**Comment by oudemen** [comment]
+1

**Comment by ytc301** [comment]
![223](https://cloud.githubusercontent.com/assets/9103314/9896094/e35e74e2-5c69-11e5-9e42-6ce41526494f.jpg)
![224](https://cloud.githubusercontent.com/assets/9103314/9896100/f022039c-5c69-11e5-85c7-5ca3a0b065d3.jpg)

not appeared

**Comment by ehazlett** [comment]
Correct.  The deploy script is currently for a single node.  We use the IP direct for the proxy container instead of introducing the discovery service.  We are adding cluster expansion to the docs and deploy script soon.

**Comment by beyondblog** [comment]
Temporary Use ..

Download deploy  script

https://shipyard-project.com/deploy 

probably this modification
```
start_swarm() {
    TLS_OPTS=""
    if [ $ENABLE_TLS = 1 ]; then
        TLS_OPTS="--tlsverify --tlscacert=$SSL_CA_CERT --tlscert=$SSL_CERT --tlskey=$SSL_KEY"
    fi
    ID=$(docker run \
        -ti \
        -d \
        --restart=always \
        --name $PREFIX-swarm \
        --link $PREFIX-proxy:proxy \
        --volumes-from=$PREFIX-certs \
        swarm:latest \
        m token://<you token> --host tcp://0.0.0.0:$SWARM_PORT $TLS_OPTS)
}
```

redeployment
```
$ ACTION=remove ./deploy
$./deploy
```


Reference: 
[0] https://docs.docker.com/swarm/install-manual/
[1] https://docs.docker.com/swarm/

**Comment by ehazlett** [comment]
Thanks for the workaround.  We can implement that for now, however, we were wanting to add the leader election feature to the Swarm deployment.  This requires some more work.

**Comment by ytc301** [comment]
Thanks
![331](https://cloud.githubusercontent.com/assets/9103314/9897814/76cde16c-5c7f-11e5-8823-b249fbad906f.jpg)
![442](https://cloud.githubusercontent.com/assets/9103314/9897821/83feef16-5c7f-11e5-8311-049adac7ddc5.jpg)

**Comment by qiankunli** [comment]
@ytc301 how to add a node like you?

**Comment by chromerobv** [comment]
wha is i already have swarm running? anyway to have it use that one ?

don't really need to going.

**Comment by qiankunli** [comment]
@ehazlett Thank you for your work! I can not use the default discovery service because i am in china. can you show me how to use "IP direct for the proxy container " to add a node?

**Comment by ehazlett** [comment]
@chromerobv yes we will have manual deployment docs shortly.

**Comment by ytc301** [comment]
https://docs.docker.com/swarm/install-manual/

**Comment by ehazlett** [comment]
@ytc301 thanks.  i know how to install swarm :)

It's not as simple as just running Swarm with options.  But good new:  I have a multihost deploy script ready for testing :)

First, deploy a new Shipyard instance (sorry, it must be new because we need to launch the discovery service):

```bash
curl -sSL http://test.shipyard-project.com/deploy | bash -s
```

Then, on another node(s) with a Docker Engine, use the IP of the first machine for the `discovery` environment variable:

```bash
curl -sSL http://test.shipyard-project.com/deploy | ACTION=node DISCOVERY=<IP-OF-SHIPYARD>:8500 bash -s
```

This will configure Swarm on the second node to use the discovery system on the first node.  You should end up with a two node Swarm cluster:

![2015-09-17-230112_917x366_scrot](https://cloud.githubusercontent.com/assets/260642/9951073/02ba678e-5d90-11e5-9b4b-7e5e43eef081.png)

**Comment by ehazlett** [comment]
@chromerobv here are some preliminary manual docs: http://test.shipyard-project.com/docs/deploy/manual/

**Comment by beyondblog** [comment]
+1 :+1:

**Comment by qiankunli** [comment]
@ehazlett Thank you! I solved the problem. there is a feature which may be useful: shipyard could remove exited container and unused image periodically.

**Comment by maxmouchet** [comment]
Hi,

Thanks @ehazlett for the script! However after launching a shipyard instance on a first node (using the new script), I get this error on the second one:

```bash
# docker logs shipyard-swarm-manager
FATA[0000] Leader election is only supported with consul, etcd and zookeeper discovery.

# docker logs shipyard-swarm-agent
INFO[0000] Registering on the discovery service every 20s...  addr=172.22.42.24:2375 discovery=172.22.2.73:8500
ERRO[0000] not implemented in this discovery service
```

Any idea ? Thanks !

**Comment by ehazlett** [comment]
You need to set the env var with the name of the kv store. Like this:
DISCOVERY=consul://172.22.2.73:8500

**Comment by maxmouchet** [comment]
Indeed, thanks !

**Comment by sbilly** [comment]
I'm deployed shipyard on virtualbox, and deployed another node on different VM. But I can not add this node to shipyard. It seems all my VMs has the same ip address 10.0.2.15 on eth0. 


```
ACTION=node DISCOVERY=etcd://192.168.99.100:4001 bash /tmp/deploy

docker logs shipyard-swarm-manager
# docker logs shipyard-swarm-manager
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost
INFO[0000] Registered Engine swarm-node at 10.0.2.15:2375
ERRO[0000] Discovery error: Unexpected watch error
ERRO[0004] Leader Election: watch leader channel closed, the store may be unavailable...
ERRO[0014] Leader Election: watch leader channel closed, the store may be unavailable...

docker logs shipyard-swarm-agent
# docker logs shipyard-swarm-agent
INFO[0000] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
INFO[0020] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
ERRO[0020] 501: All the given peers are not reachable (failed to propose on members [http://10.0.2.15:4001] twice [last error: Put http://10.0.2.15:4001/v2/keys/docker/swarm/nodes/10.0.2.15:2375: dial tcp 10.0.2.15:4001: connection refused]) [0]
INFO[0040] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
ERRO[0040] 501: All the given peers are not reachable (failed to propose on members [http://10.0.2.15:4001] twice [last error: Put http://10.0.2.15:4001/v2/keys/docker/swarm/nodes/10.0.2.15:2375: dial tcp 10.0.2.15:4001: connection refused]) [0]
INFO[2063] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
ERRO[2063] 501: All the given peers are not reachable (failed to propose on members [http://10.0.2.15:4001] twice [last error: Put http://10.0.2.15:4001/v2/keys/docker/swarm/nodes/10.0.2.15:2375: dial tcp 10.0.2.15:4001: connection refused]) [0]
INFO[2083] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
ERRO[2083] 501: All the given peers are not reachable (failed to propose on members [http://10.0.2.15:4001] twice [last error: Put http://10.0.2.15:4001/v2/keys/docker/swarm/nodes/10.0.2.15:2375: dial tcp 10.0.2.15:4001: connection refused]) [0]
INFO[2103] Registering on the discovery service every 20s...  addr=10.0.2.15:2375 discovery=etcd://192.168.99.100:4001
ERRO[2103] 501: All the given peers are not reachable (failed to propose on members [http://10.0.2.15:4001] twice [last error: Put http://10.0.2.15:4001/v2/keys/docker/swarm/nodes/10.0.2.15:2375: dial tcp 10.0.2.15:4001: connection refused]) [0]
```

**Comment by ehazlett** [comment]
You will need to create a new network with either bridge mode or internal
instead of nat. otherwise they won't be able to talk to each other.

**Comment by ehazlett** [comment]
I will add a how to the the docs for vbox.

**Comment by AtulKamra** [comment]
Can I add second node of another machine (Second machine only have Docker Engine installed and not shipyard) on my first machine where I have shipyard installed? 

Any tentative date by which you will be updating script for adding nodes at time of installation?

**Comment by AtulKamra** [comment]
Any plan to have GUI added for adding Nodes?

**Comment by AtulKamra** [comment]
Any plan to have GUI added for adding multiple Nodes in shipyard? If yes, by when we can expect new release to be available.

**Comment by wildsurfer** [comment]
Simple mechanism for adding nodes is very important. So +1 from me

**Comment by AtulKamra** [comment]
Can anyone share the simple steps with me for adding multiple nodes when we already have shipyard installed as docker image?

**Comment by sunshibin21** [comment]
hi everyone,I meet this error ,what's wrong？
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$9OnH6vSzK4FKS/r3e1G1WeJXyfDUIeHzg6KjGthMOHyM/xUOG9gIy"}},"statusText":"Gateway Timeout"}

**Comment by okkervil** [comment]
Current version of shipyard, I can not add a node to cluster. Is there any guide?

**Comment by decker502** [comment]
+1

**Comment by ehazlett** [comment]
Use the deploy script and specify "ACTION=node" to add a node to the
cluster. http://shipyard-project.com/docs/deploy/automated/

**Comment by ehazlett** [comment]
You can also just add another node to the swarm cluster using the normal
swarm methods -- shipyard will detect it.

**Comment by nipunarora** [comment]
is this issue now addressed. Based on the previous comments, it seems like the latest shipyard scripts allow for node addition. How does the "ACTION=node" works. Do I give an IP Address, or will it look in the same subnet for a leader

**Comment by ehazlett** [comment]
You set the DISCOVERY env var and it will join the Swarm agent to that
cluster.

**Comment by ehazlett** [comment]
http://shipyard-project.com/docs/deploy/automated/ -- at the bottom.

**Comment by zh99998** [comment]
only ip address works, domains not.
```
etcd://112.124.115.96:4001
```
=> works
```
etcd://ygobbs.com:4001
```
=> ERRO[0003] client: etcd cluster is unavailable or misconfigured 

it's considered a bug or designed as?

**Comment by ehazlett** [comment]
Are you sure that DNS name is resolvable from the container?

**Comment by zh99998** [comment]
yes it's a public domain and my server resolv works well.
ping is success.

**Comment by nipunarora** [comment]
@ehazlett : Thanks for the response, I am having some issues with the discovery. I have shipyard running locally on my machine(server A), and I can see all the containers on this machine. I have docker installed on another server B, and I ran the following command on server B:

curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://<ip address of server A>:4001 bash -s

However I cannot see the containers of server B in shipyard running on server A

I installed shipyard on server A using the standard mechanism described:

sudo apt-get install docker.io
curl -sSL https://shipyard-project.com/deploy | bash -s

Am I missing something?

**Comment by spudupak** [comment]
Hi,
Any suggestions on how to get multiple docker-machine hosts show up in shipyard.
I have 3 docker-machine virtual hosts.
```
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
consul-ks      -        virtualbox   Running   tcp://192.168.99.107:2376           v1.11.1
swarm-master   -        virtualbox   Running   tcp://192.168.99.118:2376           v1.11.1
swarm-node     -        virtualbox   Running   tcp://192.168.99.119:2376           v1.11.1
```

consul-ks has consul running.
```
[sandeep@spuddupa-lnx ~ [consul-ks]]$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                            NAMES
3bcc7f017302        progrium/consul     "/bin/start -server -"   4 days ago          Up 4 days           53/tcp, 53/udp, 8300-8302/tcp, 8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp   consul

```
swarm-master has swarm and shipyard running.
I started shipyard inside the host using shipyard_deploy.sh modifying it to use DISCOVERY=consul://192.168.99.107:8500 and commenting out starting the "$ACTION" = "deploy" case.
Here is the output of docker ps on the swarm-master node.
```
[sandeep@spuddupa-lnx DOCKER [swarm-master]]$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                            NAMES
37785d5fa388        shipyard/shipyard:latest       "/bin/controller --de"   17 hours ago        Up 17 hours         0.0.0.0:8080->8080/tcp           shipyard-controller
13d23cdc01f4        swarm:latest                   "/swarm j --addr 10.0"   17 hours ago        Up 17 hours         2375/tcp                         shipyard-swarm-agent
be87e9024d16        swarm:latest                   "/swarm m --replicati"   17 hours ago        Up 17 hours         2375/tcp                         shipyard-swarm-manager
518db87f0fb2        shipyard/docker-proxy:latest   "/usr/local/bin/run"     17 hours ago        Up 17 hours         0.0.0.0:2375->2375/tcp           shipyard-proxy
9272aed999d8        alpine                         "sh"                     17 hours ago        Up 17 hours                                          shipyard-certs
88cc791a1ead        rethinkdb                      "rethinkdb --bind all"   17 hours ago        Up 17 hours         8080/tcp, 28015/tcp, 29015/tcp   shipyard-rethinkdb
```

I then created another docker-machine host called swarm-node.
Then I ran the command [export ACTION=node;./shipyard_deploy.sh] to try and join the node

```
sandeep@spuddupa-lnx DOCKER [swarm-node]]$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
ae695bbed8eb        swarm:latest                   "/swarm j --addr 10.0"   16 hours ago        Up 16 hours         2375/tcp                 shipyard-swarm-agent
9a53a1456d32        swarm:latest                   "/swarm m --replicati"   16 hours ago        Up 16 hours         2375/tcp                 shipyard-swarm-manager
782109719da7        shipyard/docker-proxy:latest   "/usr/local/bin/run"     16 hours ago        Up 16 hours         0.0.0.0:2375->2375/tcp   shipyard-proxy
423753f7afe0        alpine                         "sh"                     16 hours ago        Up 16 hours                                  shipyard-certs

```
The issue I have is:
1) I don't see the swarm-node in the shipyard gui.
2) I also notice that there is another instance of shipyard-swarm-manager running inside swarm-node which does not look right. Should I be running the manual deploy script instead?

**Comment by hflamboauto1** [comment]
+1 here . Having apparently samer issues as described by @spudupak 

I see the `node` on shipyard UI but it looks to be not part of the swarm cluster.. 

On `node` I see these containers:

efc1edcfffa1        swarm:latest                   "/swarm j --addr 172."   About an hour ago   Up About an hour    2375/tcp                 shipyard-swarm-agent
521e8fc960a8        swarm:latest                   "/swarm m --replicati"   About an hour ago   Up About an hour    2375/tcp                 shipyard-swarm-manager
95eacfd375be        shipyard/docker-proxy:latest   "/usr/local/bin/run"     About an hour ago   Up About an hour    0.0.0.0:2375->2375/tcp   shipyard-proxy
0f10aaf25ae5        alpine                         "sh"                     About an hour ago   Up About an hour                             shipyard-certs


as pointed `shipyard-swarm-manager` on node.. does not look right and here is a screenshot of the shipyard UI

after removing and reinstall (execute script ACTION=node on same node) .. all goes fine and I can see that it belongs to the cluster

and on this sencond install... swarm-manager is not installed on `node` as expected .. cc @spudupak

**Comment by prologic** [comment]
Let's get this documented :) I did a manual deployment with `docker-compose`:

```#!yml
version: "2"

services:
  database:
    image: rethinkdb
    network_mode: "bridge"
    restart: always

  discovery:
    image: microbox/etcd
    ports:
      - "4001:4001"
      - "7001:7001"
    network_mode: "bridge"
    command: -name discovery
    restart: always

  dockerproxy:
    image: shipyard/docker-proxy
    network_mode: "bridge"
    ports:
      - "2375:2375"
    environment:
      - PORT=2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  swarmmanager:
    image: swarm
    network_mode: "bridge"
    command: manage --host tcp://0.0.0.0:3375 etcd://192.168.0.1:4001
    restart: always

  swarmagent:
    image: swarm
    network_mode: "bridge"
    command: join --addr 192.168.0.1:2375 etcd://192.168.0.1:4001
    restart: always

  controller:
    image: shipyard/shipyard
    links:
      - database:rethinkdb
      - swarmmanager:swarm
    ports:
      - "8080:8080"
    network_mode: "bridge"
    command: server -d tcp://swarm:3375
    restart: always
```

```#!bash
docker-compose up -d
```

**Comment by prologic** [comment]
And here's how you join a second node:

```#!yml
version: "2"

services:
  dockerproxy:
    image: shipyard/docker-proxy
    hostname: node2
    network_mode: "bridge"
    ports:
      - "2375:2375"
    environment:
      - PORT=2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  swarmagent:
    image: swarm
    network_mode: "bridge"
    command: join --addr 192.168.0.2:2375 etcd://192.168.0.1:4001
    restart: always
```

```#!bash
eval $(docker-machine env node2)
docker-compose -f node.yml up -d
```

**Comment by marxenegls** [comment]
is it possible that the default swarm mode is conflicting with shipyards intentions on managing its own swarm cluster? I launched the setup script after i had the cluster configured x1 pi2 /manager-node and  x4 pi3/worker-nodes . all running raspbian jessie and docker 1.12 .

manager1 

pi@rasp-mast:~ $ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                  PORTS                                            NAMES
e286779567f9        janeczku/curl-armv7              "curl --output /dev/n"   1 seconds ago       Up Less than a second                                                    jovial_khorana
0855b0f41cc5        janeczku/shipyard-armv7:latest   "/bin/controller --de"   18 hours ago        Up 18 hours             0.0.0.0:8080->8080/tcp                           shipyard-controller
31c26e32d9d1        hypriot/rpi-swarm:latest         "/swarm j --addr 192."   18 hours ago        Up 18 hours             2375/tcp                                         shipyard-swarm-agent
b52d04b11596        hypriot/rpi-swarm:latest         "/swarm m --replicati"   18 hours ago        Up 18 hours             2375/tcp                                         shipyard-swarm-manager
2b3dd2670311        janeczku/docker-proxy-armv7      "/usr/local/bin/run"     18 hours ago        Up 18 hours             0.0.0.0:2375->2375/tcp                           shipyard-proxy
81ae397d8aee        scaleway/alpine:3.2              "sh"                     18 hours ago        Up 18 hours                                                              shipyard-certs
0c262d6be5fe        janeczku/etcd-armv7:latest       "/bin/etcd -addr 192."   18 hours ago        Up 18 hours             0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
96234d2c1b99        modul8com/rethinkdb-armv7-rpi2   "rethinkdb --bind all"   18 hours ago        Up 18 hours             8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkdb

---   ----    ----  
pi@rasp-mast:~ $ docker info
Containers: 18
 Running: 7
 Paused: 0
 Stopped: 11
Images: 17
Server Version: 1.12.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: 474gcop45nvyp4byo9vdsypb2
 Is Manager: true
 ClusterID: 83mfr7nvoh222gwa68tvl6yl1
 Managers: 1
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months

----------------------------------------   ...    ---------------------------------------  ....  --------------
i ran the deploy script + ACTION=node on each node , all successfully added .

 node00 

pi@raspberrypi00:~ $ docker ps 
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
090483c68865        hypriot/rpi-swarm:latest      "/swarm j --addr 192."   16 hours ago        Up 16 hours         2375/tcp                 shipyard-swarm-agent
627818046c82        hypriot/rpi-swarm:latest      "/swarm m --replicati"   16 hours ago        Up 16 hours         2375/tcp                 shipyard-swarm-manager
6467dc04f7a2        janeczku/docker-proxy-armv7   "/usr/local/bin/run"     16 hours ago        Up 16 hours         0.0.0.0:2375->2375/tcp   shipyard-proxy
088fffd4e82d        scaleway/alpine:3.2           "sh"                     16 hours ago        Up 16 hours                                  shipyard-certs

exact same output on other 3 nodes 

yet no nodes found by shipyard, nor containers or images via the web interface, accessible on rasp-mast:8080 ok. 

I could use a hint as to what is going on

**Comment by ehazlett** [comment]
Correct. Swarm and Swarm mode are mutually exclusive. You cannot yet run
shipyard with swarm mode.

**Comment by hackeys** [comment]
https://www.ivankrizsan.se/2016/07/10/managing-containers-shipyard/ 

The above document is very beautiful :)
