### ISSUE TITLE
How to add new nodes

### ISSUE THREAD

**Issue by ytc301** [shipyard/shipyard#601]
How to add new nodes

**Comment by John-Lin** [comment]
Duplicate of #599

**Comment by beyondblog** [comment]
Reference：https://docs.docker.com/swarm/

:stuck_out_tongue_winking_eye: 

![image](https://cloud.githubusercontent.com/assets/3734587/9896015/28f0d064-5c69-11e5-9c90-d7fca3dcd335.png)

**Comment by ehazlett** [comment]
Closing as a duplicate to #599
