### ISSUE TITLE
Found a BUG at web ui

### ISSUE THREAD

**Issue by ytc301** [shipyard/shipyard#602]
Under the condition of the container
![121](https://cloud.githubusercontent.com/assets/9103314/9894935/387f0288-5c5c-11e5-9ea5-a079276a7d15.JPG)

then click on CONTAINERS
![1222](https://cloud.githubusercontent.com/assets/9103314/9894970/9d1364a0-5c5c-11e5-8aaa-670c4d997305.JPG)

**Comment by ehazlett** [comment]
Thanks for reporting.  Could you tell what browser and version you are using?

/cc @tombee

**Comment by ytc301** [comment]
google chrome    version:42.0.2311.90 m

**Comment by ehazlett** [comment]
Do you get this @tombee ?  I can't reproduce.

**Comment by tombee** [comment]
Yeah I've seen this by selecting a container and then navigating to the
inspect page. I think we can put in a fix where we unload the sidebar on
the destroy event of the containerscontroller.

**Comment by ehazlett** [comment]
Cool.  +1
