### ISSUE TITLE
Shipyard v3 - does it only support docker registry API v1?

### ISSUE THREAD

**Issue by sich75** [shipyard/shipyard#606]
I added a registry (v2) from the UI and when clicking on the search icon for that registry, it brings me to page with this message: "It looks like an error occurred:"

In the web browser console, in the network view, I see that the angular.js script does some sort of query on repositories: "Get 10.7.22.106:5000/v1/search?q=&n=100&page=1: unsupported protocol scheme "". Are you trying to connect to a TLS-enabled daemon without TLS?"  This is the "v1" portion that attracted my attention.

**Comment by tombee** [comment]
Yup, we only support V1.  I've added some validation code in the following PR: #608

**Comment by sich75** [comment]
Are there any plans to support the v2 registry in a near futur?

**Comment by tianon** [comment]
I think this is probably even more important now that https://github.com/docker/docker/pull/16385 has merged (and the intent to completely deprecate v1 has been officialized).

**Comment by ehazlett** [comment]
@tianon +1

**Comment by ehazlett** [comment]
Will track in #625

**Comment by ehazlett** [comment]
Thanks!

**Comment by eterry1388** [comment]
:+1:

**Comment by hhy5861** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
