### ISSUE TITLE
Containers Port Configuration always empty

### ISSUE THREAD

**Issue by Smile42RU** [shipyard/shipyard#609]
What is debug information you need for reproduce it?
Ubuntu 14.04, clear environment (docker, docker-compose, shipyard).

**Comment by Smile42RU** [comment]
Request payload:

{"HostConfig":{"RestartPolicy":{"Name":"no"},"Links":[],"Binds":[],"Privileged":false,"PublishAllPorts":false,

"PortBindings":{"1234/tcp":[{"HostPort":"4321"}]}},

"Links":[],"ExposedPorts":{},"Volumes":{},"Env":[],"AttachStdin":false,"Tty":true,"Image":"centos:7","CpuShares":null,"Memory":null}

**Comment by Smile42RU** [comment]
So, manually exposed by Dockerfile or docker-compose.yml works properly. Shipyard UI still not.

**Comment by ehazlett** [comment]
You need to add an ExposedPorts config. See https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container

**Comment by Smile42RU** [comment]
@ehazlett,

ah, okay. For API calls it will may works, but i mean this is a web interface issue.

Thanks you.

**Comment by ehazlett** [comment]
Ah ok. I will try it on my side. I've never had trouble with the ports. I
will check.

**Comment by ehazlett** [comment]
What are you specifying in the UI?  Can you add a screenshot?

**Comment by Smile42RU** [comment]
What is UI: https://drive.google.com/open?id=0B4AXybL9EEXUeXRDNzNSZU1NVkU

How i use Shipyard for exposing ports: https://drive.google.com/open?id=0B4AXybL9EEXULVZ4VmJMM1BlbW8

What is result of it: https://drive.google.com/open?id=0B4AXybL9EEXUbWV2aFBoSHNEZTA

What is result of exposing ports by Docker Compose: https://drive.google.com/open?id=0B4AXybL9EEXULU1ER1N3S2Vrelk

**Comment by Smile42RU** [comment]
@ehazlett hi, you could repro this issue?

**Comment by Smile42RU** [comment]
@ehazlett any news?

**Comment by Smile42RU** [comment]
@ehazlett bro, any updates?

**Comment by ehazlett** [comment]
Ok I have re-created.  If the image has exposed ports everything is fine.

![2015-09-24-080517_1852x869_scrot](https://cloud.githubusercontent.com/assets/260642/10072926/28bc8932-6293-11e5-8278-82f8d3cb2ddc.png)

![2015-09-24-080527_480x778_scrot](https://cloud.githubusercontent.com/assets/260642/10072928/2cd0eb26-6293-11e5-934a-ff0dfbd8192f.png)

And an automatically allocated one:

![2015-09-24-080704_1855x864_scrot](https://cloud.githubusercontent.com/assets/260642/10072947/49c15072-6293-11e5-9db3-f5a9bd45010a.png)

![2015-09-24-080714_524x801_scrot](https://cloud.githubusercontent.com/assets/260642/10072952/4e16a44c-6293-11e5-9e9b-e0ff808c2dcb.png)

However, if the image does not have an exposed port you cannot manually expose one.  I'll get this fixed.

Thanks for reporting!

**Comment by ehazlett** [comment]
This should be fixed.  I've released `shipyard/shipyard:3.0.1` which is also tagged as `shipyard/shipyard:latest`.  You should be able to `docker pull shipyard/shipyard` and it should be fixed.  Thanks!

**Comment by Smile42RU** [comment]
@ehazlett Great! Thank you.
