### ISSUE TITLE
Checking that websockets works properly

### ISSUE THREAD

**Issue by Smile42RU** [shipyard/shipyard#610]
Please add checker and notifier that websockets works properly nearby vm.connect function.

If someone using nginx proxy and don't using following settings:
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
then websockets will be offline and console will be broken.

Thanks.

**Comment by ehazlett** [comment]
Thanks for the feedback.

/cc @tombee

**Comment by tap3** [comment]
Thx Smile42RU
