### ISSUE TITLE
Use relative url mapping so reverse proxies supported

### ISSUE THREAD

**Issue by markdav** [shipyard/shipyard#612]
Shipyard redirects to root urls, making reverse-proxying trickier.  e.g. 

```
    location /shipyard/ {
       proxy_set_header X-Real-IP  $remote_addr;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_pass http://shipyard_hosts/;
       }
```
Won't work as it forwards to /auth, /images, /containers, etc.  This requires a second reverse proxy on the shipyard host to get around.  Would be better if relative URLs were used so that this wasn't necesary, as in Kibana for instance.

**Comment by ehazlett** [comment]
Closing as duplicate to #587
