### ISSUE TITLE
Port configuration ignored for new containers

### ISSUE THREAD

**Issue by dnshs** [shipyard/shipyard#613]
Any port configuration I set for new containers is being ignored when they're deployed.  The containers deploy fine, i can interact with them, but there is no port configuration. Existing containers (eg. the shipyard-controller ) show port configuration and work OK. 

I'm using docker 1.8.2 , and I've tried deploying shipyard using : 

curl -sSL https://shipyard-project.com/deploy | bash -s
curl -sSL https://shipyard-project.com/deploy | IMAGE=shipyard/shipyard:test bash -s
curl -sSL http://test.shipyard-project.com/deploy | bash -s

So i'm beginning to think it might be an issue with my docker/swarm installation?  Any pointers?

**Comment by ehazlett** [comment]
Hmm can you tell how you are running?  I use specified ports and do not run
into this issue.

**Comment by dnshs** [comment]
I'm running docker on an Ubuntu 14.04 HVM instance on an EC2 instance. I've just created a fresh instance and  installed docker via curl -sSL https://get.docker.com/ | sh , then curl -sSL https://shipyard-project.com/deploy | bash -s 

I can see the existing containers and their port configurations via the shipyard GUI. 

When i create a new ubuntu:15.10 container and specify a port under port configuration (i've tried ports above and below >1024) the container is created but the port configuration isn't applied , and doesn't appear in the GUI when I open the container. 

The container config.json file does show the port , but the hostconfig.json file doesn't list it as exported, perhaps this is the issue?

**Comment by dnshs** [comment]
(if i create a new ubuntu container from the docker CLI the ports work , and i can see them in the shipyard GUI)

**Comment by ehazlett** [comment]
Could be.  I use Debian and haven't had any issues.  Do you have any other
firewall software enabled?

**Comment by Angristan** [comment]
Same problem

**Comment by ehazlett** [comment]
That is a bit old for shipyard. We track the latest stable as supported.
Can you try 1.10 or 1.11 and see if you have the same issues?

**Comment by Angristan** [comment]
I'm runnig the latest version and shipyard does not bind the container port to the host port when creating a container

**Comment by thibentran** [comment]
I encounter the same issue with Docker 1.11.0 (build 4dc5990) and Debian 8.

**Comment by AWoelfel** [comment]
me 2; 
on a fresh installed ubuntu 16.04 using the current shipyard auto install script (curl -s https://shipyard-project.com/deploy | bash -s)

docker version 1.10.3 for linux/amd64


running the mongo db image from the shipyard web ui 'docker ps' stated "27107/tcp" under ports.
Shipyard shows "Internal 27107/tcp" in the container info page.

runing the same container from bash using "-p 27017:27017" shows the correct "0.0.0.0:27017->27017/tcp" in 'docker ps' and the correct "Exposed IP_ADDRESS:27017 → 27017/tcp" within the container info page in shipyard

**Comment by thibentran** [comment]
It seems it is the same problem as mentioned in issue #797
