### ISSUE TITLE
Can't see swarm nodes on the manager node

### ISSUE THREAD

**Issue by mosaicisland** [shipyard/shipyard#615]
Your app looks great and really nice way to see what's going on and what's deployed where within a Swarm.

I think I'm missing something though. I have a 3 node swarm cluster with 4th VM running as the Swarm manager. When I connect to the Swarm manager and do a 'docker info' I can see all the nodes. When I use the Shipyard deploy script on the Swarm Manager node it installs fine and I can login to the app, however I can only see the Swarm Manager node and none of the cluster nodes. How do I get the Shipyard app to see the cluster? Should it be installed on the Swarm Manager?

If I switch the Docker Host to use the Swarm Manger port then I get the following error when deploying Shipyard.

Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=shipyard-certs --link=shipyard-rethinkdb:rethinkdb --link=shipyard-swarm:swarm

**Comment by ehazlett** [comment]
Thanks!

You should be able to install Shipyard anywhere as long as you point it at
the Swarm manager.  The reason it's failing on the second host is because
it probably cannot find the containers needed for the links.

How are you deploying Shipyard?  Via the deploy script or manually?

**Comment by mosaicisland** [comment]
Each host machine has the Docker Daemon listening on port 2375. With the Swarm Manager exposing port 5001. When I run the 'curl -s https://shipyard-project.com/deploy | bash -s' command either directly on the Swarm Manager host or locally with DOCKER_HOST set to SWARM_MANAGER:2375 it installs but can't see the cluster nodes. If I switch to SWARM_MANAGER:5001 then it fails with the above error message.

**Comment by ehazlett** [comment]
The deploy script will launch its own Swarm instance.  If you want to bring
your own Swarm manager, you will need the manual deploy:
http://test.shipyard-project.com/docs/deploy/manual/

**Comment by mosaicisland** [comment]
Ah ok, that's the bit of the jigsaw I was missing. So is it possible to specify the Swarm Token when initialising the Shipyard deployment?

**Comment by ehazlett** [comment]
You can use your own Discovery mechanism if you setup Shipyard without the
deploy script.  We have test docs that you can use as reference:
http://test.shipyard-project.com/docs/deploy/

**Comment by jitendra200890** [comment]
Hello Experts,

I'm new to Shipyard and trying use existing Swarn manager, I have followed the manual setup page but still could't able to see the nodes and containers. though my swarm manager works fine.

Bash#  docker run --rm swarm list token://34bb0cd0faf4c7b304533fc60897af8c
10.200.10.196:2375
10.200.10.193:2375

root@lab-n1:~# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                             NAMES
12fa56dc9883        swarm                          "/swarm join --addr=1"   20 hours ago        Up 20 hours         2375/tcp                                                                          hopeful_lovelace
f32d7f6b4c06        swarm                          "/swarm manage token:"   20 hours ago        Up 20 hours         0.0.0.0:32768->2375/tcp                                                           high_ramanujan
08668363d12b        swarm                          "/swarm join --addr=1"   21 hours ago        Up 21 hours         2375/tcp                                                                          cocky_pare
e0a5f033854f        dockerui/dockerui              "/dockerui"              22 hours ago        Up 22 hours         0.0.0.0:9000->9000/tcp                                                            hungry_mayer
c61e7fadab56        docker/ucp-controller:0.7.1    "/bin/controller serv"   11 days ago         Up 27 hours         0.0.0.0:443->8080/tcp                                                             ucp-controller
4bde460387e6        docker/ucp-cfssl-proxy:0.7.1   "/bin/run"               11 days ago         Up 27 hours         0.0.0.0:12381->12381/tcp                                                          ucp-swarm-ca-proxy
f877f95e7b4c        docker/ucp-cfssl:0.7.1         "/bin/cfssl serve -ad"   11 days ago         Up 27 hours         8888/tcp                                                                          ucp-swarm-ca
4052f68c11cb        docker/ucp-cfssl-proxy:0.7.1   "/bin/run"               11 days ago         Up 27 hours         12381/tcp, 0.0.0.0:12382->12382/tcp                                               ucp-ca-proxy
999f05672a27        docker/ucp-cfssl:0.7.1         "/bin/cfssl serve -ad"   11 days ago         Up 27 hours         8888/tcp                                                                          ucp-ca
a8d533bd6c01        docker/ucp-etcd:0.7.1          "/bin/etcd --data-dir"   11 days ago         Up 27 hours         2380/tcp, 4001/tcp, 7001/tcp, 0.0.0.0:12380->12380/tcp, 0.0.0.0:12379->2379/tcp

Please guide.


Regards

**Comment by AndreeaDora** [comment]
Hey @jitendra200890, I also deployed Shipyard with an already existing swarm (for deploying the swarm I used the same steps as in the manual deploy). If you already have your swarm you only need to deploy the datastore and the controller, make sure in the controller to change the shipyard-swarm-manager with the name or ID of your swarm container.

**Comment by borzamircea** [comment]
Hello @jitendra200890 . I had the same issue with containers and images when deploying with my swarm using the manual steps. Please take a look at #743 , as I managed to fix it. Just change the proxy to use the `shipyard/shipyard:latest` image.

**Comment by ehazlett** [comment]
This has been fixed in the docs on the site.  Please re-open if you continue to have issues.  Thx!

**Comment by jitendra200890** [comment]
So here is what I did as per manual doc steps, but now its only showing one node on the UI i.e the local node (10.200.8.196). however my swarm list shows two node, so I think shipyard still trying to create local manager and agent.

Physical Host 1 : 10.200.10.196
Physical Host 2 : 10.200.10.193

root@altair:~# docker run --rm swarm list token://34bb0cd0faf4c7b30fe83fc60897af8c
10.200.10.193:2375
10.200.10.196:2375

==============Steps=============
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-rethinkdb \
    rethinkdb
    
    
    docker run \
    -ti \
    -d \
    -p 4001:4001 \
    -p 7001:7001 \
    --restart=always \
    --name shipyard-discovery \
    microbox/etcd -name discovery
    
    docker run \
    -ti \
    -d \
    -p 2375:2375 \
    --hostname=$HOSTNAME \
    --restart=always \
    --name shipyard-proxy \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e PORT=2375 \
    shipyard/docker-proxy:latest
    
    docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-manager \
    swarm:latest \
    manage --host tcp://0.0.0.0:3375 etcd://10.200.8.196:4001
    
    docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-agent \
    swarm:latest \
    join --addr 10.200.10.196:2375 etcd://10.200.10.196:4001
    
    docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-controller \
    --link shipyard-rethinkdb:rethinkdb \
    --link shipyard-swarm-manager:swarm \
    -p 8080:8080 \
    shipyard/shipyard:latest \
    server \
    -d tcp://swarm:3375

Please help.

Regards
Jitendra
