### ISSUE TITLE
Error when installing Shipyard on Swarm cluster

### ISSUE THREAD

**Issue by Arwany** [shipyard/shipyard#616]
Hi,

I am getting an error after creating a new swarm cluster and tried to install Shipyard on it. This is the error I am getting:

Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=shipyard-certs --link=shipyard-rethinkdb:rethinkdb --link=shipyard-swarm:swarm

This is the entire script I wrote to make the entire creation process using **docker-machine**:

```
# Create the machines...
echo "Creating Swarm cluster - Cluster Manager: machine-01 ..."

# Generate a swarm cluster token:
TOKEN=$(docker run --rm swarm create)
echo "Got the token: " $TOKEN

docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://$TOKEN machine-01
docker-machine create -d virtualbox --swarm --swarm-discovery token://$TOKEN machine-02
docker-machine create -d virtualbox --swarm --swarm-discovery token://$TOKEN machine-03

eval $(docker-machine env --swarm machine-01)

curl -sSL https://shipyard-project.com/deploy | bash -s
```

The output is:

```
Deploying Shipyard
 -> Starting Database
 -> Starting Cert Volume
 -> Starting Proxy
 -> Starting Swarm
 -> Starting Controller
Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=shipyard-certs --link=shipyard-rethinkdb:rethinkdb --link=shipyard-swarm:swarm
```

What am I doing wrong?

BTW the cluster is working, and I can see using docker info all the nodes.

Thank you guys.

**Comment by Arwany** [comment]
Also the answer here didn't help me much #615.

**Comment by ehazlett** [comment]
The problem is the deploy script launches an embedded Swarm container.  We should update it to detect an existing Swarm.
