### ISSUE TITLE
make build - "cannot find package"

### ISSUE THREAD

**Issue by swege** [shipyard/shipyard#617]
I tried setting up shipyard like described in the "Contributing" section on ubuntu 14.04. I've installed `go version go1.5.1 linux/amd64` and `godep v12 (linux/amd64/go1.5.1)`. I've set up my `GOPATH` env variable to `/home/soeren/gocode`. `make build` failed with the following messages:

    make build            
    main.go:8:2: cannot find package "github.com/shipyard/shipyard/controller/commands" in any of:
    	/usr/local/go/src/github.com/shipyard/shipyard/controller/commands (from $GOROOT)
    	/home/soeren/Projects/swege/shipyard/Godeps/_workspace/src/github.com/shipyard/shipyard/controller/commands (from $GOPATH)
    	/home/soeren/gocode/src/github.com/shipyard/shipyard/controller/commands
    main.go:9:2: cannot find package "github.com/shipyard/shipyard/version" in any of:
    	/usr/local/go/src/github.com/shipyard/shipyard/version (from $GOROOT)
    	/home/soeren/Projects/swege/shipyard/Godeps/_workspace/src/github.com/shipyard/shipyard/version (from $GOPATH)
    	/home/soeren/gocode/src/github.com/shipyard/shipyard/version
    godep: go exit status 1
    make: *** [build] Error 1

Since I recognized where it looked for the packages, I made it work on my machine by `cd ~/gocode/src/github.com/`, `mkdir shipyard && cd shipyard` and `ln -s /home/soeren/Projects/swege/shipyard/ shipyard`

I've no experience with go at all and just set it up for shipyard, but I don't think it is intended to work this way to be able to locate the needed packages.

**Comment by ehazlett** [comment]
I will add a note to the readme.  Thanks!

**Comment by ehazlett** [comment]
Yes the problem was it wasn't in the GOPATH.  Typically, I work from my
GOPATH which for me is $HOME/dev/gocode.  I then clone this repo to
$HOME/dev/gocode/src/github.com/shipyard/shipyard.

**Comment by hhy5861** [comment]
I have encountered this problem, I try go 1.5.2, the same error message. Is there any solution?

error message:
main.go:8:2: cannot find package "github.com/shipyard/shipyard/controller/commands" in any of:
	/usr/local/go/src/github.com/shipyard/shipyard/controller/commands (from $GOROOT)
	/Volumes/Code/golang/src/shipyard/Godeps/_workspace/src/github.com/shipyard/shipyard/controller/commands (from $GOPATH)
	/Volumes/Code/golang/src/github.com/shipyard/shipyard/controller/commands
main.go:9:2: cannot find package "github.com/shipyard/shipyard/version" in any of:
	/usr/local/go/src/github.com/shipyard/shipyard/version (from $GOROOT)
	/Volumes/Code/golang/src/shipyard/Godeps/_workspace/src/github.com/shipyard/shipyard/version (from $GOPATH)
	/Volumes/Code/golang/src/github.com/shipyard/shipyard/version
godep: go exit status 1
make: *** [build] Error 1

my gopath:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/Code/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

my code path:

/Volumes/Code/golang/src/shipyard

**Comment by fbertone** [comment]
Same problem here.
I solved using the same path as suggested above by ehazlett, eg:
mkdir -p ~/dev/gocode/src/github.com/shipyard/
cd ~/dev/gocode/src/github.com/shipyard/
git clone [...]

However, if you want to use your path you should probably create some symlink as suggested by swenge
(I think the issue ticket should be reopened as it have not yet been solved)

**Comment by batandwa** [comment]
Also, assuming I'm at the root of the repository, I believe the help command in the readme should be *./controller/controller -h*. If it's fine, I could combine this and the approach by @fbertone into a pull request.

**Comment by batandwa** [comment]
I found the Docker Compose file to be quite helpful to getting started on front-end related tweaks. Maybe that could be added to the documentation too.

**Comment by fbertone** [comment]
@batandwa I also thought the command to be controller/controller but if you run it like that it wont work.
You should actually cd into the directory controller then run ./controller from there.

**Comment by batandwa** [comment]
@fbertone True. Perhaps the instructions should indicate that one should **cd** in there.
