### ISSUE TITLE
Never seem to see existing images and containers

### ISSUE THREAD

**Issue by Heaphestus** [shipyard/shipyard#619]
Using Centos 7.  The shipyard install works fine and I can log-in and connect but it never seems to connect properly to the docker daemon so I can see the existing containers and images.  I feel this configuration would work fine on ubuntu but I need to use a centos base for our project.  Also, something you probably already know but debian based os puts the docker config in (/etc/default/docker) and Fedora based puts the config in (/etc/sysconfig/docker).  I know this file is usually updated to ensure docker listens on the needed port for Shipyard to connect.  Thoughts?  I am a little new to this so be gentle.

**Comment by ehazlett** [comment]
How are you installing Docker on CentOS?  There is nothing in Shipyard that
depends on the host.  Shipyard just needs Docker.

**Comment by Heaphestus** [comment]
yum install docker

**Comment by Heaphestus** [comment]
I install docker (version 1.7.1-115) as mentioned above, start docker, then run the shipyard deploy bash from the Shipyard website.  The necessary images get pulled and the containers get created and started.  Shipyard is then accessible remotely via the IP and port (x.x.x.x:8080) provided after the pull is complete.

**Comment by ehazlett** [comment]
Hmm well RedHat rebuilds Docker with custom patches.  You may want to use
the official repositories (curl -sSL get.docker.com | sh -).  What are the
logs from the controller (docker logs)?

**Comment by Heaphestus** [comment]
Thanks, I think that did it.  I pull straight from the docker site getting version 1.8, ran your shipyard command and now the images and containers display properly on the web console.  Thanks again.

**Comment by ehazlett** [comment]
Awesome!  You're welcome :D
