### ISSUE TITLE
Support for custom DNS when creating container

### ISSUE THREAD

**Issue by eljrax** [shipyard/shipyard#624]
Feature request: When creating new containers through Shipyard - it would be great to have support for the per-container DNS setting (--dns on the CLI).

**Comment by tombee** [comment]
@eljrax 
Are you referring to adding a new option in the deploy container view?

**Comment by eljrax** [comment]
@tombee yes, just an input field in the "Container Deployment" view

**Comment by tombee** [comment]
Cool okay!  Sounds fine to me.

(We welcome PRs btw :smile:)

**Comment by RustJason** [comment]
thanks @tombee, @eljrax  PRs are welcome, But if you dont't want to do that, I can help

**Comment by tombee** [comment]
@RustJason Yup, submit a PR if you can :)

**Comment by eljrax** [comment]
Go for it, @RustJason
