### ISSUE TITLE
Support Docker Registry v2

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#625]
As v1 is being deprecated we should support registry v2.

**Comment by tombee** [comment]
+1

**Comment by RustJason** [comment]
+1

**Comment by avesanen** [comment]
v2 registry is a requirement for me, so +1.

**Comment by klaakso** [comment]
+1

**Comment by szechyjs** [comment]
:+1:

**Comment by ntrifunovic** [comment]
:+1:

**Comment by tuxknight** [comment]
Awsome 
Expecting authentication service for registry

**Comment by timgriffiths** [comment]
+1

**Comment by fsilveira** [comment]
+1

**Comment by voduytuan** [comment]
+1

**Comment by Args** [comment]
+1

**Comment by QIvan** [comment]
+1

**Comment by eterry1388** [comment]
:+1:

**Comment by kuailedubage** [comment]
+1

**Comment by mariusznet** [comment]
+1
any news on this?

**Comment by ehazlett** [comment]
Yes I have a branch started that works with v2.  The UI needs to be
refactored.

**Comment by bmunday** [comment]
+1 Any idea when this feature will be good to go? What skills are required to refactor the UI?

**Comment by jonaskello** [comment]
+1

**Comment by starlight36** [comment]
+1

**Comment by RustJason** [comment]
@starlight36 你来啦～

**Comment by starlight36** [comment]
@RustJason 是啊，用上了

**Comment by ricard2k** [comment]
+1

**Comment by Aphex2k** [comment]
+1

**Comment by xiagujinqiao** [comment]
registry V2 +1

**Comment by blackside** [comment]
+1

**Comment by asdfsx** [comment]
+1

**Comment by AngieB** [comment]
+1

**Comment by computerlyrik** [comment]
+1 @ehazlett https://github.com/ehazlett/shipyard/tree/registry-v2 nice work, hope this gets productive soon

**Comment by kaiden-gui** [comment]
+1

**Comment by blijblijblij** [comment]
+1

**Comment by loveai88** [comment]
+1

**Comment by eitanshp** [comment]
+1

**Comment by pmccarren** [comment]
+1

**Comment by alexw23** [comment]
If this includes authentication that'd be awesome

**Comment by abdouuullah** [comment]
+1

**Comment by isymbo** [comment]
+1

**Comment by ericLemanissier** [comment]
+1

**Comment by mbentley** [comment]
While I'm sure it is appreciated to see that there is interest, adding `+1`s just ends up sending unnessary emails to everyone subscribed and PRs are always welcome :smile:

**Comment by clhlc** [comment]
+1

**Comment by computerlyrik** [comment]
The above adds the glue code to the branch of @ehazlett 
If anyone is able to add more features and info fields to registry-client-api i am willing to integrate these.

Also, here is a small wiki article about my development environment: https://github.com/shipyard/shipyard/wiki/Develop:-UI-in-AngularJS

**Comment by flavioaiello** [comment]
+1

**Comment by lundner** [comment]
+1

**Comment by nfoonf** [comment]
+1

**Comment by Rohlik** [comment]
+2

**Comment by meAmidos** [comment]
+1

**Comment by ricard2k** [comment]
After 5 months without solving this issue. Somebody are using other docker registry console that supports V2?

**Comment by ehazlett** [comment]
There is the Docker Trusted Registry from Docker that supports v2.

**Comment by kenho1703** [comment]
+1

**Comment by ffrouin** [comment]
+1

**Comment by mavencode01** [comment]
+1

**Comment by gemoya** [comment]
+1

**Comment by TaChao** [comment]
+1

**Comment by wenns** [comment]
+1

**Comment by nfoonf** [comment]
This is some kind of practical joke, isn't it?

**Comment by marsmensch** [comment]
+1 This seems to be the central issue for the v2 registry feature. As i am currently working on a project where shipyard would be the perfect fit, i am interested in getting this feature asap.

As a start, it would be great if there was an official dockerhub image shipyard:registry.v2 available as source for joint testing and/or documentation.

**Comment by gcavalcante8808** [comment]
+1

**Comment by changsijay** [comment]
+1

**Comment by nfoonf** [comment]
Could we just close this issue and admit that shipyard will never support registry v2?

**Comment by ehazlett** [comment]
@nfoonf if you would like to contribute I would be more than happy to review.  as stated in IRC:

```
10:03 <nfoonf> hi i am following this channel for nearly to months now
10:03 <nfoonf> and I finally come to the conclusion, that shipyard is practically totally dead
10:04 <nfoonf> for example the registryv2 support thread is mostly a practically joke
10:06 <nfoonf> as I sunk quite an amount of time (and thererfore money) into getting a productive environment for cluster management running based on shipyard I suggest, that you publicly mark this project as broken/unmaintained etc. to not let other people make the same mistake
10:07 <nfoonf> as in using a immature and unready project in the hope that seemingly minor bugs can and will be fixed or community input is actually in any way either wanted or honored
10:08 <ehazlett> it is an open source project and people's free effort and our own time (usually nights and weekends) cannot always be put priority as we have to maintain day jobs.  being an open source project we welcome contributions and i personally have continued to give direction towards the registry v2 branch.  i'm sorry you are upset you cannot get more effort into
10:08 <ehazlett> this.  i welcome any and all help.
10:12 <ehazlett> in fact there were 5 PRs merged in Feb including one of your own (thank you).  calling a project and its features "practically a joke" is insulting to everyone that has put time and effort into a project and these comments are why people leave open source.  
```

I would love any and all help as my day job is taking priority.  I welcome any and all help.

**Comment by wangkangluo1** [comment]
+1

**Comment by tom-aa** [comment]
+1

**Comment by kazaff** [comment]
now v2 is be cool?

**Comment by kazaff** [comment]
why i get 404 erro when i add local registry: http://192.168.1.23:5000?

**Comment by MrToy** [comment]
So,how can I use registery v2?

**Comment by rqc** [comment]
Hello, everyone... we have incorporated the work that was started on branch https://github.com/shipyard/shipyard/tree/registry-v2 into our work for Shipyard / ILM project, which adds image testing and verification to Shipyard. Our work is still experimental, but if you want to give it a spin, you can clone our fork and switch to the `demo` branch https://github.com/eedevops/shipyard/tree/dev. We hope to eventually submit a pull request back to Shipyard.

**Comment by hezengliang** [comment]
+1

**Comment by RustamGimadiev** [comment]
+1

**Comment by soninob** [comment]
We have a PR submitted for supporting V2, please check #852

**Comment by hackeys** [comment]
+1
