### ISSUE TITLE
Add roles like container ownership for management 

### ISSUE THREAD

**Issue by chun-wang** [shipyard/shipyard#627]
It would be very useful with this feature and ldap for an enterprise using

**Comment by RustJason** [comment]
@tombee  What do you think about this?

**Comment by tombee** [comment]
Sounds good to me.  I think we have some work to do first on ensuring that our LDAP/LDAP over SSL support is good enough before further complicating it with ACL/Roles.

**Comment by ehazlett** [comment]
Currently the LDAP only authenticates so we would do the role support in Shipyard.  I wouldn't defer to LDAP for that for the initial implementation.

I had a prototype starting to do this with labels.  We could do it for containers but other things like images do not have labels to track.
