### ISSUE TITLE
Run container from "templates"

### ISSUE THREAD

**Issue by etlweather** [shipyard/shipyard#632]
Similar to the "scale" option, it would be very useful to be able to define container configuration and start new containers without having to specify every single field each time. It could pre-fill everything from the template, letting you make some adjustment.

Right now, I would have to click "Deploy Container", enter values everywhere and click Deploy. But if I could pull from pre-configured entries it would be awesome.

**Comment by SebOnAir** [comment]
+1 :)

**Comment by scapewang** [comment]
+1

**Comment by nthien** [comment]
+1

**Comment by Smile42RU** [comment]
Dockerfile + docker-compose.yml

**Comment by hlj** [comment]
+1

**Comment by shairozan** [comment]
What I've been trying to get working over the last few days is getting access to the swarm cluster from outside. If you could, and get your client to connect to the cluster via TLS, you could use docker-compose against it and generate environments based off of that template. 

From what I can see in the default implementation, however, the proxy exposed only gives information regarding the node itself, and isn't the swarm cluster details. That's all done internally on 3376 which isn't exposed to the host.

**Comment by drakeu** [comment]
+1

**Comment by elboletaire** [comment]
:+1:

**Comment by exogenesick** [comment]
+1

**Comment by shairozan** [comment]
In case anyone is curious, I have it working where you can connect to the swarm cluster and use docker-compose to deploy applications via docker-client. [Here's](http://darrellbreeden.kinja.com/building-docker-the-scale-of-enterprise-1751723343) the article on how to build it out if anyone is interested.

**Comment by evodevo** [comment]
+1

**Comment by allamand** [comment]
this is related to #591
