### ISSUE TITLE
Issue with LDAP Auth: Spaces in LDAP Base DN

### ISSUE THREAD

**Issue by cmiles74** [shipyard/shipyard#637]
I'm having issues getting the LDAP authentication working with my Active Directory server. I think the issue may be that we have a space in our base DN.

`OU=User Accounts,DC=ourdomain,DC=com`

When Shipyard starts up, it looks like it's not getting the entire base DN that I've configured, it's cut off right at that space.

```
INFO[0000] shipyard version 3.0.1                    
INFO[0000] Using LDAP authentication: server=dc.ourdomain.com port=389 basedn='OU=User 
INFO[0000] checking database                            
INFO[0000] controller listening on :8080                
WARN[0044] unauthorized request for /containers/json from 10.1.1.31:50722 
ERRO[0049] error during login for myself from 10.1.1.31:50722: LDAP Result Code 49 
"Invalid Credentials": 80090308: LdapErr: DSID-0C0903C5, 
comment: AcceptSecurityContext error, data 52e, v2580
```

This might just be an issue with the way the data is displayed, but looking at the relevant Go code has me suspecting otherwise. Escaping the space with `\` doesn't appear to make a difference.

Thank you!

**Comment by ehazlett** [comment]
Hav eyou tried using quotes on the flag?

**Comment by cmiles74** [comment]
Yep, I'm using double quotes on the parameters. I also tried changing it to just "DC=ourdomain,DC=com" thinking it will just search the whole tree (this works for our Nexus server) but that gives the same error. It muddies the water some, perhaps it's an Active Directory issue after all. 

We use Nexus and Gitlab, both use AD for authentication but require a domain user's credentials in order to function, in addition to the DC hostname and base DN. Is there any particular switch or setting on the AD side that Shipyard may be expecting?

**Comment by ehazlett** [comment]
Hmm shouldn't be. I tested on both AD and OpenLDAP and they are fine. I
will see if I can duplicate. is there anything in the logs of AD that would
give more info?

**Comment by darioajr** [comment]
I have the same issue, 
curl -sSL https://shipyard-project.com/deploy | SHIPYARD_ARGS="--ldap-server=10.20.5.47 --ldap-base-dn=cn=linux_admins,OU=Grupos Segurança,DC=company,DC=local --ldap-autocreate-users --auth-whitelist-cidr=admin" bash -s

I miss some parameters: LDAP Filters, LDAP BIND User and Password, LDAP, bypass certificate, type of search (sub, one), convert user names to lowercase, attribute of LDAP account(sAMAccountName)...

**Comment by ehazlett** [comment]
Ok I don't think this will work but could you try:

```
curl -sSL https://shipyard-project.com/deploy | SHIPYARD_ARGS="--ldap-server=10.20.5.47 --ldap-base-dn=\"cn=linux_admins,OU=Grupos Segurança,DC=company,DC=local\" --ldap-autocreate-users --auth-whitelist-cidr=admin" bash -s
```

**Comment by darioajr** [comment]
I executed the command above, but no sucess.
Look the dokcer inspect of container:

```
 "Cmd": [
            "--debug",
            "server",
            "--listen",
            ":8080",
            "-d",
            "tcp://swarm:3375",
            "--ldap-server=10.20.5.47",
            "--ldap-base-dn=\"cn=linux_admins,OU=Grupos",
            "Segurança,DC=company,DC=local\"",
            "--ldap-autocreate-users",
            "--auth-whitelist-cidr=admin"
```
there was a line break.

**Comment by pirogoeth** [comment]
@darioajr Maybe try escaping the space?

```
curl -sSL https://shipyard-project.com/deploy | SHIPYARD_ARGS="--ldap-server=10.20.5.47 --ldap-base-dn=\"cn=linux_admins,OU=Grupos\ Segurança,DC=company,DC=local\" --ldap-autocreate-users --auth-whitelist-cidr=admin" bash -s
```

**Comment by darioajr** [comment]
@pirogoeth Same problem

`````
 "Cmd": [
            "--debug",
            "server",
            "--listen",
            ":8080",
            "-d",
            "tcp://swarm:3375",
            "--ldap-server=10.20.5.47",
            "--ldap-base-dn=\"cn=linux_admins,OU=Grupos\\",
            "Segurança,DC=company,DC=local\"",
            "--ldap-autocreate-users",
            "--auth-whitelist-cidr=admin"

`````

**Comment by innanill** [comment]
+1

**Comment by j-beeler** [comment]
:thumbsup:

**Comment by mohamedfarag** [comment]
:thumbsup:

**Comment by see-SGM** [comment]
Hi,
Ldap does not support anonymous search,How to specify the linux_admins password?
