### ISSUE TITLE
Uninstall shipyard

### ISSUE THREAD

**Issue by miton18** [shipyard/shipyard#639]
I try to remove shipyard, but whaen I reboot, shipyard is stay here
I used: sudo curl -sSL https://shipyard-project.com/deploy | ACTION="remove" bash -s

**Comment by ehazlett** [comment]
Are there any errors when that is run?

**Comment by HansHammel** [comment]
when using sudo try
**sudo** curl -sSL https://shipyard-project.com/deploy | ACTION="remove" **sudo -E** bash -s
cause -E preserves environmental vaiables set
