### ISSUE TITLE
Controller loses shipyard-swarm-manager

### ISSUE THREAD

**Issue by djskinner** [shipyard/shipyard#644]
Hi,

After having got Shipyard up and running with the automated deploy script I have been really impressed. However, after a few hours of running I am coming across an issue whereby the containers disappear from the list and the web UI is showing a loading spinner that never stops and nothing else happens. The controller itself isn't broken because I can load up a new tab, login etc.

I've removed and reinstalled the whole thing which solves the issue but after a few hours it happens again.

There's nothing of interest in the container logs and I'm not sure what to consider next. Any ideas?

Thanks.

**Comment by djskinner** [comment]
`docker restart shipyard-swarm-manager` seems to get it back. What is the problem likely to be with swarm manager?

**Comment by ehazlett** [comment]
This will happen if the Swarm agent stops.  Is there any memory constraints that would be causing the container to be killed?  Can you paste your Docker version info?

**Comment by ephemeraleclipse** [comment]
Having this issue as well...  restarting manager does get everything back up and running... checked the manager's log... not much useful info there

**Comment by ehazlett** [comment]
Can you paste the logs of the controller. It may help even if it doesn't
seem like it. It's most likely an etcd issue as it's not HA.

**Comment by ephemeraleclipse** [comment]
INFO[0000] shipyard version 3.0.2
INFO[0000] checking database
DEBU[0032] connected to docker: url=tcp://swarm:3375
DEBU[0032] configured docker proxy target: http://swarm:3375
INFO[0032] created admin user: username: admin password: shipyard
INFO[0032] controller listening on :8080
WARN[0122] unauthorized request for /containers/json from {{IP Redacted}}:2526
DEBU[0125] GET: /containers/json?all=1
DEBU[0130] GET: /api/accounts
DEBU[0130] GET: /api/roles
DEBU[0131] GET: /api/accounts/admin
DEBU[0134] POST: /api/accounts
DEBU[0134] updated account: name=admin
DEBU[0137] GET: /images/json?all=1
DEBU[0138] GET: /api/nodes
DEBU[0732] GET: /api/registries
DEBU[0737] GET: /api/nodes
WARN[37066] unauthorized request for /containers/json from {{IP Redacted}}:50298
DEBU[37075] GET: /containers/json?all=1
DEBU[37077] GET: /images/json?all=1
DEBU[37334] GET: /api/nodes
DEBU[37406] POST: /containers/create?name=Shipyard-Nginx-Reverse-Proxy
DEBU[37406] POST: /containers/360958b09337b71ec403c8d43066e54fef3872881e1d7c35dfa2ef8a2fbc003f/start
DEBU[38087] GET: /containers/json?all=1
DEBU[38097] POST: /containers/5095091be6bfad42b3550546410c63c6ab59acc1c063a35b8221211ee6af92e7/restart
WARN[38114] unauthorized request for /containers/json from {{IP Redacted}}:59138
DEBU[38131] GET: /containers/json?all=1
WARN[38145] unauthorized request for /containers/json from {{IP Redacted}}:59271
DEBU[38152] GET: /containers/json?all=1
DEBU[38155] GET: /api/nodes
DEBU[38160] GET: /images/json?all=1
DEBU[38163] GET: /containers/json?all=1
DEBU[38172] GET: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/json
DEBU[38174] GET: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/logs?stderr=1&stdout=1&timestamps=1
DEBU[38193] GET: /containers/json?all=1
DEBU[38197] POST: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/restart
DEBU[38197] GET: /containers/json?all=1
DEBU[38418] GET: /api/nodes
DEBU[38419] GET: /api/nodes
DEBU[38420] GET: /api/nodes
DEBU[38421] GET: /api/nodes
DEBU[38421] GET: /api/nodes
DEBU[38422] GET: /api/nodes
DEBU[38422] GET: /api/nodes
DEBU[38423] GET: /api/nodes
DEBU[38423] GET: /api/nodes
DEBU[38423] GET: /containers/json?all=1
DEBU[38458] GET: /containers/json?all=1
DEBU[38462] GET: /api/nodes
DEBU[38510] GET: /containers/json?all=1
DEBU[38519] GET: /api/nodes
DEBU[38606] POST: /containers/5095091be6bfad42b3550546410c63c6ab59acc1c063a35b8221211ee6af92e7/stop
DEBU[46542] GET: /containers/json?all=1
DEBU[46546] GET: /containers/json?all=1
DEBU[46547] GET: /api/nodes
DEBU[46548] GET: /containers/json?all=1
DEBU[46705] GET: /containers/json?all=1
DEBU[46707] GET: /api/nodes
DEBU[46709] GET: /containers/json?all=1
WARN[173775] unauthorized request for /containers/json from {{IP Redacted}}:32923
DEBU[173784] GET: /containers/json?all=1
DEBU[173798] GET: /api/nodes
DEBU[173835] GET: /containers/json?all=1
WARN[173841] invalid login for admin from {{IP Redacted}}:32940
WARN[173861] unauthorized request for /containers/json from {{IP Redacted}}:32947
WARN[173880] unauthorized request for /containers/json from {{IP Redacted}}:32952
DEBU[173887] GET: /containers/json?all=1
WARN[173910] unauthorized request for /containers/json from {{IP Redacted}}:33113
DEBU[173920] GET: /containers/json?all=1
INFO[0000] shipyard version 3.0.2
INFO[0000] checking database
DEBU[0000] connected to docker: url=tcp://swarm:3375
DEBU[0000] configured docker proxy target: http://swarm:3375
INFO[0000] controller listening on :8080
DEBU[0006] GET: /containers/json?all=1
DEBU[0011] GET: /containers/json?all=1
DEBU[0014] GET: /containers/json?all=1
DEBU[0043] GET: /containers/json?all=1
DEBU[0046] GET: /containers/json?all=1
DEBU[0161] GET: /containers/json?all=1
DEBU[0166] GET: /containers/json?all=1
DEBU[0175] GET: /containers/json?all=1
DEBU[0176] GET: /api/nodes
lxing@us1:~$ sudo docker --version
Docker version 1.9.1, build a34a1d5
lxing@us1:~$ sudo docker logs shipyard-controller
INFO[0000] shipyard version 3.0.2
INFO[0000] checking database
DEBU[0032] connected to docker: url=tcp://swarm:3375
DEBU[0032] configured docker proxy target: http://swarm:3375
INFO[0032] created admin user: username: admin password: shipyard
INFO[0032] controller listening on :8080
WARN[0122] unauthorized request for /containers/json from {{IP Redacted}}:2526
DEBU[0125] GET: /containers/json?all=1
DEBU[0130] GET: /api/accounts
DEBU[0130] GET: /api/roles
DEBU[0131] GET: /api/accounts/admin
DEBU[0134] POST: /api/accounts
DEBU[0134] updated account: name=admin
DEBU[0137] GET: /images/json?all=1
DEBU[0138] GET: /api/nodes
DEBU[0732] GET: /api/registries
DEBU[0737] GET: /api/nodes
WARN[37066] unauthorized request for /containers/json from {{IP Redacted}}:50298
DEBU[37075] GET: /containers/json?all=1
DEBU[37077] GET: /images/json?all=1
DEBU[37334] GET: /api/nodes
DEBU[37406] POST: /containers/create?name=Shipyard-Nginx-Reverse-Proxy
DEBU[37406] POST: /containers/360958b09337b71ec403c8d43066e54fef3872881e1d7c35dfa2ef8a2fbc003f/start
DEBU[38087] GET: /containers/json?all=1
DEBU[38097] POST: /containers/5095091be6bfad42b3550546410c63c6ab59acc1c063a35b8221211ee6af92e7/restart
WARN[38114] unauthorized request for /containers/json from {{IP Redacted}}:59138
DEBU[38131] GET: /containers/json?all=1
WARN[38145] unauthorized request for /containers/json from {{IP Redacted}}:59271
DEBU[38152] GET: /containers/json?all=1
DEBU[38155] GET: /api/nodes
DEBU[38160] GET: /images/json?all=1
DEBU[38163] GET: /containers/json?all=1
DEBU[38172] GET: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/json
DEBU[38174] GET: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/logs?stderr=1&stdout=1&timestamps=1
DEBU[38193] GET: /containers/json?all=1
DEBU[38197] POST: /containers/2ae6307f2663f99a26cf18fe2cfec57cc932738f2217dc9e3c3b67683bf8e818/restart
DEBU[38197] GET: /containers/json?all=1
DEBU[38418] GET: /api/nodes
DEBU[38419] GET: /api/nodes
DEBU[38420] GET: /api/nodes
DEBU[38421] GET: /api/nodes
DEBU[38421] GET: /api/nodes
DEBU[38422] GET: /api/nodes
DEBU[38422] GET: /api/nodes
DEBU[38423] GET: /api/nodes
DEBU[38423] GET: /api/nodes
DEBU[38423] GET: /containers/json?all=1
DEBU[38458] GET: /containers/json?all=1
DEBU[38462] GET: /api/nodes
DEBU[38510] GET: /containers/json?all=1
DEBU[38519] GET: /api/nodes
DEBU[38606] POST: /containers/5095091be6bfad42b3550546410c63c6ab59acc1c063a35b8221211ee6af92e7/stop
DEBU[46542] GET: /containers/json?all=1
DEBU[46546] GET: /containers/json?all=1
DEBU[46547] GET: /api/nodes
DEBU[46548] GET: /containers/json?all=1
DEBU[46705] GET: /containers/json?all=1
DEBU[46707] GET: /api/nodes
DEBU[46709] GET: /containers/json?all=1
WARN[173775] unauthorized request for /containers/json from {{IP Redacted}}:32923
DEBU[173784] GET: /containers/json?all=1
DEBU[173798] GET: /api/nodes
DEBU[173835] GET: /containers/json?all=1
WARN[173841] invalid login for admin from {{IP Redacted}}:32940
WARN[173861] unauthorized request for /containers/json from {{IP Redacted}}:32947
WARN[173880] unauthorized request for /containers/json from {{IP Redacted}}:32952
DEBU[173887] GET: /containers/json?all=1
WARN[173910] unauthorized request for /containers/json from {{IP Redacted}}:33113
DEBU[173920] GET: /containers/json?all=1
INFO[0000] shipyard version 3.0.2
INFO[0000] checking database
DEBU[0000] connected to docker: url=tcp://swarm:3375
DEBU[0000] configured docker proxy target: http://swarm:3375
INFO[0000] controller listening on :8080
DEBU[0006] GET: /containers/json?all=1
DEBU[0011] GET: /containers/json?all=1
DEBU[0014] GET: /containers/json?all=1
DEBU[0043] GET: /containers/json?all=1
DEBU[0046] GET: /containers/json?all=1
DEBU[0161] GET: /containers/json?all=1
DEBU[0166] GET: /containers/json?all=1
DEBU[0175] GET: /containers/json?all=1
DEBU[0176] GET: /api/nodes

**Comment by ehazlett** [comment]
Controller looks OK. What are the logs from the other containers?

**Comment by ephemeraleclipse** [comment]
Swarm Agent's log is just bunch of "Registering on the discovery service every 20s..."

Swarm Manager's log is:
```
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost
ERRO[0000] Discovery error: Unexpected watch error
ERRO[0000] Leader Election: watch leader channel closed, the store may be unavailable...
INFO[0000] Leader Election: Cluster leadership acquired
INFO[0020] Registered Engine us1 at {{IP Redacted}}:2375
ERRO[0663] Get http://{{IP Redacted}}:2375/v1.15/info: dial tcp {{IP Redacted}}:2375: connection refused
INFO[46680] Registered Engine docker-node-1 at {{IP Redacted}}:2375
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost
INFO[0000] Registered Engine us1 at {{IP Redacted}}:2375
INFO[0000] Registered Engine docker-node-1 at {{IP Redacted}}:2375
ERRO[0003] HTTP error: No elected primary cluster manager  status=500
ERRO[0009] HTTP error: No elected primary cluster manager  status=500
INFO[0014] Leader Election: Cluster leadership acquired
```

etcd logs:
```
[etcd] Dec 11 06:16:31.005 WARNING   | Using the directory f164b7a508cc.etcd as the etcd curation directory because a directory was not specified.
[etcd] Dec 11 06:16:31.006 INFO      | f164b7a508cc is starting a new cluster
[etcd] Dec 11 06:16:31.009 INFO      | etcd server [name f164b7a508cc, listen on :4001, advertised url http://{{{{IP Redacted}}}}:4001]
[etcd] Dec 11 06:16:31.009 INFO      | peer server [name f164b7a508cc, listen on :7001, advertised url http://{{IP Redacted}}:7001]
[etcd] Dec 11 06:16:31.010 INFO      | f164b7a508cc starting in peer mode
[etcd] Dec 11 06:16:31.010 INFO      | f164b7a508cc: state changed from 'initialized' to 'follower'.
[etcd] Dec 11 06:16:31.010 INFO      | f164b7a508cc: state changed from 'follower' to 'leader'.
[etcd] Dec 11 06:16:31.010 INFO      | f164b7a508cc: leader changed from '' to 'f164b7a508cc'.
[etcd] Dec 11 07:29:13.600 INFO      | f164b7a508cc: snapshot of 10003 events at index 10003 completed
[etcd] Dec 11 08:41:44.094 INFO      | f164b7a508cc: snapshot of 10006 events at index 20009 completed
[etcd] Dec 11 09:54:14.596 INFO      | f164b7a508cc: snapshot of 10006 events at index 30015 completed
[etcd] Dec 11 11:06:45.089 INFO      | f164b7a508cc: snapshot of 10006 events at index 40021 completed
[etcd] Dec 11 12:19:15.583 INFO      | f164b7a508cc: snapshot of 10005 events at index 50026 completed
[etcd] Dec 11 13:31:46.083 INFO      | f164b7a508cc: snapshot of 10007 events at index 60033 completed
[etcd] Dec 11 14:44:16.590 INFO      | f164b7a508cc: snapshot of 10005 events at index 70038 completed
[etcd] Dec 11 15:56:47.097 INFO      | f164b7a508cc: snapshot of 10006 events at index 80044 completed
[etcd] Dec 11 17:08:44.591 INFO      | f164b7a508cc: snapshot of 10008 events at index 90052 completed
[etcd] Dec 11 18:18:15.076 INFO      | f164b7a508cc: snapshot of 10009 events at index 100061 completed
[etcd] Dec 11 19:27:48.577 INFO      | f164b7a508cc: snapshot of 10008 events at index 110069 completed
[etcd] Dec 11 20:37:16.093 INFO      | f164b7a508cc: snapshot of 10001 events at index 120070 completed
[etcd] Dec 11 21:46:46.586 INFO      | f164b7a508cc: snapshot of 10007 events at index 130077 completed
[etcd] Dec 11 22:56:14.077 INFO      | f164b7a508cc: snapshot of 10002 events at index 140079 completed
[etcd] Dec 12 00:05:41.584 INFO      | f164b7a508cc: snapshot of 10001 events at index 150080 completed
[etcd] Dec 12 01:15:12.079 INFO      | f164b7a508cc: snapshot of 10009 events at index 160089 completed
[etcd] Dec 12 02:24:39.570 INFO      | f164b7a508cc: snapshot of 10001 events at index 170090 completed
[etcd] Dec 12 03:34:10.059 INFO      | f164b7a508cc: snapshot of 10007 events at index 180097 completed
[etcd] Dec 12 04:43:37.547 INFO      | f164b7a508cc: snapshot of 10002 events at index 190099 completed
[etcd] Dec 12 05:53:05.032 INFO      | f164b7a508cc: snapshot of 10001 events at index 200100 completed
[etcd] Dec 12 07:02:35.526 INFO      | f164b7a508cc: snapshot of 10009 events at index 210109 completed
[etcd] Dec 12 08:12:03.010 INFO      | f164b7a508cc: snapshot of 10002 events at index 220111 completed
[etcd] Dec 12 09:21:30.487 INFO      | f164b7a508cc: snapshot of 10001 events at index 230112 completed
[etcd] Dec 12 10:31:00.969 INFO      | f164b7a508cc: snapshot of 10009 events at index 240121 completed
[etcd] Dec 12 11:40:31.446 INFO      | f164b7a508cc: snapshot of 10007 events at index 250128 completed
[etcd] Dec 12 12:50:01.923 INFO      | f164b7a508cc: snapshot of 10007 events at index 260135 completed
[etcd] Dec 12 13:59:29.408 INFO      | f164b7a508cc: snapshot of 10003 events at index 270138 completed
[etcd] Dec 12 15:08:59.893 INFO      | f164b7a508cc: snapshot of 10007 events at index 280145 completed
[etcd] Dec 12 16:18:27.387 INFO      | f164b7a508cc: snapshot of 10002 events at index 290147 completed
[etcd] Dec 12 17:27:54.872 INFO      | f164b7a508cc: snapshot of 10001 events at index 300148 completed
[etcd] Dec 12 18:37:25.357 INFO      | f164b7a508cc: snapshot of 10007 events at index 310155 completed
[etcd] Dec 12 19:46:52.837 INFO      | f164b7a508cc: snapshot of 10002 events at index 320157 completed
[etcd] Dec 12 20:56:20.325 INFO      | f164b7a508cc: snapshot of 10001 events at index 330158 completed
[etcd] Dec 12 22:05:50.823 INFO      | f164b7a508cc: snapshot of 10007 events at index 340165 completed
[etcd] Dec 12 23:15:18.311 INFO      | f164b7a508cc: snapshot of 10002 events at index 350167 completed
[etcd] Dec 13 00:24:45.805 INFO      | f164b7a508cc: snapshot of 10001 events at index 360168 completed
[etcd] Dec 13 01:34:16.292 INFO      | f164b7a508cc: snapshot of 10009 events at index 370177 completed
[etcd] Dec 13 02:43:46.769 INFO      | f164b7a508cc: snapshot of 10009 events at index 380186 completed
[etcd] Dec 13 03:53:20.286 INFO      | f164b7a508cc: snapshot of 10005 events at index 390191 completed
[etcd] Dec 13 05:02:50.774 INFO      | f164b7a508cc: snapshot of 10007 events at index 400198 completed
[etcd] Dec 13 06:12:21.262 INFO      | f164b7a508cc: snapshot of 10009 events at index 410207 completed
```

**Comment by ehazlett** [comment]
Ya try a manager restart. We should get a proper HA deploy that would
handle restarts more graceful.

**Comment by ephemeraleclipse** [comment]
any idea when that would be? Thanks :+1: 

also as a side note i'm getting this on chrome as well... is this a known issue?

```
TypeError: Cannot read property 'Names' of null
    at shortestContainerName (containers.controller.js:288)
    at ContainersController.containerName (containers.controller.js:278)
    at angular.js:12474
    at Object.<anonymous> (angular.js:12883)
    at n.$digest (angular.js:14404)
    at n.$apply (angular.js:14675)
    at l (angular.js:9725)
    at F (angular.js:9915)
    at XMLHttpRequest.C.onload (angular.js:9856)
```

**Comment by ehazlett** [comment]
Not sure on the HA deploy.  Contributions welcome :)

That looks like you are on an older version of Swarm or the Engine perhaps.

On Sat, Dec 12, 2015 at 11:58 PM, ephemeraleclipse <notifications@github.com

**Comment by ephemeraleclipse** [comment]
hmm... okay... thanks :)

**Comment by benariamir** [comment]
I got the same issue yesterday. Looks like it might be related to Swarm Manager leader election.

If the master's swarm manager shuts down or restarts for some reason, one of the nodes will be elected as the "primary cluster manager" (awesome failover!). The problem is.. that either all managers or the shipyard controller needs to communicate with the newly elected leader.. on port 3375 which is not exposed from the manager container to the host and between hosts.

@ehazlett please add me as a contributor so I can open a pull request
I've changed the deployment script on the starm_swarm_manager function, adding
-p $SWARM_PORT:$SWARM_PORT \


start_swarm_manager() {
    get_ip

    TLS_OPTS=""
    if [ $ENABLE_TLS = 1 ]; then
        TLS_OPTS="--tlsverify --tlscacert=$SSL_CA_CERT --tlscert=$SSL_CERT --tlskey=$SSL_KEY"
    fi

    EXTRA_RUN_OPTS=""

    if [ -z "$DISCOVERY" ]; then
        DISCOVERY="$DISCOVERY_BACKEND://discovery:$DISCOVERY_PORT"
        EXTRA_RUN_OPTS="--link $PREFIX-discovery:discovery"
    fi
    ID=$(docker run \
        -ti \
        -d \
        -p $SWARM_PORT:$SWARM_PORT \
        --restart=always \
        --name $PREFIX-swarm-manager \
        --volumes-from=$PREFIX-certs $EXTRA_RUN_OPTS \
        swarm:1.1.2 \
        m --replication --addr $SHIPYARD_IP:$SWARM_PORT --host tcp://0.0.0.0:$SWARM_PORT $TLS_OPTS $DISCOVERY)
}

I simulated it with manually restarting the master's swarm manager container... and then I got 504 from the controller for a minute or two.. and then everything went back live.
