### ISSUE TITLE
ARM support for agents

### ISSUE THREAD

**Issue by didiersmith** [shipyard/shipyard#646]
We're deploying containers in a configuration with a central x86 linux server and raspberry pi leaf agents (running raspbian). I'd like to be able to manage this entire swarm with shipyard, but there currently does not appear to be ARM support. Would it be possible for you to produce ARM builds and make them available on docker hub?

This is currently what happens:

[root@alarmpi ~]# curl -sSL https://shipyard-project.com/deploy > shipyard.sh && chmod +x shipyard.sh
[root@alarmpi ~]# ACTION=node DISCOVERY=etcd://...:4001 ./shipyard.sh 
Adding Node
 -> Starting Cert Volume
Unable to find image 'alpine:latest' locally
latest: Pulling from alpine
f4fddc471ec2: Pulling fs layer
f4fddc471ec2: Verifying Checksum
f4fddc471ec2: Download complete
f4fddc471ec2: Pull complete
alpine:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:fb9f16730ac6316afa4d97caa5130219927bfcecf0b0ce35c01dcb612f449739
Status: Downloaded newer image for alpine:latest
time="2015-10-22T22:26:43Z" level=fatal msg="Error response from daemon: Cannot start container 81fb828e7931f787caf68b07582f611be15b1defa52a5fd9f02dfe277632ed63: [8] System error: exec format error"

**Comment by ehazlett** [comment]
I think once we get multi-arch support in the official repos we could add this.  Would it be ok for this to be in a separate registry for the interim?

**Comment by didiersmith** [comment]
A separate registry would be fine :)

**Comment by janeczku** [comment]
@didiersmith In the meantime you can use https://github.com/janeczku/docker-shipyard-armv7. I am running this on Scaleway's bare-metal ARM nodes.

**Comment by Tapppi** [comment]
Any updated on this (or the possibility of it being included in the main repo)? This would be really cool for some development and test environments I'm running, since I have some rPi 2s sitting around. Also thank you @janeczku for an excellent option. :smile:
