### ISSUE TITLE
v3.0.1 web ui new issue

### ISSUE THREAD

**Issue by ytc301** [shipyard/shipyard#651]
Multiple container names duplicate
![1](https://cloud.githubusercontent.com/assets/9103314/10837041/ef3ac48e-7eef-11e5-850f-c1961dbf52e1.JPG)
![2](https://cloud.githubusercontent.com/assets/9103314/10837052/000b81b8-7ef0-11e5-86e2-2e9be9aec38a.jpg)

**Comment by ehazlett** [comment]
Can you post the output of "docker version"

**Comment by ehazlett** [comment]
Actually I believe this is fixed in e7c8e52ff166e1a0790bf66f5c9074f7a4c9c55f.  It will come in the next release.  If you continue to have issues after that please re-open.

**Comment by ytc301** [comment]
Docker version 1.7.1, build 446ad9b/1.7.1

**Comment by ehazlett** [comment]
Please paste the full output.  I want to see if this is the RedHat build.

**Comment by ytc301** [comment]
![3](https://cloud.githubusercontent.com/assets/9103314/10837143/0aa6c3fc-7ef1-11e5-9e80-a4b7e33b1246.jpg)

**Comment by ytc301** [comment]
![image](https://cloud.githubusercontent.com/assets/9103314/10837160/309f1014-7ef1-11e5-9b65-7b00c65e1581.png)

**Comment by ehazlett** [comment]
Hmm looks like they changed the format.  That is a custom build of Docker
and is known to have issues (notice the build 446ad9b -- the official 1.7.1
is 786b29d).  I recommend using the official Docker builds from the Docker
RPM repositories.  See here for more info
http://docs.docker.com/installation/rhel/

**Comment by ytc301** [comment]
![image](https://cloud.githubusercontent.com/assets/9103314/10837322/0707a5d4-7ef3-11e5-9f5c-456e5aaa6ef9.png)
docker 1.7.1 This version is not supported

**Comment by ytc301** [comment]
os:centos 7.1

**Comment by ytc301** [comment]
kernel and docker version update new
![image](https://cloud.githubusercontent.com/assets/9103314/10838925/183c4282-7f08-11e5-8f08-c06a467184da.png)

issue still exist

![image](https://cloud.githubusercontent.com/assets/9103314/10838932/39a4183c-7f08-11e5-96f3-159d0b4f6a25.png)

**Comment by ytc301** [comment]
@ehazlett

**Comment by ehazlett** [comment]
See my comment above.  It should be fixed in master and will come with the
next release.
