### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by aleafboat** [shipyard/shipyard#652]
Automated Deployment 

curl -sSL https://shipyard-project.com/deploy | bash -s

http://192.168.113.141:8080/
504 Gateway Time-out
The server didn't respond in time.

why?

[root@localhost docker]# docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                                            NAMES
1a0057699325        shipyard/shipyard:latest       "/bin/controller --d   About an hour ago   Up 9 minutes        0.0.0.0:8080->8080/tcp                           shipyard-controller  
a5affd503ee9        swarm:latest                   "/swarm j --addr 192   About an hour ago   Up 9 minutes        2375/tcp                                         shipyard-swarm-agent  
57150a0a39d7        swarm:latest                   "/swarm m --replicat   About an hour ago   Up 9 minutes        2375/tcp                                         shipyard-swarm-manager  
2ad71e330384        ehazlett/docker-proxy:latest   "/usr/local/bin/run"   About an hour ago   Up 9 minutes        0.0.0.0:2375->2375/tcp                           shipyard-proxy  
90712d94e988        alpine:latest                  "sh"                   About an hour ago   Up 9 minutes                                                         shipyard-certs  
2999b23c9171        microbox/etcd:latest           "/bin/etcd -addr 192   About an hour ago   Up 9 minutes        0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery

**Comment by ehazlett** [comment]
That looks like you have it running behind nginx or something. Are you sure
you have the backend and access configured properly?  We don't use nginx in
the deploy.

**Comment by aleafboat** [comment]
i not use nginx，i not change any configured properly

**Comment by sunshibin21** [comment]
I meet the same issue,do you solve it ?
