### ISSUE TITLE
Add host option missing to start a container

### ISSUE THREAD

**Issue by mbettan** [shipyard/shipyard#654]
Hello,

I am not able to find "Add Host" option in order to add an entry in hosts file ? Can we add this as enchancement ?

Thanks

**Comment by ehazlett** [comment]
You can use links. That is how Docker does it.

**Comment by AntoinePlantin** [comment]
Thanks, but is there any way to use --add-host ? (https://docs.docker.com/reference/run/#managing-etc-hosts)
