### ISSUE TITLE
(Solved) Connection Time Out

### ISSUE THREAD

**Issue by Heaphestus** [shipyard/shipyard#657]
Running "curl -sSL https://shipyard-project.com/deploy | bash -s"

[root@docker01 ~]# curl -sSL https://shipyard-project.com/deploy | bash -s
Unable to find image 'alpine:latest' locally
Pulling repository alpine
Get https://registry-1.docker.io/v1/repositories/library/alpine/tags: dial tcp 52.7.140.240:443: connection timed out
Deploying Shipyard
 -> Starting Database
Unable to find image 'rethinkdb:latest' locally
Pulling repository rethinkdb
Get https://registry-1.docker.io/v1/repositories/library/rethinkdb/tags: dial tcp 52.7.140.240:443: connection timed out

Anyone getting this issue?  I have even tried pinging "registry-1.docker.io" and still get the timeout.

**Comment by Heaphestus** [comment]
Disregard, just starting working.

**Comment by ehazlett** [comment]
Thx.
