### ISSUE TITLE
(SOLVED)Server Error: Status 0

### ISSUE THREAD

**Issue by Heaphestus** [shipyard/shipyard#658]
Receiving the following problem when trying to install Shipyard.

[root@docker01 ~]# curl -sSL https://shipyard-project.com/deploy | bash -s
Unable to find image 'alpine:latest' locally
Pulling repository alpine
f4fddc471ec2: Pulling image (latest) from alpine
f4fddc471ec2: Pulling image (latest) from alpine, endpoint: https://registry-1.d             ocker.io/v1/
f4fddc471ec2: Pulling dependent layers
f4fddc471ec2: Pulling metadata
f4fddc471ec2: Pulling fs layer
f4fddc471ec2: Error pulling dependent layers
f4fddc471ec2: Error pulling image (latest) from alpine, endpoint: https://regist             ry-1.docker.io/v1/, Server error: Status 0 while fetching image layer (f4fddc471             ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0)
f4fddc471ec2: Error pulling image (latest) from alpine, Server error: Status 0 w             hile fetching image layer (f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0             302588197c0)
Error pulling image (latest) from alpine, Server error: Status 0 while fetching              image layer (f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0)
Deploying Shipyard
 -> Starting Database
Unable to find image 'rethinkdb:latest' locally
Pulling repository rethinkdb
684ad5d758db: Pulling image (latest) from rethinkdb
684ad5d758db: Pulling image (latest) from rethinkdb, endpoint: https://registry-             1.docker.io/v1/
684ad5d758db: Pulling dependent layers
575489a51992: Pulling metadata
575489a51992: Pulling fs layer
575489a51992: Error pulling dependent layers
684ad5d758db: Error pulling image (latest) from rethinkdb, endpoint: https://reg             istry-1.docker.io/v1/, Server error: Status 0 while fetching image layer (575489             a51992d5d30976ff5ba7f7eabdc134acfb51c79ff48883089009594e64)
684ad5d758db: Error pulling image (latest) from rethinkdb, Server error: Status              0 while fetching image layer (575489a51992d5d30976ff5ba7f7eabdc134acfb51c79ff488             83089009594e64)
Error pulling image (latest) from rethinkdb, Server error: Status 0 while fetchi             ng image layer (575489a51992d5d30976ff5ba7f7eabdc134acfb51c79ff48883089009594e64             )

**Comment by Heaphestus** [comment]
Disregard this post.  Looks like issue was my own network.  All the needed domain URLs are hard to filter through on the firewall.  It was all easier when I just opened up the server completely to the internet.  I was trying to filter through only the neep IPs and ports and then resolve the ip through an internal DNS.  The need URL IPs are constantly changing.

**Comment by ehazlett** [comment]
Thanks for the follow up!
