### ISSUE TITLE
Failed to add new node as ID duplicated

### ISSUE THREAD

**Issue by Zhaojp-Frank** [shipyard/shipyard#660]
Hi, 
I cloned some VM, then failed to add the 2nd VM node to the cluster. see logs below.
so where is this ID from? may I have any option to modify/edit it (assuming I'm root)? thanks.

INFO[20677] Registered Engine ubuntu-tgt-252 at 10.62.98.252:2375
ERRO[21612] ID duplicated. MEJY:GQ6Q:7SLE:Y3MP:SWLV:Y7ZH:BO5R:MYK4:GNP5:5SDA:7SKI:B63O shared by 10.12.13.246:2375 and 10.12.13.249:2375

**Comment by Zhaojp-Frank** [comment]
btw, I am running shipyard behind a cooperate firewall. so I download the deploy script and run it locally

**Comment by ehazlett** [comment]
You cannot clone as the IDs will be the same.  Remove `/etc/docker/key.json` after clone and it should be fine.
