### ISSUE TITLE
Support selecting net mode

### ISSUE THREAD

**Issue by hanxiaole** [shipyard/shipyard#661]
Current shipyard just support default network mode--brigde. Pls support other network mode .

**Comment by mahnunchik** [comment]
+1

**Comment by keyboardfann** [comment]
+1

**Comment by matt-horwood-mayden** [comment]
+1

**Comment by jpsenior** [comment]
I need the ability to specify a custom IPAM driver and a custom network for a docker swarm.  I can do this on the CLI, but not through docker shipyard.

eg: docker run -d --net=example --ipam-driver=example nginx

**Comment by MayankTahil** [comment]
+1
