### ISSUE TITLE
Cannot see tag names in registry

### ISSUE THREAD

**Issue by jonaskello** [shipyard/shipyard#662]
I have a private v1 registry which I can see in shipyard. However I cannot see the image tag names. All I can see is the number of tags each image has, not the actual names of the tags. The view in shipyard looks something like this:

Namespace Repository  Tags  Layers	Size
library          foo              2        36           129.07 MB

If I view the details of this image, there are a lot of layers but my 2 tag names are not visible anywhere. I know they exist becuase I can see them through the API at https://myregistry/v1/repositories/foo/tags
How can I view the actual name of the tags?

**Comment by ehazlett** [comment]
This is actually going to be replaced by the new v2 registry functionality.

**Comment by jonaskello** [comment]
I actually had a v2 registry, but since I like shipyard I downgraded to v1 to get it to work :-). Just wanted to check if I did something wrong, but I guess the v1 support in shipyard does not display tag names. Hoping it will be included in the v2 support!
