### ISSUE TITLE
[HOT] Shipyard Controller don't connect to DB

### ISSUE THREAD

**Issue by Smile42RU** [shipyard/shipyard#668]
$ docker ps

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                         PORTS                                            NAMES
ad13d2d82238        shipyard/shipyard:latest       "/bin/controller --de"   24 seconds ago      Restarting (1) 8 seconds ago   0.0.0.0:8080->8080/tcp                           shipyard-controller
7dd5b788df5a        swarm:latest                   "/swarm j --addr 46.4"   7 minutes ago       Up 7 minutes                   2375/tcp                                         shipyard-swarm-agent
5ca11abc476e        swarm:latest                   "/swarm m --replicati"   7 minutes ago       Up 7 minutes                   2375/tcp                                         shipyard-swarm-manager
12c19e890ef5        ehazlett/docker-proxy:latest   "/usr/local/bin/run"     7 minutes ago       Up 7 minutes                   0.0.0.0:2375->2375/tcp                           shipyard-proxy
5bbdac67274d        alpine                         "sh"                     7 minutes ago       Up 7 minutes                                                                    shipyard-certs
c8ee6a0517f5        microbox/etcd:latest           "/bin/etcd -addr 46.4"   7 minutes ago       Up 7 minutes                   0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
228893527fb0        rethinkdb                      "rethinkdb --bind all"   7 minutes ago       Up 7 minutes                   8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkdb

$ docker logs ad13d2d82238

INFO[0000] shipyard version 3.0.1
WARN[0000] Error creating connection dial tcp 172.17.0.1:28015: getsockopt: connection refused
FATA[0000] no connections were made when creating the session

$ netstat -lntp 

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:\*               LISTEN      11368/mysqld
tcp        0      0 0.0.0.0:80              0.0.0.0:\*               LISTEN      1251/nginx
tcp        0      0 10.0.3.1:53             0.0.0.0:\*               LISTEN      20271/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      24437/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:\*               LISTEN      23544/postgres
tcp6       0      0 127.0.0.1:8000          :::\*                    LISTEN      7535/java
tcp6       0      0 :::4001                 :::\*                    LISTEN      18104/docker-proxy
tcp6       0      0 :::2375                 :::\*                    LISTEN      18236/docker-proxy
tcp6       0      0 :::8080                 :::\*                    LISTEN      31817/docker-proxy
tcp6       0      0 fe80::8849:bff:fe54::53 :::\*                    LISTEN      20271/dnsmasq
tcp6       0      0 :::22                   :::\*                    LISTEN      24437/sshd
tcp6       0      0 :::7001                 :::\*                    LISTEN      18097/docker-proxy
tcp6       0      0 :::8090                 :::\*                    LISTEN      7535/java

**Comment by Smile42RU** [comment]
Rethink DB started but not listen ports in host machine.

$ docker logs 228893527fb0

Recursively removing directory /data/rethinkdb_data/tmp
Initializing directory /data/rethinkdb_data
Running rethinkdb 2.1.3~0jessie (GCC 4.9.1)...
Running on Linux 3.19.0-26-generic x86_64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 172.17.0.1, ::1, fe80::42:acff:fe11:1%1794
Server ready, "228893527fb0_tut" 90d1db09-8e74-448c-bb1e-ed13dc26f215
A newer version of the RethinkDB server is available: 2.1.5-2. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.

**Comment by ehazlett** [comment]
It doesn't need to listen on the host as it is linked. What host OS and
docker version?

**Comment by Smile42RU** [comment]
Ubuntu 14.04

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

**Comment by Smile42RU** [comment]
Any ideas?

**Comment by ehazlett** [comment]
Is there any firewall collisions or restrictions enabled?

**Comment by ehazlett** [comment]
Have you been able to check the firewall?

**Comment by manseuk** [comment]
i have this exact issue - i have disable the firewall and it doesnt make a difference - i am using a VPN connection - seemed to work find until i installed that ... im guessing that has caused my issue

**Comment by ehazlett** [comment]
Yes it's probably not able to reach the container.  Shipyard must be able to connect to the container.  The controller logs (`shipyard-controller`) should report the error.

**Comment by manseuk** [comment]
@ehazlett any idea how i can fix it ?

**Comment by ehazlett** [comment]
What does `docker logs shipyard-controller` output?

**Comment by manseuk** [comment]
```
INFO[0005] checking database                            
FATA[0005] error creating table: gorethink: Table `shipyard.config` already exists. in: 
r.DB("shipyard").TableCreate("config") 
INFO[0000] shipyard version 3.1.0                       
DEBU[0000] setting up rethinkdb session                 
WARN[0131] Error creating connection: gorethink: dial tcp 81.200.64.50:28015: getsockopt: connection timed out 
FATA[0131] no connections were made when creating the session 
```
@ehazlett see above - you need ipconfig output or anything else ? this is a fresh install of ubuntu 16.04 - all i have installed is docker and created a cisco vpn connection

**Comment by ehazlett** [comment]
The IP `81.200.64.50` does not appear to be a private IP that I would expect inside a VPN.  Are you sure that's the IP of the rethink container?

**Comment by manseuk** [comment]
OK - so that was a DNS issue that i managed to resolve by undoing a change i made based on another recommendation - so now shipyard is working fine.

I had commented out `dns=dnsmasq` in my `/etc/NetworkManager/NetworkManager.conf`

Thanks for your help and sorry i wasted your time

**Comment by ehazlett** [comment]
Ah yep -- network manager can be a tricky beast sometimes.  No worries - glad it's working!

**Comment by ehazlett** [comment]
@Smile42RU my suspicion is that your issue is related to the above.  Can you see if checking the network helps?

**Comment by hron84** [comment]
For me, shipyard deploy script figured out an external IP address on a Server4You QEMU VPS. It's potentially because it tried to resolve a single hostname, and default config of Server4You VMs is resolving all single names by completing it with 'dedicatedpanel.com'. It would be nice if this behaviour could be either disabled or changed. Basically, I tihnk there is no need to resolve any domains at deploy time, link containers via raw IP addresses.
