### ISSUE TITLE
Can't add private registry

### ISSUE THREAD

**Issue by bitsofinfo** [shipyard/shipyard#671]
I have a local registry running, the local docker host is configured with --insecure-registry  (docker 1.9)

When I try to add it such as

10.222.19.5:5000

I get back 

```
Get 10.222.19.5:5000/v1/search: unsupported protocol scheme 
```

If i try http://10.222.19.5:5000 I get `404 Not Found`

If i try https://10.222.19.5:5000 `Get https://10.222.19.5:5000/v1/search: tls: oversized record received with length 20527`

**Comment by bitsofinfo** [comment]
is this because v2 registry support is not in yet? https://github.com/shipyard/shipyard/pull/670

**Comment by ehazlett** [comment]
If you are using v2 no it is not yet supported.

**Comment by bitsofinfo** [comment]
eta?

**Comment by ehazlett** [comment]
Unknown currently.  Pull requests welcome :)

**Comment by ehazlett** [comment]
Most of the heavy lifting is done as part of the commits I referenced in that PR.

**Comment by ehazlett** [comment]
Referencing #670 and closing.  Thanks!

**Comment by victort** [comment]
:+1:
