### ISSUE TITLE
Duplicate bind mount error

### ISSUE THREAD

**Issue by bitsofinfo** [shipyard/shipyard#672]
Trying to launch a container and I specify ONE volume

host path = /mydir
container path = /config

I get an error back on top in red that says "Duplicate bind mount /config"  error 500

This is the only volume I am specifying...

**Comment by ehazlett** [comment]
What version of Docker?

**Comment by bitsofinfo** [comment]
1.9

**Comment by edasque** [comment]
I am seeing the same issue.
```
500 Internal Server Error: Duplicate bind mount /opt/nodebb/config.json
```

I think the cause is that there was a prior container with that mount, that I destroyed. Docker 1.9.1.

Restarting the docker daemon seems to have cured it. I'll try to reproduce.
