### ISSUE TITLE
Bad parse logs

### ISSUE THREAD

**Issue by elerion** [shipyard/shipyard#677]
Hi,

I use shipyard to deploy some spring application but I have some problem. My logs does not appear.
It's seems there are some problem with the parser
![shipyardcapture](https://cloud.githubusercontent.com/assets/14874472/11369293/6e0b353c-92be-11e5-9bc8-26f0f5cd047a.PNG)

King regardds

**Comment by ehazlett** [comment]
Closing as a duplicate of #676
