### ISSUE TITLE
x509 Error connecting to private repository

### ISSUE THREAD

**Issue by computerlyrik** [shipyard/shipyard#678]
The exact error message is

```
Get https://mydockerrepository:5000/v2//v1/search: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "CA Cert Signing Authority") 
```

How can i tell the shipyard about trusting the root certificate?

**Comment by Tochirou** [comment]
Hello,

I'm also getting the same error:

Get https://myrepository:5000/v1/search: x509: certificate signed by unknown authority 

What's is that in a shell terminal I can pull/push on my private repo.
I've created my own self signed certificate (https://docs.docker.com/registry/insecure/) and i've added it on the correct folders & all.

Hope we could get a little help about this.

**Comment by ehazlett** [comment]
This should help you. https://docs.docker.com/registry/insecure/
