### ISSUE TITLE
Installing shipyard into existing swarm cluster

### ISSUE THREAD

**Issue by wildsurfer** [shipyard/shipyard#679]
I have an existing swarm cluster. Trying to install shipyard inside. If I got it right I have to put up 2 conteiners: `rethynkdb` and `shipyard-controller`.

Issue: When I log in to shipyard I see error: "Internal server error 500"

![image](https://cloud.githubusercontent.com/assets/1456389/11428792/2d910624-9478-11e5-9edf-da2e3b53baed.png)

Here are steps to reproduce the issue:

```
#!/bin/bash

docker-machine create -d virtualbox cluster-store                                                  
CLUSTER_STORE_IP=$(docker-machine ip cluster-store)

docker $(docker-machine config cluster-store) run -d \
    --restart="always" \
    --publish="2379:2379" \
    microbox/etcd:2.1.1 \
    -name etcd0 \
    -advertise-client-urls http://${CLUSTER_STORE_IP}:2379 \
    -listen-client-urls http://0.0.0.0:2379 \
    -initial-cluster-state new

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery="etcd://$(docker-machine ip cluster-store):2379/swarm" \
    --engine-opt="cluster-advertise=eth1:2376" \
    --engine-opt="cluster-store=etcd://$(docker-machine ip cluster-store):2379/store" \
    swarm-0

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-discovery="etcd://$(docker-machine ip cluster-store):2379/swarm" \
    --engine-opt="cluster-advertise=eth1:2376" \
    --engine-opt="cluster-store=etcd://$(docker-machine ip cluster-store):2379/store" \
    swarm-1

eval $(docker-machine env --swarm swarm-0)
docker network create -d overlay multihost

docker run \
    --net=multihost \
    -ti \
    -d \
    --restart=always \
    --name rethinkdb \
    rethinkdb

docker run \
    --net=multihost \
    -ti \
    -d \
    --restart=always \
    --name shipyard-controller \
    -p 8080:8080 \
    shipyard/shipyard:latest --debug \
    server \
    -d tcp://$(docker-machine ip swarm-0):2376

```

Environment:

```
bash-3.2$ docker --version
Docker version 1.9.1, build a34a1d5
Press any key to continue...

bash-3.2$ docker-machine --version
docker-machine version 0.5.1 (7e8e38e)
Press any key to continue...

bash-3.2$ uname -a
Darwin Ivans-MBP.lan 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by wildsurfer** [comment]
anyone?

**Comment by yellowiscool** [comment]
I also would like to use Shipyard with an existing SWARM cluster, if possible.

**Comment by yellowiscool** [comment]
I managed to have run Shipyard with the following command:
```
docker run -ti -d --restart=always  -p 8080:8080 \
    --name shipyard-controller \
    --link swarm-agent-master:swarm \
    --link shipyard-rethinkdb:rethinkdb \
    -e  DOCKER_TLS_VERIFY="1" \
    -e DOCKER_HOST="tcp://192.168.1.6:3376" \
    -e DOCKER_MACHINE_NAME="swarm-master"
    -e DOCKER_CERT_PATH=/opt/cert \
    -v /home/username/.docker/machine/machines/swarm-master:/opt/cert:ro \
    shipyard/shipyard:latest server -d tcp://swarm:3376
```
I used the information provided by [the manual](http://test.shipyard-project.com/docs/deploy/manual/), [a comment explaining how to do it for docker-compose-ui](https://github.com/francescou/docker-compose-ui/issues/5#issuecomment-135697832), and the result of the command `docker-machine env --swarm swarm-master`

I also have a "swarm-master" VM created using "docker-machine --swarm --swarm-master".

**Comment by ehazlett** [comment]
I would recommend looking at the "Manual" deploy section http://shipyard-project.com/docs/deploy/manual/.  You will need to configure the access to Swarm if you bring your own.

**Comment by wildsurfer** [comment]
@yellowiscool, thank you!

**Comment by wildsurfer** [comment]
Here is a minimal configuration that worked for me:

```
$ cat docker-compose.yml 
rethinkdb:
    image: rethinkdb:2.2.1
shipyard:
    image: shipyard/shipyard:latest
    ports:
        - "8080"
    command: "--debug server -d tcp://swarm:3376"
    external_links:
        - swarm-agent-master:swarm
    links:
        - rethinkdb
    environment:
        - DOCKER_TLS_VERIFY
        - DOCKER_HOST
        - DOCKER_MACHINE_NAME
        - DOCKER_CERT_PATH
    volumes:
        - "$DOCKER_CERT_PATH:$DOCKER_CERT_PATH"
```

Please note that before running docker-compose you should switch to swam docker host (no `--swarm` !)

```
$ eval $(docker-machine env baydoor-swarm-master)
```

**Comment by tronicum** [comment]
does this stil exist? i could install shipyard into an existing swarm cluster just fine...

**Comment by AnuyogChauhan** [comment]
Can anyone give step by step solution to install shipyard for existing swarm mode cluster?

**Comment by ehazlett** [comment]
Shipyard does not yet work with a 1.12 swarm mode cluster.

**Comment by tronicum** [comment]
i am a little bit confused. that swarm was initially setup with docker 1.11 (now running 1.12) but uses the old swarm style by pulling swarm:latest (done by docker machine) . 

i am not using "docker swarm" or any new style ways to setup. this is only about getting shipyard to reuse an old database.

**Comment by allamand** [comment]
Shipyard perfectly works with a swarm cluster in docker 1.12 (but i'm note using new SwarmMode, using swarm containers as before docker 1.12). You can launch Shipyard within an existing cluster with the client talking to the swarm endpoint, but you need to provide the DOCKER_CERT_PATH with all needed certificates. For me there is no issue here..

**Comment by mkamlesh** [comment]
What is the best way to deploy clean slate Docker shipyard with swarm in order to form a 3 node Docker Swarm cluster managed fully by Shipyard? We've tried couple of approaches to find that though Shipyard thinks that there 2 nodes in the cluster, docker swarm cli thinks that there is only one. We are on docker engine 1.12.

**Comment by tronicum** [comment]
* use docker-machine
* install docker with swarm (old swarm)
* deploy an swarm with access to the swarm master

**Comment by mkamlesh** [comment]
So, docker-1.12 with integrated swarm wouldn't well with Shipyard?

**Comment by tronicum** [comment]
It will in the future

**Comment by mkamlesh** [comment]
Any approximate ETA?

**Comment by tronicum** [comment]
I don't code on it. But I run classic swarm mode. I would recommend use a resent docker but set it up with classic swarm. In 6 month if docker 0.13 or later has stable native swarm features, upgrade.
