### ISSUE TITLE
Port conflict in Shipyard

### ISSUE THREAD

**Issue by mavencode01** [shipyard/shipyard#680]
I keep getting this error when installing shipyard

	ubuntu@devmaster:~$ curl -sSL https://shipyard-project.com/deploy | bash -s
	Deploying Shipyard
	 -> Starting Database
	 -> Starting Discovery
	 -> Starting Cert Volume
	 -> Starting Proxy
	Error response from daemon: Cannot start container 1510425d19bc284527740d2ff26ed45fae1fbd455730e35e227b5e5caed1a81f: failed to 
    create endpoint shipyard-proxy on network bridge: Bind for 0.0.0.0:2375 failed: port is already allocated

Here is my docker version

    ubuntu@devmaster:~$ docker  -v
    Docker version 1.9.1, build a34a1d5

**Comment by ehazlett** [comment]
Try using the `PROXY_PORT` option when deploying.  Set this to something besides 2375.  For example, `curl -sSL https://shipyard-project.com/deploy | PROXY_PORT=4375 bash -s`.  That should fix it.
