### ISSUE TITLE
why? Error creating connection dial tcp 172.17.0.28:28015: getsockopt: connection refused

### ISSUE THREAD

**Issue by liusongsen** [shipyard/shipyard#683]
shipyard-swarm-manager_1 | time="2015-12-03T08:39:55Z" level=info msg="Listening for HTTP" addr="0.0.0.0:3375" proto=tcp 
shipyard-swarm-manager_1 | time="2015-12-03T08:39:55Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured" 
shipyard-swarm-manager_1 | time="2015-12-03T08:39:55Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured" 
shipyard-swarm-manager_1 | time="2015-12-03T08:39:55Z" level=error msg="Discovery error: Unexpected watch error" 
shipyard-controller_1    | time="2015-12-03T08:39:55Z" level=info msg="shipyard version 3.0.1" 
shipyard-controller_1    | time="2015-12-03T08:39:55Z" level=warning msg="Error creating connection dial tcp 172.17.0.28:28015: getsockopt: connection refused" 
shipyard-controller_1    | time="2015-12-03T08:39:55Z" level=fatal msg="no connections were made when creating the session" 
webserver_1              | 2015-12-03 08:39:56,579 INFO spawned: 'php-fpm' with pid 11
webserver_1              | 2015-12-03 08:39:56,580 INFO spawned: 'nginx' with pid 12
webserver_1              | 2015-12-03 08:39:56,581 INFO spawned: 'memcache' with pid 13

**Comment by ehazlett** [comment]
What version of Docker?

**Comment by coreylenertz** [comment]
I'm having the same problem. Docker version 1.9.1, build a34a1d5. Also appears to resemble issue #668 where the controller goes into "restarting" status.

@ehazlett any update on this?

**Comment by liusongsen** [comment]
Docker version 1.8.1, build d12ea79

**Comment by ehazlett** [comment]
What is your host OS?  It looks like perhaps the datastore container didn't start or is having trouble access it.

**Comment by lueliu** [comment]
@liusongsen 
“etcd cluster is unavailable or misconfigured"  It looks like your etcd docker (microbox/etcd ?) error. I have the same problem,but I config etcd cluster outside is well, now.

I have a problem: (when I add shipyard-swram-agent)
"getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS? "

**Comment by liusongsen** [comment]
not etcd cluster is unavailable or misconfigured
172.17.0.28:28015 is database

**Comment by liusongsen** [comment]
I suspect it is the starting order (docker-compose.yml),
I made a docker-compose.yml, this docker-compose can guarantee the order of start, but can not guarantee the right to start the next one

**Comment by ehazlett** [comment]
@liusongsen could you try the deploy script http://shipyard-project.com/docs/deploy/ and see if that works?

**Comment by liusongsen** [comment]
@ehazlett 
I just wrote it in this document, but I just added those commands to the docker-compose.yml, where there are more containers, I don't have a start, and all I do is a project
Https://github.com/liusongsen/php-docker-machine

**Comment by liusongsen** [comment]
@ehazlett 
I would like to join this project in shipyard, thank you for your patience.

**Comment by ehazlett** [comment]
Have you checked the routes and firewall on the instance?

**Comment by mariolameiras** [comment]
The same happens to me as well by running `curl -sSL https://shipyard-project.com/deploy | bash -s` with Docker version 17.03.0-ce, build 60ccb22

shipyard-controller seems to be trying to connect to my host address instead of the rethinkdb link

**Comment by amigcamel** [comment]
Same. Mine is `Docker version 17.05.0-ce, build 89658be` + `Ubuntu 16.04.2 LTS`
