### ISSUE TITLE
Universal Control Plane

### ISSUE THREAD

**Issue by aaronrobertson** [shipyard/shipyard#684]
Is shipyard being replaced by Universal Control Plane?

**Comment by yangdongsheng** [comment]
Interesting, is "Universal Control Plane" doing the same thing with shipyard? where is the reference of it?

**Comment by aaronrobertson** [comment]
If you go to this page of the docker website and watch the product demo.
https://www.docker.com/universal-control-plane
It looks to me like they took shipyard, made a bunch of UI and functional updates, just my theory though.

**Comment by yangdongsheng** [comment]
@aaronrobertson Thanx.

@ehazlett More information about it?

**Comment by ehazlett** [comment]
There are some similarities in the functionality between the two.  However, UCP has deeper integration into the Docker core stack as well as enterprise facing properties such as AD integration and tighter LDAP, DTR integration, centralized installation and upgrade capabilities, deeper plugin support for Volumes and Networking, etc.

Shipyard is an open source and community supported management application similar to Docker UI, etc.  There are no plans to replace it.
