### ISSUE TITLE
web ui displays wrong names

### ISSUE THREAD

**Issue by ingardm** [shipyard/shipyard#686]
See attached screenshot from shipyard ui and docker ps on the host
![screen shot 2015-12-04 at 10 55 52](https://cloud.githubusercontent.com/assets/2324855/11586870/3b0f5662-9a76-11e5-99da-a14ae89ec317.png)
![screen shot 2015-12-04 at 10 55 37](https://cloud.githubusercontent.com/assets/2324855/11586869/3b0c3662-9a76-11e5-9a29-323cac959155.png)

**Comment by zittix** [comment]
This is fixed in master.

I have prepared a new image to be used with the latest master changes + a fix for network stats bug (see #688 ) named zittix/shipyard:fix-network-stats. See https://hub.docker.com/r/zittix/shipyard/ for more info.

**Comment by ehazlett** [comment]
I will create a new release for this fix.  Thanks!

**Comment by ingardm** [comment]
This problem is still in 3.0.2

**Comment by ehazlett** [comment]
Can you please confirm you have pulled and are using the latest swarm?  This looks fixed to me.

![2015-12-09-080125_1878x605_scrot](https://cloud.githubusercontent.com/assets/260642/11685973/1ea5f016-9e4b-11e5-82b5-6b212a52997e.png)

**Comment by zittix** [comment]
This seems fixed to me as well.

**Comment by ingardm** [comment]
i'm still seeing the bug. Versions:
root@virt-001:~# docker exec -ti swarm /swarm -v
swarm version 1.0.0 (087e245)
root@virt-001:~# docker exec -ti swarm-manager /swarm -v
swarm version 1.0.0 (087e245)
root@virt-001:~# docker exec -ti shipyard-controller /bin/controller -v
shipyard version 3.0.1 (df62301)

**Comment by ingardm** [comment]
Right. 3.0.1. puppet seems to have reverted the image somehow.

**Comment by ingardm** [comment]
root@virt-001:~# docker exec -ti shipyard-controller /bin/controller -v
shipyard version 3.0.2 (8e84bed)

**Comment by ingardm** [comment]
Still seeing the bug
![screen shot 2015-12-09 at 15 56 41](https://cloud.githubusercontent.com/assets/2324855/11688536/8118fe04-9e8d-11e5-9459-687e99c39499.png)

**Comment by zittix** [comment]
Open the web inspector of your browser and refresh the Container page. Post here the answer of the AJAX request sent to the endpoint /containers/json?all=1

**Comment by ingardm** [comment]
[{"Id":"4c9cce01bf83ed54530baab3ae9bab088357f96ecbebbd0c5dced9eb93264153","Names":["/virt-001/shipyard-controller"],"Image":"shipyard/shipyard","Command":"/bin/controller
server -d tcp://swarm:2375
-disable-usage-info","Created":1449672923,"Status":"Up 22
hours","Ports":[{"IP":"10.0.70.101","PrivatePort":8080,"PublicPort":8080,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"c6c6781498545b60d485dfefa3ec4842970e44e9beb6da544375d1fb8a42e82a","Names":["/virt-001/shipyard-controller/swarm","/virt-001/swarm-manager"],"Image":"swarm","Command":"/swarm
manage consul://consul-master.domain.com:8500/swarm_nodes","Created":1449672299,"Status":"Up
22
hours","Ports":[{"IP":"10.0.70.101","PrivatePort":2375,"PublicPort":3000,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"41a286b9bad5282394478134666ab3750e84d10fa271170e1f2902df2faf1874","Names":["/virt-004/registry"],"Image":"registry:2","Command":"/bin/registry
/etc/docker/registry/config.yml","Created":1449663418,"Status":"Up 25
hours","Ports":[{"IP":"10.0.70.104","PrivatePort":5000,"PublicPort":5000,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"46eaa2d18108bd7d1d732dafbf3b1f334a9805dab189e817bf29517b8acd4164","Names":["/virt-003/photosbuilder"],"Image":"photosbuilder_docked","Command":"/opt/domain/PhotosBuilder/PhotosBuilder
importer write_log","Created":1449589433,"Status":"Up 45
hours","Ports":[{"IP":"10.0.70.103","PrivatePort":8095,"PublicPort":8095,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"70824cc6a6cc0550c0dc7ab137f761531b22228e6473fc31575eb02a932c3b47","Names":["/hp-002/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.62.11:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449139334,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"3faaeecb58e1d44b1a38bb2a49d82a6ab0fa8a6ef81b9c5c810fc5fe76b6ed67","Names":["/hp-001/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.62.10:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449139333,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"2cf378b397edb57e0c55296b74da30558a66a966f4f610640456970a77eb123e","Names":["/virt-004/nominatim-global2"],"Image":"bosse/nom-global","Command":"/bin/sh
-c /app/nominatim/start.sh","Created":1449097296,"Status":"Up 7
days","Ports":[{"IP":"10.0.70.104","PrivatePort":8080,"PublicPort":8080,"Type":"tcp"},{"IP":"","PrivatePort":5432,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"3ea7dfe49250137da383a1191d3d3439cbe85908a1b8b81364674386078ff46d","Names":["/virt-004/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.70.104:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449097027,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"e0f1a07fe634e627a33901394405b70bc825575be479942ac62587ef2cb3db71","Names":["/virt-002/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.70.102:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449089214,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"8f6721ab3a0c1c1758d9b80cdf71ed0a978d3f22537f797167d9a34465415c1f","Names":["/virt-003/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.70.103:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449085818,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"6b2ccb90ba606676275231afc17cc74be26850f169124e08164dc1fb84f3de24","Names":["/virt-001/shipyard-controller/rethinkdb","/virt-001/shipyard-rethinkdb"],"Image":"rethinkdb","Command":"rethinkdb
--bind all","Created":1449079685,"Status":"Up 7
days","Ports":[{"IP":"","PrivatePort":29015,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":28015,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":8080,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"433623da01a5edfe0eebecbcdb59565936e601fb5f47154d5d3510bc15a37edb","Names":["/virt-001/swarm"],"Image":"swarm","Command":"/swarm
join --addr=10.0.70.101:2375 consul://
consul-master.domain.com:8500/swarm_nodes","Created":1449061515,"Status":"Up
7
days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"56f697f3a4d50f051e24e6b3525838e575cb7e68862248f705f9fae15d4652bd","Names":["/virt-003/nominatim-norway"],"Image":"nominatim-norway","Command":"/bin/sh
-c /app/nominatim/start.sh","Created":1447762409,"Status":"Up 7 days
(Paused)","Ports":[{"IP":"10.0.70.103","PrivatePort":8080,"PublicPort":8080,"Type":"tcp"},{"IP":"","PrivatePort":5432,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"275de13caa682b85513520c1ce7bd8429f8ad0a9fd9bfcecba8368ac2dd8b3f2","Names":["/hp-001/product_webclients"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
webclient","Created":1436463091,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"0261b1902da791fb610519f004ad14a15f6000c8a82e7e02ad2e8ffef1803691","Names":["/hp-001/product_worker_9"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463091,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"ed4fc8aad9d1bf9767caf64d4b87e287a2fbfd27e53cc5eb0b95ebec1d7f34bb","Names":["/hp-001/product_worker_8"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463090,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"7273123439d4a389f842067738dce8efd4d79410a57f9f88aa6907e458bccb93","Names":["/hp-001/product_worker_7"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463090,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"805a488d32cdb1360c480e8d125c51751801f365fa8609520ca7998b32d2538f","Names":["/hp-001/product_worker_6"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463090,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"cc4157101f8fa3125d9dc714d3028adb3dd687fd00451fa38339521b9bee8100","Names":["/hp-001/product_worker_5"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463089,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"12f970016c4ee4650c4dcf1878d8e098eb6f60c3e629d972af08a02a71b6823f","Names":["/hp-001/product_worker_4"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463089,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"d7450b7e9babf97ecb0c586640f1b9394d1e2521a1e3bdc0a3cd9d4a4e42af9c","Names":["/hp-001/product_worker_3"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463089,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"f6f4ad280ca7e2f9922f3a31dc8ed287132774abffa16bd2a4f5e26c650d5225","Names":["/hp-001/product_worker_2"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463089,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"46ce6b0e5fbc55b0030e856b96be27336c03f59663dc14d5d7cd273c94d6dfcc","Names":["/hp-001/product_worker_1"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
worker","Created":1436463088,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"8cb7c0f94517a7e8b158ee7618b1c52f7e0f6794e182794dfb862ee21217337b","Names":["/hp-001/product_pregen_worker_9"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463088,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"86a452c4d9f62767a9aa05ec3694918d3693fa8d227e3ab51dec3464f6177d1f","Names":["/hp-001/product_pregen_worker_8"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463088,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"ff8c901b801ac72a467e22c71fd919745c45224786c2354974f61983856f11b2","Names":["/hp-001/product_pregen_worker_7"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463087,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"ed194278dc06e52214fdd21b96f0c86106b958c7430e186c14c9abc5e8f047c9","Names":["/hp-001/product_pregen_worker_6"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463087,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"ecd01d3fdf3ac663869c687856335d115a28f6d6e6c067ba122ea55cc96d5a70","Names":["/hp-001/product_pregen_worker_5"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463087,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"85769db815d337f9f7a87d89882ca0c13228a409ca36fe9cf723ccda1012c0bb","Names":["/hp-001/product_pregen_worker_4"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463087,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"b40d641ec8d118d3e60f59e792153a3c50341a280a8805e4354b116d4902e890","Names":["/hp-001/product_pregen_worker_3"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463086,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"7c38a72b9bf65b639f4062d00dde9411ef5047531b532f49b9ec60abd3a0e251","Names":["/hp-001/product_pregen_worker_2"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463086,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"80f8043c6841c5e4fd7782ee561a1ed24950f024f37678d0b8f09d2a2def8935","Names":["/hp-001/product_pregen_worker_1"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
pregen","Created":1436463086,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"6b023cad9164aa0db6294161c8a53b8242ede379a38b37db5d54a9b5a7b149b7","Names":["/hp-001/product_broker","/hp-001/product_pregen_worker_1/product_broker","/hp-001/product_pregen_worker_2/product_broker","/hp-001/product_pregen_worker_3/product_broker","/hp-001/product_pregen_worker_4/product_broker","/hp-001/product_pregen_worker_5/product_broker","/hp-001/product_pregen_worker_6/product_broker","/hp-001/product_pregen_worker_7/product_broker","/hp-001/product_pregen_worker_8/product_broker","/hp-001/product_pregen_worker_9/product_broker","/hp-001/product_webclients/product_broker","/hp-001/product_worker_1/product_broker","/hp-001/product_worker_2/product_broker","/hp-001/product_worker_3/product_broker","/hp-001/product_worker_4/product_broker","/hp-001/product_worker_5/product_broker","/hp-001/product_worker_6/product_broker","/hp-001/product_worker_7/product_broker","/hp-001/product_worker_8/product_broker","/hp-001/product_worker_9/product_broker"],"Image":"productdocked","Command":"/opt/domain/product/initd/entrypoint
broker","Created":1436463086,"Status":"Exited (-1) 10 days
ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"3d1f21cfa3c9698590c51c86a114abd10faebda1a4c42b43f324967403119069","Names":["/hp-001/mad_fermat"],"Image":"1e1f92f8aa902ef5b705321d3f8dff46a9b3394c0e1aeed37f8ff837bcc2f60e","Command":"/bin/bash
-s","Created":1435653842,"Status":"","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"9689a9e1609d17796674830c05d82a68c0c6e4011e1283f49c0b989010aed594","Names":["/hp-001/insane_mayer"],"Image":"1e1f92f8aa902ef5b705321d3f8dff46a9b3394c0e1aeed37f8ff837bcc2f60e","Command":"/bin/bash
-s","Created":1435652304,"Status":"","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"0f74febd8df9a101ef51f96bbe254de81bc069a7bacd80d96808570b346b866e","Names":["/hp-001/naughty_morse"],"Image":"bc6c054fe77e76f9f9fcbb692cd4928e1bed8b0b390f17cc7e78652739ba1382","Command":"/bin/bash
-s","Created":1435580720,"Status":"","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}}]


2015-12-10 13:58 GMT+01:00 Mathieu Monney <notifications@github.com>:

> Open the web inspector of your browser and refresh the Container page.
> Post here the answer of the AJAX request sent to the endpoint
> /containers/json?all=1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shipyard/shipyard/issues/686#issuecomment-163603730>.
>



-- 
Ingard Mevåg
Driftssjef
JottaCloud

Mobil: +47 450 22 834
E-post: ingard@jottacloud.com
Webside: www.jottacloud.com

**Comment by zittix** [comment]
@ingardm FYI The function that parse the displayed container name is reproduced below:

```js
function containerName(container) {
	// Remove the node name by returning the last name component of the shortest container name
	var components = shortestContainerName(container).split('/');
	return components[components.length-1];
}

function shortestContainerName(container) {
	// Distill shortest container name by taking the name with the fewest components
	// Names with the same number of components are considered in undefined order
	var shortestName = "";
	var minComponents = 99;
	
	var names = container.Names
	for(var i=0; i<names.length; i++) {
		var name = names[i];
		var numComponents = name.split('/').length
		if(numComponents < minComponents) {
			shortestName = name;
			minComponents = numComponents;
		}
	}

	return shortestName;			
}
```

If you try to run the containerName() function on one of your container data you just posted, it works totally fine.

Therefore I am suspecting a problem on your side: you probably still have the old version in your browser cache - kill your browser cache

**Comment by ingardm** [comment]
Correct. incognito mode works.
