### ISSUE TITLE
Stats Loading...

### ISSUE THREAD

**Issue by zoell** [shipyard/shipyard#689]
Hi,

I have a Shipyard running in docker and just noticed that the stats page is not working for any containers. It just says Loading... for CPU, Memory and Network.
As I remember it worked when I first installed but don't know what happened.
Just for the reference, I have around 26 containers running.

Is there anything I can check to discover what or where is the issue? Or any other thoughts would be really appreciated.

Many thanks,
Zoltan

**Comment by kiron783** [comment]
Yes, even I am facing the same issue, containers are not listing 
![shipyard_container](https://cloud.githubusercontent.com/assets/9953155/11611363/c6264d92-9b97-11e5-8378-01dec7888fe8.PNG)

**Comment by zoell** [comment]
Containers are there for me.
But if I go to the Stats page, I get this:
![shipyard](https://cloud.githubusercontent.com/assets/3702564/11611372/1eabd1f6-9bc2-11e5-9ece-3901f2c93569.jpg)

However I just noticed that if I resize the browser window, the stats will start to flow in and displays the graph properly.

**Comment by zoell** [comment]
Tested on:
- Chrome 47.0.2526.73 m: graphics displays after window resize
- Firefox 42: graphics does not display even if I resize the window. Only Loading... displays.

**Comment by kiron783** [comment]
I have restated the controller and cleared the browser cache ... its all good now
able to see containers and stats too .

Try it out

**Comment by yangdongsheng** [comment]
@zoell Did you try https://github.com/shipyard/shipyard/pull/688 ?

**Comment by ehazlett** [comment]
I will create a new release with this fix.

**Comment by ehazlett** [comment]
`shipyard/shipyard:3.0.2` has been released and `shipyard/shipyard:latest` has been updated to it.

**Comment by wangyun** [comment]
Still has this issue, my shipyard tag is 3.0.2
chrome version 47.0.2526.73 m
always Loading... even if resize the browser window.

**Comment by wangyun** [comment]
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

and I'm using TLS connection,
and launching swarm manager using token discovery backend

**Comment by wangyun** [comment]
chrome F12:
![shipyard](https://cloud.githubusercontent.com/assets/222225/11685628/733dff50-9eb5-11e5-8f7a-3a8631855c57.png)

**Comment by ehazlett** [comment]
This is working.  Chrome 43.0.2357.134 (64-bit)

![2015-12-09-075429_1211x238_scrot](https://cloud.githubusercontent.com/assets/260642/11685859/3dda54e6-9e4a-11e5-9be4-ca399c74ab0c.png)

![2015-12-09-075411_2524x1318_scrot](https://cloud.githubusercontent.com/assets/260642/11685869/44b7f638-9e4a-11e5-8ab2-82a6c75053c0.png)

Please check the logs of the controller, swarm, etc.

**Comment by wangyun** [comment]
There is no error related logs,
But I found the stats api is not working on my machine, don't know why..

$ docker stats --no-stream swarm_shipyard_1
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
swarm_shipyard_1    0.00%               0 B / 0 B           0.00%               0 B / 0 B           0 B / 0 B

returns all zero.

**Comment by wangyun** [comment]
I tail docker daemon log and found:
ERRO[21833] collecting stats for aa906919f7f726567caaa9ca96e2711e04532de94ceb860a54e1babd21843a3f: [8] System error: failed to parse memory.memsw.usage_in_bytes - read /sys/fs/cgroup/memory/docker/aa906919f7f726567caaa9ca96e2711e04532de94ceb860a54e1babd21843a3f/memory.memsw.usage_in_bytes: operation not supported

totally can't understand why, go to sleep now...
