### ISSUE TITLE
Shipyard UI customization 

### ISSUE THREAD

**Issue by kiron783** [shipyard/shipyard#690]
I am trying to customize the web UI according to my team needs, I used to edit the containers/container.html code and used see the changes reflected on shipyard UI but now .. its not happening !! 

Not sure why , if anyone working on similar project please help me out.

Note: Its not a issue .. rather doubt very new to shipyard

**Comment by ehazlett** [comment]
You will need to rebuild the media.  Try `make media` in the root.
