### ISSUE TITLE
controller cannot authenticate against active directory(anonymous bind only)

### ISSUE THREAD

**Issue by tdeath1** [shipyard/shipyard#691]

**Comment by tdeath1** [comment]
Hi guys,

I am attempting to test this out in a large enterprise environment, and unfortunately a major blocker(at least in terms of widespread usage among teams) is present due to no method of authenticating against ldap / active directory unless you are executing an anonymous bind.  

These are the properties being passed to controller(verified as valid):

/bin/controller server -l :8080 --rethinkdb-addr 172.17.0.1:28015 --rethinkdb-database shipyard -d tcp://swarm:3375 --ldap-server xxx.ca.com --ldap-autocreate-users --ldap-default-access-level containers:ro --ldap-port 389 --ldap-base-dn OU=Users,OU=North America,DC=ca,DC=com


result:

time="2015-12-06T10:26:05Z" level=error msg="error during login for nelje05 from x.x.x.x:42714: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1\x00" 

Any suggestions, am I missing anything obvious?


thanks,
Jeremy

**Comment by ehazlett** [comment]
What version of LDAP are you using?

**Comment by tiagomiguelsousa** [comment]
Hi.

I´ve exactly the same problem. The command i run is:

curl -sSL https://shipyard-project.com/deploy | SHIPYARD_ARGS="--ldap-server=XXXX.i2s.local --ldap-base-dn=cn=XXXX,CN=Users,DC=i2s,DC=local --ldap-autocreate-users" bash -s

My LDAP supports version 2 and 3.

Any possible help?

Thanks.

Tiago

**Comment by relvacode** [comment]
+1 This is the only thing stopping us using Shipyard
