### ISSUE TITLE
docker login fails with unauthorized error

### ISSUE THREAD

**Issue by dupperinc** [shipyard/shipyard#692]
I installed shipyard on 1 machine and added 2 other nodes to the cluster using below commands.

1. curl -sSL https://shipyard-project.com/deploy | bash -s on machine-1
2. curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://$MACHINE_1_IP:4001 bash -s on machine-2
3. curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://$MACHINE_1_IP:4001 bash -s on machine-3

From UI I can see all three nodes listed and adding a container schedules it to one of the node.

I want to connect to swarm master to see all the nodes via docker info. However when I try to access shipyard-controller through docker cli using username:admin, password:shipyard, it give unauthorized error.

docker -H tcp://MACHIN_1_IP:8080 login
Username: admin
Password:
Email:
Error response from daemon: unauthorized

Please let me know if I missed some basic step or connecting to the wrong port. 

docker logs for shipyard-controller below.

DEBU[33336] GET: /containers/json?all=1
DEBU[33337] GET: /containers/json?all=1
DEBU[33343] DELETE: /containers/23676c4d920e3d0acc13ba0624b34d5285a6841f37afbc8efd6df564d40f4526?v=1&force=1
DEBU[33343] GET: /containers/json?all=1
WARN[34132] unauthorized request for /v1.20/info from 76.88.80.113:47525
WARN[34138] unauthorized request for /v1.20/info from 76.88.80.113:47539
WARN[34149] unauthorized request for /v1.20/info from 76.88.80.113:47556
WARN[34158] unauthorized request for /v1.20/auth from 76.88.80.113:47571
WARN[34201] unauthorized request for /v1.20/auth from 76.88.80.113:47644
WARN[34216] unauthorized request for /v1.20/auth from 76.88.80.113:47670
WARN[34265] unauthorized request for /v1.20/auth from 76.88.80.113:47754
WARN[34316] unauthorized request for /v1.20/auth from 76.88.80.113:47843
WARN[34342] unauthorized request for /v1.20/auth from 76.88.80.113:47889
WARN[34359] unauthorized request for /v1.20/auth from 76.88.80.113:47922
WARN[34435] unauthorized request for /v1.20/auth from 76.88.80.113:48044
WARN[34440] unauthorized request for /v1.20/auth from 76.88.80.113:48054
WARN[34569] unauthorized request for /v1.20/info from 172.17.42.1:54889
WARN[34578] unauthorized request for /v1.20/auth from 172.17.42.1:54890

**Comment by dupperinc** [comment]
After further investigation it looks like swarm master port 3375 is not exposed outside container. Is there a way to expose then via environment variable?

**Comment by ehazlett** [comment]
We are planning to add TLS authentication via the Docker client.  Optionally you can use the manual setup and expose Swarm on an external port.  See http://shipyard-project.com/docs/deploy/manual/ for manual deployment.

**Comment by dupperinc** [comment]
Thanks for your response. Any timeline for TLS authentication feature.
