### ISSUE TITLE
shipyard Gateway Timeout","status":504

### ISSUE THREAD

**Issue by sunshibin21** [shipyard/shipyard#693]
when i use ui to visit ,i meet this error,
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$4WR2qFg/Mv7rpYzuFYgAb.62UzmX8NtZdOalAZNDTm5d6tr9WglBa"}},"statusText":"Gateway Timeout"}

**Comment by ehazlett** [comment]
are you getting any errors in the controller?

**Comment by haoyixin** [comment]
+1

**Comment by haoyixin** [comment]
and no log in container

**Comment by ehazlett** [comment]
Closing as I'm not able to reproduce.  I would suggest to check your setup as it appears to have a proxy in front.
