### ISSUE TITLE
ldap makes assumptions on user dn

### ISSUE THREAD

**Issue by osallou** [shipyard/shipyard#695]
When authenticating with ldap following code is used

```
dn := fmt.Sprintf("cn=%s,%s", username, a.BaseDN)
if err := l.Bind(dn, password); err != nil {
    return false, err
}
```

We see that user is search with a dn starting with cn=xx. However dn can have multiple forms, for example we have dn with uid=xx, .....
Furthermore basedn is added to username to get complete dn, this means that all users must be under the same/exact basedn (ou=people,dc=x,dc=y) for example. This is not always the case either.

One should be able to specify the dn setup (which field to use). Best would be to do an ldap search in subtree defined by basedn, matching a configured input field (cn, uid, email, ...). Once you get a match from ldap, then you extract the dn of the user from response and bind against this dn.

**Comment by ehazlett** [comment]
What version of LDAP are you using?

**Comment by osallou** [comment]
Openldap on centos7 but this not a matter of ldap software or version but
how dn are setup in ldap

Le ven. 11 déc. 2015 16:21, Evan Hazlett <notifications@github.com> a
écrit :

**Comment by ehazlett** [comment]
Ok well the versions do matter (take a look at oracle ldap) but not in this context.  It's a slippery slope to support the variances.  Perhaps we can get some others to chime in to find the best path for the most support here.

**Comment by meister** [comment]
We have a similar problem in our system at the moment. However what I’ve seen from other LDAP integrations they support configurations for complex searches, and it could be done the same way for shipyard. For example:
```
--ldap-user-request="(&(objectClass=inetOrgPerson)(uid={username}))"
```
This would give the flexibility to customise their own searches based on their LDAP server configuration, `{username}` being the substitution string in this particular case.

**Comment by meister** [comment]
I actually created a pull request to address this issue, making it a bit more flexible: https://github.com/shipyard/shipyard/pull/735

**Comment by rreinurm** [comment]
+1 I was forced to rewrite that piece of code to integrate with ipa ldap.

**Comment by justindavis** [comment]
+1

Our directory tree is using "uid" rather than "cn" for distinguished names as well.

I'd love to see the ability to limit access based on group membership as well -- perhaps a simple ldap filter in addition to a simple LDAP bind? That would allow for more complicated authorization scenarios (arbitrary group membership) without too much clutter.
