### ISSUE TITLE
Account for Docker Swarms that do not support privileged containers

### ISSUE THREAD

**Issue by funkytaco** [shipyard/shipyard#697]
Account for Docker Swarms that do not support privileged containers by allowing it to be turned off during shipyard install and maybe toggled back on at a later date.

https://getcarina.com/blog/running-shipyard-on-carina/

Carina by Rackspace (e.g. hosted Docker Swarm) doesn't allow the privileged flag for security reasons.

**Comment by ehazlett** [comment]
How exactly would this be implemented?  It seems odd to limit a function that is part of native swarm.  Perhaps a global authorization model would be better.

**Comment by funkytaco** [comment]
Rackspace is using AppArmor.
https://getcarina.com/docs/concepts/docker-swarm-carina/

I can deal with it as my team is small. I just thought I'd bring it to your attention. Thanks.
