### ISSUE TITLE
registry 2.2.1 auth fail

### ISSUE THREAD

**Issue by hhy5861** [shipyard/shipyard#700]
Can push directly on the terminal，failed to add the shipyard.

![b45b9de5-8e9f-4a7d-a730-4984a1a50f60](https://cloud.githubusercontent.com/assets/8274977/11776893/85e40310-a285-11e5-8a23-8e3b69740ca8.png)

**Comment by hhy5861** [comment]
docker run \
    -d \
    -p 5000:5000 \
    --restart=always \
    --name quancheng_registry \
    -v /data/docker/registry/auth:/auth \
    -v /data/docker/registry/certs:/certs \
    -e "REGISTRY_AUTH=htpasswd" \
    -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
    -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key \
    -v /data/docker-hub:/var/lib/registry \
    registry:2.2.1

**Comment by hhy5861** [comment]
no auth password is fail?
![image](https://cloud.githubusercontent.com/assets/8274977/11779437/0c6b04dc-a296-11e5-986e-f0d6c2dd4d2c.png)

**Comment by ehazlett** [comment]
Registry v2 is not yet supported.  Please see #670 .  Thanks!
