### ISSUE TITLE
Can't get localhost node

### ISSUE THREAD

**Issue by osallou** [shipyard/shipyard#701]
I installed with "automatic" setup on CentOS 7. I can access the Web UI of shipyard, but local node (where master is installed) does not appear.

Install gives:

    [root@dockerdev ~]# curl -sSL https://shipyard-project.com/deploy | bash -s
    Deploying Shipyard
    -> Starting Database
     -> Starting Discovery
     -> Starting Cert Volume
     -> Starting Proxy
     -> Starting Swarm Manager
     -> Starting Swarm Agent
     -> Starting Controller
    Waiting for Shipyard on a.b.c.d:8080
    .......................

and it remains stalled on the waiting, though web ui is accessible. If I Ctrl-C , it stops waiting and containers are all up:

    [root@dockerdev ~]# docker ps
    CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
    28c0a805abff        shipyard/shipyard:latest       "/bin/controller --de"   16 minutes ago      Up 4 minutes        0.0.0.0:8080->8080/tcp                           shipyard-controller
    3b4ae8bab3b6        swarm:latest                   "/swarm j --addr 192."   16 minutes ago      Up 16 minutes       2375/tcp                                         shipyard-swarm-agent
    c0d8d147f4a8        swarm:latest                   "/swarm m --replicati"   16 minutes ago      Up 16 minutes       2375/tcp                                         shipyard-swarm-manager
    b4a17ee63cd5        ehazlett/docker-proxy:latest   "/usr/local/bin/run"     16 minutes ago      Up 16 minutes       0.0.0.0:2375->2375/tcp                           shipyard-proxy
    4c17af944b49        alpine                         "sh"                     16 minutes ago      Up 16 minutes                                                        shipyard-certs
    96deb2c63f4c        microbox/etcd:latest           "/bin/etcd -addr 192."   16 minutes ago      Up 16 minutes       0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
    1eba7ec13172        rethinkdb                      "rethinkdb --bind all"   16 minutes ago      Up 16 minutes       8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkdb

But if I go to the "node" section, no node appear. If I try to manually add it with the ...| ACTION=node ...  command, I get an error:

    [root@dockerdev ~]# curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://a.b.c.d:4001 bash -s
    Adding Node
     -> Starting Cert Volume
    Error response from daemon: Conflict. The name "shipyard-certs" is already in use by container 4c17af944b49. You have to remove (or rename) that container to be able to reuse that name.

Any idea of what is goind wrong? I see no error on controller logs.

**Comment by osallou** [comment]
[root@dockerdev ~]# docker -v
Docker version 1.9.1, build a34a1d5

**Comment by ehazlett** [comment]
The deploy script already starts a Swarm agent on the node that the
installer runs from. There is no need to run it again for the node.

**Comment by osallou** [comment]
I know, but as no node appears, i tested the command, just in case.
Anyway i can see the swarm agent, and can query it directly on port 2375, but still no host node in web manager

**Comment by ehazlett** [comment]
Can you see containers in the UI?

**Comment by osallou** [comment]
No container, no image, ... Seems it gets nothing from swarm, though i get no error in docker logs, and querying swarm manager direcly works. Anyway, i have uninstalled shipyard for the moment. Could be an iptable stuff issue, i tried several tool and iptables had a lot of rules, i don t think shipyard installed them.
I close the issue for the moment and reopen if i can reproduce in a later try

**Comment by mach-kernel** [comment]
@osallou I'm having the same issue on a clean Linux install with docker. Were you able to find a solution?

**Comment by osallou** [comment]
Nope sorry, haven t tried again but you should check your iptables rules

Le ven. 1 janv. 2016 19:14, David Stancu <notifications@github.com> a
écrit :

**Comment by andrewmgee** [comment]
same issue on clean ubuntu install. turned off iptables, same issue. anyone find a solution?

**Comment by nathraQ** [comment]
used ```vagrant init geerlingguy/ubuntu1204``` for testing
after that followed the instructions from the  [docker site](https://docs.docker.com/engine/installation/linux/ubuntulinux/) to install docker (last step was ```sudo docker run hello-world```). After that I just the automatic way to install shipyard ```curl -s https://shipyard-project.com/deploy | bash -s```

My result was the following:

> docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/swarm/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fswarm%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers).

**Comment by inthroxify** [comment]
I had the same issue described by osallou exactly, but in a brand new vagrant box (phusion/ubuntu-14.04-amd64) with a freshly installed docker. 

I found a workaround. There might be a better way than this, but at least this can get a person up and running. On a fresh install, I disabled the firewall temporarily just in case, and then did the following:

```
$ curl -sSL https://shipyard-project.com/deploy | bash -s
$ curl -sSL https://shipyard-project.com/deploy | ACTION=remove bash -s
$ curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://127.0.0.1:4001 bash -s
$ curl -sSL https://shipyard-project.com/deploy | ACTION=remove bash -s
$ curl -sSL https://shipyard-project.com/deploy | bash -s
```
Then my host node showed up in the web interface.
