### ISSUE TITLE
Linking containers changes container name in 'container' tab

### ISSUE THREAD

**Issue by markayre** [shipyard/shipyard#703]
I deploy container X and link container Y with it. When i return to the container tab they will briefly appear as container X and Y, but after a few refreshes they both appear as container Y. when i inspect them separately they have the correct names (also when i run docker ps on the hosts).

This becomes an issue when i need to link another container to X, because it has this incorrect name i can't select it from the link dropdown.

Anyone else having this issue?

shipyard version 3.0.1 and 3.0.2

**Comment by markayre** [comment]
just saw v3.0.2 is out. going to update and see if it resolves the issue

**Comment by markayre** [comment]
![screen shot 2015-12-14 at 18 14 12](https://cloud.githubusercontent.com/assets/11960543/11789500/ba9c877c-a28e-11e5-972f-7d57e99ede4b.png)
![screen shot 2015-12-14 at 18 14 22](https://cloud.githubusercontent.com/assets/11960543/11789501/ba9f3170-a28e-11e5-8ba2-3d328a500ce4.png)
![screen shot 2015-12-14 at 18 15 27](https://cloud.githubusercontent.com/assets/11960543/11789502/baa25f44-a28e-11e5-8a78-10b2d42b105c.png)

**Comment by tombee** [comment]
@markayre 
Could you use your browser's developer tools to take a look at the response you're receiving back from the controller?

The API returns multiple names for each container, just curious to see how we're ending up selecting the 'wrong' one.  I believe this should have been fixed in https://github.com/shipyard/shipyard/pull/633.

**Comment by markayre** [comment]
Hi @tombee thanks for getting back to me. I looked through developer tools and i'm assuming you mean the containers.controller.js? Below is the output in the response tab:

```javascript
(function(){
    'use strict';

    angular
        .module('shipyard.containers')
        .controller('ContainersController', ContainersController);

    ContainersController.$inject = ['$scope', 'ContainerService', '$state'];
    function ContainersController($scope, ContainerService, $state) {
        var vm = this;
        
        vm.error = "";
        vm.errors = [];
        vm.containers = [];
        vm.selected = {};
        vm.selectedItemCount = 0;
        vm.selectedAll = false;
        vm.numOfInstances = 1;
        vm.selectedContainer = null;
        vm.selectedContainerId = "";
        vm.newName = "";

        vm.showDestroyContainerDialog = showDestroyContainerDialog;
        vm.showRestartContainerDialog = showRestartContainerDialog;
        vm.showStopContainerDialog = showStopContainerDialog;
        vm.showPauseContainerDialog = showPauseContainerDialog;
        vm.showScaleContainerDialog = showScaleContainerDialog;
        vm.showRenameContainerDialog = showRenameContainerDialog;
        vm.destroyContainer = destroyContainer;
        vm.stopContainer = stopContainer;
        vm.pauseContainer = pauseContainer;
        vm.unpauseContainer = unpauseContainer;
        vm.restartContainer = restartContainer;
        vm.scaleContainer = scaleContainer;
        vm.renameContainer = renameContainer;
        vm.refresh = refresh;
        vm.containerStatusText = containerStatusText;
		vm.nodeName = nodeName;
		vm.containerName = containerName;
        vm.checkAll = checkAll;
        vm.clearAll = clearAll;
        vm.destroyAll = destroyAll;
        vm.stopAll = stopAll;
        vm.restartAll = restartAll;

        refresh();

        // Apply jQuery to dropdowns in table once ngRepeat has finished rendering
        $scope.$on('ngRepeatFinished', function() {
            $('.ui.sortable.celled.table').tablesort();
            $('#select-all-table-header').unbind();
            $('.ui.right.pointing.dropdown').dropdown();
        });

        $('#multi-action-menu').sidebar({dimPage: false, animation: 'overlay', transition: 'overlay'});

        $scope.$watch(function() {
            var count = 0;
            angular.forEach(vm.selected, function (s) {
                if(s.Selected) {
                    count += 1;
                }
            });
            vm.selectedItemCount = count;
        });

        // Remove selected items that are no longer visible 
        $scope.$watchCollection('filteredContainers', function () {
            angular.forEach(vm.selected, function(s) {
                if(vm.selected[s.Id].Selected == true) {
                    var isVisible = false
                    angular.forEach($scope.filteredContainers, function(c) {
                        if(c.Id == s.Id) {
                            isVisible = true;
                            return;
                        }
                    });
                    vm.selected[s.Id].Selected = isVisible;
                }
            });
            return;
        });

        function clearAll() {
            angular.forEach(vm.selected, function (s) {
                vm.selected[s.Id].Selected = false;
            });
        }

        function restartAll() {
            angular.forEach(vm.selected, function (s) {
                if(s.Selected == true) {
                    ContainerService.restart(s.Id)
                        .then(function(data) {
                            delete vm.selected[s.Id];
                            vm.refresh();
                        }, function(data) {
                            vm.error = data;
                        });
                }
            });
        }

        function stopAll() {
            angular.forEach(vm.selected, function (s) {
                if(s.Selected == true) {
                    ContainerService.stop(s.Id)
                        .then(function(data) {
                            delete vm.selected[s.Id];
                            vm.refresh();
                        }, function(data) {
                            vm.error = data;
                        });
                }
            });
        }

        function destroyAll() {
            angular.forEach(vm.selected, function (s) {
                if(s.Selected == true) {
                    ContainerService.destroy(s.Id)
                        .then(function(data) {
                            delete vm.selected[s.Id];
                            vm.refresh();
                        }, function(data) {
                            vm.error = data;
                        });
                }
            });
        }

        function checkAll() {
            angular.forEach($scope.filteredContainers, function (container) {
                vm.selected[container.Id].Selected = vm.selectedAll;
            });
        }

        function refresh() {
            ContainerService.list()
                .then(function(data) {
                    vm.containers = data; 
                    angular.forEach(vm.containers, function (container) {
                        vm.selected[container.Id] = {Id: container.Id, Selected: vm.selectedAll};
                    });
                }, function(data) {
                    vm.error = data;
                });

            vm.error = "";
            vm.errors = [];
            vm.containers = [];
            vm.selected = {};
            vm.selectedItemCount = 0;
            vm.selectedAll = false;
            vm.numOfInstances = 1;
            vm.selectedContainerId = "";
            vm.newName = "";
        }

        function showDestroyContainerDialog(container) {
            vm.selectedContainerId = container.Id;
            $('#destroy-modal').modal('show');
        }

        function showRestartContainerDialog(container) {
            vm.selectedContainerId = container.Id;
            $('#restart-modal').modal('show');
        }

        function showStopContainerDialog(container) {
            vm.selectedContainerId = container.Id;
            $('#stop-modal').modal('show');
        }

        function showPauseContainerDialog(container) {
            vm.selectedContainerId = container.Id;
            $("#pause-modal").modal('show');
        }

        function showScaleContainerDialog(container) {
            vm.selectedContainerId = container.Id;
            $('#scale-modal').modal('show');
        }

        function showRenameContainerDialog(container) {
            vm.selectedContainer = container;
            $('#rename-modal').modal('show');
        }

        function destroyContainer() {
            ContainerService.destroy(vm.selectedContainerId)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function stopContainer() {
            ContainerService.stop(vm.selectedContainerId)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function pauseContainer() {
            ContainerService.pause(vm.selectedContainerId)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function unpauseContainer(container) {
            vm.selectedContainerId = container.Id;
            ContainerService.unpause(vm.selectedContainerId)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function restartContainer() {
            ContainerService.restart(vm.selectedContainerId)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function scaleContainer() {
            ContainerService.scale(vm.selectedContainerId, vm.numOfInstances)
                .then(function(response) {
                    vm.refresh();
                }, function(response) {
                    // Add unique errors to vm.errors
                    $.each(response.data.Errors, function(i, el){
                            if($.inArray(el, vm.errors) === -1) vm.errors.push(el);
                    });
                });
        }

        function renameContainer() {
            ContainerService.rename(vm.selectedContainer.Id, vm.newName)
                .then(function(data) {
                    vm.refresh();
                }, function(data) {
                    vm.error = data;
                });
        }

        function containerStatusText(container) {
            if(container.Status.indexOf("Up")==0){
                if (container.Status.indexOf("(Paused)") != -1) {
                    return "Paused";
                }
                return "Running";
            }
            else if(container.Status.indexOf("Exited")==0){
                return "Stopped";
            }            
            return "Unknown";
        }   
		
		function nodeName(container) {
			// Return only the node name (first component of the shortest container name)
			var components = shortestContainerName(container).split('/');
			return components[1];
		}
		
		function containerName(container) {
			// Remove the node name by returning the last name component of the shortest container name
			var components = shortestContainerName(container).split('/');
			return components[components.length-1];
		}
		
		function shortestContainerName(container) {
			// Distill shortest container name by taking the name with the fewest components
			// Names with the same number of components are considered in undefined order
			var shortestName = "";
			var minComponents = 99;
			
			var names = container.Names
			for(var i=0; i<names.length; i++) {
				var name = names[i];
				var numComponents = name.split('/').length
				if(numComponents < minComponents) {
					shortestName = name;
					minComponents = numComponents;
				}
			}

			return shortestName;			
		}
    }
})();
```

**Comment by tombee** [comment]
If you're using Chrome, you should be able to ctrl+shift+n, select the
network tab.  Once the network tab is open, navigate to the Containers
page.  You should see a XHR request that you should be able to inspect and
see the raw json from the server.

**Comment by markayre** [comment]
Thanks. the raw json returned is below. Looking through it the container that has the 'wrong' name has 3 names assigned to "Names":["/AACORE03/infra_kafka/zk","/AACORE03/infra_storm_supervisor/zk_kafka","/AACORE03/infra_zookeeper_kafka"],

Full json below:`

[{"Id":"1f66b6f776035256d2b1ec8b2075214aa1250416541c330645210e03c049670f","Names":["/AACORE01/edge"],"Image":"10.110.3.222:5000/hpad/edge","Command":"sh -c 'java -jar $VERTICLE_FILE -conf /config/conf.json -instances 10'","Created":1450295209,"Status":"Restarting (1) 4 minutes ago","Ports":[{"IP":"10.110.3.221","PrivatePort":4321,"PublicPort":4321,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"31b60b98cd3205595931c85623732624acfaa6e71bc15565a97258e4a19a2a2d","Names":["/AACORE01/backend_jobs"],"Image":"10.110.3.222:5000/hpad/backend-jobs","Command":"/bin/sh -c $CATALINA_HOME/start-tomcat.sh","Created":1450295204,"Status":"Up 18 minutes","Ports":[{"IP":"","PrivatePort":8080,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"9f1fdf49deecbf13281ced645ba5bc632a03efa5bfc1492f5b9cf540052a7052","Names":["/AACORE01/internal_ui"],"Image":"10.110.3.222:5000/hpad/ui-internal","Command":"/bin/sh -c $CATALINA_HOME/start-tomcat.sh","Created":1450295195,"Status":"Up 18 minutes","Ports":[{"IP":"10.110.3.221","PrivatePort":8080,"PublicPort":8083,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"37d1642b223076525f458b7e63a8be045b8a00b36a2add05dae9e019643e8f1c","Names":["/AACORE01/command_channel"],"Image":"10.110.3.222:5000/hpad/command-channel","Command":"/bin/sh -c $CATALINA_HOME/start-tomcat.sh","Created":1450295183,"Status":"Up 19 minutes","Ports":[{"IP":"10.110.3.221","PrivatePort":8080,"PublicPort":8081,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"42d390278d527d61c11d7d23a7e1492d704503e97170a1241d22dcb60392e951","Names":["/AACORE01/consul"],"Image":"progrium/consul","Command":"/bin/start -server -bootstrap-expect 3 -advertise 10.110.3.221 -join 10.110.3.221","Created":1450284456,"Status":"Up 3 hours","Ports":[{"IP":"10.110.3.221","PrivatePort":8302,"PublicPort":8302,"Type":"tcp"},{"IP":"10.110.3.221","PrivatePort":8301,"PublicPort":8301,"Type":"tcp"},{"IP":"10.110.3.221","PrivatePort":8300,"PublicPort":8300,"Type":"tcp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"tcp"},{"IP":"10.110.3.221","PrivatePort":8600,"PublicPort":53,"Type":"udp"},{"IP":"10.110.3.221","PrivatePort":8500,"PublicPort":8500,"Type":"tcp"},{"IP":"10.110.3.221","PrivatePort":8400,"PublicPort":8400,"Type":"tcp"},{"IP":"10.110.3.221","PrivatePort":8302,"PublicPort":8302,"Type":"udp"},{"IP":"10.110.3.221","PrivatePort":8301,"PublicPort":8301,"Type":"udp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"udp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"1dda632fcc26101260251d30b4e36719ddd0adcc08ee7f5ea2493eb084515622","Names":["/AACORE01/db_migrations"],"Image":"10.110.3.222:5000/hpad/db-migrations","Command":"/bin/sh -c /config/start-migration.sh","Created":1450284310,"Status":"Restarting (0) 51 minutes ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"a8844d7f1928c675de489231d87a9949105af522260b25247b880494f8335668","Names":["/AACORE03/infra_topologies"],"Image":"10.110.3.222:5000/hpad/topologies","Command":"/bin/sh -c /config/submit-topologies.sh","Created":1450283510,"Status":"Exited (-1) 2 hours ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"60e8ea362e28ae4266f37f0be0dadd5be413c3f411bb3a30d453e9bd85b3af69","Names":["/AACORE03/infra_storm_supervisor","/AACORE03/infra_topologies/supervisor"],"Image":"10.110.3.222:5000/hpad/storm-supervisor","Command":"/bin/sh -c /usr/bin/start-supervisor.sh","Created":1450282612,"Status":"Up 3 hours","Ports":[{"IP":"","PrivatePort":8000,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":6703,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":6702,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":6701,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":6700,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":22,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"7a6d1fa22d82e755dd815f36d83fdf7d15d8e7f3eb7c370848039a7b5ec3933b","Names":["/AACORE03/infra_kafka","/AACORE03/infra_storm_supervisor/kafka"],"Image":"10.110.3.222:5000/hpad/kafka","Command":"/bin/sh -c start-kafka.sh","Created":1450281887,"Status":"Up 4 hours","Ports":[{"IP":"10.110.3.223","PrivatePort":9092,"PublicPort":9092,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"c8e10a00654997130184766f68e1b04940075472862c2d23d82def6bf9f2e444","Names":["/AACORE03/infra_kafka/zk","/AACORE03/infra_storm_supervisor/zk_kafka","/AACORE03/infra_zookeeper_kafka"],"Image":"10.110.3.222:5000/hpad/zookeeper","Command":"/bin/sh -c '/usr/sbin/sshd \u0026\u0026 start-zk.sh'","Created":1450281560,"Status":"Up 4 hours","Ports":[{"IP":"","PrivatePort":2181,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":22,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":3888,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":2888,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"9e77f2ef3686986e994be9feac00eb4f0bb0491be04f47408df32c93f371f848","Names":["/AACORE03/infra_storm01"],"Image":"10.110.3.222:5000/hpad/storm-ui","Command":"/bin/sh -c /usr/bin/start-supervisor.sh","Created":1450281266,"Status":"Up 4 hours","Ports":[{"IP":"10.110.3.223","PrivatePort":8080,"PublicPort":49080,"Type":"tcp"},{"IP":"","PrivatePort":22,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"586be627eb9afc64fc46e71729c1a9485d549bc6a7e85102c1d871e8cc397e5b","Names":["/AACORE03/infra_storm01/nimbus","/AACORE03/infra_storm_nimbus","/AACORE03/infra_storm_supervisor/nimbus","/AACORE03/infra_topologies/nimbus"],"Image":"10.110.3.222:5000/hpad/storm-nimbus","Command":"/bin/sh -c /usr/bin/start-supervisor.sh","Created":1450280994,"Status":"Up 4 hours","Ports":[{"IP":"","PrivatePort":3773,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":3772,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":22,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":6627,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"6931c7fe339c757e774c8cc2d5742b6283ed9ba330544d1de3df90ddeebca269","Names":["/AACORE03/infra_storm01/zk","/AACORE03/infra_storm_nimbus/zk","/AACORE03/infra_storm_supervisor/zk","/AACORE03/infra_zookeeper_storm"],"Image":"10.110.3.222:5000/hpad/zookeeper","Command":"/bin/sh -c '/usr/sbin/sshd \u0026\u0026 start-zk.sh'","Created":1450280799,"Status":"Exited (-1) 2 hours ago","Ports":[],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"f30faafcef546309a78e53bed9d362314ae8b2ecbc210927bcbc00175ff21d7f","Names":["/AACORE03/infra_cassandra01","/AACORE03/infra_storm_supervisor/cassandra"],"Image":"10.110.3.222:5000/hpad/cassandra","Command":"/docker-entrypoint.sh cassandra -f","Created":1450280699,"Status":"Up 2 hours","Ports":[{"IP":"10.110.3.223","PrivatePort":9042,"PublicPort":9042,"Type":"tcp"},{"IP":"","PrivatePort":9160,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":7199,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":7001,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":7000,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"b0d833850904c669762907b1d0b8d56aad620c8e1ee49221af40790655a2375f","Names":["/AACORE01/shipyard"],"Image":"shipyard/shipyard","Command":"/bin/controller server -d tcp://swarm:3375","Created":1450116288,"Status":"Up 2 days","Ports":[{"IP":"10.110.3.221","PrivatePort":8080,"PublicPort":8080,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"724d43242d29350bc689aa3c8de9bc66c3e8495006cf1820d8b10f0a7c643b02","Names":["/AACORE02/Registry"],"Image":"registry:0.9.1","Command":"docker-registry","Created":1449609334,"Status":"Up 7 days","Ports":[{"IP":"10.110.3.222","PrivatePort":5000,"PublicPort":5000,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"3ba8a272e9612845c52bdee1a0d0ec2110bd5e6a5a3cc12e9dd3afcddf1cf132","Names":["/AACORE02/consul"],"Image":"progrium/consul","Command":"/bin/start -server -bootstrap-expect 3 -advertise 10.110.3.222 -join 10.110.3.221","Created":1449609127,"Status":"Up 7 days","Ports":[{"IP":"10.110.3.222","PrivatePort":8400,"PublicPort":8400,"Type":"tcp"},{"IP":"10.110.3.222","PrivatePort":8500,"PublicPort":8500,"Type":"tcp"},{"IP":"10.110.3.222","PrivatePort":8302,"PublicPort":8302,"Type":"udp"},{"IP":"10.110.3.222","PrivatePort":8301,"PublicPort":8301,"Type":"tcp"},{"IP":"10.110.3.222","PrivatePort":8301,"PublicPort":8301,"Type":"udp"},{"IP":"10.110.3.222","PrivatePort":8600,"PublicPort":53,"Type":"udp"},{"IP":"10.110.3.222","PrivatePort":8300,"PublicPort":8300,"Type":"tcp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"udp"},{"IP":"10.110.3.222","PrivatePort":8302,"PublicPort":8302,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"3c057453ba543f267316e4b8e5efae3fed8632d10d44462fc61de739f7f41d2d","Names":["/AACORE02/sick_wescoff"],"Image":"swarm","Command":"/swarm join --addr=10.110.3.222:2375 consul://10.110.3.222:8500/swarm","Created":1449605481,"Status":"Up 7 days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"5f5f671f4399723aa11d29f87d9f457756e6ab9d1d0aed09122c844eebc06b76","Names":["/AACORE01/rethinkdb","/AACORE01/shipyard/rethinkdb"],"Image":"rethinkdb","Command":"rethinkdb --bind all","Created":1449210887,"Status":"Up 12 days","Ports":[{"IP":"","PrivatePort":29015,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":28015,"PublicPort":0,"Type":"tcp"},{"IP":"","PrivatePort":8080,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"13d2ddf0d61f2d6b4eeb9edd244d9661f9f8a229fa46c15a999d0f171e1fae73","Names":["/AACORE01/shipyard/swarm","/AACORE01/swarm-manager"],"Image":"swarm","Command":"/swarm manage --host tcp://0.0.0.0:3375 consul://10.110.3.221:8500/swarm","Created":1449209399,"Status":"Up 12 days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"35eec29562af63756cc707b46a0c461cc5756958fcfbf153f8f74b174b43d56f","Names":["/AACORE03/lonely_aryabhata"],"Image":"swarm","Command":"/swarm join --addr=10.110.3.223:2375 consul://10.110.3.223:8500/swarm","Created":1449207667,"Status":"Up 12 days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"5d1feeab37d3291520e8db2fcaea412b820cfc7b86314f01a9b88168e249c318","Names":["/AACORE01/focused_mahavira"],"Image":"swarm","Command":"/swarm join --addr=10.110.3.221:2375 consul://10.110.3.221:8500/swarm","Created":1449207667,"Status":"Up 12 days","Ports":[{"IP":"","PrivatePort":2375,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}},{"Id":"d3e82f71d362d37501adddb789c0265f85903b0a2381551626a00aa8b0975862","Names":["/AACORE03/consul"],"Image":"progrium/consul","Command":"/bin/start -server -bootstrap-expect 3 -advertise 10.110.3.223 -join 10.110.3.221","Created":1449190128,"Status":"Up 12 days","Ports":[{"IP":"10.110.3.223","PrivatePort":8500,"PublicPort":8500,"Type":"tcp"},{"IP":"10.110.3.223","PrivatePort":8302,"PublicPort":8302,"Type":"udp"},{"IP":"10.110.3.223","PrivatePort":8301,"PublicPort":8301,"Type":"udp"},{"IP":"10.110.3.223","PrivatePort":8300,"PublicPort":8300,"Type":"tcp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"udp"},{"IP":"10.110.3.223","PrivatePort":8400,"PublicPort":8400,"Type":"tcp"},{"IP":"10.110.3.223","PrivatePort":8600,"PublicPort":53,"Type":"udp"},{"IP":"10.110.3.223","PrivatePort":8302,"PublicPort":8302,"Type":"tcp"},{"IP":"10.110.3.223","PrivatePort":8301,"PublicPort":8301,"Type":"tcp"},{"IP":"","PrivatePort":53,"PublicPort":0,"Type":"tcp"}],"SizeRw":0,"SizeRootFs":0,"Labels":{}}]

**Comment by tombee** [comment]
Hmm I thought that the PR I referenced should select the name with the fewest components, and in this case, should select the correct name in the case above.

Can you confirm that you're using shipyard 3.0.2?  If not, how old is the shipyard image that you're using?

**Comment by markayre** [comment]
I had this issue on 3.0.1 and then upgraded to 3.0.2 (using the 'latest' tag):

REPOSITORY                               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
shipyard/shipyard                        latest              4db14669ff0c        9 days ago          58.7 MB

**Comment by tombee** [comment]
@markayre Hmm okay, and you're still seeing the wrong name displayed on 3.0.2? :(

**Comment by markayre** [comment]
unfortunately yes. And because of this it means that i can't create a link to this container when deploying.

Has anyone else been able to replicate? I saw from #633 that it should have been fixed, maybe it needs to pick the last name instead of the shortest one?

Thanks for your help @tombee

**Comment by tombee** [comment]
My understanding of @gerco's change in https://github.com/shipyard/shipyard/pull/633/files, is that it should select the last name in the example you gave:

```json
"Names":["/AACORE03/infra_kafka/zk","/AACORE03/infra_storm_supervisor/zk_kafka","/AACORE03/infra_zookeeper_kafka"]
```

Since `/AACORE03/infra_zookeeper_kafka` is deemed the shortest, since it has 2 components, instead of the 3 that `/AACORE03/infra_kafka/zk` has.

@ehazlett: PR 633 is in 3.0.2 right?  Or does @markayre need to use `latest`?

**Comment by ehazlett** [comment]
Yes 3.0.2 is latest.
