### ISSUE TITLE
What is "User Defined Container DNS" on the containers page

### ISSUE THREAD

**Issue by funkytaco** [shipyard/shipyard#704]
What is "User Defined Container DNS" on the containers page? e.g. how do I define DNS that would show up here?

**Comment by tombee** [comment]
@funkytaco There's a "Container DNS" section on the container deploy page, alternatively this should pick up dns supplied at the command line, e.g.

```
$ docker run --dns="1.2.3.4" busybox top
```

**Comment by funkytaco** [comment]
Okay, thank you.

**Comment by tombee** [comment]
You're welcome! :)
