### ISSUE TITLE
Mount patch invisible

### ISSUE THREAD

**Issue by roasten** [shipyard/shipyard#706]
I can't see any mount patch in container information. This is something you have manage according to screenshots at your website. Have you remove this or is it a bug?

Best tool to handle docker, keep up the good work!

**Comment by edasque** [comment]
I see this issue as well. Container links are present as are processes & ports but not volumes.

Incidentally I can't configure a volume to be *ro* in Shipyard

**Comment by ehazlett** [comment]
This looks like a bug.  Thanks for reporting.
