### ISSUE TITLE
How can I add host node to shipyard?

### ISSUE THREAD

**Issue by jeremywu0127** [shipyard/shipyard#708]
hi, I use the shipyard (v3.0.2) on the host(192.168.2.104), then I run the following command  on the host(192.168.3.44)
***sudo docker run  \
     -ti \
     -d \
      --restart=always \
     --name shipyard-swarm-agent \
    swarm:latest \
    join --addr 192.168.2.104:2375 etcd://192.168.2.104:4001***
but I can't see the 192.168.3.44 on the shipyard nodes dashbord ! Anything wrong?

**Comment by yangdongsheng** [comment]
Please try the deploy script.
```curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://192.168.2.104:4001 bash -s```

**Comment by jeremywu0127** [comment]
@yangdongsheng actually, I want to add the 3.44 to the 2.104 , the 2.104 is the manager ! it doesn't work ! anyway, thx
