### ISSUE TITLE
Update shipyard to latest version?

### ISSUE THREAD

**Issue by R0GGER** [shipyard/shipyard#710]
I am running shipyard now for a while and it works great, but how do I update shipyard to its latest version?

**Comment by markayre** [comment]
depends on how you deployed. if you deployed using the automated script follow the instructions on the site and use the 'upgrade' action.

http://shipyard-project.com/docs/deploy/automated/

if you did it manually you would just destroy your controller container and re-run it with the latest container image (shipyard/shipyard:latest). I don't believe there is anything else needed to update this way.

http://shipyard-project.com/docs/deploy/manual/

**Comment by R0GGER** [comment]
Uh... automated... 
I guess "curl -sSL https://shipyard-project.com/deploy | bash -s" to update?

**Comment by markayre** [comment]
I think you need to do:

curl -sSL https://shipyard-project.com/deploy | ACTION=upgrade bash -s

**Comment by ehazlett** [comment]
Correct.  You should be able to use the "ACTION=upgrade" on the deploy
script.

**Comment by R0GGER** [comment]
How to keep username and password?

**Comment by ehazlett** [comment]
You would need to use a manual upgrade procedure.  Basically pull the latest Shipyard image and re-launch -- this needs documented.
