### ISSUE TITLE
Expected Procedures for a reboot

### ISSUE THREAD

**Issue by ccit-spence** [shipyard/shipyard#714]
How is Shipyard expected to behave when a Node or UI/Controller reboots?

Currently testing things to see how they work.  Rebooted the UI and the Nodes.  The UI came up after the reboot with no effort. The Node however, did not come up within the UI. 

What is the expected behavior?  Should a rejoin of the Node be performed?

**Comment by shairozan** [comment]
One thing I've found is that you should bring up the non UI containers first, then the UI. After a little bit they'll go through re-election and show back up in the UI.

You can do a lot more ugly stuff about stopping and starting the agents and managers, but the above is the cleanest way I've seen it done.

**Comment by ehazlett** [comment]
@shairozan is correct - you need to wait until the cluster is ready to start the Shipyard controller.
