### ISSUE TITLE
Shipyard doesn't find itself on installation

### ISSUE THREAD

**Issue by duel007** [shipyard/shipyard#717]
I can duplicate this issue on Centos 7. Fully updated, fresh install of the OS, docker engine, and shipyard. It stops on the last step of the install on waiting for shipyard. The web interface starts but shows no containers, including the ones that shipyard runs. Seems to work fine on Ubuntu but I don't understand why it doesn't work on Centos7.

**Comment by ehazlett** [comment]
I believe this is an issue with the firewall.  Could you try to disable and
see if it still persists?

**Comment by duel007** [comment]
Yep, you're right. Sorry, I should have tried that first.

**Comment by ehazlett** [comment]
No problem :)
