### ISSUE TITLE
Shipyard runs with errors

### ISSUE THREAD

**Issue by llqzwh** [shipyard/shipyard#719]
I setup shipyard with following commands:
#docker run -it -d --name shipyard-rethinkdb-data --entrypoint /bin/bash shipyard/rethinkdb -l
#docker run -it -P -d --name shipyard-rethinkdb --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb
#docker run -it -p 8082:8080 -d --name shipyard --link shipyard-rethinkdb:rethinkdb --restart=always shipyard/shipyard server

Login shipyard with username 'admin' and password 'shipyard'
Click 'CONTAINERS', met following error:
![image](https://cloud.githubusercontent.com/assets/12825720/12161103/156493b0-b52d-11e5-8411-91df38fb93c7.png)

Click 'IMAGES' and 'NODES', met following error:
![image](https://cloud.githubusercontent.com/assets/12825720/12161107/1a58116c-b52d-11e5-9777-6aa4e684f7d3.png)

Docker version:
Docker version 1.9.1, build a34a1d5

Shipyard version:
3.0.2 (8e84bed)

Could anyone give some help? Thanks!

**Comment by llqzwh** [comment]
shipyard needs swarm correctly, I have solved this issue.

**Comment by valleylord** [comment]
seems that I face the same problem with you. Could you tell me how you solve this?
