### ISSUE TITLE
Add ability to order containers in groups

### ISSUE THREAD

**Issue by AlexGustafsson** [shipyard/shipyard#721]
In the "Containers" view / page of the Web UI there should be the option to group a number of containers and give that group a name. For example, this would allow for adding a group named "Shipyard" under which Shipyard related containers could be listed. It would simplify the view greatly when many containers are being managed. The groups would have no deeper meaning than simplifying the aforementioned view / page.

**Comment by Finkes** [comment]
I would like to see this feature as well. What do you think about labels that you could apply to containers and create dynamic groups based on that labels? Or do you prefer a basic grouping feature like e.g. in Jenkins for jobs?

**Comment by Ducatel** [comment]
This feature should be automatic when we use the `scale` command.
Example: when I scale my web server up to 50 instances, it isn't relevant to list these 50 entries.

![firefox_2016-05-18_11-59-42](https://cloud.githubusercontent.com/assets/1184332/15354908/39be83a8-1cf0-11e6-9661-f9b0a3f3dbba.png)

**Comment by tombee** [comment]
If anyone has some time to look at this, switching the tables to use: http://ng-table.com/#/grouping/demo-grouping-basic would help with this.
