### ISSUE TITLE
shipyard-swarm-manager could not recognize etcd discovery service

### ISSUE THREAD

**Issue by tiagomiguelsousa** [shipyard/shipyard#722]
Hi.

I´m trying to install shipyard on a Oracle Linux 7.2 (single host). To do that i'm using the manual installation.
After several attempts i'm facing the same error on swarm-manager:

INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
ERRO[0001] Discovery error: client: etcd cluster is unavailable or misconfigured
ERRO[0002] Discovery error: client: etcd cluster is unavailable or misconfigured
ERRO[0003] Discovery error: Unexpected watch error

My docker configurations are:
Server Version: 1.9.1

ExecStart=/usr/bin/docker daemon -D --insecure-registry DOCKERTEST:5000 --storage-opt dm.basesize=20G --storage-opt dm.loopdatasize=100G --exec-opt native.cgroupdriver=cgroupfs -H unix:///var/run/docker.sock $DOCKER_OPTS

With this i can access the UI at http://<host_ip>:8080 but i can not see any information about hosts, images and containers. My guess is that this is due to the error with swarm manager gettting registered with discovery service.

Can anyone help me?

Thanks in advance.

Tiago Sousa

**Comment by ehazlett** [comment]
This is an etcd issue.  Check the logs for the etcd container and see if there were any issues in starting.

**Comment by marsmensch** [comment]
Was not able to reproduce with Docker 1.10.3 on RHEL 7.2.
