### ISSUE TITLE
reset password(s)

### ISSUE THREAD

**Issue by bernardgut** [shipyard/shipyard#726]
I lost the pass for the admin user. How can I recover from this without reinstalling the whole thing ?

the docs is a bit succinct.

thanks

**Comment by ehazlett** [comment]
There isn't an easy way to recover.  You would need to delete the user from the RethinkDB container and then restart the controller.  This will re-create the default user.

**Comment by leveryd** [comment]
so how to delete the user from RethinkDB container ?
