### ISSUE TITLE
the error on private registry mount a local path

### ISSUE THREAD

**Issue by moon9sky** [shipyard/shipyard#727]
shipyard is a good tool.I'm trying to use shipyard to manage a container that is a private registry mount a local path, but shipyard can't seem to work right way.Shipyard can't get the infomation of the registry,and chrome got a error
![123](https://cloud.githubusercontent.com/assets/13216945/12349018/54e7ac2c-bba7-11e5-8fd2-bfc7f7a0ae30.png)

. And if I don't mount a local path,shipyard work well.display the right infomation

**Comment by ehazlett** [comment]
What version of the registry?

**Comment by marsmensch** [comment]
Looks exactly like the error i received when testing with a v2 registry initially. #625 #716
