### ISSUE TITLE
shipyard -ldap auth

### ISSUE THREAD

**Issue by rnagarajan12** [shipyard/shipyard#731]
I am having problem setting up LDAP auth with shipyard.
The error,

level=error msg="error during login for admin from : LDAP Result Code 200 \"\": ldap: could not retrieve response"

I am running shipyard with following args,
--ldap-server="ldap" --ldap-port="636" --ldap-base-dn=dc=company,dc=com --ldap-default-access-level="containers:ro"  --ldap-autocreate-users

**Comment by rreinurm** [comment]
I don't know your ldap setup, but try to use ldap port 389. Port 636 is used for ldap over ssl and current shipyard ldap integration does not support it.

**Comment by rnagarajan12** [comment]
I get this for port 389,

level=error msg="error during login for : LDAP Result Code 13 \"Confidentiality Required\": confidentiality required"

**Comment by ehazlett** [comment]
Correct.  Currently this is not supported.
