### ISSUE TITLE
Ability to commit and push a container

### ISSUE THREAD

**Issue by openStove** [shipyard/shipyard#732]
I'm not sure, but it seems that this feature is not yet implemented:
- I'd like to commit a container
- Being able to push it at the same time or in a second step

**Comment by WTFKr0** [comment]
Hi !
Just installed my first shipyard, and expected to find this feature too.
Is it on the roadmap ?

Thanx

**Comment by Tochirou** [comment]
You don't commit containers but images
This feature isn't implemented in shipyard though

**Comment by bleakgadfly** [comment]
+1 for this feature

 (As a side note, [Docker documentation](https://docs.docker.com/engine/reference/commandline/commit) seem to use the wording "Commit a container")

**Comment by tombee** [comment]
@bleakgadfly, @openStove, @WTFKr0 
Could you give some insight into your use case?  What are you using `docker commit` for?  This would help anyone looking to implement this to build the correct UX.

**Comment by bleakgadfly** [comment]
@tombee Absolutely! For me, in short, I've given access to my shipyard instance to someone whom I'd like to be able to administer their own containers and images without ever touching a command line. 

E.g. if they want to create a container from a joomla image and download some themes or plugins in that container I want them to be able to commit their changes from the Shipyard interface (and not touch the CLI or do any host/container volume mapping).

_Ideally_ what I would like from a UI would then be to access a container, see a button called "Commit" which opens a modal dialog to input a new Image Name and then have something like the following options:

A) Create a new container based on that image (e.g. redirecting to deploy controller with the view model for image name set to the image name from the modal dialog)
B) Destroy current container and create a new with the same setting (e.g. redirecting to deploy controller with the view model set to the properties of the existing container, and a button saying something in the vicinity of "Destroy Old & Deploy New")

But this is just a wish list ;

**Comment by tombee** [comment]
@bleakgadfly 
Thanks -- this should definitely help with proposal/design of this feature.

Would you like to help out with building this? :)

**Comment by bleakgadfly** [comment]
@tombee Sure :-)

**Comment by tombee** [comment]
@ehazlett 
Will probably have some ideas on this, as I'm not sure how `docker commit` behaves via swarm.  It's not something I ever use :)

**Comment by WTFKr0** [comment]
docker commit transform a running (or stopped) container into image.
It just create a new image with a new layer.
It works fine in a non swarm env, and create image locally (with the tag you give)
I don't know how swarm handle this, but i think it commits on each node => had to be tested
