### ISSUE TITLE
getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS?

### ISSUE THREAD

**Issue by nycjv321** [shipyard/shipyard#733]
I am trying to do the install via https://shipyard-project.com/deploy. But the install never completes. Here is the log:

[localhost ~]$ curl -sSL https://shipyard-project.com/deploy | bash -s
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
2314ad3eeb90: Pulling fs layer
2314ad3eeb90: Verifying Checksum
2314ad3eeb90: Download complete
2314ad3eeb90: Pull complete
Digest: sha256:d7201bdfa765bebed9a79c385db4378f55593e50dc8d002b9713810320ad93b9
Status: Downloaded newer image for alpine:latest
Deploying Shipyard
 -> Starting Database
Unable to find image 'rethinkdb:latest' locally
latest: Pulling from library/rethinkdb
523ef1d23f22: Pulling fs layer
140f9bdfeb97: Pulling fs layer
974fbb3f74a4: Pulling fs layer
5a6da0cf3149: Pulling fs layer
51989e3e851a: Pulling fs layer
7796214e5880: Pulling fs layer
27b42fd22794: Pulling fs layer
8ddb844cc93d: Pulling fs layer
3900feac1bd3: Pulling fs layer
2773572f7d51: Pulling fs layer
ae2a5b8a0cb6: Pulling fs layer
3900feac1bd3: Verifying Checksum
3900feac1bd3: Download complete
2773572f7d51: Verifying Checksum
2773572f7d51: Download complete
8ddb844cc93d: Verifying Checksum
8ddb844cc93d: Download complete
ae2a5b8a0cb6: Verifying Checksum
ae2a5b8a0cb6: Download complete
140f9bdfeb97: Verifying Checksum
140f9bdfeb97: Download complete
7796214e5880: Verifying Checksum
7796214e5880: Download complete
51989e3e851a: Verifying Checksum
51989e3e851a: Download complete
5a6da0cf3149: Verifying Checksum
5a6da0cf3149: Download complete
974fbb3f74a4: Verifying Checksum
974fbb3f74a4: Download complete
27b42fd22794: Verifying Checksum
27b42fd22794: Download complete
523ef1d23f22: Verifying Checksum
523ef1d23f22: Download complete
523ef1d23f22: Pull complete
140f9bdfeb97: Pull complete
974fbb3f74a4: Pull complete
5a6da0cf3149: Pull complete
51989e3e851a: Pull complete
7796214e5880: Pull complete
27b42fd22794: Pull complete
8ddb844cc93d: Pull complete
3900feac1bd3: Pull complete
2773572f7d51: Pull complete
ae2a5b8a0cb6: Pull complete
Digest: sha256:152eed5a1ee8703e317b355302f57b3c2fa91886ef3f1cece971c77204ed8f22
Status: Downloaded newer image for rethinkdb:latest
 -> Starting Discovery
Unable to find image 'microbox/etcd:latest' locally
latest: Pulling from microbox/etcd
2137493e8179: Pulling fs layer
b765026875b7: Pulling fs layer
b60ee7014c90: Pulling fs layer
a1d5226bdf32: Pulling fs layer
73c70be297f6: Pulling fs layer
96192a5fe39d: Pulling fs layer
a1d5226bdf32: Verifying Checksum
a1d5226bdf32: Download complete
96192a5fe39d: Verifying Checksum
96192a5fe39d: Download complete
73c70be297f6: Verifying Checksum
73c70be297f6: Download complete
b60ee7014c90: Verifying Checksum
b60ee7014c90: Download complete
b765026875b7: Verifying Checksum
b765026875b7: Download complete
2137493e8179: Verifying Checksum
2137493e8179: Download complete
2137493e8179: Pull complete
b765026875b7: Pull complete
b60ee7014c90: Pull complete
a1d5226bdf32: Pull complete
73c70be297f6: Pull complete
96192a5fe39d: Pull complete
Digest: sha256:941fd46b4eab265c65da9bfbf33397b853a7cef6c16df93a1e3fea7b4e47fc90
Status: Downloaded newer image for microbox/etcd:latest
 -> Starting Cert Volume
 -> Starting Proxy
Unable to find image 'shipyard/docker-proxy:latest' locally
latest: Pulling from shipyard/docker-proxy
74e49af2062e: Pulling fs layer
5ce25d7e3e30: Pulling fs layer
5e94d6bbd90b: Pulling fs layer
ac53919faac7: Pulling fs layer
31b11fb6acec: Pulling fs layer
276373c72857: Pulling fs layer
31b11fb6acec: Verifying Checksum
31b11fb6acec: Download complete
ac53919faac7: Verifying Checksum
ac53919faac7: Download complete
276373c72857: Verifying Checksum
276373c72857: Download complete
5e94d6bbd90b: Verifying Checksum
5e94d6bbd90b: Download complete
5ce25d7e3e30: Verifying Checksum
5ce25d7e3e30: Download complete
74e49af2062e: Verifying Checksum
74e49af2062e: Download complete
74e49af2062e: Pull complete
5ce25d7e3e30: Pull complete
5e94d6bbd90b: Pull complete
ac53919faac7: Pull complete
31b11fb6acec: Pull complete
276373c72857: Pull complete
Digest: sha256:da6bbd1a145581a940d44940cce0f43705d7f8ec552a4e97e77104ec1b6dc3d1
Status: Downloaded newer image for shipyard/docker-proxy:latest
 -> Starting Swarm Manager
Unable to find image 'swarm:latest' locally
latest: Pulling from library/swarm
d681c900c6e3: Pulling fs layer
188de6f24f3f: Pulling fs layer
90b2ffb8d338: Pulling fs layer
237af4efea94: Pulling fs layer
3b3fc6f62107: Pulling fs layer
7e6c9135b308: Pulling fs layer
986340ab62f0: Pulling fs layer
a9975e2cc0a3: Pulling fs layer
237af4efea94: Verifying Checksum
237af4efea94: Download complete
a9975e2cc0a3: Verifying Checksum
a9975e2cc0a3: Download complete
3b3fc6f62107: Verifying Checksum
3b3fc6f62107: Download complete
986340ab62f0: Verifying Checksum
986340ab62f0: Download complete
7e6c9135b308: Verifying Checksum
7e6c9135b308: Download complete
90b2ffb8d338: Verifying Checksum
90b2ffb8d338: Download complete
188de6f24f3f: Verifying Checksum
188de6f24f3f: Download complete
d681c900c6e3: Verifying Checksum
d681c900c6e3: Download complete
d681c900c6e3: Pull complete
188de6f24f3f: Pull complete
90b2ffb8d338: Pull complete
237af4efea94: Pull complete
3b3fc6f62107: Pull complete
7e6c9135b308: Pull complete
986340ab62f0: Pull complete
a9975e2cc0a3: Pull complete
Digest: sha256:c21fd414b0488637b1f05f13a59b032a3f9da5d818d31da1a4ca98a84c0c781b
Status: Downloaded newer image for swarm:latest
 -> Starting Swarm Agent
 -> Starting Controller
Unable to find image 'shipyard/shipyard:latest' locally
latest: Pulling from shipyard/shipyard
8a648f689ddb: Pulling fs layer
5bc522db8631: Pulling fs layer
f0f03ad56349: Pulling fs layer
d0dacfa77aa0: Pulling fs layer
cdfdb219e352: Pulling fs layer
4db14669ff0c: Pulling fs layer
cdfdb219e352: Verifying Checksum
cdfdb219e352: Download complete
4db14669ff0c: Verifying Checksum
4db14669ff0c: Download complete
d0dacfa77aa0: Verifying Checksum
d0dacfa77aa0: Download complete
8a648f689ddb: Verifying Checksum
8a648f689ddb: Download complete
8a648f689ddb: Pull complete
f0f03ad56349: Verifying Checksum
f0f03ad56349: Download complete
5bc522db8631: Verifying Checksum
5bc522db8631: Download complete
5bc522db8631: Pull complete
f0f03ad56349: Pull complete
d0dacfa77aa0: Pull complete
cdfdb219e352: Pull complete
4db14669ff0c: Pull complete
Digest: sha256:fe25e20695fda0a7aa576a8f0e25e9f257cc350c874ce1dba263704319df9adf
Status: Downloaded newer image for shipyard/shipyard:latest
Waiting for Shipyard on my_host:8080 # this never completes
...................................................................................................................................................^C

When I look at the logs I see this: 

[locahost ~]$ ps aux | grep dockerdocker logs -f shipyard-swarm-manager
grep: shipyard-swarm-manager: No such file or directory
[locahost ~]$ docker logs -f shipyard-swarm-manager 
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost  
INFO[0000] Leader Election: Cluster leadership acquired 
ERRO[0001] Get http://my_host:2375/v1.15/info: dial tcp my_host:2375: getsockopt: no route to host. Are you trying to connect to a TLS-enabled daemon without TLS? 

Below is my docker info output:

[localhost ~]$ docker info
Containers: 8
Images: 43
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-301.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 12
Total Memory: 15.58 GiB
Name: willy_wonka
ID: IGPH:72EC:QH5L:XRFJ:XFKI:HHQV:W52R:LTKG:5NVN:RTKM:OQCE:XDR7
Username: me
Registry: https://index.docker.io/v1/
[localhost ~]

This may be related to #683

**Comment by nycjv321** [comment]
The command works perfectly on my other box.

**Comment by ehazlett** [comment]
What is your host OS?

**Comment by nycjv321** [comment]
@ehazlett I am using Fedora 23 64bit edition. I included the docker info above. Both of my hosts run the same distros, just different hardware.

**Comment by ehazlett** [comment]
Thanks.  A lot of issues on the RedHat based distros are related to the firewall.  Can you try disabling that and see if that helps?

**Comment by nycjv321** [comment]
@ehazlett disabling the firewall and restarting the docker daemon fixes the problem. 

I noticed if I restart firewalld and docker, shipyard successfully loads but doesn't detect any containers.
