### ISSUE TITLE
Specifying --volumes-from in the GUI

### ISSUE THREAD

**Issue by chris-redekop** [shipyard/shipyard#734]
(How) can '--volumes-from' be specified when deploying a container with the Shipyard GUI?  (I get the impression from #225 that this is possible, but I don't see how.)

If specifying '--volumes-from' is not possible via the GUI, what are the recommended alternatives?  Is running 'docker run ... --volumes-from ...' on the Docker host the best way, or?

Thanks!

**Comment by Nox-404** [comment]
I'm stuck on the same problem :+1:

**Comment by ehazlett** [comment]
Currently it's not possible to specify volumes_from.  You can use regular
Docker volumes and pass the name of the volume instead of the host path.

**Comment by OmgImAlexis** [comment]
@ehazlett are there any plans on adding support for this?

**Comment by ehazlett** [comment]
We would love to track the same options as Swarm but we need more contributors.  Currently it's a matter of resourcing to get them in.

**Comment by pstreef** [comment]
I'm looking for the same functionality. Looking at the code and the api docs the changes seem trivial. However I have almost 0 experience with node.js and/or go so I'm not sure how to test and would have to take some considerable time to do so.

However I have tried to mess around a bit with the master branch code and think I have an implementation. However untested.

I also have never made a pull request before and am unsure if it is "not done" to present someone with untested code/pseudo code solutions to my own problem. So would like some insight before I continue!
