### ISSUE TITLE
Deploy shipyard on AWS Amazon EC2 instance

### ISSUE THREAD

**Issue by abipit** [shipyard/shipyard#737]
Hi @ehazlett 
I tested shipyard on 2 servers, one classic, it's ok, I see my containers, images....
I installed on an EC2 instance on Amazon AWS (with a private ip address on eth0 and a public ip address) and I don't see my containers, images....
I test a first time but at the end of installation, your script show the private ip address on my instance, so I can't access to the UI. I removed, exported the public IP as environment variable and installed a new time, now I have access to the UI but after login, it says : "There are no containers".
Do you have an idea please ? I don't find.
Thank you

**Comment by abipit** [comment]
Hi, @ehazlett, I tested a lot of methods but I don't find a solution :(
Others, have you already installed on AWS ?
Thanks

**Comment by ehazlett** [comment]
This is usually a security group issue.  Make sure the security group has rules to allow traffic between the hosts.

**Comment by abipit** [comment]
All TCP ports are open (0 - 65535) in the security group (for inbound).
For outbound, all traffic, all protocol and all port range are open.

=> But I still have the problem, there are no containers :(

**Comment by ehazlett** [comment]
There was an updated proxy image as part of the deploy script.  Could you
try to re-run the deploy and see if you continue to have issues?  Thx

**Comment by abipit** [comment]
First I still have the problem with #752, I deleted all the images and re-run the deploy but docker-proxy is in mode "Restarting"

**Comment by abipit** [comment]
It's ok now here. After fix the #752, I opened 2375 & 8080 ports in the console AWS and it's ok, I see my containers.
Thank you @ehazlett
