### ISSUE TITLE
vm.clearAll() 

### ISSUE THREAD

**Issue by yamateh** [shipyard/shipyard#738]
When i select-all container items,then click "clear",but don't set **vm.selectedAll**
`
function clearAll() {
            angular.forEach(vm.selected, function (s) {
                vm.selected[s.Id].Selected = false;
//add   vm.selectedAll=false;
            });
        }
`

**Comment by yamateh** [comment]
>

**Comment by llitfkitfk** [comment]
Is this function built for hide containers?
Or is there any way to hide containers for non-admin user (who can manage containers) cannot destroy the system-related-containers(like swarm or  shipyard)
