### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by zanjs** [shipyard/shipyard#740]
`exec: "bash": executable file not found in $PATH `

**Comment by tombee** [comment]
@zanjs Are you running a container that has bash available on its path?  You might need to run `sh` for something like busybox, or `ash` for something alpine based.

**Comment by zanjs** [comment]
@tombee  thinks

**Comment by tombee** [comment]
@zanjs You're welcome!  Feel free to close the issue if it's resolved :smile:
