### ISSUE TITLE
shipyard fails after copy Linux  Partition

### ISSUE THREAD

**Issue by little-joe999** [shipyard/shipyard#741]
Hi, 

I was running shipyard on a Manjaro 15.12 with Kernel 4.1.x without any issue. Just recently I moved the partition from one ssd to another (larger) one. Since then shipyard keeps failing. The container seem to start correctly but when I logon to shipyard I get the following error:

`Error...

{"data":"��<\u0000H\u0000T\u0000M\u0000L\u0000>\u0000<\u0000B\u0000O\u0000D\u0000Y\u0000>\u0000T\u0000h\u0000e\u0000 \u0000r\u0000e\u0000q\u0000u\u0000e\u0000s\u0000t\u0000e\u0000d\u0000 \u0000f\u0000i\u0000l\u0000e\u0000 \u0000i\u0000s\u0000 \u0000n\u0000o\u0000t\u0000 \u0000f\u0000o\u0000u\u0000n\u0000d\u0000!\u0000<\u0000/\u0000B\u0000O\u0000D\u0000Y\u0000>\u0000<\u0000/\u0000H\u0000T\u0000M\u0000L\u0000>\u0000\r\u0000\n\u0000\r\u0000\n\u0000\u0000\u0000","status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"NOT FOUND"}`

No container running.

If I click for example the images tab I get kicked out and the message "It looks like an error occurred" appears, not error message attached.

I deleted all container and images and restarted the automated deployment (which I did in the first place) 
`curl -sSL https://shipyard-project.com/deploy | bash -s`
without success. Same problem appears. I have no idea what could cause the issue since all other container are running well.

Thanks for any help.
Joe

**Comment by little-joe999** [comment]
btw. docker version is 1.9.1 
`Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 15:43:56 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 15:43:56 UTC 2016
 OS/Arch:      linux/amd64
`

**Comment by ehazlett** [comment]
Can you paste the logs from the controller?

**Comment by little-joe999** [comment]
thanks for the quick reply. I assume you mean the docker logs?

Here they are:

`INFO[0000] shipyard version 3.0.2                       
INFO[0000] checking database                            
DEBU[0024] connected to docker: url=tcp://swarm:3375    
DEBU[0024] configured docker proxy target: http://swarm:3375 
INFO[0024] created admin user: username: admin password: shipyard 
INFO[0024] controller listening on :8080 `

**Comment by ehazlett** [comment]
Ok no errors there. I'll try to reproduce.

**Comment by little-joe999** [comment]
Never mind, I think it must be something with my partition restoration. I just put my "old" ssd back and it still worked... so it seems Shipyard works find but my partition may be corrupted.
I will restore the image one more time to see what I did wrong. 

Thanks for your help anyway.
Joe

**Comment by ehazlett** [comment]
Cool thanks for the update

**Comment by little-joe999** [comment]
I think I found the problem and it is some (not exactly) reproducible. Could be a different issue though.

After I restored the partition, my system got a different IP address upon reboot. I did not realize it since I was accessing shipyard via localhost and before the restore I had not problem. Now since I realized that i tired to change my IP on purpose and in fact once this happens shipyard is telling me that no docker container is running and that no image is available. 

I run docker - UI in parallel since they have both some non overlapping features, however docker - UI still shows me all the running containers and pulled images.

I also realized that shipyard is hard wireing the local IP Address into the (i guess) rethinkdb. Is there a way to update the info (table, database, login credentials) via python for example, or can I force shipyard to ignore it?

This may be the root cause of my issue.

Thanks
Joe

**Comment by ehazlett** [comment]
It all depends on how you deploy.  As with any service if you use DNS you
can update the IP there and have it work. Shipyard needs to talk to Swarm
and is intended to work on multiple hosts so you cant use a socket. This is
probably why it's not working.

Can you give more info on how you deployed?  By default the deploy script
detects the IP and uses that to configure the setup.

**Comment by little-joe999** [comment]
I just used the standard automated deployment script provided on the shipyard website:

`curl -sSL https://shipyard-project.com/deploy | bash -s`

**Comment by ehazlett** [comment]
If you did not specify an override DNS address and the IP changed you will
need to either re-run the shipyard controller using the manual method (from
the docs) or reinstall.
