### ISSUE TITLE
Containers and images are not displayed when deploying shipyard manual

### ISSUE THREAD

**Issue by AndreeaDora** [shipyard/shipyard#742]
I deployed shipyard manual using the commands from here http://shipyard-project.com/docs/deploy/manual/ , on a Ubuntu Trusty vm. I can access the UI and login but I can not see any containers or images.
When deploying automated I can see the images and the containers also.  
How would I be able to see my containers and images using manual deployment?

**Comment by borzamircea** [comment]
+1

**Comment by ehazlett** [comment]
As long as the swarm agent is running you should see containers.  What are the logs from the Swarm manager and agents?

**Comment by AndreeaDora** [comment]
Logs for the swarm manager:
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
ERRO[0068] Get http://10.0.2.15:2375/v1.15/info: EOF. Are you trying to connect to a TLS-enabled daemon without TLS? 
Logs for the swarm agent:
INFO[0000] Registering on the discovery service every 1m0s...  addr=10.0.2.15:2375 discovery=etcd://10.0.2.15:4001
INFO[0060] Registering on the discovery service every 1m0s...  addr=10.0.2.15:2375 discovery=etcd://10.0.2.15:4001
INFO[0120] Registering on the discovery service every 1m0s...  addr=10.0.2.15:2375 discovery=etcd://10.0.2.15:4001
INFO[0180] Registering on the discovery service every 1m0s...  addr=10.0.2.15:2375 discovery=etcd://10.0.2.15:4001
INFO[0240] Registering on the discovery service every 1m0s...  addr=10.0.2.15:2375 discovery=etcd://10.0.2.15:4001

**Comment by AndreeaDora** [comment]
I manage to solve the issue by adding the -addr $SHIPYARD_IP:$DISCOVERY_PORT -peer-addr $SHIPYARD_IP:$DISCOVERY_PEER_PORT to the discovery and changing the image for proxy to shipyard/docker-proxy:latest.

**Comment by ehazlett** [comment]
Thanks. I'll check the docs and update if needed.

**Comment by ehazlett** [comment]
Thanks @AndreeaDora !  I did a fresh install and it worked fine.  You may have had an old image.  I'm closing but feel free to re-open if you continue to have issues.
