### ISSUE TITLE
Using consul as a discovery service

### ISSUE THREAD

**Issue by borzamircea** [shipyard/shipyard#743]
Hi Evan!

I'm using the manual deployment script to deploy shipyard with `consul` instead of `etcd` as a discovery service. In both cases, after being deployed, neither with `etcd`, nor with `consul` does shipyard display any images or containers. I can access the `consul` UI and see the consul service up and running, but I can't display the swarm manager and agent. When deploying via the `docker-compose.yml`, shipyard does display the images and containers. 

Could you please provide any insights on deploying shipyard using `consul` instead of `etcd` and a way to correctly display the images and containers in the UI.

Thanks!

Here are the modifications I did to the manual deployment script:

```
###DISCOVERY
docker run \
    -ti \
    -d \
    -p 8400:8400 \
    -p 8500:8500 \
    -p 8600:53/udp \
    --restart=always \
    --name shipyard-discovery \
    progrium/consul \
    -server -bootstrap -ui-dir /ui && #-name discovery &&
###PROXY
docker run \
    -ti \
    -d \
    -p 2375:2375 \
    --hostname=$HOSTNAME \
    --restart=always \
    --name shipyard-proxy \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e PORT=2375 \
    --entrypoint=/bin/docker-proxy \ //complains about the embedded "-h" command, had to override that
    ehazlett/docker-proxy:latest &&
###MANAGER
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-manager \
    swarm:latest \
    manage --host tcp://0.0.0.0:3375 consul://192.168.160.129:8500/swarm &&
###AGENT
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-agent \
    swarm:latest \
    join --addr 192.168.160.129:2375 consul://192.168.160.129:8500/swarm
```

**Comment by ehazlett** [comment]
Hmm looks like an error in the docs.  I'll get that updated.  Make sure to use the latest `shipyard/docker-proxy:latest` image.

**Comment by borzamircea** [comment]
Did some changes and managed to use `consul` as a discovery service. Changed to the latest docker proxy image. Now my images and containers are visible.

**Comment by ehazlett** [comment]
The docs have been updated.  Please re-open if you continue to have issues.  Thanks!
