### ISSUE TITLE
ability to deploy container to specific node

### ISSUE THREAD

**Issue by fedya** [shipyard/shipyard#746]
I need to deploy specific containers on specific hosts.

Like:
postgresql-container ---> server5.org
redis-container ---> server17.org

**Comment by tombee** [comment]
Hi @fedya, this should be possible already using swarm constraints:
https://docs.docker.com/swarm/scheduler/filter/

**Comment by fedya** [comment]
Hi @tombee i found it but it is not so obvious and not working as expected, look:
![snapshot6](https://cloud.githubusercontent.com/assets/598477/12988245/dba977a8-d110-11e5-8ba5-a10945b69323.png)

But when i trying to deploy container to specific node i see

![snapshot6](https://cloud.githubusercontent.com/assets/598477/12988275/fe568aa2-d110-11e5-917e-b7ea42799bd6.png)

bongiepc is same host where shipyard webui running.

**Comment by ehazlett** [comment]
@fedya this isn't the hostname it's the node name in Swarm.  View the "Nodes" page to get the node name for the constraint.
