### ISSUE TITLE
User-dependent containers

### ISSUE THREAD

**Issue by port22** [shipyard/shipyard#747]
I just tested shipyard and - holy whale, I'm overwhelmed!  (DockerUI is nice, but ... meh)

What are you thinking of enhancing the functionality to limit users to be able to only manage containers belonging to them?
That would revolutionize Hosting Control Panels (as they're all crap).

**Comment by ehazlett** [comment]
Thanks!  There are currently no plans for this.  Shipyard is meant for a Swarm management UI and defers to how Swarm handles container visibility.  Great suggestion though :)
