### ISSUE TITLE
Unexpected UI errors after restarting shipyard controller container from Shipyard UI itself.

### ISSUE THREAD

**Issue by rqc** [shipyard/shipyard#748]
Hello,

Playing around with Shipyard I decided it would be interesting to restart shipyard's controller container using Shipyard's UI. Here is what happened:

![image](https://cloud.githubusercontent.com/assets/89690/13009362/5a621d1e-d172-11e5-8db4-1d70cf95e533.png)

Still need to take a look at the dev tools console errors, but this seems like an interesting scenario, albeit edge.

**Comment by ehazlett** [comment]
This happens when the UI cannot connect to the backend.  There's not much we can do until it restarts and you reload the page.  We give you enough rope ;)

**Comment by rqc** [comment]
@ehazlett I know! Thanks :wink:
