### ISSUE TITLE
Issue with shipyard-proxy

### ISSUE THREAD

**Issue by mrsanuk** [shipyard/shipyard#752]
Hi, I tryed to use your script for install shipyard on Ubunut 14.04, but have some issues with shipyard-proxy. It can not start work (de35ce9e895c        ehazlett/docker-proxy      "/bin/docker-proxy -h"   8 minutes ago       Restarting (2) About a minute ago   0.0.0.0:2375->2375/tcp                           shipyard-proxy)

log:
INFO[0000] docker proxy                                 
Usage of /bin/docker-proxy:
  -D	enable debug logging
  -cert string
    	path to certificate
  -d string
    	path to the Docker socket (default "/var/run/docker.sock")
  -i	allow insecure communication
  -key string
    	path to certificate key
  -l string
    	listen address (default ":2375")

docker --version
Docker version 1.10.1, build 9e83765

I tryed to replace ehazlett/docker-proxy:lastest to ehazlett/docker-proxy, but it did not help 
Can you help me?

**Comment by abipit** [comment]
Hi, same problem for me.

**Comment by Gielert** [comment]
+1

**Comment by ehazlett** [comment]
There was an update to the deploy script.  That is using the old image.
Please try the install again.

**Comment by abipit** [comment]
Sorry but still the problem.

=> faa75abb4281        ehazlett/docker-proxy:latest       "/bin/docker-proxy -h"   59 seconds ago       Restarting (2) 6 seconds ago   0.0.0.0:2375->2375/tcp     shipyard-proxy

**Comment by AThilenius** [comment]
+1
Ubuntu 14.04 (AWS EC2 Instance):
```
root@ip-172-31-30-146:~# docker logs shipyard-proxy
INFO[0000] docker proxy
Usage of /bin/docker-proxy:
  -D	enable debug logging
  -cert string
    	path to certificate
  -d string
    	path to the Docker socket (default "/var/run/docker.sock")
  -i	allow insecure communication
  -key string
    	path to certificate key
  -l string
    	listen address (default ":2375")
INFO[0000] docker proxy
Usage of /bin/docker-proxy:
  -D	enable debug logging
  -cert string
    	path to certificate
...
```

**Comment by Gielert** [comment]
it worked for me guys.

**Comment by AThilenius** [comment]
Perhaps I installed something wrong. Do you need to have a docker swarm set up before running the automated install? I have docker up and running (I can launch containers no problem) but never set up a swarm. I looks like the install script does that for you? The only other thing on the system is nginx (bound to P80 and P443). Apart from that it's a clean Ubuntu 14.04 (or as clean as the EC2 builds come).

We also have the fact that we are both running on EC2 instances in common. It's possible there is an issue there?

**Comment by dbeaugrand** [comment]
i'm seeing similar issue with the docker proxy and i'm on local hardware that's running debian (jesse) as the base OS

**Comment by AThilenius** [comment]
I just tried it on Amazon's Linux build as well. Exact same thing.

**Comment by dbeaugrand** [comment]
I noticed that ehazlett mentioned that there was an update to the deploy script. So i looked at the curl results and noticed that the script being download still contains the ehazlett/docker-proxy:latest instead of the shipyard/docker-proxy:latest. Which github link should it be using?

**Comment by dbeaugrand** [comment]
It looks like the problem I was having was due to the ehazlett/docker-proxy being used instead of shipyard/docker-proxy. I manually changed the deploy file and reinstalled, it now is working fine. But that means there is a bug in the version that is downloaded from the documentation at this link http://shipyard-project.com/docs/deploy/automated/

**Comment by mrsanuk** [comment]
dbeaugrand Could you show us your new deploy file? or what you changed?

**Comment by dbeaugrand** [comment]
It was a simple fix i just took what ehazlett had in his repo as the change see comment << BELOW <<

start_proxy() {
    TLS_OPTS=""
    if [ $ENABLE_TLS = 1 ]; then
        TLS_OPTS="-e SSL_CA=$SSL_CA_CERT -e SSL_CERT=$SSL_CERT -e SSL_KEY=$SSL_KEY -e SSL_SKIP_VERIFY=1"
    fi
    # Note: we add SSL_SKIP_VERIFY=1 to skip verification of the client
    # certificate in the proxy image.  this will pass it to swarm that
    # does verify.  this helps with performance and avoids certificate issues
    # when running through the proxy.  ultimately if the cert is invalid
    # swarm will fail to return.
    ID=$(docker run \
        -ti \
        -d \
        -p $PROXY_PORT:$PROXY_PORT \
        --hostname=$HOSTNAME \
        --restart=always \
        --name $PREFIX-proxy \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -e PORT=$PROXY_PORT \
        --volumes-from=$PREFIX-certs $TLS_OPTS\
        ehazlett/docker-proxy:latest) **<< THIS LINE APPEARS TO BE WRONG/ I changed it to shipyard/docker-proxy:latest <<**
}


Hope this helps

**Comment by ehazlett** [comment]
If you manually downloaded the script you will have to update it manually.
Otherwise, just curl http://shipyard-project.com/deploy as the docs explain
-- this has the updated image name.

**Comment by abipit** [comment]
It's ok for me with the change ehazlett/docker-proxy:latest => shipyard/docker-proxy:latest in tge deploy script. Thanks

**Comment by kwiky** [comment]
http://shipyard-project.com/deploy not updated for me
it always have ehazlett/docker-proxy
