### ISSUE TITLE
No healthy node available in the cluster

### ISSUE THREAD

**Issue by dbeaugrand** [shipyard/shipyard#753]
I'm not sure if this is a bug or incorrect install on my part. I installed shipyard using the automated scripts and the default values. I have a machine running as the shipyard management server and three running as nodes. Installs went smooth (no errors) and the shipyard site shows the three nodes. The name fields shows "(unknown)" for some reason. But when i try to deploy a container (like hello-world) i get an error message that "No healthy node available in the cluster". Any idea what i might have done wrong?

**Comment by Gielert** [comment]
See #752. Its related I think.

**Comment by dbeaugrand** [comment]
yep this looks like what i'm seeing too ... i'll close this issue and follow the other
