### ISSUE TITLE
Added node is unhealthy

### ISSUE THREAD

**Issue by valentin2105** [shipyard/shipyard#754]
Hi,

Thanks for Shipyard, it work great !

I'm trying to add a node using the deploy script, no problem, my node is detected in "Nodes" section.

My problem is than my node seem unhealthy :

![selection_001](https://cloud.githubusercontent.com/assets/12403145/13065301/2973efee-d4af-11e5-9b20-8b0ce83f5eae.png)

I have also trying to add a node with  `docker run -d swarm join --addr=192.168.42.29:2375 etcd://192.168.42.32:4001/` 

It's work but the node is also unhealthy.

Here my /etc/default/docker
`DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"`

Any idea ?

**Comment by mrsanuk** [comment]
Hi, I have a similar problem

**Comment by myownsoul** [comment]
Hello,I have the same problem. 
Could you help to give any advice?
