### ISSUE TITLE
Install on coreos issues (solved)

### ISSUE THREAD

**Issue by RVN-BR** [shipyard/shipyard#755]
Summary: I was unable to get automatic install to work on a CoreOS cluster.  I adjusted the manual instructions in order to get the UI and one node working.  I still havent gotten other nodes to join successfully. (EDIT: I did manage to get the nodes to connect... this is a write-up step by step of the entire process)

I have come across a series of issues trying out shipyard on a coreos cluster.  

I deployed a 3 node cluster using vagrant (as per the instructions on https://coreos.com/blog/coreos-clustering-with-vagrant/).

I tried running an automated install, but that doesnt work... Presumably because etcd is already running in coreos (?) and shipyard errors out with a port conflict... (notice its not a proxy port conflict, which I could get by theoretically using PROXY_PORT=)

```
docker: Error response from daemon: failed to create endpoint shipyard-discovery on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:7001: bind: address already in use.
```

Off to manual install ;)

I initially tried using the ports and etcd configuration that was included in the manual install steps (minus discovery container itself) but then realized the ports were amiss, so here are the steps I had to use:
- Install rethink:

```
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-rethinkdb \
    rethinkdb
```

(no change)
- Skip discovery, I already have etcd on coreos, I'll use that...
- On a whim I decided to skip the proxy (although I'm not sure this isnt causing problems)
- Run swarm manager

```
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-manager \
    swarm:latest \
    manage --host tcp://0.0.0.0:3375 etcd://<IP-OF-HOST>:2379
```

(notice the ip:port of the final command was changed to the coreos etcd port - from 4001 -> 2379)
- Run swarm agent

```
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-agent \
    swarm:latest \
    join --addr <ip-of-host>:2375 etcd://<ip-of-host>:2379
```

(notice the ip:port of the final command was changed to the coreos etcd port - from 4001 -> 2379)
- Run controller

```
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-controller \
    --link shipyard-rethinkdb:rethinkdb \
    --link shipyard-swarm-manager:swarm \
    -p 8080:8080 \
    shipyard/shipyard:latest \
    server \
    -d tcp://swarm:3375
```

(no change from instructions)

I am now able to access the UI on port 8080 of the host's public ip from my computer.

I was able to launch a container successfully!

I had been unable to add another node however... as there was a conflict with the proxy port, and I assumed it may be a duplication of the docker socket...

I tried adding the node "automatically":

```
core@core-02 ~ $ curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://172.17.8.101:2379 bash -s
Adding Node
 -> Starting Cert Volume
 -> Starting Proxy
Error response from daemon: Cannot start container 1cf5493d3e96e133989b7ee6f728725a97e65b73a63a844eff24b57025801d5e: failed to create endpoint shipyard-proxy on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:2375: bind: address already in use
```

(I tried another proxy_port which also didnt work, and then I tried "skipping" the proxy altogether by just launching the swarm agent)

I finally had success running only the agent

```
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-agent \
    swarm:latest \
    join --addr <ip-of-current-node>:2375 etcd://<ip-of-etcd>:2379
```

Initially I used the same IP I had for the controller host in both places, which didnt work, I then realized I should add the current-node IP, and the etcd ip (which on a coreos cluster can be the same, as etcd itself is clustered)...  Remembering I changed the etcd port to match the coreos etcd port.

After a little while (ok, more than I had set out for initially), it seems the cluster is all swarmed up and shipyard is good to go ;)

![image](https://cloud.githubusercontent.com/assets/1218902/13127549/0d8126e0-d5b7-11e5-9eed-d5da8c51dfbd.png)

I hope someone may benefit and not have to go through the guessing that I did...  I'm anxious for shipyard as well as rancher as we evaluate container orchestration options... (I think I will have to holdoff on heavy testing tho as we need compose support so I'll track that on #591)

**Comment by jdoose** [comment]
Thanks for your help! With your post I was able to use shipyard on a CoreOS system.
I used the deploy-Script available at https://shipyard-project.com/deploy (see https://shipyard-project.com/docs/deploy/automated/) and modified it slightly to skip the start of Discovery and Proxy
I modified the lines
```
    echo " -> Starting Discovery"
    start_discovery
    echo " -> Starting Cert Volume"
    start_certs
    echo " -> Starting Proxy"
    start_proxy
```
to
```
    # echo " -> Starting Discovery"
    # start_discovery
    echo " ! Skipping Discovery for CoreOS"
    echo " -> Starting Cert Volume"
    start_certs
    # echo " -> Starting Proxy"
    # start_proxy
    echo " ! Skipping Proxy for CoreOS"
```
Download complete file, rename to .sh: [deploy.sh.txt](https://github.com/shipyard/shipyard/files/361514/deploy.sh.txt) (Please note, that I only modified the "deploy" section, which worked for me. Maybe you have to modify more for your needs)

After that it can be used like this:
`$ ACTION=deploy PORT=5003 DISCOVERY=etcd://coreoshostname:4001 ./deploy.sh`
