### ISSUE TITLE
attach container is filed，such  as [18/Feb/2016 09:45:10] "GET /console/c34e64e638f193880af418c9008bb775/?logs=1&stderr=1&stdout=1&stream=1&stdin=1 HTTP/1.1" 404 2983

### ISSUE THREAD

**Issue by zwqzhangweiqiang** [shipyard/shipyard#756]

**Comment by marsmensch** [comment]
Tested with latest images and auto-deployment setup today and was not able to replicate. Host system was RHEL 7.2 with upstream Docker Engine latest (1.10.3-1.el7.centos.x86_64.rpm) packages. /cc @ehazlett
