### ISSUE TITLE
ehazlett/docker-proxy:latest breaks deploy on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by kareiva** [shipyard/shipyard#759]
**How to reproduce:**

* Install vanilla Ubuntu 14.04.3
* Install docker (https://docs.docker.com/engine/installation/linux/ubuntulinux/)
* Use https://shipyard-project.com/deploy

The container from image `ehazlett/docker-proxy:latest` fails while displaying usage options for docker-proxy.

**How to remediate:**

* Kill the docker-proxy container in question
* `docker rmi ehazlett/docker-proxy`
* `docker pull shipyard/docker-proxy` from https://hub.docker.com/r/shipyard/docker-proxy/
* Start manually with: 

```
    docker run \
        -ti -d -p 2375:2375 \
        --hostname=$HOSTNAME \
        --restart=always 
        --name shipyard-proxy \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -e PORT=2375 --volumes-from=$PREFIX-certs $TLS_OPTS\
        shipyard/docker-proxy:latest
```
Works fine from here.

**Comment by ehazlett** [comment]
Yes this was an issue and the docs have been updated to use the new image.
Thanks!

**Comment by kareiva** [comment]
Appreciate your swift reply! 

But the [deploy](https://shipyard-project.com/deploy) script hasn't been updated yet? 

```
# curl -s https://shipyard-project.com/deploy | grep docker-proxy
        ehazlett/docker-proxy:latest)
```

**Comment by ehazlett** [comment]
Hmm yes it should be. Looks like an old container is serving requests.
I'll check. Thanks for the heads up!

**Comment by benariamir** [comment]
Same here on CoreOS 766.5.0

Manually changed the deploy script to pull shipyard/docker-proxy and it worked.

**Comment by kareiva** [comment]
Seems to be fixed now. Will retest deployment and close.
