### ISSUE TITLE
deploy "stable" version

### ISSUE THREAD

**Issue by benariamir** [shipyard/shipyard#763]
Hi Guys,

We've been working for a few weeks on a docker pool service which works with Shipyard.
During that time at least one of the containers has been updated and the Docker Remote API has been updated from v1.21 to v1.22 which broke our service.

I already had a production ready cluster of two instances (one master, one node). When I added the third node it crashed my cluster and service because one of the container failed to work:
https://github.com/shipyard/shipyard/issues/759

Had to wait for 3 days for the automated deployment script to be updated.

We can't have our production cluster be so unstable. What we currently did was to have our own copy of the deployment script and changed all the docker images not to use the :latest tag but with the latest version numbers, so we won't be surprised by these changes.

I wish the automated deployment script would have had the option to deploy a "stable" version with a version number v.s. "latest" version.

**Comment by mbentley** [comment]
That could be updated as the source is available [here](https://github.com/shipyard/shipyard-project.com/blob/master/site/themes/shipyard/static/deploy) if you're willing to submit a PR for it.

**Comment by benariamir** [comment]
@mbentley true that, but there is no shipyard "version" as shipyard consists of 6 independent components/containers: 3 are 3rd parties, one is of Swarm project and another one is shipyard's.

**Comment by ehazlett** [comment]
Good point.  We should "pin" the versions of the upstreams.

**Comment by marsmensch** [comment]
+1 for the version pinning. Also see #765
