### ISSUE TITLE
Shipyard with Consul

### ISSUE THREAD

**Issue by mavencode01** [shipyard/shipyard#764]
Is there a way I can use my existing consul instead of the default etcd in shipyard ?

We prefer consul over etcd and don't want to maintain both.

Thanks,

**Comment by peceka** [comment]
Hi @mavencode01 

yes there is. If you have running consul just run swarm with it and then start shipyard-controller pointing to swarm manager port. in my env. i have on all docker servers:

```docker run -d -p 4000:4000 --restart=always --name swarm_manage_d3 swarm manage -H :4000 --replication --advertise PRIVATE_IP:4000  consul://CONSUL_IP:8500/docker```

```docker run -d --restart=always --name swarm_join_d3 swarm join --advertise=PRIVATE_IP:2375 consul://CONSUL_IP:8500/docker```

and then i've started shipyard-controller with such command:

```docker run -dti --restart=always  --name shipyard-controller --link rethinkdb:rethinkdb  --link swarm_manage_d3:swarm  -p 80:8080   shipyard/shipyard:latest  server  -d tcp://swarm:2375```

**Comment by mavencode01** [comment]
@pecka, thanks....can this be included in the deploy script as an option.

**Comment by ehazlett** [comment]
Thanks @peceka!

You can use any service discovery you want with the manual deploy.  It probably won't make it into the deploy script as there are many permutations and options for the various discovery mechanisms.
