### ISSUE TITLE
Add version number to shipyard

### ISSUE THREAD

**Issue by mavencode01** [shipyard/shipyard#765]
Can we add a version number to shipyard to tag the release users are running.
I think this will be helpful for users to report bugs for a specific version.

I ran into the issue where I don't know if my version is the latest from the version
my colleague is running.

The alternative is to shutdown pull the latest container which I really don't want to do
except I know there is a newer version out there.

**Comment by ehazlett** [comment]
It's in the logs. The first few lines should report the version.

**Comment by mavencode01** [comment]
Yes, but this is good to show in the UI.

**Comment by marsmensch** [comment]
It should be relatively easy to display the version (docker image tag? git revision?) in the footer or top menu of the server in the web gui as soon as #763 is implemented.

This should help troubleshooting issues here, too.
