### ISSUE TITLE
Can't exec into a container

### ISSUE THREAD

**Issue by mavencode01** [shipyard/shipyard#766]
I can't exec into any container after pulling the latest shipyard.

![capture-shipyard](https://cloud.githubusercontent.com/assets/542912/13303405/396aacf2-db1d-11e5-8428-fe568847624f.PNG)

**Comment by Tochirou** [comment]
same here.
had to use `docker exec` instead...

**Comment by tombee** [comment]
This should be fixed in master, https://github.com/shipyard/shipyard/pull/760.
