### ISSUE TITLE
ACTION=node in deploy shell script is broken

### ISSUE THREAD

**Issue by blackdoginet** [shipyard/shipyard#768]
If I try to run this script after Shipyard has been deployed I get errors
` -> Starting Cert Volume
docker: Error response from daemon: Conflict. The name "/shipyard-certs" is already in use by container `
If I remove shipyard and try fresh deploy using ACTION=node only the containers in the ACTION=node sub routine get installed

**Comment by ehazlett** [comment]
Are you trying to run this on the same instance of an existing shipyard?
This must be ran on a separate instance.

**Comment by marsmensch** [comment]
I guess you guessed correctly @ehazlett ;-) Maybe it is a good time for a FAQ with frequent issues for new users?

**Comment by blackdoginet** [comment]
Yes that's correct

**Comment by ehazlett** [comment]
@marsmensch :)

@blackdoginet thx for the update!
