### ISSUE TITLE
Getting started is unclear

### ISSUE THREAD

**Issue by matanster** [shipyard/shipyard#769]
Running [automated installation](https://shipyard-project.com/docs/deploy/automated/) the script seems to just hang

```
Status: Downloaded newer image for shipyard/shipyard:latest
Waiting for Shipyard on my-ip:8080
............................................................................................................................................
```

Whereas accessing the UI on localhost:8080 presents an unsurpassable login window. It is really unclear how to get started this way....

**Comment by ehazlett** [comment]
What is your host OS and did you pass any options to the install?

**Comment by alifiratari** [comment]
Centos 7.2 i have the problem

**Comment by kmartin26** [comment]
Try to login with admin:shipyard ?

**Comment by ehazlett** [comment]
If you are in RedHat like distros the firewall does not play nice and causes this issue. Try opening port 8080 and see if you can access.

**Comment by simonsmiley** [comment]
I had to restart all containers for login to work
