### ISSUE TITLE
LDAP auth won't search subtrees

### ISSUE THREAD

**Issue by j-beeler** [shipyard/shipyard#770]
I'm experiencing an issue that would prevent me from being able to use LDAP auth on shipyard in a large enterprise.  The code is not structuring the LDAP queries such that the domain subtree is being searched which means that users in subtree cannot not log in.

Example:
- There exists an account "CN=bob,OU=Atlanta,OU=Offices,DC=company,DC=com"
- Set shipyard ldap-base-dn to "DC=company,DC=com". 
- When attempting to log in the following error is displayed: "LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\x00""
- Change the ldap-base-dn value to "OU=Atlanta,OU=Offices,DC=company,DC=com".
- Login is successful.

**Comment by innanill** [comment]
+1

**Comment by mohamedfarag** [comment]
+1

**Comment by mgardnercc** [comment]
+1

**Comment by puppetmaster** [comment]
+1

**Comment by ajodock** [comment]
I was able to get around this with Active Directory before the Shipyard 3.1 release but 8edbeac7637d64fe59194a2adcc28f8ed043c339 broke it.

Pre 3.1 the LDAP logic by default would bind on essentially cn=${username},${ldap-base-dn}  But there was an undocumented option to put the string "{username}" in your ldap-base-dn in which case it would not prepend the cn= and just bind with the ldap-base-dn.

In active directory there are two ways that you can bind.  Either with a full DN or else with username@REALM.COM  This meant that you could use "{username}@REALM.COM" as your ldap-base-dn and then any user that can bind to LDAP would be able to login (provided that you had created their account or enabled the auto create account setting).

Ideally Shipyard should have three more options.  ldap-bind-dn, ldap-bind-password, and ldap-search-filter.    That way the bind is done with the service account and we could provide an ldap query that returns the DN of the user wherever it exists in the search tree.  In this case ldap-base-dn shouldn't have anything to do with generating the user's DN it should just be the base of the search.
