### ISSUE TITLE
Unable to pull from private dockerhub repository

### ISSUE THREAD

**Issue by pgporada** [shipyard/shipyard#771]
I've configured my /root/.docker/config.json across my swarm cluster and can successfully manually pull containers from my repository. However, when I use the Shipyard GUI, I receive the following
```
Error: image COMPANY/MYCONTAINER not found 
```

I've successfully added https://hub.docker.com to the registry pane. http://i.imgur.com/4G7IiO3.png

When I click the magnifying glass/info button on that registry, I receive an error as well. http://i.imgur.com/Fu7bBCn.png

I am using the latest, as of today, shipyard.

**Comment by pgporada** [comment]
I think my problem is that Swarm pulls the containers and not the underlying docker hosts. I ran a docker login against the swarm manager container and have been able to pull containers out of docker hub from the CLI so far.

As for the private docker hub repository, I believe the actual url is 
```
https://index.docker.io
```

**Comment by ehazlett** [comment]
Yes as @pgporada said you need to `docker login` on the Swarm managers.

**Comment by ehazlett** [comment]
Ah sorry I didn't see you opened the issue ;)  Doing a `docker login` on all Swarm managers should work.
