### ISSUE TITLE
Issue with cluster

### ISSUE THREAD

**Issue by mrsanuk** [shipyard/shipyard#772]
Hi, everybody
I have 2 hosts, at the first I have installed shipyard  with this script:
curl -sSL https://shipyard-project.com/deploy | bash -s

at the second with this:
curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://"ip of my first node":4001 bash -s

and now i have 2 nodes in the web interface

But when i do this command "sudo docker -H tcp://0.0.0.0:2375 info", I don not see any information about cluster

sudo docker -H tcp://0.0.0.0:2375 info
Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: nod1
ID: WLN6:D5KJ:K5C5:YR4Z:CGLK:4MAI:RH6X:YQZ5:5QIY:KCQ3:2FEZ:NXV4
WARNING: No swap limit support

What a did wrong?
Can I manage all my nodes from one master?
And in future I want to use docker multi network between nodes. Is this possible with shipyard?

**Comment by pgporada** [comment]
@mrsanuk 
Port 2375 is the docker proxy port for the hosts themselves. What you want to do is actually hit the swarm manager port.

From that deploy script, you'll need to hit port 3376
```
SWARM_PORT=3376
```

This will show you what you want.
```
docker -H :3376 info
```

**Comment by mrsanuk** [comment]
@pgporada 
docker -H tcp://0.0.0.0:3376 info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

and i don't see 3376 port

shipyard/shipyard:latest        0.0.0.0:8080->8080/tcp                           shipyard-controller
swarm:latest                                   2375/tcp                                         shipyard-swarm-agent
swarm:latest                                   2375/tcp                                         shipyard-swarm-manager
shipyard/docker-proxy          0.0.0.0:2375->2375/tcp                           shipyard-proxy
alpine                                                                                                    shipyard-certs
microbox/etcd:latest  0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
rethinkdb                           8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkdb

**Comment by ehazlett** [comment]
By default the Swarm port is 3375.  Try it as `docker -H tcp://<host>:3375 ps`

**Comment by mrsanuk** [comment]
$docker -H tcp://localhost:3375 ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

when i added this "-H tcp://0.0.0.0:3375 -H unix:///var/run/docker.sock" I had this:
:~# docker -H tcp://localhost:3375 ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
3206c3ad1d70        shipyard/shipyard:latest       "/bin/controller --de"   42 minutes ago      Up About a minute   0.0.0.0:8080->8080/tcp                           shipyard-controller
265e1362e8df        swarm:latest                   "/swarm j --addr 192."   43 minutes ago      Up About a minute   2375/tcp                                         shipyard-swarm-agent
191a446015e5        swarm:latest                   "/swarm m --replicati"   43 minutes ago      Up About a minute   2375/tcp                                         shipyard-swarm-manager
0e91be97452b        shipyard/docker-proxy:latest   "/usr/local/bin/run"     43 minutes ago      Up About a minute   0.0.0.0:2375->2375/tcp                           shipyard-proxy
8394bd43b4ca        alpine                         "sh"                     43 minutes ago      Up About a minute                                                    shipyard-certs
d2fa21a7775e        microbox/etcd:latest           "/bin/etcd -addr 192."   43 minutes ago      Up About a minute   0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
a608bbd48a6d        rethinkdb                      "rethinkdb --bind all"   43 minutes ago      Up About a minute   8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkd


~# docker -H tcp://localhost:3375 info
Containers: 12
 Running: 7
 Paused: 0
 Stopped: 5
Images: 13
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 126
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: nod1
ID: WLN6:D5KJ:K5C5:YR4Z:CGLK:4MAI:RH6X:YQZ5:5QIY:KCQ3:2FEZ:NXV4
WARNING: No swap limit support



I don't understand how manage cluster from console(for example: I give command to run the container and cluster manager have to decide on  which node start it)
Should I write down something in /etc/default/docker?

**Comment by el-liberator** [comment]
HI 
Use this implementation , it's works fine 
[http://darrellbreeden.kinja.com/building-docker-the-scale-of-enterprise-1751723343]

**Comment by marsmensch** [comment]
I don't think there is an issue here @ehazlett. Worked for me multiple times with the exact commands with a multiple members cluster. Red Hat 7.2 with latest Docker Upstream Packages installed.

**Comment by ehazlett** [comment]
@marsmensch thanks!  i'm not able to reproduce either.

**Comment by Tochirou** [comment]
I also had this problem on RHEL 7.
My workaround was to specify the swarm manager container's ip: 

docker -H <ip_swarm_manager>:3375 info
