### ISSUE TITLE
Issue Shipyard GUI

### ISSUE THREAD

**Issue by el-liberator** [shipyard/shipyard#773]
Hi 

When a container is started with a hostname and a domain.
 On the "Containers Page" ,  "Actions/Scale", the new container will be created with a hostname equal to the id of the new container and not the hostname of the original container.

-Centos 7.2
-Docker 1.10.2
-Swarm:latest
-Shipyard:latest
-Interlock:latest

**Comment by ehazlett** [comment]
This is known.  If you want to scale, make sure to not set a hostname as Shipyard needs to copy the container config and if that contains a specified hostname Docker will not duplicate.
