### ISSUE TITLE
shipyard containers  show error

### ISSUE THREAD

**Issue by Chenpipi** [shipyard/shipyard#775]
Hi,
Global Environment: 
           centos 6 + kernel 3.10.97-1.el6.elrepo.x86_64
           docker version:
            Client version: 1.7.1
            Client API version: 1.19
            Go version (client): go1.4.2
            Git commit (client): 786b29d/1.7.1
            OS/Arch (client): linux/amd64
            Server version: 1.7.1
            Server API version: 1.19
            Go version (server): go1.4.2
            Git commit (server): 786b29d/1.7.1
            OS/Arch (server): linux/amd64
I am use registry:2 + nginx-proxy https, private registry pull and push is ok.
I refer to documents operation,
as follow:
docker run -ti -d --restart=always -v /data/registry/rethinkdb-data:/data --name shipyard-rethinkdb rethinkdb
docker run -ti -d -p 4001:4001 -p 7001:7001 --restart=always --name shipyard-discovery microbox/etcd -name discovery
docker run -ti -d -p 2375:2375 --hostname=$HOSTNAME --restart=always --name shipyard-proxy -v /var/run/docker.sock:/var/run/docker.sock -e PORT=2375 shipyard/docker-proxy
docker run -ti -d --restart=always --name shipyard-swarm-manager swarm manage --host tcp://0.0.0.0:3375 etcd://{IP}:4001
docker run -ti -d --restart=always -l docker.bestv.com --name shipyard-swarm-agent swarm join --addr {IP}:2375 etcd://{IP}:4001
docker run -ti -d --restart=always --name shipyard-controller --link shipyard-rethinkdb:rethinkdb --link shipyard-swarm-manager:swarm -p 8080:8080 shipyard/shipyard server -d tcp://{IP}:3375

The following problems:
shipyard server logs:
INFO[0000] shipyard version 3.0.2
INFO[0000] checking database
INFO[0026] created admin user: username: admin password: shipyard
INFO[0026] controller listening on :8080
WARN[0032] unauthorized request for /containers/json from {my IP}:34345
WARN[0042] unauthorized request for /containers/json from {my IP}:34345
WARN[0046] unauthorized request for /containers/json from {my IP}:34345
WARN[0055] unauthorized request for /containers/json from {my IP}:34345

****shipyard dashboard show:
 {"data":"Bad Gateway","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$sh38RnkTE5Nd69s1n3s8iebLad7mM4AUXqsw1OQSziNwZHLiQKXIe"}},"statusText":"Bad Gateway"}**
**
Other programs log is ok,such as:
swarm-agent:
INFO[0000] Initializing discovery without TLS
INFO[0000] Registering on the discovery service every 1m0s...  addr={{IP}}:2375 discovery=etcd://{{IP}}:4001
INFO[0060] Registering on the discovery service every 1m0s...  addr={{IP}}:2375 discovery=etcd://{{IP}}:4001
INFO[0120] Registering on the discovery service every 1m0s...  addr={{IP}}:2375 discovery=etcd://{{IP}}:4001

swarm-manager:
INFO[0000] Initializing discovery without TLS
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0001] Registered Engine docker.bestv.com at {{IP}}:2375

docker logs -f shipyard-proxy
Listening on 2375

docker logs -f shipyard-discovery
[etcd] Mar  7 13:35:03.565 WARNING   | Using the directory discovery.etcd as the etcd curation directory because a directory was not specified.
[etcd] Mar  7 13:35:03.567 INFO      | discovery is starting a new cluster
[etcd] Mar  7 13:35:03.571 INFO      | etcd server [name discovery, listen on :4001, advertised url http://127.0.0.1:4001]
[etcd] Mar  7 13:35:03.572 INFO      | peer server [name discovery, listen on :7001, advertised url http://127.0.0.1:7001]
[etcd] Mar  7 13:35:03.572 INFO      | discovery starting in peer mode
[etcd] Mar  7 13:35:03.572 INFO      | discovery: state changed from 'initialized' to 'follower'.
[etcd] Mar  7 13:35:03.572 INFO      | discovery: state changed from 'follower' to 'leader'.
[etcd] Mar  7 13:35:03.572 INFO      | discovery: leader changed from '' to 'discovery'.

docker logs -f shipyard-rethinkdb
Recursively removing directory /data/rethinkdb_data/tmp
Initializing directory /data/rethinkdb_data
Running rethinkdb 2.2.5~0jessie (GCC 4.9.2)...
Running on Linux 3.10.97-1.el6.elrepo.x86_64 x86_64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 172.17.0.2, ::1, fe80::42:acff:fe11:2%395
Server ready, "2a866f45b1c0_ro7" 350d6e59-77c7-4b95-b9b5-dd9038d2bf3c

anyone know how to solve it?

Regards

**Comment by ggtools** [comment]
I saw that you closed the issue, did you find a way to solve it?

**Comment by ggtools** [comment]
Duplicate of #576
