### ISSUE TITLE
can't see logs in the action of logs 

### ISSUE THREAD

**Issue by du2016** [shipyard/shipyard#776]
when i start a docker container,i can see logs in the  action of logs ,but a feel seconds later,all logs lose ,it only display the container id,i execute command docker logs  can see logs,who can tell me why,
![image](https://cloud.githubusercontent.com/assets/12290300/13667735/e3b120ac-e6f2-11e5-97ab-d58e807e3acb.png)

**Comment by Chenpipi** [comment]
Can you tell me what is your installed version? Refer to the official documentation to install?

**Comment by Rohlik** [comment]
I can reproduce this bug too.
But only sometimes and for different containers.
No logs aren't displayed in Shipyard, but in CLI (docker logs XXXXXX) are.
Using shipyard version 3.0.2 (8e84bed).

**Comment by 245347881** [comment]
i am use hipyard version 3.0.2 too
