### ISSUE TITLE
Can't run console commands on containers

### ISSUE THREAD

**Issue by petems** [shipyard/shipyard#778]
I've followed the steps on https://shipyard-project.com/docs/deploy/manual/

Everything seems to work ok, but when I try to do an exec the terminal window is pure black, unable to run anything:
<img width="1322" alt="screenshot 2016-03-13 21 51 58" src="https://cloud.githubusercontent.com/assets/1064715/13731969/47c3a588-e96e-11e5-8fc2-4f552a6c55b7.png">

No errors coming up in the console either

**Comment by nfoonf** [comment]
+1

i suspect, the problem correlates with the update to Docker. Shipyard has several compatibility issues regarding actual Docker, Docker Registry and Docker Swarm Releases

**Comment by ffrouin** [comment]
+1

Linux 3.16.0-62-generic
Docker version 1.10.2, build c3959b1

**Comment by petems** [comment]
Yep, just downgraded and it started working again! :fearful: 

```
yum downgrade docker-engine-1.9.1-1.el7.centos
```

<img width="1369" alt="screenshot 2016-03-14 11 07 23" src="https://cloud.githubusercontent.com/assets/1064715/13742648/f353bc56-e9d4-11e5-9745-e08e81fc3c01.png">

**Comment by petems** [comment]
Looks like it's fixed in master:

https://github.com/shipyard/shipyard/pull/760

Same issue: https://github.com/shipyard/shipyard/issues/766

**Comment by ehazlett** [comment]
This has been fixed and released.  Please make sure to pull the latest `shipyard/shipyard:latest` to get the update.
