### ISSUE TITLE
shipyard must be to turn off iptables to display container

### ISSUE THREAD

**Issue by Chenpipi** [shipyard/shipyard#779]
ENV
centos7 / docker 1.10.2 / kernel 3.10.0-327.10.1 / shipyard version 3.0.2 / iptables v1.4.21

On centos 7, I have to empty the iptables rules shipyard deploy script generated to properly display container and other content on the web ui, otherwise they can not display some container and images,and can not pull images. It was my mistake or shipyard bug?

I've followed the steps on https://shipyard-project.com/docs/deploy/automated/
add node to swarm cluster,But does not recognize,as follows：
![12](https://cloud.githubusercontent.com/assets/9670781/13739904/d0455ac4-ea08-11e5-9263-ff58c34af099.png)

**Comment by ehazlett** [comment]
This looks like a conflict with firewalld.  Try disabling firewalld and see if that helps.

**Comment by Chenpipi** [comment]
Thank you,but i disabling firewalld,The problem persists。
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
![1](https://cloud.githubusercontent.com/assets/9670781/13765188/ba06e8d4-ea91-11e5-830d-ee0119ec03fe.png)
![2](https://cloud.githubusercontent.com/assets/9670781/13765189/ba0bbbca-ea91-11e5-9989-ef3e5b9c2546.png)
![3](https://cloud.githubusercontent.com/assets/9670781/13765190/ba1e1f68-ea91-11e5-9459-9c502609fdfb.png)
![4](https://cloud.githubusercontent.com/assets/9670781/13765191/baa8309a-ea91-11e5-8687-e003e30c07a2.png)
![5](https://cloud.githubusercontent.com/assets/9670781/13765192/babf70ca-ea91-11e5-89cf-93a706dab15d.png)

Everyone,Is only do I have this problem?

**Comment by gcavalcante8808** [comment]
+1

**Comment by Chenpipi** [comment]
I know what the problem is, Need to open a separate release ports. Otherwise, the request can not come in。
![image](https://cloud.githubusercontent.com/assets/9670781/13869134/3208e388-ed0c-11e5-918d-3dd81690c0a9.png)

**Comment by yanhuixie** [comment]
@Chenpipi Same problem to me, and your solution save my time. Thank you and all you guys. :-)
