### ISSUE TITLE
Does shipyard support overlay mode

### ISSUE THREAD

**Issue by keyboardfann** [shipyard/shipyard#781]
Dear Sir,
    From Shipyard Web UI Network Mode, I only see Bridge, Host and None. But if we run swarm cluster there are containers on different hosts and always need to connect each other. Docker 1.9 support overlay network mode to solve multi host containers connection problem . Does shipyard support overlay mode or have any way to handle it ?

**Comment by wido-gg** [comment]
+1 to this

Having shipyard natively work with swarm and not support overlay is odd at this point

**Comment by gontro** [comment]
+1

This is probably the last thing stopping me from doing my container deployments through shipyard as opposed to the docker cli.  Once this is in place shipyard will be able to handle nearly all my orchestration needs.

**Comment by innovak** [comment]
Is there any news about overlay ?

**Comment by marioluan** [comment]
Any news regarding this issue?

**Comment by ehazlett** [comment]
Nothing more than the work being done in the branch.  Help is welcome!
