### ISSUE TITLE
Scale ignores "Automatically expose all ports"?

### ISSUE THREAD

**Issue by ThomasEg** [shipyard/shipyard#784]
Hi,

When scaling a container, shipyard does not take e.g. "Expose all ports" into account. This Is this inherited and/or intended behavior or is it a bug?

(testet in version 3.0.3)

**Comment by Chenpipi** [comment]
+1

**Comment by nfoonf** [comment]
the problem lies in the use of the Swarm-API. If you send hostconfig via the 'start' command, this is deprecated and broken atm.
You can build your own container based on the master bramch, which fixes this issue.

**Comment by cabrinoob** [comment]
+1
