### ISSUE TITLE
Unable to update the docker node ip after host IP has changed

### ISSUE THREAD

**Issue by tirithen** [shipyard/shipyard#786]
I installed shipyard (with the install script that puts up various docker containers) on a machine and everything worked fine. That machine has now been connected to a different network and suddenly there my containers are not listed any more. It seem that the node was setup by the install script as the current IP of the machine rather that some static IP that would allow the machine to change networks without the connection breaking. Everything is running on the same local machine, there is no need for me to connect to remote machines. I think that if I manage to set the IP to 172.17.0.1:2375 everything would work (seems like the docker0 network always gets this IP?).

There is no way of changing the IP in the web UI and I don't understand how to connect to the RethinkDB inside it's container or whatever is storing that bad IP value.

I'm sure that many others experience this issue as well. How can I get my list of containers back?

Thanks for an otherwise nice tool. :)

**Comment by Tochirou** [comment]
If you're not confortable using docker using command lines, I suggest you should remove / reinstall shipyard using the automated script:

curl -sSL https://shipyard-project.com/deploy | ACTION=remove bash -s

curl -sSL http://shipyard-project.com/deploy | SHIPYARD_ARGS="--disable-usage-info"  bash -s
