### ISSUE TITLE
"add registry" doesn't work with registry v2 API

### ISSUE THREAD

**Issue by ddup2** [shipyard/shipyard#788]
Shipyard is slim and sexy, I love it,  however there are several issues, hopefully this will be addressed very soon!

From log, it seems shipyard is still trying to use v1 registry API.

docker: 1.10.3
registry: 2.3.1

ERRO[1624] error saving registry: Get docker.musical.ly:5000/v1/search: unsupported protocol scheme "docker.musical.ly"
ERRO[1634] error saving registry: 404 Not Found
ERRO[1639] error saving registry: 404 Not Found
ERRO[1641] error saving registry: 404 Not Found
ERRO[1642] error saving registry: 404 Not Found

**Comment by Tochirou** [comment]
Shipyard doesn't support v2 registry yet... 
Hope it will soon though !

**Comment by chuck-knox** [comment]
+1

**Comment by nipunarora** [comment]
+1

**Comment by kazaff** [comment]
....not support v2?? omg

**Comment by soninob** [comment]
We have a PR submitted for supporting V2, please check #852

**Comment by soninob** [comment]
We have a PR submitted for supporting V2, please check #852

**Comment by pedroponte** [comment]
+1

**Comment by soninob** [comment]
you can check #852
