### ISSUE TITLE
console disappears if run vim in ubuntu image

### ISSUE THREAD

**Issue by ddup2** [shipyard/shipyard#790]
reproduce steps:
1) deploy a container with ubuntu:latest image;
2) launch "console" and enter the bash;
3) in the console, run apt-get update && apt-get install vim;
4) vim /etc/passwd;

console will disappear in the webpage, it works with "vi" for the vanilla ubuntu:latest image though.

**Comment by wouteroosterveld** [comment]
You can fix this by doing 'export TERM=vt100' before invoking vim.
