### ISSUE TITLE
Domains and Hipache

### ISSUE THREAD

**Issue by rudimk** [shipyard/shipyard#792]
I'm a little confused with setting up subdomains for Docker containers through Shipyard. Right now, the hack is to set up a Hipache container, and manually add keys to its Redis datastore, to assign a subdomain to a container's exposed port. Is that something Shipyard can do, without me messing with the Hipache instance?

**Comment by ehazlett** [comment]
You may be interested in https://github.com/ehazlett/interlock

**Comment by rudimk** [comment]
Thanks a bunch! Sure looks awesome, Interlock does.
