### ISSUE TITLE
Can't get ports to expose to host port

### ISSUE THREAD

**Issue by itaimalek** [shipyard/shipyard#797]
Hi,
I'm very new to Docker, I decided to use shipyard as a management tool for containers.
I'm running Docker and Shipyard on the same CentOS7 machine.

I'm able to create containers but I can see the ports exposed.
for example, my image is set to expose ports 22,8080,8000,4403 - I set the ports conf. like so:
![image](https://cloud.githubusercontent.com/assets/8522568/14711185/11504c90-07e1-11e6-9e99-89ffb3ae3bcd.png)

but I still get this once the container is created:
![image](https://cloud.githubusercontent.com/assets/8522568/14711240/3f32f6d0-07e1-11e6-895f-652ed61fd04d.png)

I want to be able to expose my ports like here:
![image](https://cloud.githubusercontent.com/assets/8522568/14711294/7a15b5c6-07e1-11e6-86c1-a9ddfc9f7a87.png)

what am i doing wrong?

 PS: I can of course do this when starting my container from my command line (no Shipyard involved)

**Comment by robertbudge** [comment]
I too am having this issue on ubuntu server 14.04.4 however I cannot get any ports to be exposed

**Comment by timothysnave** [comment]
I'm also having this issue, also on CentOS 7. I've tried every way I can think of to expose ports, and nothing will work. Running on Docker version 1.10.1, build 9e83765. Not sure what version of swarm.

**Comment by hannaj** [comment]
I am having this problem running on a 4 instance OpenStack (Liberty) configuration with one master and three minions.  All are running ubuntu 14.01.4 server.  All were configured using the https://shipyard-project.com/deploy script.

In the past (a couple of seeks ago) I was able to deploy nginx and the wordpress examples via the shipyard GUI and the port mapping worked.

I have since rebuilt my OpenStack instances and it no longer works.  Don't know if this is caused by recent changes to shipyard, its containers, docker, or the deploy script.  

NOTE if I deploy a container from the command line of one of the minions the ports expose just fine, just not from the shipyard GUI.

**Comment by timothysnave** [comment]
I can also exports ports from the command line without problem. I also only have problems from the shipyard GUI.

**Comment by itaimalek** [comment]
@ehazlett 
any hint on this?

**Comment by robertbudge** [comment]
I attempted to set up shipyard on a clean instance of 14.04 still no luck, I might try 16.04 soon

**Comment by robertbudge** [comment]
Well I'm pleased that installation of docker and shipyard worked great on 16.04 however what ever port I try to expose externally is later mapped internally, I feel like I must be missing something.

**Comment by napir** [comment]
Same issue here. Ports aren't exposed when deploying containers via Shipyard, but exposing ports works fine from the command line. This worked fine on past versions of Shipyard.

**Comment by gontro** [comment]
Jumping in with the same issue.  Exposing ports works fine in via command line but is broken in Shipyard gui.

+1

**Comment by frol2103** [comment]
Same problem in debian 8.

+1

**Comment by robertbudge** [comment]
Is it possible to regress to an older version of shipyard easily?

**Comment by airtonix** [comment]
Doesn't really matter what your host operating system is, this a problem due to how it interacts with docker-swarm.

https://github.com/shipyard/shipyard/issues/784#issuecomment-202835583

**Comment by ehazlett** [comment]
This looks like a potential engine issue.  I'll take a look

**Comment by robertbudge** [comment]
Sorry if commenting here is the wrong place, but how do I know that I have a version with this fix? I have started with a clean install with the script on shipyard-project.com and I am still unable to expose ports. Should I have installed the testing version?
