### ISSUE TITLE
hide shipyard containers in web

### ISSUE THREAD

**Issue by zh99998** [shipyard/shipyard#798]
There is 7 containers for a shipyard host and 4 for a node.
It's a lot of messy in web
consider hide shipyard-related containers and images in web page for a cleaner look?

**Comment by guhcampos** [comment]
+1 For that. Having a filter to only show non-shipyard containers would be really, really great.

**Comment by wouteroosterveld** [comment]
The filter I use for this is "!shipyard" in the search box.

**Comment by pironic** [comment]
@wouteroosterveld this is pretty great, but i wish this was default. having to type that in every time is a pain.

**Comment by zh99998** [comment]
closing this since long time inactive
