### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by Pseudonomy** [shipyard/shipyard#799]
There's very little documentation on the project. Docs don't make it clear what command you should run to completely remove it. Running command `curl -sSL https://shipyard-project.com/deploy | bash -s -- -h` gives me options, okay. How can I call the options?

Running `sudo curl -sSL https://shipyard-project.com/deploy | IMAGE=remove bash -s` doesn't work

**Comment by ehazlett** [comment]
`curl -sSL https://shipyard-project.com/deploy | ACTION=remove bash -s`
