### ISSUE TITLE
Cannot add host to registries

### ISSUE THREAD

**Issue by lambayd** [shipyard/shipyard#800]
Scenario: I am installing Shipyard on a Hyper-V Virtual machine running Ubuntu

Initially I had issue installing Shipyard using the Automated approach, so I followed the manual approach and completed the installation on the 20/4/16

I can open the web interface but could not add the host to the registry or find the host within the Nodes page.

Additionally I added this line to the file 

DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"

On the add registry page, I entered
http://172.17.42.1:4243

No error message is displayed, but no device is added

**Comment by ehazlett** [comment]
Registries are Docker Registries, not Docker Engines.  Currently Shipyard only supports v1 registries.  See https://docs.docker.com/registry/ for details.
