### ISSUE TITLE
DEAD?

### ISSUE THREAD

**Issue by 0x4139** [shipyard/shipyard#801]
is this dead?

**Comment by robertbudge** [comment]
I've been wondering the same thing...

**Comment by ehazlett** [comment]
The code is still here and PRs are still welcome :). I only have so much
time for free work :)

**Comment by zh99998** [comment]
consider merge into https://github.com/rancher/rancher ?

**Comment by tombee** [comment]
Same goes for me, I don't have as much time free recently.  Would be awesome if we could grow the community and get more contributors :)
