### ISSUE TITLE
Shipyard cleanup

### ISSUE THREAD

**Issue by aardelean** [shipyard/shipyard#802]
Hi guys, I am having a bit of difficulty trying to uninstall shipyard from my ubuntu machine.
So, I installed automatically, running on port 8080. Of course, this port is used by default by a lot of applications so I tried to free it somehow afterwards. I am amazed I could not do it. 
It is occupied by the controller container.
So first I started a new controller container, on port 8180. I could access the new shipyard. 
Then next I tried to remove all container. Successfully. But the 8080 is still running, showing the shipyard interface.

Then I tried `sudo curl -sSL https://shipyard-project.com/deploy | ACTION="remove" bash -s`
It said it removed all, but both 8180 and 8080 still run, showing shipyard interface. 
I restarted, still are there.
I manually removed all the containers related to shipyard. Now docker ps shows no container. The interfaces still run on both ports.
I ran again the remove command, somehow says all the time with sudo, or without, that remove was successfully, but unfortunately nothing happens, shipyard is still there, on both ports.
I do not have any new ideas, I even tried some cleanup old commands, which don't work anymore.

Am I missing something?

**Comment by ehazlett** [comment]
Can you report what docker ps gives?

**Comment by aardelean** [comment]
docker ps gives nothing after removal. No container running.

**Comment by aardelean** [comment]
wait, my bad, I think cache removal of the browser didn't work well. I'm gonna close this one.

**Comment by ehazlett** [comment]
cool thanks!
