### ISSUE TITLE
"--device" option when deploy container in web UI

### ISSUE THREAD

**Issue by DeanChan** [shipyard/shipyard#806]
Hello everyone. I am deploying a container to do some GPU accelerated task like below:

```bash
docker run \
--device /dev/nvidia-uvm:/dev/nvidia-uvm \
--device /dev/nvidiactl:/dev/nvidiactl \
--device /dev/nvidia0:/dev/nvidia0 \
--device /dev/nvidia1:/dev/nvidia1 \
--device /dev/nvidia1:/dev/nvidia2 \
-ti pcalab/ubuntu-cuda:alpha bash
```

Is there a way to do this on shipyard web UI?

Thanks in advance!

**Comment by tombee** [comment]
@DeanChan We don't support this via the UI at the moment, should be reasonably easy for someone to add though, following the same code that that is used for volumes/links on the deploy screen.

**Comment by DeanChan** [comment]
Thank you @tombee . I'll close this issue now.
