### ISSUE TITLE
Problem with webhook to shipyard

### ISSUE THREAD

**Issue by jorjoh** [shipyard/shipyard#810]
I have been setting up a php/mysql wepbage in an docker image and container.I have my own webserver witch i would like to run the image from. This works fine. I also though that i could use shipyard (installed on my linuxserver) to take the latest pushed image on dockerhub and deploy it on my server with a webhook from docker hub repo. I have created a webhookkey pointing to the image, witch looks like this: http://myserver:8080/hub/webhook/webhookkey. Sadly my running containers on my webserver dont seem to be pulling the latest image and therefore is not updated to the last version.  EDIT: I can see i the container shipyard-controller that the notification for webhook is received, but it dont seem to be handled. Someone have experience with this? :)

**Comment by hasselrot** [comment]
I have the exact same problem.

My key:
{"id":"XXXXX","image":"hasselrot/node","key":"XXXXXXX"}

My webhook:
http://shipyardurlhere/hub/webhook/XXXXX

Shipyard container logs:
`INFO[8038] received webhook notification for hasselrot/node
INFO[8041] received webhook notification for hasselrot/node
INFO[8042] received webhook notification for hasselrot/node`

Nginx access logs:
`52.204.105.43 - - [20/Jul/2016:15:34:52 +0000] "POST /hub/webhook/881f8616a6bf4f39 HTTP/1.1" 200 0 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.13.0-79-generic"
52.204.103.25 - - [20/Jul/2016:15:34:54 +0000] "POST /hub/webhook/881f8616a6bf4f39 HTTP/1.1" 200 0 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.13.0-79-generic"
52.2.68.253 - - [20/Jul/2016:15:34:56 +0000] "POST /hub/webhook/881f8616a6bf4f39 HTTP/1.1" 200 0 "-" "python-requests/2.6.0 CPython/2.7.9 Linux/3.13.0-79-generic"`
