### ISSUE TITLE
Error response from daemon: SHM size must be greater then 0

### ISSUE THREAD

**Issue by jston** [shipyard/shipyard#812]
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:  
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:  
 OS/Arch:         linux/amd64

**Comment by ehazlett** [comment]
I believe this is fixed in recent versions of docker.
