### ISSUE TITLE
driver failed

### ISSUE THREAD

**Issue by geostant** [shipyard/shipyard#821]
[~]$ sudo curl -sSL https://shipyard-project.com/deploy | bash -s
Deploying Shipyard
 -> Starting Database
 -> Starting Discovery
 -> Starting Cert Volume
 -> Starting Proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint shipyard-proxy (b6f760b12220a78b27e24063d8eb341e78a311a8962119ec2016436d3e0c75f5): Bind for 0.0.0.0:2375 failed: port is already allocated.

Can't find port 2375 in use on my system 
netstat -tuna | grep 2375

**Comment by matt-baker** [comment]
I have the same issue. Using Docker Beta for mac.

**Comment by kdubb1337** [comment]
I have the same problem on mac and the manual install doesn't work even with a fresh docker engine.

**Comment by ehazlett** [comment]
I'll take a look.

**Comment by jacobzeng** [comment]
I have the same problem on mac
