### ISSUE TITLE
Waiting for Shipyard on x.x.x.x:8080 hangs

### ISSUE THREAD

**Issue by adamjimenez** [shipyard/shipyard#824]
New install on Fedora 23. (FirewallD is disabled).
Installing with:
`#curl -sSL https://shipyard-project.com/deploy | bash -s`

Gets to:
`Waiting for Shipyard on x.x.x.x:8080
...`

And keeps adding dots but never finishes.

**Comment by adamjimenez** [comment]
looks like I needed to do:
`firewall-cmd --zone=trusted --add-interface=docker0`

Even though firewalld wasn't even running. Maybe this could be added to the install script?

**Comment by Amar-Chaudhari** [comment]
Thanks !
Your commands work on CentOS 7 too !
Any idea how to fix the same on CentOS 6 ?

**Comment by nbaillie** [comment]
any idea how to do this on Photon OS which only has iptables and not firewall-cmd ?

**Comment by ehazlett** [comment]
This is not needed on a normal install. What OS are you using?

**Comment by ehazlett** [comment]
I meant that for Adam. You shouldn't need to do anything. How are you
accessing it?  I'm not familiar with Photon.

**Comment by nbaillie** [comment]
Photon OS is from VMware quite minimal OS, installed from their OVA, had to install AWK to run the installer but now, i see the bellow:

# curl -sSL https://shipyard-project.com/deploy | bash -s
Deploying Shipyard
 -> Starting Database
 -> Starting Discovery
 -> Starting Cert Volume
 -> Starting Proxy
 -> Starting Swarm Manager
 -> Starting Swarm Agent
 -> Starting Controller
Waiting for Shipyard on x.x.x.x:8080
..................................................................................................................................................................................................................................................................................................................................................................................

**Comment by adamjimenez** [comment]
@ehazlett that was on fedora (22 I think)

**Comment by taiffu** [comment]
Possible related to this issue? https://github.com/shipyard/shipyard/issues/807

**Comment by mnbf9rca** [comment]
Not sure if you figured this out @nbaillie but see #921 - I disabled iptables (systemctl stop iptables && systemctl disable iptables) then rebooted.
