### ISSUE TITLE
Shipyard not showing any nodes

### ISSUE THREAD

**Issue by demhyt** [shipyard/shipyard#828]
Dear Folks, I have setup using 4 machines docker running on Ubuntu 14.04 the all docker version is same (ver 1.11.1).. I'm using consul as my service discovery and I can show the all my nodes like below

root@docker-man:~# docker -H docker-man:4000 info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 33
Server Version: swarm/1.2.2
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 docker01: 192.168.1.240:2375
  └ ID: S24Q:4MCL:DRMZ:O36F:37MT:ZKN2:YQC2:A4OZ:TAA4:SNE5:MEIZ:OAU3
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.44 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-09T15:31:12Z
  └ ServerVersion: 1.11.1
 docker02: 192.168.1.241:2375
  └ ID: OYAP:LUAC:VKZE:6AUD:EG4D:RHB5:LT7A:VB5R:YFC5:FSTK:BEAS:ZRKR
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.44 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-09T15:31:02Z
  └ ServerVersion: 1.11.1
 docker-man: 192.168.1.238:2375
  └ ID: XMF5:DDBS:OSIR:6A44:CJ6R:INAC:BCBQ:XOPC:LXNZ:5QYD:FFAA:4RJD
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.039 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-32-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-06-09T15:31:10Z
  └ ServerVersion: 1.11.1
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.13.0-32-generic
Operating System: linux
Architecture: amd64
CPUs: 10
Total Memory: 36.92 GiB
Name: b2d6352b1a1a
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

But I cannot see at my shipyard dashboard
![image](https://cloud.githubusercontent.com/assets/10397993/15935623/1772190a-2e92-11e6-8e30-7c353525e4d5.png)

Any thoughts?,,thank you a lot

**Comment by ehazlett** [comment]
How did you install shipyard?  Can you post the logs of the controller?

**Comment by demhyt** [comment]
Hi ezhalett, thanks for answer....Sorry dumb question, how to collect the logs?...Like this?

root@docker-man:~# docker logs -f shipyard-controller 
INFO[0000] shipyard version 3.0.5                       
INFO[0000] checking database                            
INFO[0000] controller listening on :8080                
INFO[0000] shipyard version 3.0.5                       
INFO[0000] checking database                            
INFO[0000] controller listening on :8080                
INFO[0000] shipyard version 3.0.5                       
INFO[0000] checking database                            
INFO[0000] controller listening on :8080   

Thank you

**Comment by demhyt** [comment]
Just give the my topology, so I have 4 docker running at ubuntu 14.04...

- 2 as docker nodes (only swarm client / agent running)
- 1 as consul service discovery (only consul running)
- 1 as manager (swarm manager, shipyard-rethinkdb, shipyard-controller, swarm client / agent)

Running container on docker-manager like below

root@docker-man:~# docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                    NAMES
3c61196156ad        swarm                      "/swarm join --addr 1"   3 minutes ago       Up 3 minutes        2375/tcp                                 shipyard-swarm-agent
192ddc34bbc4        shipyard/shipyard:latest   "/bin/controller serv"   5 days ago          Up 4 minutes        0.0.0.0:8080->8080/tcp                   shipyard-controller
966daf5d6c80        rethinkdb                  "rethinkdb --bind all"   5 days ago          Up 11 minutes       8080/tcp, 28015/tcp, 29015/tcp           shipyard-rethinkdb
b2d6352b1a1a        swarm                      "/swarm manage -H :40"   6 days ago          Up 11 minutes       2375/tcp, 192.168.1.238:4000->4000/tcp   docker-manage

**Comment by lingdengch** [comment]
do you know how to fix this:Get http://swarm:2222/v1.21/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02" when chose nodes?
