### ISSUE TITLE
Cannot connect to console when shipyard is behind an ELB

### ISSUE THREAD

**Issue by michaelpjohnson** [shipyard/shipyard#829]
I currently running shipyard behind an AWS ELB on my swarm. Everything seems fine with the exception of connecting to a remote container via the `Run` button on the `Console` page. It just immediately returns. There are no errors in the logs or events. When I connect to the shipyard directly via the IP, it connects just fine. I've allowed all traffic on the ELB to my IP but to no avail. I saw there was a some issues with DNS resolving and the console a few years ago, perhaps this is related?

**Comment by ehazlett** [comment]
Try running the ELB in tcp mode.

**Comment by michaelpjohnson** [comment]
That did the trick. Thanks.
