### ISSUE TITLE
is the master repo  support registry v2 for now?

### ISSUE THREAD

**Issue by kazaff** [shipyard/shipyard#833]
why get 404 error when i add local registry2 use "--insecure-registry" ?

**Comment by ehazlett** [comment]
No v2 is not supported

**Comment by kazaff** [comment]
hi @ehazlett , i saw that you open you own repo to support v2 version, but i can not find how to use? the readme.md in you branch is the same with the master repo.

what can i do?  thank you for your time~

**Comment by borzamircea** [comment]
Hi @ehazlett , @tombee ,@kazaff ! We actually have a working registry `v2` for shipyard implemented here https://github.com/eedevops/shipyard, under the `registry-v2` branch. I can integrate it with your current master and test it. Would you accept a PR, if we submit it? TY!

**Comment by ehazlett** [comment]
Please submit a PR and we will review it. Thanks!

**Comment by borzamircea** [comment]
Hi @ehazlett , @tombee . Just submitted a PR. Thanks!

**Comment by borzamircea** [comment]
The pr is here, if you want to check it out: https://github.com/shipyard/shipyard/pull/852
