### ISSUE TITLE
Shipyard and Docker 1.12

### ISSUE THREAD

**Issue by giscardff** [shipyard/shipyard#834]
Hi guys,

I'm just experimenting docker 1.12RC, and tried to put shipyard to work with its embedded swarm ochestration... so  far no success....

Basically I started a swarm cluster and after that both rethinkdb and shipyard-controller pointing to server tcp://<swarm-manage-host>:<port>.

Is there something I might me missing? Or they were not supposed together after all?

Regards.

**Comment by ehazlett** [comment]
Shipyard will need some updating. We've been talking about it already. We
hope to have something soon.

**Comment by giscardff** [comment]
Thanks.
