### ISSUE TITLE
support swarm mode in docker 1.12

### ISSUE THREAD

**Issue by rahulbats** [shipyard/shipyard#839]
does shipyard support swarm mode in docker 1.12

**Comment by tombee** [comment]
Not yet, but I'm working on it when I have some free time:
https://github.com/shipyard/shipyard/pull/837

**Comment by jmzwcn** [comment]
I think the latest swarm mode is a flash point, could we consider take a priority for it?

**Comment by tombee** [comment]
Yup, I'm working on it in my free time.  Check out #837.

**Comment by rsippl** [comment]
@tombee, I'd love to try out your work related to 1.12, but unfortunately, docker-compose fails to start the webpack container. I'm on a Mac, using the 1.12 Docker Toolbox (on Virtualbox). I'm getting a ton of errors like this one:
```
webpack_1     | npm ERR! tar.unpack untar error /root/.npm/esutils/2.0.2/package.tgz
webpack_1     | npm WARN install:esutils@2.0.2 EPERM: operation not permitted, chown '/usr/src/app/node_modules/.staging/esutils-0a626159/package.json'
```
so for some reason, chown fails on Virtualbox. I wonder if you stumbled upon something similar and whether you have a solution for this?

**Comment by rsippl** [comment]
Forgot to mention that I'm using dinghy. The issue is described [here](https://github.com/codekitchen/dinghy/issues/17), I fixed it by running webpack in a custom container which runs as a non-root user. I'm using a very simple Dockerfile for this:

```
FROM node

RUN useradd -ms /bin/bash node

USER node
```

**Comment by borzamircea** [comment]
Hey guys! I just pulled branch `1.12` and tested it. Installed docker `1.12` and it works fine. One question: why is the `Registries` tab gone? Did you decide you will take out registry support, both `v1` and `v2`, or is it just not implemented yet? Thanks a lot!

**Comment by joekohut** [comment]
I am getting this error in Shipyard agent log with Docker version 1.12.0, build 8eab29e:
ERRO[0000] cannot set or renew session for ttl, unable to operate on sessions

I am using:
shipyard version 3.0.5 (ca9efec)
swarm version 1.2.4 (5d5f7f0)

Can someone confirm this issue in docker 1.12/shipyard?

**Comment by tibmeister** [comment]
So how exactly does this work behind a firewall?  I did try to add the HTTP_PROXY env variables to the docker-compose.yaml file but no luck.  I can't get the shipyard to actually come up with anything other than a white screen.

Docker 1.12 on CentOS7

**Comment by el-liberator** [comment]
The same here :(

Docker 1.12.1  on RHEL7

**Comment by bennythomps** [comment]
I'm able to log in but I also just receive a blank white page after logging in. Inspecting the traffic it looks like it's because it can't reach "/swarm". I also tried via REST and couldn't find a way to interact with the Docker Remote API. Even if that were possible, I could start gaining some value. Any suggestions how to at least use the API to interact with 1.12 swarm @tombee ?

**Comment by sebgie** [comment]
Hey, I have tried out the branch today and it looks amazing 😍 ! I'm in the process of building a new cluster and would like to use shipyard to provide our team with an overview of the cluster (node configuration, container logs, environment, ...) and do management tasks.

I was wondering if there is a list of tasks that is left to do for 1.12 being shipped? An epic, milestone or label would great to find places where you would appreciate help? I'm also more than happy to do testing.

**Comment by thefallentree** [comment]
any updates on this issue?

**Comment by tombee** [comment]
It's being worked on :smile:, there's been a similar question asked here (with a response on what to help out with): https://github.com/shipyard/shipyard/issues/889#issuecomment-272095889
