### ISSUE TITLE
connect via tcps swarm fails

### ISSUE THREAD

**Issue by tronicum** [shipyard/shipyard#840]
I try to connect to a swarm manager running TLS on port 3376. 
$DOCKER_CERT_PATH is present. Trying to give --tls-* paramets fail with file not found (does it try to find them within the image?).
Does work when using stunnel with matching client certificates and provide an non-encrypted port...

**Comment by tronicum** [comment]
mentioned in https://github.com/shipyard/shipyard/issues/794 , too

**Comment by rprashad** [comment]
i dont think this is a bug, works fine via:

function start_shipyard() {

docker run \
    -ti \
    -d \
    -v /etc/docker:/etc/docker:ro \
    -v /etc/ssl/:/etc/ssl:ro \
    --restart=always \
    --name shipyard \
    --link rethinkdb:rethinkdb \
    --link $SWARM_MASTER:$SWARM_MASTER \
    -p 8080:8080 \
    shipyard/shipyard:latest \
    --debug \
    server \
    -d tcp://$SWARM_MASTER:3376 --tls-ca-cert /etc/docker/ca.pem --tls-cert /etc/docker/server.pem --tls-key /etc/docker/server-key.pem
}

**Comment by tronicum** [comment]
well I would consider exposing the ca into the node an ugly hack. especially making your CA Key readable is really bad.

**Comment by rprashad** [comment]
If your swarm nodes were created by docker-machine, then they should all have the same generated certs.  Exposing them is certainly not ideal, but warranted for secure comms between shipyard and the swarm cluster.

**Comment by tronicum** [comment]
i must admit that it is server-key on the swarm node, not ca-key which is on the docker-machine host.  
btw. passing through /etc/ssl/ is only needed if you use a external signed certificate. 
it works as you suggested.
