### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by tronicum** [shipyard/shipyard#841]
I was able to authenticate against a ldap server, with accounts auto creation. 
There where some problems:
- It's ldap user only so how can i login as local shipyard admin?
- if you disable ldap, the users stay, but the password is not set, so you can not use them

btw, if your username (fixed to "cn=" part of a ldap DN) contains spaces, it is safe to login with "user name".

Is it possible to login against TLS ldap? do i just need to adjust the port?

**Comment by csreddy** [comment]
@tronicum I'm having trouble getting the ldap auth setup correctly. Could you please share what params you provided while deploying ?

Here' what I passed
curl -sSL https://shipyard-project.com/deploy | SHIPYARD_ARGS="--ldap-server=ldap.mycompany.com --ldap-autocreate-users --ldap-base-dn=\"OU=CORP,DC=mycompany,DC=com\" bash -s
