### ISSUE TITLE
uneven scaling with a swarm strategy spread

### ISSUE THREAD

**Issue by tronicum** [shipyard/shipyard#843]
I am using shipyard:latest 
with a swarm cluster and spread strategy, consul swarm discovery.

if scale using the UI, the volumes are not distributed evenly. 

I double checked the docker API Port, it points to the swarm. I can see all nodes so it seems right.

If I run a manual docker run multiple times on my swarm manager via CLI with eval $(docker-machine env node1 --swarm); where node1 is my swarm manager it distributes evenly over all nodes.

Any ideas why the shipyard scale does not in the same fashion? 
I click on the "action -> tool icon" to scale. 
The only idea I have it that it would use the node from that image but that would be quite odd.

**Comment by ehazlett** [comment]
Since there was no "scaling" in Swarm before Docker 1.12 we did it like
compose did (docker run etc). This will be resolved in the 1.12 release.
