### ISSUE TITLE
Why only see a node on the container start status?

### ISSUE THREAD

**Issue by hhy5861** [shipyard/shipyard#849]
I have two nodes, manager alone can only monitor the status of a section on the container, the container should be able to see the status of the two nodes? Thank you!
![1](https://cloud.githubusercontent.com/assets/8274977/17077758/bb553676-510e-11e6-9362-02aeddd536ee.png)
![2](https://cloud.githubusercontent.com/assets/8274977/17077759/bbce4e62-510e-11e6-87a7-841cb1429f0d.png)

**Comment by justinyuan** [comment]
Did you create these two node by cloning VMs?
