### ISSUE TITLE
Error : No healthy node available in the cluster 

### ISSUE THREAD

**Issue by Dremor** [shipyard/shipyard#850]
I installed Shipyard using the deploy script, but couldn't create any container because of a "No healthy node available in the cluster" error.

Node list :
![](https://framapic.org/gSjh4DRjLV4s/Oq695gHHqCV5.png)

**Comment by faddat** [comment]
That looks like a regular docker daemon address there.  Actually, I am not sure if the shipyard install script has been updated for our great new era

**Comment by Dremor** [comment]
I'll try to do it again, but this time with the manual procedure.

**Comment by johnny-wang86** [comment]
+1

**Comment by kongou-ae** [comment]
+1

**Comment by cupen** [comment]
I meet the same problem. I just run `curl -s https://shipyard-project.com/deploy | bash -s` which follow the **README.md**.

My environments.
* centos 7.3
* docker 1.12.6

**Comment by cupen** [comment]
Well, maybe I found the reason of this problem.
I just install the `docker-machine`, then it works for me.
https://docs.docker.com/machine/install-machine/

@Dremor  @johnny-wang86 @kongou-ae

**Comment by Dremor** [comment]
@cupen I'll try as soon as I get my hand on a good vps.
