### ISSUE TITLE
how to restart shipyard after installation went fine with Curl?

### ISSUE THREAD

**Issue by FrankMaute** [shipyard/shipyard#853]
Hi, 

guess this is a real beginner question:

I installed Shipyard using Curl. Startup was fine, everything worked.
How do I **restart** the Shipyard infrastructure after all containers have been stopped? Doing so, I would like to keep data **persistent**. So all settings come up again as configured. 
Thanks for helping!

**Comment by tronicum** [comment]
data for shipyard is kept within the rethinkdb (or read from docker via the API). If you create a docker volume that is persistent for the rethinkdb, you should keep persistent data (like users, passwords, etc).

**Comment by tronicum** [comment]
i just checked the rethinkdb dockerfile (https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/d129775a6b33cb9e9a3ced40edda31ba9016a647/jessie/2.3.4/Dockerfile) it does use a volume so it should be persistent already.

**Comment by FrankMaute** [comment]
Hi @tronicum:
Thanks for this. Do you know also, how and with which options/flags I need to start shipyard when it was shut down?

**Comment by tronicum** [comment]
That depends on your setup (like how you access docker, with or without TLS) . Why not run the curl command without the | (pipe) part to see what command it executes?

**Comment by FrankMaute** [comment]
That's a very long bash script. No idea how to generate a docker-compose.yml out of it. I mean, this must be known already somewhere. Cannot be Rocketscience to restart the Shipyard containers. 

The Script is here:
[Link to bash-File](https://privatewolke.com/s/l30ty7UHocochWx)

**Comment by tronicum** [comment]
What about the docker-compose.yml right here @github ? https://github.com/shipyard/shipyard/blob/master/docker-compose.yml

**Comment by FrankMaute** [comment]
Well, to me it seems, that this is building a new image/container every time it is called. 
Not sure, this'll work. I guess if it is reduced to just connect the containers and the ports it should do. I will give it a try. Thanks for the hint!

**Comment by tronicum** [comment]
The image should be stable once it was built.
...and central part of the docker concept is that once the main process ends, the container ends, too. Do you mean a "reload" like change of configuration?

**Comment by FrankMaute** [comment]
No, I meant to re-start the container with existing values, persistent storage (which is enabled). I need to start all prerequisites, so at the end the whole shipyard infrastructure is up and running without building new containers. Just a simple start of the shipyard infrastructure. Does this make sense to you?

**Comment by tronicum** [comment]
well beside the user configuration, everything is read from the docker API. I
 am struggling at the moment to restart shipyard with an existing rethinkdb.

**Comment by FrankMaute** [comment]
Thanks for digging into this. And thanks for opening https://github.com/shipyard/shipyard/issues/857
