### ISSUE TITLE
too many "socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock" process

### ISSUE THREAD

**Issue by johnny-wang86** [shipyard/shipyard#856]
I installed Shipyard using the deploy script, There are some problems。

- There are many processes
![dd0c29b0-d754-4bd6-bfcf-7b7132a5559c](https://cloud.githubusercontent.com/assets/5415121/17613935/c09bdd16-6094-11e6-8cad-3ce195a5bb5f.png)

- Couldn't create any container because of a "No healthy node available in the cluster" error.
![error01](https://cloud.githubusercontent.com/assets/5415121/17614075/d0c64c84-6095-11e6-935a-c230cd64b0f0.png)

- Node list display "unknown"
![9a27d4e8-4cb8-430a-bdbc-9968934265fd](https://cloud.githubusercontent.com/assets/5415121/17614164/901258bc-6096-11e6-8cb6-b57098fe48ad.png)

os version：CentOS release 6.5 
docker version ：  1.7.1

logs：
[root@iZ11gbrk32jZ ~]# docker logs shipyard-swarm-manager
`INFO[0000] Initializing discovery without TLS
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost
INFO[0000] Leader Election: Cluster leadership acquired
ERRO[0728] HTTP error: No healthy node available in the cluster  status=500
`
Who can give me some helps，Thanks

**Comment by tronicum** [comment]
this docker version looks **very** old

**Comment by johnny-wang86** [comment]
@tronicum ,thanks
I upgraded the os version（centos 7.2） and the docker version(1.12.),  shipyard was working properly.

**Comment by Anixceed** [comment]
Could the shipyard work on ubuntu14 &docker version1.9.0?I got the same problem.Shipyard cann't list any containers.
