### ISSUE TITLE
 oci runtime error: exec: "/usr/sbin/sshd":

### ISSUE THREAD

**Issue by systemroot** [shipyard/shipyard#865]
![](http://image.prntscr.com/image/29a9a4f2fcbf4e04b1a51e09b19c7f95.png)

This problem is just with alpine! Ubuntu/Debian/CentOS Is working without problem. 

Also i try to build alpine 3.4 directly from terminal and 
![](http://image.prntscr.com/image/a6c4b31752764229bebe6eb7d8eb7d50.png)
Is working without problems, I don't know why i can't build it from shipyard?

<pre>
root@vps299422:~# docker info
Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 28
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-95-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.767 GiB
Name: vps299422
ID: 5GJT:ZGEN:BRHT:EFTZ:PTWK:UIUN:CBLN:UHBL:CSKR:MP5L:4QPV:I57X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
</pre>

<pre>
root@vps299422:~# /usr/sbin/sshd 
OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014
</pre>

Thanks.

**Comment by ehazlett** [comment]
This seems to be working fine for me.  This would be a problem with the
image.  Can you try to run it manually on the Docker host to see if it's
any different?

**Comment by systemroot** [comment]
the same
`"docker start cb1f23638021
Error response from daemon: oci runtime error: exec: "/usr/sbin/sshd": stat /usr/sbin/sshd: no such file or directory
Error: failed to start containers: cb1f23638021
"`

**Comment by ehazlett** [comment]
Ya this looks like some sort of image fail.  Try pulling the latest.  I
tested on alpine:latest and it worked fine.

**Comment by ehazlett** [comment]
- docker run -ti --rm alpine ash
- apk add -U openssh
- /usr/sbin/sshd -D

**Comment by systemroot** [comment]
> - docker run -ti --rm alpine ash
> - apk add -U openssh
> - /usr/sbin/sshd -D
yea this was the problem
Thank you

**Comment by ehazlett** [comment]
yw
