### ISSUE TITLE
Adding Node not possible

### ISSUE THREAD

**Issue by volands** [shipyard/shipyard#869]
Hi,

I have problems with adding nodes to my shipyard master (both on Ubuntu 16.04, Docker 1.9.1; with no TLS for shipyard). 

On my master node (e.g. 192.168.1.171) everything works fine (I can see alls containers, can deploy containers, etc.) - from my second node I can ping the shipyard master as well as curl all shipyard ports (in case of etcd port 4001: curl http://shipyard-ip:port = 404 not found). I've also checked the iptables logs - I noticed no blocked connection.

Unfortunately, it is not possible to add the second node to the master - I tried it with automatic delopyment:
curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://192.168.1.171:4001 bash -s
as well as with manually deployment:
docker run \
    -ti \
    -d \
    --restart=always \
    --name shipyard-swarm-agent \
    swarm:latest \
    join --addr 192.168.1.171:2375 etcd://192.168.1.171:4001

The shipyard-agent container only logs:
INFO[0000] Initializing discovery without TLS
INFO[0000] Registering on the discovery service every 1m0s...  addr=192.168.1.171:2375 discovery=etcd://192.168.1.171:4001
ERRO[0003] client: etcd cluster is unavailable or misconfigured

On the master I have checked all shipyard container logs - but found only this in the logs of "shipyard-swarm-manager":
2016-09-19T22:01:55.602791282Z [31mERRO[0m[0002] Unable to update state of container "7c5d6961588f6164ba5977332c726e7d30f8fccd38b8b3310ab1456a01a07165": Error response from daemon: Unknown device 7c5d6961588f6164ba5977332c726e7d30f8fccd38b8b3310ab1456a01a07165  [31mid[0m=Z3RM:FEM6:RE45:ZV3L:YMNZ:CEQ5:BRIP:D7UA:VN4O...

Thanks and best regards,
Patrick

**Comment by xushy1** [comment]
first you should start firewalld service and then add the source by 
firewall-cmd --zone=public --add-source=192.168.1.0/24,
--addr should be append with agent's address,
