### ISSUE TITLE
Botched install, trying to reinstall

### ISSUE THREAD

**Issue by bithead666** [shipyard/shipyard#870]
I'd like to wipe everything SHipyard-related on a swarm 1.12 two-node setup I have.  The reason is that I kind of botched the install and I think I started removing things but lost my train of thought on another project interrupt.  Now I'm in Zombie land.

I started the remove:

curl -s https://shipyard-project.com/deploy | bash -s remove

And now I'm getting this message:

docker: Error response from daemon: Conflict. The name "/shipyard-rethinkdb" is already in use by container ......

Thanks for any assistance on removing this so I can start over.

**Comment by xushy1** [comment]
not supports 1.12

**Comment by akosveres** [comment]
To solve the docker error response, check if the docker container has been trully stopped and removed with docker ps and docker ps -a. If it's still there do:
docker stop shipyard-rethinkdb && docker rm shipyard-rethinkdb

You'll need to do the same with all other containers that belong to shipyard.

**Comment by ehazlett** [comment]
Try this

curl -s https://shipyard-project.com/deploy | ACTION=remove bash -s

**Comment by MasterCATZ** [comment]
@ehazlett 

Thank You
