### ISSUE TITLE
Broken on latest Docker 12

### ISSUE THREAD

**Issue by vaskaloidis** [shipyard/shipyard#873]
Hey guys I updated to the latest docker today and broke Shipyard. I am now on Docker version 1.12.1, build 23cf638.

I had to deal with a tedious reinstall process to clear out all the auto-starting shipyard containers and delete them all, but once I did that and finally got Shipyard running again, it still doesen't display any containers.

I'll see if I have some time to pull the code and contribute this week

Thanks

**Comment by tronicum** [comment]
it works with my 1.12.1 swarm cluster. and that was upgraded from 1.11, too.

**Comment by ehazlett** [comment]
Can you post some logs from the controller?
