### ISSUE TITLE
Click on Search on REGISTRIES throws error

### ISSUE THREAD

**Issue by rgrsoucy** [shipyard/shipyard#879]
shipyard: v3.1

Hello,
I am having the following issue when trying to view my docker registry info.

Click on “REGISTRIES” menu
Click on search icon (magnifying glass)
Message on page: “It looks like an error occurred:”
Message in debugger: invalid character '<' looking for beginning of value

I am able to Deploy Containers without issues within shipyard.

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

**Comment by soninob** [comment]
@rgrsoucy - I encounter this problem when I define the registry incorrectly, please verify your link to the registry.
let me know if it make a difference.

**Comment by rgrsoucy** [comment]
I have my docker registry in jfrog Artifactory. I am wondering if this is the issue and should even work? Does it only work with registries on the same host as the docker host?

I have added my registry to shipyard like this (asterisk for my private info):

http://****.artifactoryonline.com/***/api/docker/my-docker-repo/

If from the command line I run:

curl -i -uUSERNAME:PASSWORD http://****.artifactoryonline.com/***/api/docker/my-docker-repo/v2/my_image/manifests/1

It successfully retrieves my data.

**Comment by soninob** [comment]
@rgrsoucy - we actually tested v2, and can tell you that Artifactory, Nexus, and DTR are supported, and of course, they **don't** have to be on the same host.
Did you verify that http://*.artifactoryonline.com//api/docker/my-docker-repo/ contains Docker images?

**Comment by rgrsoucy** [comment]
@soninob - Here is some more checking I did today.

When I run curl to the repo, I do get the image information returned. See snippet below.

```
curl -i -uUSERNAME:PASSWORD http://****-docker-localjfrog.io/v2/jenkins_slave/manifests/1

{
  "schemaVersion" : 1,
  "name" : "jenkins_slave”,
  "tag" : "1",
  "architecture" : "amd64",
  "fsLayers" : [ {
    "blobSum" : "sha256:a3ed95caeb02ggt43cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
  }, {
```
Since that seemed to work, I tried adding  “http://****-docker-localjfrog.io”  to the registry but I get the message:

```
“Error...
Cannot ping registry “
```

If I ping "****docker-localjfrog.io" and use the IP returned to enter into the registry settings, it accepts the "http://IP" value but when I click the search icon for the registry I get the

 `“It looks like an error occurred:” `

message

**Comment by soninob** [comment]
I saw some problems when we missed a'/' in the end of the URL. Can check that. Rather than that I can suggest to verify the URL, or maybe some dns issue. Sorry about that.

**Comment by rgrsoucy** [comment]
@soninob -  I am starting wonder if it has something to do with the new jfrog FQDN. Specifically the .io instead of .com

**Comment by rgrsoucy** [comment]
Yeah, It just doesn't let me use the DNS name. Always get the "Cannot ping registry" and using the IP that I get when I ping the DNS from the host always returns “It looks like an error occurred:”

**Comment by soninob** [comment]
Maybe @ehazlett can help you here, he had a similar problem when he tested the PR.

**Comment by jetz** [comment]
Same problem here, always "Cannot ping registry", ping @ehazlett .

**Comment by soninob** [comment]
@jetz - which registry are you using?

**Comment by jetz** [comment]
@soninob It's a private registry in our company, just as @rgrsoucy said, it's ok to `curl` it, but failed in shipyard. Now I've solved this problem by setting up newest registry myself, with nginx basic auth.
