### ISSUE TITLE
It won't work with Docker 1.12.1 on macOS Sierra

### ISSUE THREAD

**Issue by david9991** [shipyard/shipyard#880]
> $ export PORT=8082
> $ curl -sSL https://shipyard-project.com/deploy | bash -s
> Deploying Shipyard
>  -> Starting Database
>  -> Starting Discovery
>  -> Starting Cert Volume
>  -> Starting Proxy
>  -> Starting Swarm Manager
>  -> Starting Swarm Agent
>  -> Starting Controller
> Waiting for Shipyard on 192.168.1.129:8082

And it stuck at the line "Waiting for Shipyard on 192.168.1.129:8082".

> $ docker logs shipyard-controller
> INFO[0000] shipyard version 3.1.0
> DEBU[0000] setting up rethinkdb session
> WARN[0075] Error creating connection: gorethink: dial tcp 60.19.29.22:28015: getsockopt: connection refused
> FATA[0075] no connections were made when creating the session 
> INFO[0000] shipyard version 3.1.0
> DEBU[0000] setting up rethinkdb session

The log show me that it cannot resolve the hostname 'rethinkdb' properly, But i tried to ping the host 'rethinkdb' in the container, I got a correct ip address.

> $ docker exec -it shipyard-controller /bin/sh
> / # ping rethinkdb
> PING rethinkdb (172.17.0.2): 56 data bytes
> 64 bytes from 172.17.0.2: seq=0 ttl=64 time=0.233 ms
> 64 bytes from 172.17.0.2: seq=1 ttl=64 time=0.095 ms

Version info.

> $ docker version
> Client:
>  Version:      1.12.1
>  API version:  1.24
>  Go version:   go1.7.1
>  Git commit:   6f9534c
>  Built:        Thu Sep  8 10:31:18 2016
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      1.12.1
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   23cf638
>  Built:        Thu Aug 18 17:52:38 2016
>  OS/Arch:      linux/amd64

**Comment by david9991** [comment]
This problem resolved by add nsswitch.conf to /etc.
You missed to add /etc/nsswitch.conf in Dockefile, because Gorethinkdb library uses Go resolver by default that read /etc/nsswitch.conf first then /etc/hosts. It's different against the Cgo resolver uses alpine linux's native resolver in libc. So to solve the hostname resolving problem, you can add a nsswitch.conf to /etc, or force Go to use Cgo Resolver instead. This issue not occurred on linux because docker is more native for linux and also for Go resolver that running on it?

**Comment by tronicum** [comment]
If you would use docker-compose the names should be transparent as they would be added to the docker DNS (at least thats how it works for me).  And docker hostnames should work as DNS within a docker, regardless of the nsswitch.conf.

**Comment by david9991** [comment]
@tronicum Have you tested it on macOS Sierra? In here the /etc/resolv.conf pointed to validate DNS addresses, and all --linked container's hostname added to the /etc/hosts file correctly, and the libc resolver work just fine for other program like ping, nslookup and any other applications that running on the container, yes it did work like a DNS server properly, but except Go apps/modules (e.g. gorethinkdb library) that use default Go resolver still not work, except I copy nsswitch.conf to that container or switch resolver to Cgo Resolver.   PS: In my opinion docker-composer just like a package (service) manage system and provides pre-configuration, dependence management and service management, it won't help in this situation, please correct me if I was wrong. :P

**Comment by tronicum** [comment]
I did not upgrade to Sierra. Could test on El captain only. 
Docker-compose would create an overlay network.

But what I am saying is if you can not resolve container names in docker that should be a docker bug.

**Comment by david9991** [comment]
@tronicum Thanks, and I'll do more investigation on it and give docker-compose a try.

**Comment by tronicum** [comment]
you might give https://github.com/tronicum/werfty/blob/master/toolbox/shipyard/docker-compose.yaml a try. that is what i use to start it. 
It has a problem though that if the container name is taken you might have to through away the database. as i dont have really persistent stuff in the db, I dont care.

**Comment by david9991** [comment]
@tronicum Ok, thanks.

**Comment by david9991** [comment]
@tronicum I have tried your yaml, and with no luck it still require /etc/nsswitch.conf there. the ip address 60.19.29.22 is the wrong ip address assigned when a hostname cannot be resolved.

> time="2016-10-14T07:57:44Z" level=info msg="shipyard version 3.1.0" 
> time="2016-10-14T07:57:44Z" level=debug msg="using tls for communication with docker" 
> time="2016-10-14T07:57:44Z" level=debug msg="setting up rethinkdb session" 
> time="2016-10-14T07:58:59Z" level=warning msg="Error creating connection: gorethink: dial tcp 60.19.29.22:28015: getsockopt: connection refused" 
> time="2016-10-14T07:58:59Z" level=fatal msg="no connections were made when creating the session"

**Comment by david9991** [comment]
@tronicum I decide to add nsswitch.conf to my container manually, it at least works for me. thank you all the same.

**Comment by tronicum** [comment]
you might close this issue if it is solved

**Comment by AaronFeng2014** [comment]
# nimenhao

## hafsdg
