### ISSUE TITLE
你好，容器多了的时候，小菜单显示不出来

### ISSUE THREAD

**Issue by gg444108853** [shipyard/shipyard#881]
![image](https://cloud.githubusercontent.com/assets/17719524/19210904/46ebd7f0-8d62-11e6-87f2-d48ba18fe83c.png)
容器多的时候这个小菜单会被隐藏，显示不出来

**Comment by tronicum** [comment]
google translates it to something like
"Containers with short names will be hidden, do not show up". 
Still not sure if this is just UX bug, as this is only the left part of the screen shot you should still see name before clicking on the tool icon.

**Comment by david9991** [comment]
@tronicum He said "The menu cannot be displayed if too many containers in the list." I guess he mean "The operation menu is too long to be displayed if container list is too long? truncated by browser's client area"

<img width="1055" alt="screen shot 2016-10-14 at 1 55 51 pm" src="https://cloud.githubusercontent.com/assets/123219/19377116/133424f4-9216-11e6-89d5-02c2e2c8fba2.png">

**Comment by tronicum** [comment]
Oh Thanks. Does that occur with any browser @gg444108853 ?

**Comment by tombee** [comment]
There's a potential fix for this in #861

**Comment by gg444108853** [comment]
@david9991 对的我说的就是这个意思

**Comment by gg444108853** [comment]
我在chrome上测试，原谅我 才回复 抱歉
