### ISSUE TITLE
bower -s install --allow-root -p | xargs echo > /dev/null，The following 

### ISSUE THREAD

**Issue by xhz-bza** [shipyard/shipyard#894]
bower angular-jwt#~0.0.6       ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/auth0/angular-jwt.git", exit code of #128 fatal: unable to access 'https://github.com/auth0/angular-jwt.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

Additional error details:
fatal: unable to access 'https://github.com/auth0/angular-jwt.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

Why？

**Comment by xhz-bza** [comment]
bower -v
1.7.9

**Comment by xhz-bza** [comment]
Now what do I do，It's very urgent

**Comment by ehazlett** [comment]
That looks like a connection error.  Can you try from a remote instance to see if it's your connection?  I will try to re-create.

**Comment by xhz-bza** [comment]
Thinks.I am a student from China, it is very urgent, because the graduation project to be used.

Next, I should do something about it.

**Comment by xhz-bza** [comment]
build a few days ago when the very soon OK, and these two days is very strange.

**Comment by xhz-bza** [comment]
I try use "git config --global url."http://".insteadOf git://"，it is not valid，Now very distressed.

I need your help

**Comment by xhz-bza** [comment]
@ehazlett

**Comment by ehazlett** [comment]
The "great firewall" is probably blocking.  I'm not sure how to help as we can't control from that side.
