### ISSUE TITLE
Registry authentication w/ bearer token

### ISSUE THREAD

**Issue by SEAPUNK** [shipyard/shipyard#895]
I run a private GitLab container registry, and the registry does not authenticate via HTTP basic auth, but by bearer tokens.

When adding the registry to Shipyard, it gave me the "Cannot ping registry" error; looking in the code, it looks like the ping command attempts registry ping with HTTP basic auth only.

Am I doing something wrong, or is it not yet supported? I am using the `shipyard/shipyard:latest` image, ID `36fb3dc0907d`.

Ref: https://docs.docker.com/registry/spec/auth/token/

**Comment by athurg** [comment]
Same to me

**Comment by untergrundbiber** [comment]
+1
Same problem here

**Comment by morph027** [comment]
Me too....

**Comment by markrey** [comment]
+1
