### ISSUE TITLE
shipyard 1.12 branch problem

### ISSUE THREAD

**Issue by agenge** [shipyard/shipyard#898]
`git clone https://github.com/shipyard/shipyard.git && cd shipyard`
`git checkout 1.12`
`docker-compose build`
`docker-compose up`

Hi, I am having problems with this step. details as follows:
1. docker-compose up 
2. log in http://192.168.56.102:8080

3. go to the "Get Started" page
4. Click the “Initialize” button

but ,No response after clicking. 
the ssh console logs:
controller_1 | time="2016-11-10T02:50:06Z" level=debug msg="POST: /swarm/init"

On the “Initialize” page , open chrome F12 console and Refresh, Output 406 error:
GET http://192.168.56.102:8080/swarm 406 (Not Acceptable)

Click the “Initialize” button, Output 500 error:
POST http://192.168.56.102:8080/swarm/init 500 (Internal Server Error)

docker compose version:  
`docker-compose version 1.8.1, build 878cff1`
`docker-py version: 1.10.3`
`CPython version: 2.7.5`
`OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013`

How to solve this problem? thanks.

**Comment by EnicPan** [comment]
ssh to the host, and execute ' docker swarm init' manually, and try login the UI again.

**Comment by tombee** [comment]
I'm hoping that #901 will help resolve this issue.  I think it could be that there's an error about being unable to determine the correct advertise address to use.  I've now made errors from `swarm init` visible and added an *Advertise Address* field.

I'll clean this up a little more in future by perhaps collapsing an *Advanced* options section by default, and then allow a user to modify them in situations such as this.

Apologies for this!  Thanks for giving the branch a spin :)

**Comment by tombee** [comment]
Hopefully this is fixed now, would you mind retrying this @agenge?

Thanks!

**Comment by agenge** [comment]
@tombee  Thank you very much for your help and answer. Now the problem has been resolved.

**Comment by tombee** [comment]
@agenge, yw!  I'm trying to find time where I can to continue to work on that branch.. :)
