### ISSUE TITLE
How do I disable http and enable https?

### ISSUE THREAD

**Issue by lxjhk** [shipyard/shipyard#899]
Currently I am accessing the controller page using http.

How could I enable https and disable http?

**Comment by ztroop** [comment]
Documentation on this subject would be greatly appreciated! Also, doing so with private certificates would also be a great topic.

**Comment by ztroop** [comment]
In lieu of this, I've taken the route of setting up a SSL reverse proxy with nginx. Having documentation on the subject would still be helpful.

**Comment by zzgm4j** [comment]
Using the reverse proxy how do you disable http?  Can't a user "go around" the reverse proxy and use http unless you have a firewall or something else in place to stop that traffic?

**Comment by ztroop** [comment]
If you're concerned about this, you can modify the docker containers to listen on localhost instead. There's sufficient documentation on the subject. Here's a snippet from my nginx configuration to save you some time.

```
server {
	listen 80;
	return 301 https://$host$request_uri;
}

server {
	listen 443;
	server_name shipyard.internal;

	ssl_certificate		   /etc/nginx/ssl/file.crt;
	ssl_certificate_key	   /etc/nginx/ssl/file.key;

	ssl on;
	ssl_session_cache  builtin:1000  shared:SSL:10m;
	ssl_protocols  TLSv1.2;
	ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
	ssl_prefer_server_ciphers on;
	add_header Strict-Transport-Security "max-age=7200";

	location / {
		proxy_set_header        Host $host;
		proxy_set_header        X-Real-IP $remote_addr;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header        X-Forwarded-Proto $scheme;
		proxy_pass          http://localhost:8080;
		proxy_read_timeout  90;
		proxy_redirect      http://localhost:8080 https://shipyard.internal;
	}
}
```

**Comment by tombee** [comment]
Thanks for providing this info @ztroop!  Agreed on the need for docs, I think this should be in the roadmap for the next release.
