### ISSUE TITLE
Can't get nodes info 

### ISSUE THREAD

**Issue by sequarius** [shipyard/shipyard#900]
I had created 2 nodes by using `curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://10.0.1.10:4001 bash -s`  script.

However when i visited the main node manage website. i can find the node i added but cant get more infomation about these nodes such as host name and the resource usage  like this
![e7f1 tm](https://cloud.githubusercontent.com/assets/7238573/20235254/19459558-a8c8-11e6-98dc-565a2f90d983.png)

I client the manage sever and using `netstat -apn|grep 2375` can find the connection between manage node and sub node was ESTABLISHED. 

so could anyone can give me any solution of this problem?

**Comment by niulin** [comment]
Please disable SELinux and reboot your nodes.
