### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by faddat** [shipyard/shipyard#905]
ARM geek here.  I'll be making commits that make the 1.12 branch work on ARM.  

Thoughts?

**Comment by tombee** [comment]
Awesome!

**Comment by mielune** [comment]
Good idea 👍

**Comment by faddat** [comment]
....but I really need to get on that. SInce shipyard is go-based, it should "just work". I think it may just be a matter of fiddling with the javascript some. I'm practicing my go for a test right now, this will be something I practice on.
