### ISSUE TITLE
Slow container discovery on WebUI

### ISSUE THREAD

**Issue by huksley** [shipyard/shipyard#911]
Sometimes when loading UI 
requesting following URL takes 10 seconds

``http://HOSTNAME:8080/containers/json?all=1``

Requesting it again - 10ms average

Environment:

CentOS 7 on Windows 8.1 on VMWare.
2 vCPU, 2048 GB RAM

**Comment by niulin** [comment]
I have the same issue.  
Env:
docker running on FC25 Guest running in KVM, Host is CentOS 7.
