### ISSUE TITLE
New to Shipyard, How I can add a node

### ISSUE THREAD

**Issue by maxtrix** [shipyard/shipyard#913]
Hi, I'm testing shipyard for the first time, I'm confused with some of the instructions.

I installed shipyard like it says the docs site (Automated Install), I can enter in the Shipyard management page but there no nodes to manage.

Is Shipyard needs a previous Swarm node to work?  What are the steps to try shipyard with a local node from installing docker and onwards?

**Comment by ehazlett** [comment]
What version of Docker are you using?

**Comment by maxtrix** [comment]
I'm using docker 1.12.3

**Comment by ehazlett** [comment]
We are working on 1.12 support (https://github.com/shipyard/shipyard/tree/1.12) but it's not quite there yet.

**Comment by maxtrix** [comment]
Thanks for your Answer. What is the latest version that shipyard supports?

**Comment by ehazlett** [comment]
1.11.x

**Comment by skys215** [comment]
https://shipyard-project.com/docs/deploy/automated/
```
curl -sSL https://shipyard-project.com/deploy | ACTION=node DISCOVERY=etcd://10.0.1.10:4001 bash -s
```
Add a node like this, which 10.0.1.10 is your host(or main) server.

**Comment by gzcwnk** [comment]
Docker 1.13.1 not supported?  I have installed shipyard but I cannot see nodes

**Comment by gzcwnk** [comment]
I tried following the link " (https://github.com/shipyard/shipyard/tree/1.12)"  but I got a 404 btw.

**Comment by gzcwnk** [comment]
I installed an older version,

root@debian8:~# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
root@debian8:~#

Still no nodes showing up

**Comment by ehazlett** [comment]
1.13 is not yet supported in swarm mode.  Can you give the output of the daemon logs and the shipyard controller logs?
