### ISSUE TITLE
Edit a container

### ISSUE THREAD

**Issue by guiguir68** [shipyard/shipyard#914]
Hi!

How can i edit a created container (created by shipyard webui)?
It's a little bit boring to create / launch / remove / create / launch / remove again and again my test container by the shipyard's deploy container form...

Any suggestion? Thanks!

**Comment by pkozlov** [comment]
+1

**Comment by niulin** [comment]
+1

**Comment by websterxsd** [comment]
+1
Would love to see this option, just adding new ports if you have missed something and you feel like a complete twat.

**Comment by ehazlett** [comment]
We will not support "editing a container" as those should be immutable (and are in docker).  However, we will support "editing services" which support reconfiguration and will launch new containers with the new requirements (ports, env vars, etc).  This is being implemented in the branch https://github.com/shipyard/shipyard/tree/swarm-mode.  Thanks!
