### ISSUE TITLE
How to integrate shipyard with inline docker swarm?

### ISSUE THREAD

**Issue by cloorc** [shipyard/shipyard#915]
# start rethinkdb
    docker run --name rdb -d -p 28015:28015 rethinkdb
    # start shipyard
    docker run --name sc -d -p 9000:8080 shipyard/shipyard:3.1 server --rethinkdb-addr  -d tcp://192.168.103.171:2377

The shipyard is listening on 9000 right now, but no nodes or images could be found while they are actually there. Additionally, there are two swarm managers and 5 swarm workers registered on basis of zookeeper.

**Comment by tombee** [comment]
We're working on it on the 1.12 branch.  There's a PR up to simplify the implementation of the new frontend (https://github.com/shipyard/shipyard/pull/910).

**Comment by soiff** [comment]
Great work, thanks!
