### ISSUE TITLE
Ping registry fails due to authorization

### ISSUE THREAD

**Issue by blckct** [shipyard/shipyard#917]
I tried adding the Gitlab CI registry and it fails the logs are:

```
401 Unauthorized
error saving registry: Cannot ping registry
```
The response to server
`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}`

It seems to me it should ignore the 401 error, after all it hasn't tried authorizing yet.

**Comment by turnerguo** [comment]
+1

**Comment by rveede** [comment]
Same here

**Comment by sbruggeman** [comment]
+1
