### ISSUE TITLE
installing shipyard breaks ipv6

### ISSUE THREAD

**Issue by dnordberg** [shipyard/shipyard#919]
On a CentOS 7.2 host I instantiate a swarm.

`docker swarm init --advertise-addr "$(hostname -I | cut -d" " -f 1)"`

Curl and wget work at this point.

I then install shipyard.

`curl -sSL https://shipyard-project.com/deploy | bash -s`

Wget and curl no longer work. They do work with ipv4 however.

`wget -4 google.com`

Works.

**Comment by engkhalid21** [comment]
Dear dnordberg
Can You Help Me To Install Shipyard On Centos 7 Step by Step Documentation , I Appreciate That.
Best Regards

**Comment by dnordberg** [comment]
Try this:  

```
# required for curl to work after shipyard install
ip -6 route add 2004::3 dev eth0

# needs to be enabled
sysctl net.ipv4.ip_forward=1

service network restart

systemctl restart docker
```
