### ISSUE TITLE
Always getting compromised / high network

### ISSUE THREAD

**Issue by RenWasHere** [shipyard/shipyard#920]
I keep getting network alerts with bandwidth usage ~500MBps.

How to replicate: Create Shipyard cluster on either Amazon AWS or Digital Ocean and leave it up for a few days. Please note: The servers were never breached (as far as I can tell), and I am unsure of what is happening. The swarm was left online for ~5 days, and one member appeared to cause this. (Cluster size: 3). 

Please Note: Passwords were not the defaults. 
No containers were created after installing, just the default ones.
This is a standard install, with no other software.
Didn't touch it for ~5 days, and this happens.

OS: Ubuntu 16.04
Docker: 1.12.3

**Comment by ehazlett** [comment]
Have you setup TLS?  My guess is you have port 2375 open to the public and
containers are being ran. You can lockdown access with iptables and TLS (I
recommend both).
