### ISSUE TITLE
Automated deployment with TLS enabled failed

### ISSUE THREAD

**Issue by bglgwyng** [shipyard/shipyard#923]
I asked this at shipyard irc channel before.
I tried following commands which is posted on [automated depolyment guide page](https://shipyard-project.com/docs/deploy/automated/)
```shell
docker run --rm \
    -v $(pwd)/certs:/certs \
    ehazlett/certm \
    -d /certs \
    bundle \
    generate \
    -o shipyard \
    --host proxy \
    --host 127.0.0.1
curl -sSL https://shipyard-project.com/deploy | TLS_CERT_PATH=$(pwd)/certs bash -s
```
But I failed with 4 different environments. I tried docker version both earlier 1.12 and later 1.12.

**Comment by bglgwyng** [comment]
I tested earlier versions of shipyard, tagged as mater in dockerhub, 3.0.2 and 2.00. But all failed. I wonder until when the automated deployment command was valid.

**Comment by ehazlett** [comment]
It depends on the version of docker you are using.  I'm going to test some
versions to find the compatibility issue.

**Comment by bglgwyng** [comment]
I just tested the latest version of shipyard with docker version 1.9.0, 1.10.0, 1.11.0(versions earlier than 1.9.0 doesn't seem to support unix socket interface). But all failed.
