### ISSUE TITLE
Issue with 1.12 branch 

### ISSUE THREAD

**Issue by kannancmohan** [shipyard/shipyard#925]
Hi , i am trying to use shipyard with an existing swarm(swarm mode)and  am having trouble accessing the shipyard page ,

when i access the http://192.168.99.100:8080/ i get the following
<img width="547" alt="screen shot 2016-12-11 at 17 22 00" src="https://cloud.githubusercontent.com/assets/2664066/21081416/836b7708-bfc6-11e6-8ee9-94f589346897.png">

and also i see that the ui container exited with error

`ui_1          | ui@0.1.0 /usr/src/app
ui_1          | `-- (empty)
ui_1          | 
ui_1          | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/fsevents):
ui_1          | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
ui_1          | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents):
ui_1          | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
ui_1          | npm ERR! Linux 4.4.27-boot2docker
ui_1          | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
ui_1          | npm ERR! node v7.1.0
ui_1          | npm ERR! npm  v3.10.9
ui_1          | npm ERR! path /usr/src/app/node_modules/react-scripts/node_modules/acorn-globals/node_modules/acorn/bin/acorn
ui_1          | npm ERR! code ENOENT
ui_1          | npm ERR! errno -2
ui_1          | npm ERR! syscall chmod
ui_1          | 
ui_1          | npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/node_modules/react-scripts/node_modules/acorn-globals/node_modules/acorn/bin/acorn'
ui_1          | npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/app/node_modules/react-scripts/node_modules/acorn-globals/node_modules/acorn/bin/acorn'
ui_1          | npm ERR! enoent This is most likely not a problem with npm itself
ui_1          | npm ERR! enoent and is related to npm not being able to find a file.
ui_1          | npm ERR! enoent 
ui_1          | 
ui_1          | npm ERR! Please include the following file with any support request:
ui_1          | npm ERR!     /usr/src/app/npm-debug.log
ui_1          | npm ERR! code 1
shipyard_ui_1 exited with code 1`

Steps 
---------
git clone https://github.com/shipyard/shipyard.git && cd shipyard
git checkout 1.12
docker-compose build
docker-compose up

additional info
--------------
docker version :1.12.3
Host Os:Mac

**Comment by Turgon37** [comment]
The ui frontend has moved to another container, so now you have to access to http://192.168.99.100:3000/ instead of 8080. It's work on 3000 for me

**Comment by kannancmohan** [comment]
no , http://192.168.99.100:3000 wont even load

**Comment by Turgon37** [comment]
@kannancmohan if you run the command 'docker-compose logs ui' with the shipyard's docker-compose file, do you see an output which like to the following ?

If not try to wait a bit, the nodejs server be up

`Compiled successfully!
The app is running at:

  http://localhost:3000/
Note that the development build is not optimized.
To create a production build, use npm run build`

**Comment by kannancmohan** [comment]
Hi Turgon37, 
this my output for docker-compose logs ui
ui_1          | npm info it worked if it ends with ok
ui_1          | npm info using npm@3.10.9
ui_1          | npm info using node@v7.1.0
ui_1          | npm info attempt registry request try #1 at 12:06:23 AM
ui_1          | npm http request GET https://registry.npmjs.org/fsevents
ui_1          | npm http 200 https://registry.npmjs.org/fsevents
ui_1          | npm info lifecycle ui@0.1.0~preinstall: ui@0.1.0
ui_1          | npm info linkStuff ui@0.1.0
ui_1          | npm info lifecycle ui@0.1.0~install: ui@0.1.0
ui_1          | npm info lifecycle ui@0.1.0~postinstall: ui@0.1.0
ui_1          | npm info lifecycle ui@0.1.0~prepublish: ui@0.1.0
ui_1          | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/fsevents):
ui_1          | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
ui_1          | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents):
ui_1          | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
ui_1          | npm info ok 
ui_1          | npm info it worked if it ends with ok
ui_1          | npm info using npm@3.10.9
ui_1          | npm info using node@v7.1.0
ui_1          | npm info lifecycle ui@0.1.0~prestart: ui@0.1.0
ui_1          | npm info lifecycle ui@0.1.0~start: ui@0.1.0
ui_1          | 
ui_1          | > ui@0.1.0 start /usr/src/app
ui_1          | > react-scripts start
ui_1          | 
ui_1          | sh: 1: react-scripts: not found
ui_1          | 
ui_1          | npm info lifecycle ui@0.1.0~start: Failed to exec start script
ui_1          | npm ERR! Linux 4.4.38-boot2docker
ui_1          | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
ui_1          | npm ERR! node v7.1.0
ui_1          | npm ERR! npm  v3.10.9
ui_1          | npm ERR! file sh
ui_1          | npm ERR! code ELIFECYCLE
ui_1          | npm ERR! errno ENOENT
ui_1          | npm ERR! syscall spawn
ui_1          | npm ERR! ui@0.1.0 start: `react-scripts start`
ui_1          | npm ERR! spawn ENOENT
ui_1          | npm ERR! 
ui_1          | npm ERR! Failed at the ui@0.1.0 start script 'react-scripts start'.
ui_1          | npm ERR! Make sure you have the latest version of node.js and npm installed.
ui_1          | npm ERR! If you do, this is most likely a problem with the ui package,
ui_1          | npm ERR! not with npm itself.
ui_1          | npm ERR! Tell the author that this fails on your system:
ui_1          | npm ERR!     react-scripts start
ui_1          | npm ERR! You can get information on how to open an issue for this project with:
ui_1          | npm ERR!     npm bugs ui
ui_1          | npm ERR! Or if that isn't available, you can get their info via:
ui_1          | npm ERR!     npm owner ls ui
ui_1          | npm ERR! There is likely additional logging output above.
ui_1          | 
ui_1          | npm ERR! Please include the following file with any support request:
ui_1          | npm ERR!     /usr/src/app/npm-debug.log

**Comment by Turgon37** [comment]
Can you post the result of the following commands please 

docker-compose exec ui ls node_modules/
docker-compose exec ui ls node_modules/react-scripts

Thanks in advance

**Comment by kannancmohan** [comment]
Hi Turgon37 
Here is the output 
$ docker-compose exec ui ls node_modules/
ERROR: No container found for ui_1

$docker-compose exec ui ls node_modules/react-scripts
ERROR: No container found for ui_1

ui is not running , it exited because of the npm error(above mentioned)

when i check ps -a , i see the ui containers status as "Exited (1) 9 minutes ago"

Thanks .........

**Comment by Turgon37** [comment]
So, I'm sorry, I've not realized that the ./ui is mount into the 'ui' docker container.
It's mean that you can access to the ./ui/node_modules directory from the directory where the docker-compose.yml file is located.
Please check that the node_module contain an existing folder with the name 'react-scripts'

So if not you can try to use this command to re-run the npm install command with all operation logs in the foreground of your terminal 
`docker run -it --volume "$(pwd)/ui/:/usr/src/app" -p 3000:3000 --workdir=/usr/src/app node:7.1  bash -c "npm install && npm run start"`

**Comment by kannancmohan** [comment]
Hi Turgon37,
Yes node_module has a folder name react-script and when i run the docker run command you gave it  throws the same error as before 

npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info attempt registry request try #1 at 8:25:04 PM
npm http request GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/fsevents
npm info lifecycle ui@0.1.0~preinstall: ui@0.1.0
npm info linkStuff ui@0.1.0
npm info lifecycle ui@0.1.0~install: ui@0.1.0
npm info lifecycle ui@0.1.0~postinstall: ui@0.1.0
npm info lifecycle ui@0.1.0~prepublish: ui@0.1.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm info ok 
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info lifecycle ui@0.1.0~prestart: ui@0.1.0
npm info lifecycle ui@0.1.0~start: ui@0.1.0

> ui@0.1.0 start /usr/src/app
> react-scripts start

sh: 1: react-scripts: not found

npm info lifecycle ui@0.1.0~start: Failed to exec start script
npm ERR! Linux 4.4.38-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ui@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ui@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

so it clear that the issue is with npm compatibly issue; either virtualbox or osx 

Thanks for your time ......

**Comment by kannancmohan** [comment]
Hi Turgon37 
i got it working......
update  working_dir and volumes for ui as following  and was able to access the shipyard at  http://192.168.99.100:3000

    working_dir: /node_app
    volumes:
      - "./ui:/node_app"
      - /node_app/node_modules

Turgon37, thanks a lot for your valuable inputs.....
