### ISSUE TITLE
Do not modify the NODE LABEL?

### ISSUE THREAD

**Issue by mojie126** [shipyard/shipyard#927]
Do not modify the NODE LABEL?

**Comment by ehazlett** [comment]
Can you be more specific?

**Comment by mojie126** [comment]
[//i.yusa.me/xQOgr9GOqAE3.png]
I want to add a label to node, must be added in docker startup scripts, and not directly in the WEB UI new

**Comment by mojie126** [comment]
Can not display its own services, such as swarm, agent and so on
