### ISSUE TITLE
Unauthorized on api request

### ISSUE THREAD

**Issue by javapenguin** [shipyard/shipyard#930]
I can do a successfull login:
> curl -X POST http://41.79.78.248:8080/auth/login -H "Content-Type: application/json" --data-binary "@login.json" > login.result.json

Response:
>{"auth_token":"$2a$10$iALWc3MfImTPY6su6hsjfuGytfzkkoAFWdcJoMgHo.IPob6zc35ve","user_agent":"curl/7.43.0"}

When I try do do any request I get an unauthorized response.

Sample requests:

> curl -X GET http://41.79.78.248:8080/api/accounts -H "Content-Type: application/json" -H "X-Access-Token: admin:$2a$10$iALWc3MfImTPY6su6hsjfuGytfzkkoAFWdcJoMgHo.IPob6zc35ve"

> curl -X GET http://41.79.78.248:8080/api/nodes -H "Content-Type: application/json" -H "X-Access-Token: admin:$2a$10$iALWc3MfImTPY6su6hsjfuGytfzkkoAFWdcJoMgHo.IPob6zc35ve"

**Comment by ehazlett** [comment]
I'm not able to reproduce.  Could you give some more info on the request?  Perhaps `curl -v` to get some more info.
