### ISSUE TITLE
deploy successfuly, but got no nothing on images/containers

### ISSUE THREAD

**Issue by kaybinwong** [shipyard/shipyard#931]
**docker version**

`
[root@app-146server ~]# docker version

Client version: 1.7.1

Client API version: 1.19

Go version (client): go1.4.2

Git commit (client): 786b29d/1.7.1

OS/Arch (client): linux/amd64

Server version: 1.7.1

Server API version: 1.19

Go version (server): go1.4.2

Git commit (server): 786b29d/1.7.1

OS/Arch (server): linux/amd64
`

**os version**

`
[root@app-146server ~]# cat /etc/redhat-release

CentOS release 6.8 (Final)
`

**shipyard node**
![image](https://cloud.githubusercontent.com/assets/5570216/21416944/e8828544-c851-11e6-866a-27b6384cb126.png)
**docker ps**
![image](https://cloud.githubusercontent.com/assets/5570216/21416955/05d3a3f8-c852-11e6-94f5-7d1b44627ff8.png)

**Comment by ehazlett** [comment]
Shipyard needs a more recent version of Docker (currently 1.11.x).  It does not support Docker that far back.

**Comment by ikodota** [comment]
I have the same problem
~~~
# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@localhost docker]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core) 
~~~

**Comment by ikodota** [comment]
[root@localhost ~]# docker run --rm swarm list token://3c739bd3a589da0788978f502ea318ea
192.168.139.129:2375
192.168.139.128:2375
[root@localhost ~]# 

~~~
[root@localhost ~]# docker -H 192.168.139.128:2376 info                 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: swarm/1.2.6
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 2
 (unknown): 192.168.139.128:2375
  └ ID: 
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ UpdatedAt: 2017-02-22T06:51:38Z
  └ ServerVersion: 
 (unknown): 192.168.139.129:2375
  └ ID: 
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ UpdatedAt: 2017-02-22T06:46:38Z
  └ ServerVersion: 
Plugins: 
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: 01d78b65a394
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false
[root@localhost ~]# 
~~~

**Comment by ikodota** [comment]
success.
~~~
firewall-cmd --zone=public --permanent --add-port=2375/tcp
firewall-cmd --reload
~~~

docker -H tcp://192.168.139.128:2376 info
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 16
Server Version: swarm/1.2.6
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 2
 (unknown): 192.168.139.129:2375
  └ ID: 
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ UpdatedAt: 2017-02-22T06:46:38Z
  └ ServerVersion: 
 localhost.localdomain: 192.168.139.128:2375
  └ ID: Z7QL:AZLP:2L6V:SCUP:B23Z:MHUK:ENAF:AHOP:IXUX:LBEM:6FMX:HA67
  └ Status: Healthy
  └ Containers: 10 (7 Running, 0 Paused, 3 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.001 GiB
  └ Labels: kernelversion=3.10.0-514.6.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=overlay
  └ UpdatedAt: 2017-02-22T07:22:51Z
  └ ServerVersion: 1.13.1
Plugins: 
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 1.001 GiB
Name: 01d78b65a394
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false
