### ISSUE TITLE
Shipyard should not bind to public interfaces (if not TLS)

### ISSUE THREAD

**Issue by luca-moser** [shipyard/shipyard#932]
Setting up Shipyard without TLS client authentication automatically exposes your docker deamon via the `shipyard-proxy` container on the public interfaces of the host system. Thereby everyone is able to connect to the deamon from everywhere and do all sort of fun stuff with it....

I don't think this should be the default behavior. Let the deployed containers be self contained on the host until someone manually decides to actually use Shipyard for multiple nodes.

In my opinion, Shipyard should print a big fat warning after setup if someone deploys it without having TLS client authentication enabled. Best would be to not even allow binding the `shipyard-proxy` container to public interfaces when the docker deamon is not running via TLS. There should be atleast some kind of security barrier.

Issues like https://github.com/shipyard/shipyard/issues/835 show that people don't understand what the default deployment of Shipyard actually does to their docker deamon instances.

**Comment by ehazlett** [comment]
Thank you for your feedback.  Since there is no definitive way to detect if an interface is actually "public" or not (i.e. NAT, etc) I think we should just force TLS.  I've created https://github.com/shipyard/shipyard/issues/933 to track this.
