### ISSUE TITLE
alot of errors

### ISSUE THREAD

**Issue by moltra** [shipyard/shipyard#936]
I am new using docker, so I might have done something wrong, but if I open the chrome console, I am getting alot of errors.

![image](https://cloud.githubusercontent.com/assets/1578492/21625353/461439d8-d1d9-11e6-959c-aebf628ea27a.png)

**Comment by moltra** [comment]
I did have to reinstall shipyard, and I might have messed up some of the links.  The stats are showing and I do not see anything missing on the screen.

**Comment by ehazlett** [comment]
How are you running it the image or from a build?  What version of OS and
Docker?

**Comment by moltra** [comment]
DigitalOcean Droplet 2 GB Ubuntu Docker 1.12.5 on Ubuntu 16.04

I think I installed it using this command.

docker run -it -p 8080:8080 -d --restart=always --name shipyard --link shipyard-rethinkdb:rethinkdb shipyard/shipyard

**Comment by moltra** [comment]
I still have the VM up and running and can you send you the information for it

**Comment by moltra** [comment]
I have a new docker system setup and I am getting the same errors, but alot less this time.

![image](https://cloud.githubusercontent.com/assets/1578492/21774561/df68cdac-d660-11e6-9da2-7a36d6e7b4bc.png)

**Comment by ehazlett** [comment]
You will most likely need to use the install script (https://shipyard-project.com/docs/deploy/automated/) as there are a few containers you need to have running.  I just confirmed that the install  script works on Ubuntu 16.04 and Docker 1.12.5.  If you continue to have errors after the install can you post the logs from the controller container?
