### ISSUE TITLE
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/swarm/manifests/latest: 

### ISSUE THREAD

**Issue by cloudscode** [shipyard/shipyard#937]
[root@bogon ~]# docker run \
>     -ti \
>     -d \
>     --restart=always \
>     --name shipyard-swarm-manager \
>     swarm:latest \
>     manage --host tcp://192.168.20.240:3375 etcd://192.168.20.240:4001
Unable to find image 'swarm:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/swarm/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fswarm%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 218.85.157.99:53: read udp 192.168.20.240:42208->218.85.157.99:53: i/o timeout.
See 'docker run --help'.

THx.

**Comment by ehazlett** [comment]
This looks like an access issue.  Can you perform a lookup (i.e. `dig` or `nslookup`) from that host to auth.docker.io?

**Comment by bixiaohong2015** [comment]
same error

**Comment by ehazlett** [comment]
This is almost always a local access or firewall issue.  In the original case it was a local DNS server that wasn't responding.  I would recommend changing to a more reliable DNS upstream such as Google (`8.8.8.8` and `8.8.4.4`).
