### ISSUE TITLE
custom password on installation

### ISSUE THREAD

**Issue by moltra** [shipyard/shipyard#942]
I just received notification from DigitalOcean that my server was involved in a DDOS attack.  The only thing running was some dockers that I was using to understand dockers better.  Shipyard was one of these.  I was installing it and others using a docker-compose file.  And I think I might have forgot to change the initial password for shipyard the last time I installed.  I was installing and uninstalling alot trying to get alot of containers to work together.

I do not see a way to setup the initial admin password on creation of the container.  Is there a way to pass this informtion via a docker run command or a docker-compose file?

**Comment by ehazlett** [comment]
Currently there is no way to set the password on install.  In the next version we are planning to secure by default using TLS and randomizing the password on install to reduce potential security issues.
