### ISSUE TITLE
how to deploy a container with a dedicated/static ipv4!?

### ISSUE THREAD

**Issue by systemroot** [shipyard/shipyard#947]
hello, 
sorry if looks like a noob question but yeah i'm trying i have some problems with it! 

i'm running docker 1.13 on ubuntu 14.04, and (example) my network
1. eth0 : 1.1.1.1
2. eth0:0 : 2.2.2.2
3. eth0:1 : 79.0.0.0

So now i want to create a container and use ip 79xxx with it, so to create a container with dedicated ip we need to set **Network Mode** => **host** right? this is how i did but docker isn't using this ip ex for apache nginx or everything else.

so i did a test to see if i'm able to use this ip with this container or not i installed nginx and i started it with ip 79xx:80 on vhost conf's. 
that worked! i can see nginx default page on it, 

but if i deploy a container with a ip wroted on it why docker try to user other ip's ? everything which is needed to be for public with a public port i'll need to wrote ip on it ex for a vhost i'll need to set 79xxx:80 because nginx or apache i'll try to own all other ip's :confused:  well in one part isn't a big problem, just i need to find out how to set up ssh on port 22 for this container on ip 79.xx because for now 79. is forwarding me on my host ssh not in container port :confused:

ofcourse i wrote listenaddress 79xxx on sshd_config but isn't working, extactly isn't just ssh problem, some programs doesn't have any option to set on which ip to run, 

so i haven't deploy a container with dedicated ip before, this is how docker works on network?! or i'm doing anything wrong?
also i tried to start container on bridge mode from shipyard and on ports configuration i wroted ex
22 > TCP > 79xx > 22 , but i got a error shipyard fail to bind 79xx:22 (port already in use)
may i'll be better to set host sshd to run just on 1.1.1.1:22 and to start container on bridge?!
which way will be better to use?!
Thanks ..

**Comment by ehazlett** [comment]
Yes if you want to use the host IPs you need to use `host` networking.  As for configuring the ssh service, you won't be able to bind on 22 as SSH is probably binding on all IPs.  I would suggest using a different port such as 2222.  That way you don't mess with the host.

**Comment by systemroot** [comment]
hm :confused:  thank you for information
