### ISSUE TITLE
[Error] No elected primary cluster manager

### ISSUE THREAD

**Issue by Kizoku-Dev** [shipyard/shipyard#953]
Hi,

I deployed shipyard using the automated deploy script and everything went fine.
I accessed the web interface, login with default credentials and I got an error :
![capture](https://cloud.githubusercontent.com/assets/7711201/22424572/5fa49bda-e6f7-11e6-87b8-b0f2a99da660.PNG)

And the logs of my shipyard-swarm-manager container :
![screenshot_2017-01-30-14-22-45](https://cloud.githubusercontent.com/assets/7711201/22424746/32c9fa96-e6f8-11e6-999f-27b0b84b2bd3.png)

I didn't find any relevant issues about my problem.

EDIT : I use the latest docker version (1.13.0) but before upgrading I tried with the docker 1.12.x and I had the same error.

**Comment by adventurer2008** [comment]
I have tha same error with docker version(1.13.0)

**Comment by ehazlett** [comment]
This looks related to Swarm classic.  Make sure all of the nodes can see each other and that the etcd container is up.   As an aside, for the next version of Shipyard (https://github.com/shipyard/shipyard/tree/swarm-mode) we are removing etcd and Swarm classic making the stack much more stable.

**Comment by Kizoku-Dev** [comment]
Ok it will be better.
I'll try to use the swarm-node branch, I assume it is still in dev.

**Comment by ehazlett** [comment]
Ya it's still really early but progressing.

**Comment by Kizoku-Dev** [comment]
Ok thanks for your help :)

I think it is time to close this issue.
