### ISSUE TITLE
how to deploy a service in the docker swarm mode

### ISSUE THREAD

**Issue by witwave** [shipyard/shipyard#959]
when i deploy a container, there is no choose that the container is **service** or not?
and how to add label in the container 

    --label traefik.port=80 \
    --network traefik-net \
    --label traefik.frontend.rule=Host:mydomain.com

**so how to deploy a service in the docker swam?**

the docker version:
`  Docker version 1.13.0`

the docker node

```
 ID                           HOSTNAME      STATUS  AVAILABILITY  MANAGER STATUS
 00byqhttygdp55iayr52pi96j *  iZ23qa2w53dZ  Ready   Active        Leader
 3hobaje00uvd7sk1qu32n5hid    iZ23fiyhq7eZ  Ready   Active        
 95i1hzti53154ijgo5b4i677q    iZ237b2agzgZ  Ready   Active        
```

**Comment by tombee** [comment]
Support for swarm mode is still a work in progress.  It's being worked on in the `swarm-mode` branch (https://github.com/shipyard/shipyard/tree/swarm-mode).

**Comment by batjko** [comment]
Is this the right ticket to subscribe to, in order to be updated when that swarm-mode branch gets merged?
Also, what's the timeline on that?
