### ISSUE TITLE
When use TLS for deploying shipyard, it can not be visited by windows chrome but macos chrome can.

### ISSUE THREAD

**Issue by joneyhsiao** [shipyard/shipyard#967]
Shipyard is using TLS and it can not be visited by windows chrome(the latest chrome version), error message: NET::ERR_CERT_INVALID, but macos chrome has no such issue. Any idea what happened here?

--------------------------------------------------------------------------------------------
**updates**: chrome windows version: 56.0.2924.87(64-bit)
              chrome os version: 55.0.2883.95 (64-bit)

Details error message from chrome windows:
Your connection is not a private connection

Attackers may try to steal your information from *.*.*.* (eg password, communication content or credit card information). NET :: ERR_CERT_INVALID

*.*.*.* Encryption technology is usually used to protect your information. Google Chrome attempts to connect to *.*.*.* this time, the site sent an error message. This could be because an attacker was trying to impersonate the connection with *.*.*.*, or the Wi-Fi login screen. Please be assured that your information is still safe because Google Chrome has stopped connecting without any data exchange.

You are currently unable to access *.*.*.* because the credentials sent by this site are garbled and can not be processed by Google Chrome. Network errors and aggressive behavior are usually temporary, so this page may return to normal later.

---------------------------------------------------------------------------------------------
Update: my centos7.2.1511 kernel : 3.10.0-327.el7.x86_64
docker version: 1.12.5

By the way, when using TLS, seems shipyard can not work as expected, i.e
1. No containers found including local shipyard related containers.
2. No images found

**Comment by joneyhsiao** [comment]
Figured out that shipyard maybe using SHA-1 and chrome browser does not support SHA-1 since 01/2017 completely, but no idea why chrome os works fine.So can anyone confirm this? And if yes, when will we upgrade to SHA-256? Thank you.

**Comment by ehazlett** [comment]
I've updated the upstream `ehazlett/certm` project to use the `SHA-256` signature algorithm.  Can you try to see if this works?  Cert generation appears to be fine:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            97:b3:a9:52:17:a9:33:aa:b3:54:20:36:04:10:f5:e9
    Signature Algorithm: sha256WithRSAEncryption
```

Note: I'm not a TLS expert so ymmv ;)

You will need to update to the latest `ehazlett/certm` (version 0.2.0) to get the update.

**Comment by joneyhsiao** [comment]
@ehazlett Thanks for your quick reply. I have updated the lastest ehazlett/certm (Tag: latest), and the result is not what we expected. Paste the commands I typed below:
`＃ docker run --rm \
    -v $(pwd)/certs:/certs \
    ehazlett/certm \
    -d /certs \
    bundle \
    generate \
    -o shipyard \
    --host proxy \
    --host 127.0.0.1

＃ curl -sSL https://shipyard-project.com/deploy | TLS_CERT_PATH=$(pwd)/certs bash -s`

**Comment by joneyhsiao** [comment]
@ehazlett Thanks for your quick reply. I have updated the lastest ehazlett/certm (Tag: latest), and the result is not what we expected. Paste the commands I typed below:
> ＃ docker run --rm 
-v $(pwd)/certs:/certs 
ehazlett/certm 
-d /certs 
bundle 
generate 
-o shipyard 
--host proxy 
--host 127.0.0.1

> ＃ curl -sSL https://shipyard-project.com/deploy | TLS_CERT_PATH=$(pwd)/certs bash -s

**Comment by ehazlett** [comment]
If you are still getting the `ERR_CERT_INVALID` that's probably due to the fact it's a self-signed cert.  Can you check it either by viewing more details from the error or with `openssl` to check the info on the cert?

**Comment by joneyhsiao** [comment]
I generated another cert by this way:
 > openssl req     -newkey rsa:4096 -nodes -sha256 -keyout ca.key     -x509 -days 365 -out ca.crt
 > openssl req     -newkey rsa:4096 -nodes -sha256 -keyout yourdomain.com.key     -out yourdomain.com.csr
 > echo subjectAltName = IP:192.168.1.103 > extfile.cnf
 > openssl x509 -req -days 365 -in yourdomain.com.csr -CA ca.crt -CAkey ca.key -CAcreateserial -extfile extfile.cnf -out yourdomain.com.crt

Can you specify How does shipyard work with certs?

**Comment by mvdhoning** [comment]
Got the same problems.

Found a solution in generating certificates as described here:
http://tech.paulcz.net/2016/01/secure-docker-with-tls/ 
using the paulczar/omgwtfssl docker image.
replaced /etc/docker/ssl with dockerserver as folder and
replaced ~/.docker with docker as folder
and replaced 172.17.8.101 with a for me valid ip.
copied the cert.pem and key.pem over to docker with server.pem an server-key.pem as names.
and did a chown to my user so files are no longer root. (now i realize i did not do this step the first time)

Next i used the docker folder on installing shipyard. curl -sSL https://shipyard-project.com/deploy | TLS_CERT_PATH=$(pwd)/docker bash -s

now i can continue in browser to login. importing the certificate via ie11 still fails though.
but copying over the ca.pem to windows and renaming that to ca.crt and right click install on that fixes that.
