### ISSUE TITLE
stats loading and console error

### ISSUE THREAD

**Issue by giuem** [shipyard/shipyard#969]
![20170219180359](https://cloud.githubusercontent.com/assets/8272989/23101409/d9e9022e-f6cd-11e6-8c89-d3b84abd58f5.png)

Operating System: `Ubuntu 16.04.1 LTS`

``` 
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by Sm0ke0ut** [comment]
I have the same problem but it seems a browser issue. I'm using Vivaldi which is based on chrome/webkit. Firefox seems to be working just fine.

![image](https://cloud.githubusercontent.com/assets/363388/24074629/dad1d5f4-0c0c-11e7-9c73-64fc8bb65a55.png)

**Comment by giuem** [comment]
I have found the problem.. I use nginx proxy pass the server. But the stats api use `Transfer-Encoding:chunked` which I need to set `proxy_buffering off` in nginx config. 

Simply like below
``` nginx
server {
        listen 80;
        server_name example.com;
        server_tokens off;
        location / {
                proxy_pass http://10.105.251.240:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_buffering off;
        }
}
```
