### ISSUE TITLE
shipyard-project.com is down

### ISSUE THREAD

**Issue by soulan** [shipyard/shipyard#970]
When I try to access it I always get timeouts

**Comment by davidqhr** [comment]
Me too...

**Comment by IlyasDeckers** [comment]
Same here... Happened yesterday, the website is up but the deploy url returns `No such site at :80`

**Comment by ehazlett** [comment]
It has been fixed.  Thanks for feedback!

**Comment by cristianfd** [comment]
shipyard-project.com is down again
