### ISSUE TITLE
Use only relative URLs to simplify deployments behind Nginx/Apache proxies

### ISSUE THREAD

**Issue by schuerg** [shipyard/shipyard#972]

**Comment by ehazlett** [comment]
Can you give an example?  All of the frontend links should be relative.

**Comment by schuerg** [comment]
First, thanks for the quick response!

I want to use Shipyard behind an Apache 2.4 Webserver.

Shipyard is deployed on a server, which is also running an Apache 2.4 web server on port 443 (default HTTPS port).
Shipyard itself runs on Port 8080 and is accessible at http://example.com:8080.
I want to use Apache as a proxy because only Port 443 is accessible from remote networks.

Apache should proxy requests accessing https://example.com/shipyard => http://example.com:8080.

Therefor i configured Apache as follows:

	ProxyPass /shipyard/ http://localhost:8080/
	ProxyPassReverse /shipyard/ http://localhost:8080/

Shipyard is accessible at https://example.com/shipyard but the website is broken.
The links in the navbar are correct:
```
https://example.com/shipyard/#/containers
https://example.com/shipyard/#/images
https://example.com/shipyard/#/nodes
https://example.com/shipyard/#/registry
```

But shipyard performs some Ajax requests to URLs like ...

https://example.com/containers/json?all=1
https://example.com/images/json
https://example.com/api/registries

... and so on. Which are not accessible.

How to use Apache 2.4 as a proxy for shipyard?
Is there a option to specify a HTTP-Prefix like `--httpprefix /shipyard` as it is the case for other applications like Jenkins?

**Comment by ehazlett** [comment]
Ah in that case you will most likely want to use Rewrite rules in apache.
That should get you what you need.

**Comment by schuerg** [comment]
Well then i have to specify single rules for every `https://example.com/XYZ` location that shipyard uses for Ajax Requests. One problem is that these locations under root ( / ) can then only be used by shipyard because of the rules.

```
/networks
/containers
/images
/api
/_ping
/version
/auth
/exec
/commit
/build
...
```
I did this. It works. But i think it would be better if it were possible to define a prefix for the calls in [/controller/api/api.go](shipyard/blob/master/controller/api/api.go).
So that the proxy rules in Apache could be simple as:
```
ProxyPass /shipyard http://localhost:8080/shipyard
ProxyPassReverse /shipyard http://localhost:8080/shipyard
```

Or do you think it is not really necessary?
GitLab, Jenkins and lots of other projects do this...

**Comment by StevenByks** [comment]
I am having the exact same problem schuerg is having.  This is a very common pattern, and it would be really nice if we could get this option for shipyard.  Btw, any chance you could share your complete list of Apache settings to make this work?
