### ISSUE TITLE
unauthorized containers being installed

### ISSUE THREAD

**Issue by moltra** [shipyard/shipyard#973]
I have had multiple unauthorized containers being installed.  I am not sure if it is due to shipyard or what.  Does anyone have any idea how to determine how they are being installed.  

The last time that an unauthorized container was installed it was part of a DDOS attack and digitalocean took the VPS off the public network.  The time before that I had a bitcoin miner container installed without my permission.  

I am running ubuntu 16.04 with a 14 character password including Upper case,, lower case, numbers and symbols on both the VPS root account and on shipyard with the default admin account deleted and a new one created a password the same as the ubuntu.

Any help would be appreciated.

**Comment by ehazlett** [comment]
As mentioned in the installations docs (https://shipyard-project.com/docs/deploy/automated/):

```
Note: this will expose the Docker Engine on port 2375. It is recommended to use TLS if this node will be accessible outside a secure network.
```

See the installation docs for enabling TLS.
