### ISSUE TITLE
unauthorized containers being installed 

### ISSUE THREAD

**Issue by 4stackdev** [shipyard/shipyard#974]
Have two ubuntu containers named quirky_wiles ,hardcore_jepsen installed on my vps .

outbound traffic rate by averaging 15.05 Mb/s

had change the default name and pass.

**Comment by moltra** [comment]
I have had unauthorized containers installed also.  #973

**Comment by ehazlett** [comment]
As mentioned in the installations docs (https://shipyard-project.com/docs/deploy/automated/):

```
Note: this will expose the Docker Engine on port 2375. It is recommended to use TLS if this node will be accessible outside a secure network.
```

See the installation docs for enabling TLS.
