### ISSUE TITLE
win10 start failed

### ISSUE THREAD

**Issue by duanzonglong** [shipyard/shipyard#982]
system:win10
docker version:Server Version: 17.03.1-ce
curl -sSL https://shipyard-project.com/deploy | bash -s
then I get:
-> Starting Proxy
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid bind mount spec "/C/Program Files/Git/var/run/docker.sock;C:\\Program Files\\Git\\var\\run\\docker.sock": invalid volume specification: '/C/Program Files/Git/var/run/docker.sock;C:\Program Files\Git\var\run\docker.sock': invalid mount config for type "bind": invalid mount path: '\Program Files\Git\var\run\docker.sock' mount path must be absolute.
How the win10 support?

**Comment by funky81** [comment]
It seems Shipyard doesnt support on Windows deployment
