### ISSUE TITLE
dose shipyard  support docker 17.03.1-ce for swarm mode cluster

### ISSUE THREAD

**Issue by ouyh1111** [shipyard/shipyard#983]
Recent,I use docker ce(17.03.x) with swarm mode cluster. Swarm has integrated  in docker.This feature is so new  that I found  the orchestration tools aren't support. I don't know that shipyard  whether support swarm mode feature,Is anybody  could tell me  or introduce some other orchestration tools.3q

**Comment by tetosuna** [comment]
see: https://github.com/shipyard/shipyard/issues/839
