### ISSUE TITLE
shipyard-project.com is down.

### ISSUE THREAD

**Issue by anthony-cervantes** [shipyard/shipyard#984]
https://shipyard-project.com website is down.

#970

**Comment by WebWeave** [comment]
I have the same issue :(

**Comment by ZhiqiangTao** [comment]
+1 who can contact the owners?

**Comment by WebWeave** [comment]
The owner is @ehazlett .
His personal website has the same problem to.

**Comment by ehazlett** [comment]
Sorry for the delay I've been AFK. Everythign should be back up.  Thanks!
