### ISSUE TITLE
Error: {"data":"Gateway Timeout","status":504,"config":

### ISSUE THREAD

**Issue by zhhzhfya** [shipyard/shipyard#987]
i deploy shipyard by:
curl -s https://shipyard-project.com/deploy | bash -s
and get these errors:
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$CUWdDjtqzijze9e1OmY.lesPQI/vo9TqBMkQb1q4AssHPiKe7P4/e"}},"statusText":"Gateway Timeout"}
<img width="1248" alt="wx20170509-175704 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845573/029beb5e-34e1-11e7-8f02-c8c6b6810219.png">

**Comment by zhhzhfya** [comment]
<img width="1248" alt="wx20170509-180046 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845703/78c29814-34e1-11e7-92c0-bee9f41095e6.png">
<img width="1247" alt="wx20170509-180029 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845704/78c8f38a-34e1-11e7-83a9-6306db54378f.png">
<img width="1248" alt="wx20170509-180019 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845706/78cb1d40-34e1-11e7-915c-8d0f39df1bca.png">
<img width="1247" alt="wx20170509-180003 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845707/78d2637a-34e1-11e7-8dc9-1379e4b656bb.png">
<img width="1247" alt="wx20170509-175946 2x" src="https://cloud.githubusercontent.com/assets/1484626/25845705/78caacb6-34e1-11e7-898a-e42a83c33d09.png">

**Comment by ehazlett** [comment]
It looks like the name resolution isn't working.  I'll see if I can recreate.

**Comment by josecarlosweb** [comment]
I have the same problem.
I see in the console that problem is occurring when call this url http://MY_IP:8080/containers/json?all=1
Whats is calling in this service?

**Comment by lihui7800** [comment]
same question。
