### ISSUE TITLE
webbrowser don't visit in localhost:8080

### ISSUE THREAD

**Issue by zengraoli** [shipyard/shipyard#989]
my machine environment:
VMWare IP addr---192.168.254.150
os is ubuntu 14.04
Docker version 17.04.0-ce, build 4845c56

======================================

i do some operation:

1.
sudo vi /etc/default/docker
in the last line insert:
DOCKER_OPTS="$DOCKER_OPTS -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"

2.
sudo service docker restart

3.
sudo ufw allow 8080
sudo ufw allow from 192.168.254.1

4.
curl -s https://shipyard-project.com/deploy | bash -s
docker ps can see it
----------------------------------------------
zeng@zeng-virtual-machine:~$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a2d622ba2470        shipyard/shipyard:latest       "/bin/controller -..."   6 minutes ago       Up 20 seconds       0.0.0.0:8080->8080/tcp                           shipyard-controller
0e037b468acc        swarm:latest                   "/swarm j --addr 1..."   7 minutes ago       Up 7 minutes        2375/tcp                                         shipyard-swarm-agent
83d7e20df1c9        swarm:latest                   "/swarm m --replic..."   7 minutes ago       Up 7 minutes        2375/tcp                                         shipyard-swarm-manager
b2306b2588d7        shipyard/docker-proxy:latest   "/usr/local/bin/run"     7 minutes ago       Up 7 minutes        0.0.0.0:2375->2375/tcp                           shipyard-proxy
609e866aae09        alpine                         "sh"                     7 minutes ago       Up 7 minutes                                                         shipyard-certs
31f0bcba6190        microbox/etcd:latest           "/bin/etcd -addr 1..."   7 minutes ago       Up 7 minutes        0.0.0.0:4001->4001/tcp, 0.0.0.0:7001->7001/tcp   shipyard-discovery
29ba1e0ddcc2        rethinkdb                      "rethinkdb --bind all"   8 minutes ago       Up 8 minutes        8080/tcp, 28015/tcp, 29015/tcp                   shipyard-rethinkdb
----------------------------------------------

5.
netstat -tln
can see port 8080 is opening
zeng@zeng-virtual-machine:~$ netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN     
tcp6       0      0 :::7001                 :::*                    LISTEN     
tcp6       0      0 :::4001                 :::*                    LISTEN     
tcp6       0      0 :::2375                 :::*                    LISTEN     
tcp6       0      0 :::8080                 :::*                    LISTEN

6.
in the VMWare machine , webbrowser visit in localhost:8080 or 192.168.254.150:8080
"Unable to connect"
so as well as wget 192.168.254.150:8080 
"Connecting to 192.168.254.150:8080... failed: Connection refused."

can someone help me?

**Comment by ehazlett** [comment]
can you post the logs from the shipyard controller?

**Comment by zengraoli** [comment]
@ehazlett 
what wrong with controller?

zeng@zeng-virtual-machine:~/test$ docker logs -tf 005983ec4704
2017-04-26T05:59:24.520178885Z INFO[0000] shipyard version 3.1.0                       
2017-04-26T05:59:24.520229755Z DEBU[0000] setting up rethinkdb session                 
2017-04-26T05:59:45.576178485Z WARN[0021] Error creating connection: gorethink: dial tcp 211.98.71.195:28015: getsockopt: connection refused 
2017-04-26T05:59:45.576239216Z FATA[0021] no connections were made when creating the session 
2017-04-26T05:59:46.039592257Z INFO[0000] shipyard version 3.1.0                       
2017-04-26T05:59:46.039746577Z DEBU[0000] setting up rethinkdb session                 
2017-04-26T05:59:56.059686008Z INFO[0010] checking database                            
2017-04-26T06:00:19.641261203Z DEBU[0033] connected to docker: url=tcp://swarm:3375    
2017-04-26T06:00:19.641809578Z DEBU[0033] configured docker proxy target: http://swarm:3375 
2017-04-26T06:00:19.777302769Z INFO[0033] created admin user: username: admin password: shipyard 
2017-04-26T06:00:19.777339911Z INFO[0033] controller listening on :8080                
2017-04-26T06:01:14.164128566Z WARN[0088] unauthorized request for /containers/json from 192.168.254.1:51247 
2017-04-26T06:01:44.622106130Z DEBU[0118] GET: /containers/json?all=1

**Comment by zengraoli** [comment]
i create new shipyard from 
curl -s https://shipyard-project.com/deploy | bash -s

the web page can visit,but 
Error...
{"data":"Bad Gateway","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$03omsXvGKJlb0N9wzLUwI.rw6jKHNc4IC9yI8dDrW9hnlmVhbcEF2"}},"statusText":"Bad Gateway"}

is the shipyard is can run?

**Comment by 0532110** [comment]
@zengraoli 我也是这个错误，没解决，centos7和ubuntu都这样。
