### ISSUE TITLE
Alert:Deploy script is very dangerous！

### ISSUE THREAD

**Issue by qmm0523** [shipyard/shipyard#995]
the delpoy script given in "https://shipyard-project.com/deploy" is very dangerous ,
It binds the docker api port"2375" to 0.0.0.0,
So bad guys can bypass the web authorization easily and control the docker by this api.
What's more terrible is attacker can create a new containter and mount your /root/.ssh/ directory and add an authrized_keys to your host,then they can control your machine!
Please change this script immeditely.

**Comment by ehazlett** [comment]
Yes this is why there is a warning.  Please use TLS.

![image](https://user-images.githubusercontent.com/260642/28201408-e64387f0-683e-11e7-84c8-3393008f222c.png)

**Comment by qmm0523** [comment]
But I searched the Internet and there are still lots of shipyard servers open their 8080 and 2375 port.I don't think this note is enough beacuse deafult setting is unsafe.
